### PR TITLE
Fix a bug in raw compression, where we were overflowing memory.

### PR DESCRIPTION
**Pull request by agorrod**
We weren't growing the buffer enough when adding new items in.

Refs SERVER-16664

### CODE REVIEW

**Comment by agorrod** [comment]
@keithbostic Could you take a look at this one after it passes basic testing? It fixes the issue I was seeing in JIRA ticket [16664](https://jira.mongodb.org/browse/SERVER-16664) - there are some stack traces there.

**Comment by wtbuild** [comment]
Test PASSed.

**Comment by wtbuild** [comment]
Test PASSed.

**Comment by keithbostic** [comment]
I think there is a problem with this fix because we've already updated `r->entries` before checking if the next key fits. (Or maybe I'm wrong -- it would seem to me the failure would be losing some key/value pairs, which makes me wonder why the test case kept running.)

If I'm correct: we could check `r->space_avail` before updating `r->entries` but that's messy: we'd have to do an odd split of the logic of building a block to write and we'd have to think hard about the other stuff we're doing (like promoting a key for the next block). I'd suggest something like this:

```
diff --git a/src/reconcile/rec_write.c b/src/reconcile/rec_write.c
index 328c0cf..0300596 100644
--- a/src/reconcile/rec_write.c
+++ b/src/reconcile/rec_write.c
@@ -2408,8 +2408,6 @@ no_slots:
                        break;
                }
                write_ref = dst;
-               if (r->space_avail < next_len)
-                       goto split_grow;
        } else if (no_more_rows) {
                /*
                 * Compression failed and there are no more rows to accumulate,
@@ -2434,15 +2432,7 @@ no_slots:
                 * the "page" and try again after we accumulate some more rows.
                 */
                WT_STAT_FAST_DATA_INCR(session, compress_raw_fail_temporary);
-
-split_grow:    /*
-                * Double the page size and make sure we accommodate at least
-                * one more record. The reason for the latter is that we may
-                * be here because there's a large key/value pair that won't
-                * fit in our initial page buffer, even at its expanded size.
-                */
-               r->page_size *= 2;
-               return (__rec_split_grow(session, r, r->page_size + next_len));
+               goto split_grow;
        }
 
        /* We have a block, update the boundary counter. */
@@ -2464,6 +2454,22 @@ split_grow:      /*
        } else
                WT_RET(
                    __rec_split_write(session, r, last, write_ref, last_block));
+
+       /*
+        * We got called because there wasn't enough room in the buffer for the
+        * next key and we might or might not have written a block. In any case,
+        * make sure the next key fits into the buffer.
+        */
+       if (r->space_avail < next_len) {
+split_grow:    /*
+                * Double the page size and make sure we accommodate at least
+                * one more record. The reason for the latter is that we may
+                * be here because there's a large key/value pair that won't
+                * fit in our initial page buffer, even at its expanded size.
+                */
+               r->page_size *= 2;
+               return (__rec_split_grow(session, r, r->page_size + next_len));
+       }
        return (0);
 }
```

**Comment by wtbuild** [comment]
Test PASSed.

**Comment by agorrod** [comment]
@keithbostic This fixes the issue for me. I'll merge.

**Pull request merged**
