### PR TITLE
WT-6583 Fix accidentally clearing read timestamp under cache pressure

### PR DESCRIPTION
**Pull request by quchenhao**
This change reverts WT-6339 and add a new test to make sure the error is fixed.

### CODE REVIEW

**Review by agorrod — COMMENTED** [review]
@quchenhao I can't spot the actual bug fix here - could you explain to me what the problem was?

**Comment by quchenhao** [comment]
@agorrod The bug is introduced in WT-6339 that set a flag to stop history store operation from creating a snapshot. Since WT-6339 is no longer needed with WT-6462, which changes history store operations to always read in read uncommitted isolation level. The fix here is to revert WT-6339.

**Comment by agorrod** [comment]
I'm still not understanding what the bug is. I remember that WT-6339 split one flag into two, with different meanings. That was done since we wanted the history store to have just one part of the semantic.

Then we decided in WT-6453 that the history store didn't need that functionality, but decided to keep the two separate flags. We did that because the two different results of setting WT_CBT_NO_TXN weren't obvious, and it took a while to figure that out. i.e: the code wasn't clear and clean originally and splitting into two flags clarified the code. I asked during code review of WT-6453 that the flags remained separate.

**Comment by quchenhao** [comment]
@agorrod OK. I don't know that. The issue is that now the history store cursor doesn't have WT_CBT_NO_TXN set. When you start a transaction and if it starts to do eviction and the session doesn't have any cursor open, it is possible to go into the following code after opening a hs cursor and then closing it in eviction. The underlying function will clear the read timestamp.

```
    /*	
     * When the count of active cursors in the session goes to zero, there are no active cursors,	
     * and we can release any snapshot we're holding for read committed isolation.	
     */	
    if (session->ncursors == 0 && !F_ISSET(cbt, WT_CBT_NO_TXN))	
        __wt_txn_read_last(session);
```

**Comment by quchenhao** [comment]
If we want to keep the flag separate, then the proper fix would be check

F_ISSET(cbt, WT_CBT_ACTIVE) in

```
    /*	
     * When the count of active cursors in the session goes to zero, there are no active cursors,	
     * and we can release any snapshot we're holding for read committed isolation.	
     */	
    if (session->ncursors == 0 && !F_ISSET(cbt, WT_CBT_NO_TXN))	
        __wt_txn_read_last(session);
```

**Comment by quchenhao** [comment]
We want to keep the partial code in WT-6339. So close this.

**Pull request closed without merging**
