### PR TITLE
WT-2766 Don't sweep LAS cache when aren't making progess in eviction

### PR DESCRIPTION
**Pull request by daveh86**

### CODE REVIEW

**Comment by sulabhM** [comment]
@daveh86 : LGTM

**Comment by agorrod** [comment]
@daveh86 lgtm - I'm going to hold off merging until the fallout from WT-2764 has settled.

**Comment by michaelcahill** [comment]
@daveh86, I shuffled code around so both checks are made before we call `__wt_las_sweep`.  Does this still look right to you?

**Comment by daveh86** [comment]
@michaelcahill, LGTM.

**Comment by michaelcahill** [comment]
Thanks, @daveh86 -- I'll merge.

**Pull request merged**
