### PR TITLE
The checkpoint ID is volatile, cache it so we don't keep reading it.

### PR DESCRIPTION
**Pull request by keithbostic**
@michaelcahill, this instruction is about 5% of the in-memory wtperf run-time.

I'm guessing this change might not be safe, so I put it on a separate branch to make it easy to discard.

### CODE REVIEW

**Comment by keithbostic** [comment]
@michaelcahill: if this change isn't safe, could we avoid the test by checking the session handle to see if it's a checkpoint, rather than reading the id itself? We have a ton of extra space in the `WT_TXN_STATE` structure, we could store anything we like there.

**Comment by keithbostic** [comment]
Reference WT-1907.

**Comment by michaelcahill** [comment]
autobuild: retest this please

**Comment by keithbostic** [comment]
autobuild: retest this please

**Comment by michaelcahill** [comment]
Thanks, @keithbostic, lgtm.

**Pull request merged**
