### PR TITLE
WT-5692 Revert a test change hoping to fix a Python hang

### PR DESCRIPTION
**Pull request by agorrod**
A test case was checking statistics after runWt, which closes
the connection, which led to using the wrong stats. That check
was re-ordered (along with other changes), after which some automate
testing started hanging. Revert that bit of the change to see if is
the cause.

### CODE REVIEW

**Comment by agorrod** [comment]
Evergreen retry

**Comment by lukech** [comment]
evergreen retry

**Comment by agorrod** [comment]
evergreen retry

**Comment by agorrod** [comment]
@kommiharibabu I don't know why this would fix the hang in Python testing, but it seems to (it passed three test cycles, which is a medium level signal). Would you mind reviewing and we'll see if it's good enough to mean we don't see test hangs any more.

**Pull request merged**
