### PR TITLE
WT-3849 Add timestamp validation to WT_SESSION::prepare_transaction

### PR DESCRIPTION
**Pull request by agorrod**
I'm re-opening this after a revert, since there were test/format failures after the first version was merged.

I suspect the failures were due to misuse of prepare by test/format.

An example of a failure:
```
[1522125514:954994][37349:0x7f8ad67ad700], t, WT_SESSION.prepare_transaction: prepare timestamp 217 not later than an active read timestamp 219 : Invalid argument
```

### CODE REVIEW

**Comment by bvpvamsikrishna** [comment]
autobuild : retest this please.

**Comment by bvpvamsikrishna** [comment]
@keithbostic 
Request to review the changes (i.e. [b03c73e](https://github.com/wiredtiger/wiredtiger/pull/4007/commits/b03c73ed409837906cbb5dd0e36c60cd84653a90) and [67e633d](https://github.com/wiredtiger/wiredtiger/pull/4007/commits/e7e633dedbce62d22016f9e5cd4a156a95f7cddf) I made to this pull request.  The changes are in test/format.
The changes are meant to synchronise the start of begin transaction with prepare transaction, so that prepare timestamp will be always greater than any active read timestamp.

**Comment by keithbostic** [comment]
@bvpvamsikrishna, this branch failed last night:
http://build.wiredtiger.com:8080/job/wiredtiger-test-format-stress-sanitizer-ppc/4647/console

**Comment by keithbostic** [comment]
@bvpvamsikrishna, I swapped `wiredtiger-test-format-stress-sanitizer-ppc` back to running against develop for now.

**Comment by bvpvamsikrishna** [comment]
autobuild : retest this please

**Comment by bvpvamsikrishna** [comment]
@keithbostic 
If the readers not synchronised with the prepare, they can see different read results, which is not expected. Hence it is required for this synchronisation.

I modified test/format to use a rwlock.  Could you take a look ?.

**Comment by keithbostic** [comment]
@bvpvamsikrishna 
 > If the readers not synchronised with the prepare, they can see different read results, which is not expected. Hence it is required for this synchronisation.

What is the path where a reader would see different results?

And are we talking only about snapshot-isolation?

**Comment by agorrod** [comment]
@keithbostic we've attempted to answer your questions in JIRA [here](https://jira.mongodb.org/browse/WT-3849?focusedCommentId=1854596&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1854596), since this feels like a useful record of design decisions...

**Comment by agorrod** [comment]
Thanks @bvpvamsikrishna this lgtm, I'm going to go ahead and merge.

@keithbostic we can remove the locking from test/format at the same time as we do the work in WT-4010. You and I also talked this morning about reducing how often test/format uses prepare - which I think is a good idea.

**Pull request merged**
