### PR TITLE
WT-10747 Remove out of date references to configure in WT documentation.

### PR DESCRIPTION
**Pull request by ddanderson**

### CODE REVIEW

**Comment by keitharnoldsmith** [comment]
Thanks for the images, Don! Normally for a doc review like this, I would download the branch and build the doc to read it that way. But this was even easier!

**Review by keitharnoldsmith — APPROVED** [review]
LGTM

Two minor stylistic points that I'll leave to your judgement whether to change:

- Capitalizing `Zstd` feels off to me. A lot of other documents treat it as all lower-case unless it is the first word of a sentence. See, for example, the [wikipedia page](https://en.wikipedia.org/wiki/Zstd). That would also match the way we treat snappy and zlib. (FWIW: LZ4 seems to be commonly used with the capital LZ.)
- Looking at that wikipedia page I see that Yann Collet is credited as the creator of zstd. So should we credit him(?) or Facebook?

**Comment by ddanderson** [comment]
Thanks @keitharnoldsmith.  I'll fix the Zstd -> zstd, I agree it looks more uniform.  As for the other, Yann is already credited on our page for lz4, for which he was creator and sole developer.  For zstd, there are other developers listed, so I'm going to stick with the Facebook credit.

**Comment by ddanderson** [comment]
evergreen merge

**Pull request merged**
