### PR TITLE
WT-8935 Failed transaction commit doesn't reset cursors.

### PR DESCRIPTION
**Pull request by keithbostic**
@luke-pearson, I messed this up the first time around -- `__wt_txn_commit()` gets called from a set of different places, and so the simplest fix is to put the cursor reset in that function.

### CODE REVIEW

**Comment by luke-pearson** [comment]
Does this still miss the scenario where `WT_TXN_ERROR` is set on the txn and we never get into `__wt_txn_commit` when called from `__session_commit_transaction`?

**Comment by keithbostic** [comment]
> Does this still miss the scenario where `WT_TXN_ERROR` is set on the txn and we never get into `__wt_txn_commit` when called from `__session_commit_transaction`?

I don't think so?

All of those paths should end up at the `__session_commit_transaction()` function's `err:` label with `ret != 0`, which should explicitly call `__wt_session_reset_cursors()`, followed by `__wt_txn_rollback()`.

**Review by luke-pearson — APPROVED** [review]
LGTM.

**Comment by keithbostic** [comment]
@luke-pearson, since you have a patch build running, I won't merge this until you approve that run.

**Pull request merged**
