### PR TITLE
WT-2410: Casting function pointers to different types

### PR DESCRIPTION
**Pull request by keithbostic**
@agorrod, for your review/consideration.

### CODE REVIEW

**Comment by sueloverso** [comment]
@keithbostic There is some sadness here with the explosion of new functions.  What about consolidation of functions that take an identical signature?  That is the direction I started in with the session notsup functions since there were 2 primary signatures.

**Comment by keithbostic** [comment]
@sueloverso, I thought about consolidating the functions based on signature, and decided against it, but I don't feel strongly.

If you feel strongly I'd make that change.

**Comment by keithbostic** [comment]
The branch with consolidated functions based on signature is #2510.

**Comment by agorrod** [comment]
Thanks @keithbostic lgtm - I'll merge.

**Pull request merged**
