### PR TITLE
Update test/format to use dd to make backup copies.

### PR DESCRIPTION
**Pull request by agorrod**
The hope is that using a direct IO dd command will uncover more crash-like problems.

### CODE REVIEW

**Comment by agorrod** [comment]
@keithbostic What do you think of this change? I'm hoping it will catch some missing fsync like failures.

@markbenvenuto Does test/format run on Windows? If so - do you know if this change will break the Windows build?

**Comment by keithbostic** [comment]
Sorry, Alex, didn't realized you'd already checked in with Mark.

I think I like the change, but we'll need some configuration magic.

FreeBSD's dd command doesn't have `iflag=direct`.

**Comment by markbenvenuto** [comment]
@agorrod Windows does come with dd. You can get `dd` from Cgywin or via http://gnuwin32.sourceforge.net/packages/coreutils.htm. I think for Windows we should stick to `copy` since I do not believe the `dd` emulation will be as rich as the Linux implementation in terms of doing direct I/O.

**Comment by agorrod** [comment]
There is no evidence this will find problems, and it causes platform compatibility issues. Close.

**Pull request closed without merging**
