### PR TITLE
WT-5966 4.4 downgrade can result in 4.2 core dumps if cells are ignored

### PR DESCRIPTION
**Pull request by keithbostic**
@agorrod, only lightly tested, I'm working on the testing framework next.

### CODE REVIEW

**Comment by agorrod** [comment]
I ran the MongoDB test that was failing against this branch and the segfault is gone, but I'm still seeing a (different) failure. Which is:

```
 assert: [0] != [1] are not equal
 doassert@src/mongo/shell/assert.js:20:14
 assert.eq@src/mongo/shell/assert.js:179:9
 testCRUDOperations@jstests/multiVersion/libs/config_chunks_tags_shared.js:138:5
 testChunkOperations@jstests/multiVersion/libs/config_chunks_tags_shared.js:172:5
 verifyChunksAndTags@jstests/multiVersion/libs/config_chunks_tags_shared.js:67:5
 @jstests/multiVersion/config_chunks_tags_upgrade_downgrade_cluster.js:125:1
 @jstests/multiVersion/config_chunks_tags_upgrade_downgrade_cluster.js:10:2
 Error: [0] != [1] are not equal :
 doassert@src/mongo/shell/assert.js:20:14
 assert.eq@src/mongo/shell/assert.js:179:9
 testCRUDOperations@jstests/multiVersion/libs/config_chunks_tags_shared.js:138:5
33701 [js_test:config_chunks_tags_upgrade_downgrade_cluster] 2020-04-08T02:59:30.807+0000 testChunkOperations@jstests/multiVersion/libs/config_chunks_tags_shared.js:172:5
 verifyChunksAndTags@jstests/multiVersion/libs/config_chunks_tags_shared.js:67:5
 @jstests/multiVersion/config_chunks_tags_upgrade_downgrade_cluster.js:125:1
 @jstests/multiVersion/config_chunks_tags_upgrade_downgrade_cluster.js:10:2
failed to load: jstests/multiVersion/config_chunks_tags_upgrade_downgrade_cluster.js
 exiting with code -3
```

The failure is a check that expects a collection to be empty, but is actually seeing a collection with one document in it.

**Comment by keithbostic** [comment]
@agorrod, I think it's safe, but 90e1814 deserves a close look, to ensure it's future-proof.

**Comment by keithbostic** [comment]
@agorrod, I think ` Error: [0] != [1] are not equal ` may be fixed by fcb0ae3.

**Comment by keithbostic** [comment]
> I'm also not completely clear on the process: will the changes to cell.h and cell.i also be made to the develop and mongodb-4.4 branches?

I was thinking about making the changes in the develop/4.4 branches (it's not even out of the question that checking the bit might be faster than checking the ts/txn pair, but develop/4.4 doesn't currently need the cell.i/cell.h changes). To be clear, I've been trying to keep the 4.2 & 4.4 cell code the same, so I'm in favor of this.

**Pull request merged**
