### PR TITLE
WT-7020 Assert the previous update timestamp of an item

### PR DESCRIPTION
**Pull request by kommiharibabu**
Validate the previous update timestamps of an item that was already
updated by another transaction while updating it by current transaction.

### CODE REVIEW

**Review by quchenhao — COMMENTED** [review]
@kommiharibabu Have you confirmed Alex's comment in the ticket that the sequence we set and read the commit and durable timestamps are correct?

**Comment by kommiharibabu** [comment]
@quchenhao The order the WT set timestamps is `commit` followed by `durable`. But I didn't the scenarios where both `commit` and `durable` are accessed when it is part of the update chain and uncommitted. But there are places where the update is formed before adding it into the update list, the order of setting is different.

**Comment by quchenhao** [comment]
@kommiharibabu The sequence before adding to the update chain should not matter.

**Review by quchenhao — APPROVED** [review]
lgtm

**Review by tetsuo-cpp — APPROVED** [review]
LGTM

**Pull request merged**
