### PR TITLE
Sweep file handle minimum

### PR DESCRIPTION
**Pull request by keithbostic**
@agorrod, here are the changes for #1856, that issue can be closed with the merge of this branch.

### CODE REVIEW

**Comment by keithbostic** [comment]
@agorrod, we have a minimum value for `file_manager.close_idle_time` of 1 second. That seems insane to me, it would make the sweep thread do a ton of work to no purpose. Why not make the minimum something much larger, like the default (30 seconds)?

Similarly, the minimum value for `file_manager.close_scan_interval` is 1 second, why would it ever be useful to scan every second?

**Comment by keithbostic** [comment]
@michaelcahill, @agorrod, @sueloverso, I defaulted `file_manager.close_handle_minimum` to 250.

I would support increasing that default to something like 2K (and I think it might make sense to have MongoDB configure it higher than 250, even if we default to 250).

Let's talk this one over: I've looked around, but I want to make sure I'm not missing something in some part of WiredTiger that's going to freak out with 10K open handles.

**Comment by agorrod** [comment]
@keithbostic 
> we have a minimum value for file_manager.close_idle_time of 1 second. That seems insane to me

There are two reasons I can think of for wanting a short ```close_idle_time``` and/or ```close_scan_interval```.

The first is stress testing - sweep does things nothing else in the system does. We've had bugs related to sweep racing closing handles - having the ability to sweep aggressively means we can uncover them more reliably. That was the original motivation for exposing the options as configuration values.

The second is a workload that has lots of tables (for example time series data split across tables) and only queries them occasionally. If we don't let the application set the sweep server to run aggressively, they have no other way to make sure that handles are being closed in a timely manner (thus they are more likely to run out of available handles).

As a concrete example of this, lets say an application has 10,000 tables containing time series data for a week. They are creating a new table every minute. Once a day they run analytics over the data - they know that they can only open ~2000 handles at a time on their system. So they run the analytics for each day using 1,440 handles at a time. If the sweep timeout is long, they need to wait for a long time after running the analytics before the handles are available again. The number of file handles can quickly explode if the application is creating indexes or using a complex schema on their tables.

The application has chosen to split their data across multiple tables, because the want a way to efficiently keep a time window of data, without deleting from the front of a single table. It also makes archive more practical.

**Comment by agorrod** [comment]
> I would support increasing that default to something like 2K

That would make me nervous. I've seen systems where the default handle limit is 1024 - to not start sweeping until we get to 2048 makes me nervous.

I think it'd definitely be worthwhile doing some testing with lots (thousands) of open tables. It's not something our regular testing does much of AFAIK.

**Comment by agorrod** [comment]
@keithbostic I didn't love using a statistics value as the basis for the functionality - so I shuffled that a bit.

I'd be happy for this to be merged now.

**Comment by keithbostic** [comment]
@agorrod, what's wrong with using a statistics value? We used to do that all the time for cache values, but that appears to have been removed, was there a choice at some point to not use statistics values for anything that's required to be correct?

**Comment by keithbostic** [comment]
@agorrod, I'm happy to leave the defaults low; we should update the appropriate configuration in the 
WiredTiger storage code to maybe 10K handles and 20 minutes idle? Do you know where that change goes?

**Comment by sueloverso** [comment]
I suspect statistics cannot be used for required values because they can be configured to not exist at all.  We have definitely seen big performance implications of frequently walking long lists.  We've mitigated that some by using the hashed buckets.  There are 512 buckets so an average of 20 per bucket when 10k files are open.

However Alex is right, my own AWS box has an open file limit of 16k which means I have to limit MongoDB tests to about 7-8K files at most because of collections multiplied by indexes plus overhead.

**Comment by agorrod** [comment]
> we should update the appropriate configuration in the 
> WiredTiger storage code to maybe 10K handles and 20 minutes idle? Do you know where that change goes?

I know where it goes, but it'll rely on having the new configuration option in WiredTiger first. So it will be simplest to make the changes there once the new configuration option has been pulled into the MongoDB source.

**Comment by agorrod** [comment]
> I suspect statistics cannot be used for required values because they can be configured to not exist at all. 

That was my first concern. Plus I knew I'd go looking for that field in ```WT_CONNECTION_IMPL``` at some stage and not understand why I couldn't find it.

**Comment by agorrod** [comment]
@sueloverso I should have referenced #1865 here. I did some measurements of the performance overhead related to having many file handles open.

I believe we should understand where the performance is going (hopefully to my test program?), but I wanted to separate the issues out, so we can get this change merged in sooner rather than later.

**Comment by agorrod** [comment]
I believe this one deserves a mention in the upgrading documentation, apart from that I'm happy for it to be merged now.

**Comment by keithbostic** [comment]
You cannot configure statistics to not exist at all (you can configure some of them to not be maintained, but you cannot remove the memory in the structures, which is where the value is maintained), so I don't think this change was necessary.

That said, I don't much care, if it's confusing to maintain "real" information in statistics fields, I'm OK with it living elsewhere.

**Comment by sueloverso** [comment]
Sorry - I was thinking of the changes we made from Sasha's tests, but they applied to --enable-verbose, not statistics.

**Comment by agorrod** [comment]
> I don't think this change was necessary

I concur - it worked before. I nearly pushed my change into a new pull request off this one, but decided to brute force my opinion instead..

**Comment by keithbostic** [comment]
autobuild: retest this please

**Comment by agorrod** [comment]
autobuild: retest this please

**Comment by agorrod** [comment]
autobuild: retest this please

**Comment by agorrod** [comment]
Thanks @keithbostic lgtm.

**Pull request merged**
