### PR TITLE
BACKPORT-4885 Fix the Windows CRC32 on blocks that aren't 8B aligned and/or multiples of 8B

### PR DESCRIPTION
**Pull request by keithbostic**

### CODE REVIEW

**Comment by agorrod** [comment]
@keithbostic I took a look at this, but I couldn't spot how the logic was switched (I believe you that it is) - it's going to need more time. Sorry for the delay.

**Comment by keithbostic** [comment]
> @keithbostic I took a look at this, but I couldn't spot how the logic was switched

I'm sorry, I should have been more explicit. The "fix" from @markbenvenuto was to add:
```
#if defined(_M_AMD64)
#include <intrin.h>
#endif  
```
to the source file. In the original change, that addition was made to `crc32-x86.c`, in the backport, that addition was made to `crc32-x86-alt.c`.

Mark, it would be great it you would weigh in on this as well. Thanks!

**Comment by agorrod** [comment]
@keithbostic this looks good to me. I pushed a big comment - if you are happy with that and it passes testing please go ahead and merge.

**Comment by keithbostic** [comment]
autobuild: retest this please

**Pull request merged**
