### PR TITLE
WT-12345 Return an error when setting a timestamp to an older value

### PR DESCRIPTION
**Pull request by etienneptl**
Same as https://github.com/wiredtiger/wiredtiger/pull/10443. New changes are from https://github.com/wiredtiger/wiredtiger/commit/8d986f551919c2e33304644c576663910c73df02.
Note that the next commit 0d1fe142149d08bc2bc83728a128afb41e73a010 is being merged through WT-12792 as it should be a standalone fix.

### CODE REVIEW

**Comment by etienneptl** [comment]
@pmacko86, can you have a look at 5b4393a8123efa60f89b73e4193a8285f87c1438 please?

**Comment by pmacko86** [comment]
> @pmacko86, can you have a look at [5b4393a](https://github.com/wiredtiger/wiredtiger/commit/5b4393a8123efa60f89b73e4193a8285f87c1438) please?

This would be okay, but I would prefer the code being commented out with a FIXME here, and also in the test with the stable timestamp. I'd like to eventually improve the test so that it verifies that both WT and model return the same error when trying to move the two timestamps backwards. Thanks!

**Comment by etienneptl** [comment]
Sounds good @pmacko86, added FIXME comments in 77de1790008ed7ceb6d99fdbdd48c5d2a62e70a0.

**Comment by etienneptl** [comment]
Adding @korteland to review the model changes as Peter is OOO.

**Review by korteland — APPROVED** [review]
Reviewed just the model change - LGTM.

**Pull request merged**
