### PR TITLE
WT-7457 Coverity: fix error in local store rename

### PR DESCRIPTION
**Pull request by ddanderson**

### CODE REVIEW

**Comment by ddanderson** [comment]
Ah - coverity found a real bug :-). I included some minimal testing for rename/remove which also exposed the problem.

**Comment by ddanderson** [comment]
@sueloverso, @keitharnoldsmith please hold off on review for a few minutes, there was a separate ticket for the OSX failure that I need to merge in.

**Comment by ddanderson** [comment]
@sueloverso, @keitharnoldsmith, okay after merging the OSX fix, this looks like it's going to do better with PR testing.
Ready to review!

**Review by keitharnoldsmith — APPROVED** [review]
LGTM!

**Comment by ddanderson** [comment]
@sueloverso, nvm this only needs one reviewer.

**Pull request merged**
