### PR TITLE
WT-11121 Remove the op timer check from __wt_txn_is_blocking.

### PR DESCRIPTION
**Pull request by luke-pearson**
One alternative here could be to change the RETRY mechanism to respect op_timers. Either change feels like it is trying to handle a layer of the stack that it shouldn't have knowledge of so I'm still on the fence about this.

### CODE REVIEW

**Comment by ddanderson** [comment]
@luke-pearson, for comparison, I created #9278 as the alternative you mention in your comment above.  Either approach makes sense to me.

**Comment by sueloverso** [comment]
I feel like the API retryable change hides things. It is easier to reason about the code in `wt_txn_is_blocking` than finding something in the API macro wrappers.

**Review by sueloverso — APPROVED** [review]
LGTM. We should double check that the op timer causing a rollback return is not something MongoDB counts on though.

**Comment by luke-pearson** [comment]
MongoDB does define an operation_timeout_ms in two places, if we remove it from those spots we may have unintended side effects but I think the place MongoDB is interested is in evict_lru.c, in `__wt_cache_eviction_worker` which allows the application to exit the the pulled into eviction loop if the op timer fires. That said i'm not 100% confident on that so I think @ddanderson's solution may be better for avoiding this.

**Comment by luke-pearson** [comment]
The comment does seem to imply they depend on {{WT_ROLLBACK}} I'll opt to go with @ddanderson's solution for now. 
```
        // the time limit has been exceeded on an operation in this transaction, WiredTiger returns
        // WT_ROLLBACK for that operation
```

**Comment by luke-pearson** [comment]
Closed as #9278 is the better solution.

**Pull request closed without merging**
