### PR TITLE
SLS-626 Rename oligarch tables to layered tables

### PR DESCRIPTION
**Pull request by korteland**
The main choice to disagree with here is whether to add the `_table` suffix in a bunch of places. I did it for consistency since most stuff already used the suffix, and there are some places where I think it's needed for clarity. Consider the oligarch logging code: we had a function `__wt_oligarch_log_slot_activate`, a naive renaming would yield `__wt_layered_log_slot_activate` but that sounds like the log might be layered, so I ended up doing `__wt_layered_table_log_slot_activate`.

I did one final `git grep -i olig` to verify the terminology is well and truly gone.

I would appreciate a prompt review here, so that if the PR is eventually accepted I don't spend a bunch of time resolving merge conflicts.

### CODE REVIEW

**Review by quchenhao — APPROVED** [review]
lgtm. Will you coordinate with the server team to change their usage as well?

**Comment by korteland** [comment]
> Will you coordinate with the server team to change their usage as well?

Yes, my plan is that the round of vendoring that includes this PR will also change the server's oligarch usage.

**Review by pmacko86 — APPROVED** [review]
LGTM, although that was mostly spot-checking...

**Review by ddanderson — APPROVED** [review]
LGTM!  Fantastic work.

**Pull request merged**
