### PR TITLE
WT-5083 Add mips64el support

### PR DESCRIPTION
**Pull request by lina-not-linus**

### CODE REVIEW

**Comment by wtbuild** [comment]
autobuild: Can one of the admins verify this patch?

**Comment by lina-not-linus** [comment]
I'm sorry that my mistake caused everyone trouble. I repulled the develop branch and recompiled the validation on mips64el, which is correct. thank you

**Comment by tetsuo-cpp** [comment]
autobuild: retest this please

**Comment by tetsuo-cpp** [comment]
Friendly ping @lina-not-linus. Any progress with this?

**Comment by lina-not-linus** [comment]
> Friendly ping @lina-not-linus. Any progress with this?

Sorry, I just saw it. On the mips64el machine, I changed the code to the diff.txt code and compiled the ELF file as "x86".
[MAKE-j1.log](https://github.com/wiredtiger/wiredtiger/files/3665224/MAKE-j1.log)
file ../dist/clang-format                                                                          
../dist/clang-format: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, with debug_info, not stripped

**Comment by lina-not-linus** [comment]
The compiled version is ELF for x86 architecture, not ELF for mips64el machines

**Comment by tetsuo-cpp** [comment]
> The compiled version is ELF for x86 architecture, not ELF for mips64el machines

Sorry. Could you please pull the latest commits from `develop`? That is a bug in our build tooling that has been fixed already.

**Comment by lina-not-linus** [comment]
> > The compiled version is ELF for x86 architecture, not ELF for mips64el machines
> 
> Sorry. Could you please pull the latest commits from `develop`? That is a bug in our build tooling that has been fixed already.

ok  I'm a pull

**Comment by lina-not-linus** [comment]
```
Making all in .
make[2]: Entering directory '/home/bvscode/work/wiredtiger/build_posix'
make[2]: Leaving directory '/home/bvscode/work/wiredtiger/build_posix'
Making all in lang/python
make[2]: Entering directory '/home/bvscode/work/wiredtiger/build_posix/lang/python'
(cd ../../../lang/python && \
    SWIG_NOT_FOUND_DURING_CONFIGURE -python -DPY_MAJOR_VERSION=$(/usr/bin/python -c 'import sys; print(int(sys.version_info.major))') \
    -threads -O -Wall -nodefaultctor -nodefaultdtor \
    -I/home/bvscode/work/wiredtiger/build_posix wiredtiger.i)
/bin/sh: line 1: SWIG_NOT_FOUND_DURING_CONFIGURE: command not found
make[2]: *** [Makefile:898: ../../../lang/python/wiredtiger_wrap.c] Error 127
make[2]: Leaving directory '/home/bvscode/work/wiredtiger/build_posix/lang/python'
make[1]: *** [Makefile:2298: all-recursive] Error 1
make[1]: Leaving directory '/home/bvscode/work/wiredtiger/build_posix'
make: *** [Makefile:985: all] Error 2
```
I "pull develop" again and this error occurred
[MAKE.log](https://github.com/wiredtiger/wiredtiger/files/3665323/MAKE.log)

**Comment by lina-not-linus** [comment]
"SWIG_NOT_FOUND_DURING_CONFIGURE:" this command was not found

**Comment by tetsuo-cpp** [comment]
> "SWIG_NOT_FOUND_DURING_CONFIGURE:" this command was not found

The Python test suite requires `swig`. Not sure what distro you're running but it's likely installable via your package manager.

**Comment by lina-not-linus** [comment]
> > "SWIG_NOT_FOUND_DURING_CONFIGURE:" this command was not found
> 
> The Python test suite requires `swig`. Not sure what distro you're running but it's likely installable via your package manager.

> "SWIG_NOT_FOUND_DURING_CONFIGURE:" this command was not found

The Python test suite requires `swig`. Not sure what distro you're running but it's likely installable via your package manager.

```
make clean
../configure --enable-python 2>&1 | tee CONFIGURE.log
make -j1 2>&1 | tee MAKE-j1.log
...
...
libtool: link: cc -std=c11 -D_GNU_SOURCE -O3 -g -o .libs/wt src/utilities/util_alter.o src/utilities/util_backup.o src/utilities/util_compact.o src/utilities/util_cpyright.o src/utilities/util_create.o src/utilities/util_downgrade.o src/utilities/util_drop.o src/utilities/util_dump.o src/utilities/util_import.o src/utilities/util_list.o src/utilities/util_load.o src/utilities/util_load_json.o src/utilities/util_loadtext.o src/utilities/util_main.o src/utilities/util_misc.o src/utilities/util_printlog.o src/utilities/util_read.o src/utilities/util_rebalance.o src/utilities/util_rename.o src/utilities/util_salvage.o src/utilities/util_stat.o src/utilities/util_truncate.o src/utilities/util_upgrade.o src/utilities/util_verbose.o src/utilities/util_verify.o src/utilities/util_write.o  ./.libs/libwiredtiger.so -lrt -ldl -lpthread -Wl,-rpath -Wl,/usr/local/lib                                                                
/home/bvscode/work/wiredtiger/src/docs/devdoc-schema.dox:12: warning: image file schema_generic.png\n\image is not found in IMAGE_PATH: assuming external image.
/home/bvscode/work/wiredtiger/src/docs/devdoc-schema.dox:12: warning: Illegal command n as part of a \image                         
/home/bvscode/work/wiredtiger/src/docs/devdoc-schema.dox:21: warning: image file schema_create.png\n\image is not found in IMAGE_PATH: assuming external image.
/home/bvscode/work/wiredtiger/src/docs/devdoc-schema.dox:21: warning: Illegal command n as part of a \image                         
/home/bvscode/work/wiredtiger/src/docs/devdoc-schema.dox:29: warning: image file schema_rename.png\n\image is not found in IMAGE_PATH: assuming external image.
/home/bvscode/work/wiredtiger/src/docs/devdoc-schema.dox:29: warning: Illegal command n as part of a \image                         
make[2]: *** [Makefile:2795: ../docs/index.html] Error 1
make[2]: Leaving directory '/home/bvscode/work/wiredtiger/build_posix'                                                              
make[1]: *** [Makefile:2298: all-recursive] Error 1
make[1]: Leaving directory '/home/bvscode/work/wiredtiger/build_posix'
```
[CONFIGURE.log](https://github.com/wiredtiger/wiredtiger/files/3666459/CONFIGURE.log)
[MAKE-j1.log](https://github.com/wiredtiger/wiredtiger/files/3666460/MAKE-j1.log)

**Comment by lina-not-linus** [comment]
> > > "SWIG_NOT_FOUND_DURING_CONFIGURE:" this command was not found
> > 
> > 
> > The Python test suite requires `swig`. Not sure what distro you're running but it's likely installable via your package manager.
> 
> > "SWIG_NOT_FOUND_DURING_CONFIGURE:" this command was not found
> 
> The Python test suite requires `swig`. Not sure what distro you're running but it's likely installable via your package manager.
> 
> ```
> make clean
> ../configure --enable-python 2>&1 | tee CONFIGURE.log
> make -j1 2>&1 | tee MAKE-j1.log
> ...
> ...
> libtool: link: cc -std=c11 -D_GNU_SOURCE -O3 -g -o .libs/wt src/utilities/util_alter.o src/utilities/util_backup.o src/utilities/util_compact.o src/utilities/util_cpyright.o src/utilities/util_create.o src/utilities/util_downgrade.o src/utilities/util_drop.o src/utilities/util_dump.o src/utilities/util_import.o src/utilities/util_list.o src/utilities/util_load.o src/utilities/util_load_json.o src/utilities/util_loadtext.o src/utilities/util_main.o src/utilities/util_misc.o src/utilities/util_printlog.o src/utilities/util_read.o src/utilities/util_rebalance.o src/utilities/util_rename.o src/utilities/util_salvage.o src/utilities/util_stat.o src/utilities/util_truncate.o src/utilities/util_upgrade.o src/utilities/util_verbose.o src/utilities/util_verify.o src/utilities/util_write.o  ./.libs/libwiredtiger.so -lrt -ldl -lpthread -Wl,-rpath -Wl,/usr/local/lib                                                                
> /home/bvscode/work/wiredtiger/src/docs/devdoc-schema.dox:12: warning: image file schema_generic.png\n\image is not found in IMAGE_PATH: assuming external image.
> /home/bvscode/work/wiredtiger/src/docs/devdoc-schema.dox:12: warning: Illegal command n as part of a \image                         
> /home/bvscode/work/wiredtiger/src/docs/devdoc-schema.dox:21: warning: image file schema_create.png\n\image is not found in IMAGE_PATH: assuming external image.
> /home/bvscode/work/wiredtiger/src/docs/devdoc-schema.dox:21: warning: Illegal command n as part of a \image                         
> /home/bvscode/work/wiredtiger/src/docs/devdoc-schema.dox:29: warning: image file schema_rename.png\n\image is not found in IMAGE_PATH: assuming external image.
> /home/bvscode/work/wiredtiger/src/docs/devdoc-schema.dox:29: warning: Illegal command n as part of a \image                         
> make[2]: *** [Makefile:2795: ../docs/index.html] Error 1
> make[2]: Leaving directory '/home/bvscode/work/wiredtiger/build_posix'                                                              
> make[1]: *** [Makefile:2298: all-recursive] Error 1
> make[1]: Leaving directory '/home/bvscode/work/wiredtiger/build_posix'
> ```
> 
> [CONFIGURE.log](https://github.com/wiredtiger/wiredtiger/files/3666459/CONFIGURE.log)
> [MAKE-j1.log](https://github.com/wiredtiger/wiredtiger/files/3666460/MAKE-j1.log)

I'm in trouble,An error was reported in the relevant section of the compile doc

**Comment by tetsuo-cpp** [comment]
Sorry for the delay @lina-not-linus. I haven't been able to look at this until now.

The error you posted looks like some kind of `doxygen` issue. I think it's easier if we just sidestep this for now.

- Could you please push my suggested changes to your fork? We have a build bot that will run the changes on our test infrastructure (although we don't test on MIPS).
- Were you previously building with `scons`? If so, could you please try the `scons` build again with my changes and confirm that you're able to successfully build?

If you're able to compile the `scons` build and our PR testing passes, I'm happy to merge this change.

**Comment by lina-not-linus** [comment]
> Sorry for the delay @lina-not-linus. I haven't had the chance to look at this until now.
> 
> The error you posted looks like some kind of `doxygen` issue. I think it's easier if we just sidestep this for now.
> 
> * Could you please push my suggested changes to your fork? We have a build bot that will run the changes on our test infrastructure (although we don't test on MIPS).
> * Were you previously building with `scons`? If so, could you please try the `scons` build again with my changes and confirm that you're able to successfully build?
> 
> If you're able to compile the `scons` build on your MIPS machine and our PR testing passes, I'm happy to merge this change.

Hi ，Sorry, I forgot to push the local develop branch to the repository, now I have pushed the changes you suggested last time to the repository. Thank you again for your trouble
develop:  https://github.com/Kernel-Team/wiredtiger/commit/77d1a28fd179714cb7deb0bafa461424de7f1c98

**Comment by tetsuo-cpp** [comment]
autobuild: retest this please

**Comment by lina-not-linus** [comment]
> LGTM! I assume the `scons` build is ok on your end?

If the "doc" problem is removed, it doesn't seem to be a big problem
```
bash autogen.sh
cd build_posix; ../configure
make
......
......
mv -f $depbase.Tpo $depbase.Po                                                                                                                                
depbase=`echo src/utilities/util_verbose.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\                                                                              
cc -DHAVE_CONFIG_H -I. -I..  -I../src/include  -std=c11 -D_GNU_SOURCE -O3 -g -MT src/utilities/util_verbose.o -MD -MP -MF $depbase.Tpo -c -o src/utilities/uti
l_verbose.o ../src/utilities/util_verbose.c &&\                                                                                                               
mv -f $depbase.Tpo $depbase.Po                                                                                                                                
depbase=`echo src/utilities/util_verify.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\                                                                               
cc -DHAVE_CONFIG_H -I. -I..  -I../src/include  -std=c11 -D_GNU_SOURCE -O3 -g -MT src/utilities/util_verify.o -MD -MP -MF $depbase.Tpo -c -o src/utilities/util
_verify.o ../src/utilities/util_verify.c &&\                                                                                                                  
mv -f $depbase.Tpo $depbase.Po                                                                                                                                
depbase=`echo src/utilities/util_write.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\                                                                                
cc -DHAVE_CONFIG_H -I. -I..  -I../src/include  -std=c11 -D_GNU_SOURCE -O3 -g -MT src/utilities/util_write.o -MD -MP -MF $depbase.Tpo -c -o src/utilities/util_write.o ../src/utilities/util_write.c &&\                                                                                                                     
mv -f $depbase.Tpo $depbase.Po
/bin/sh ./libtool  --tag=CC   --mode=link cc -std=c11 -D_GNU_SOURCE -O3 -g   -o wt src/utilities/util_alter.o src/utilities/util_backup.o src/utilities/util_$ompact.o src/utilities/util_cpyright.o src/utilities/util_create.o src/utilities/util_downgrade.o src/utilities/util_drop.o src/utilities/util_dump.o src/uti$ities/util_import.o src/utilities/util_list.o src/utilities/util_load.o src/utilities/util_load_json.o src/utilities/util_loadtext.o src/utilities/util_main.$ src/utilities/util_misc.o src/utilities/util_printlog.o src/utilities/util_read.o src/utilities/util_rebalance.o src/utilities/util_rename.o src/utilities/u$il_salvage.o src/utilities/util_stat.o src/utilities/util_truncate.o src/utilities/util_upgrade.o src/utilities/util_verbose.o src/utilities/util_verify.o sr$/utilities/util_write.o libwiredtiger.la -lrt -ldl -lpthread
libtool: link: cc -std=c11 -D_GNU_SOURCE -O3 -g -o .libs/wt src/utilities/util_alter.o src/utilities/util_backup.o src/utilities/util_compact.o src/utilities$util_cpyright.o src/utilities/util_create.o src/utilities/util_downgrade.o src/utilities/util_drop.o src/utilities/util_dump.o src/utilities/util_import.o sr$/utilities/util_list.o src/utilities/util_load.o src/utilities/util_load_json.o src/utilities/util_loadtext.o src/utilities/util_main.o src/utilities/util_mi$c.o src/utilities/util_printlog.o src/utilities/util_read.o src/utilities/util_rebalance.o src/utilities/util_rename.o src/utilities/util_salvage.o src/utili$ies/util_stat.o src/utilities/util_truncate.o src/utilities/util_upgrade.o src/utilities/util_verbose.o src/utilities/util_verify.o src/utilities/util_write.$  ./.libs/libwiredtiger.so -lrt -ldl -lpthread -Wl,-rpath -Wl,/usr/local/lib
/home/bvscode/work/wiredtiger/src/docs/devdoc-schema.dox:12: warning: image file schema_generic.png\n\image is not found in IMAGE_PATH: assuming external ima$e.
/home/bvscode/work/wiredtiger/src/docs/devdoc-schema.dox:12: warning: Illegal command n as part of a \image                                                  
/home/bvscode/work/wiredtiger/src/docs/devdoc-schema.dox:21: warning: image file schema_create.png\n\image is not found in IMAGE_PATH: assuming external imag$.
/home/bvscode/work/wiredtiger/src/docs/devdoc-schema.dox:21: warning: Illegal command n as part of a \image                                                  
/home/bvscode/work/wiredtiger/src/docs/devdoc-schema.dox:29: warning: image file schema_rename.png\n\image is not found in IMAGE_PATH: assuming external imag$.
/home/bvscode/work/wiredtiger/src/docs/devdoc-schema.dox:29: warning: Illegal command n as part of a \image                                                  
make[2]: 离开目录“/home/bvscode/work/wiredtiger/build_posix”
make[1]: 离开目录“/home/bvscode/work/wiredtiger/build_posix”

```

**Comment by tetsuo-cpp** [comment]
Thanks for your contribution @lina-not-linus! It's much appreciated.

**Comment by lina-not-linus** [comment]
> Thanks for your contribution @lina-not-linus! It's much appreciated.

Thank you. I appreciate your help

**Pull request merged**
