### PR TITLE
WT-8725 Consider checkpoint timestamp when updating the pinned timestamp

### PR DESCRIPTION
**Pull request by quchenhao**

### CODE REVIEW

**Comment by quchenhao** [comment]
@kommiharibabu Merging with the latest develop, the test is passing. Looks like the issue is caused by other commits.

**Comment by kommiharibabu** [comment]
@quchenhao I understand the reason behind this change. In future, if we want to allow pinned timestamp to go ahead of checkpoint timestamp for individual btree when each btree have its own history store, this solution doesn't work.

How about recording the pinned timestamp whenever the version cursor opens and using that timestamp always until the version cursor is finished similar to the checkpoint timestamp?

**Comment by quchenhao** [comment]
> @quchenhao I understand the reason behind this change. In future, if we want to allow pinned timestamp to go ahead of checkpoint timestamp for individual btree when each btree have its own history store, this solution doesn't work.
> 
> How about recording the pinned timestamp whenever the version cursor opens and using that timestamp always until the version cursor is finished similar to the checkpoint timestamp?

You mean in version cursor we check visibility differently? I think that doesn't work because other threads have a different view of visibility and would still free the updates. If you are talking about return a different value if version cursor is open from __wt_pinned_timestamp, I think it is also hard. That means that function also needs to obtain a lock.

**Comment by kommiharibabu** [comment]
> You mean in version cursor we check visibility differently? I think that doesn't work because other threads have a different view of visibility and would still free the updates. If you are talking about return a different value if version cursor is open from __wt_pinned_timestamp, I think it is also hard. That means that function also needs to obtain a lock.

Not a different visibility for the version cursor functionality. I mean whenever version cursor is started, get the pinned timestamp and save it in the `txn_global` structure and return it for all the operations similar like how the `checkpoint timestamp` is compared and returned. At the end of the version cursor, clear the saved pinned timestamp. This way we can block the pinned timestamp only for the table where the version cursor is opened along with its history store.

**Comment by kommiharibabu** [comment]
@quchenhao Do we still need this PR?

**Pull request closed without merging**
