### PR TITLE
[WT-3238] Cursor Compare and Equals in Java JNI incorrectly throw Exceptions

### PR DESCRIPTION
**Pull request by mwberry**
Refer to the Jira: https://jira.mongodb.org/browse/WT-3238

### CODE REVIEW

**Comment by wtbuild** [comment]
autobuild: Can one of the admins verify this patch?

**Comment by keithbostic** [comment]
@mwberry, thanks! We'll get this reviewed and merged shortly.

**Comment by ddanderson** [comment]
@mwberry, thanks for putting this together! I took a little different approach, that keeps the 'int' return value.  Also, we always make our pull requests against the develop branch, not master. A pull request that reflects these changes is in https://github.com/wiredtiger/wiredtiger/pull/3355, if you'd like to review it.

**Comment by mwberry** [comment]
#3355  Looks good to me!

**Comment by michaelcahill** [comment]
@mwberry, thanks for this pull request, I have merged the fix in #3355 so will close this one down.

**Pull request closed without merging**
