### PR TITLE
WT-7028 Skip sweep if checkpoint is gathering handles. (v4.2 backport)

### PR DESCRIPTION
**Pull request by etienneptl**

### CODE REVIEW

**Comment by lukech** [comment]
retest this please

**Comment by lukech** [comment]
retest this please

**Comment by lukech** [comment]
retest this please

**Comment by lukech** [comment]
retest this please

**Comment by etienneptl** [comment]
retest

**Comment by etienneptl** [comment]
retest this please

**Comment by sueloverso** [comment]
@etienneptl the problem is that the connection flags are overflowing. If you look at the 4.2 sources you'll see that `WT_CONN_WAS_BACKUP` is already at the maximum value of `0x80000000` and adding this new flag pushes it beyond 32 bits. That was solved in WT-6430, which was backported to 4.4 but not 4.2. So it looks like this ticket cannot be backported until WT-6430 is backported.

**Pull request closed without merging**
