### PR TITLE
Wtstats

### PR DESCRIPTION
**Pull request by keithbostic**
Clean up the wtstats documentation and build procedures.

### CODE REVIEW

**Comment by keithbostic** [comment]
@michaelcahill, I think this is ready to merge, a few comments:

- It requires a new step when building a release, you have to run the `dist/s_wtstats` script from the `dist` directory, that updates the `tools/wtstats/wtstats.html.template` file (installing npm as necessary), then you have to commit that file if it changed. The `s_wtstats` script downloads everything you need... I didn't update the creating-a-release Wiki page, but I will once this is merged.

- As we discussed, I put the `wtperf_stats` scripts back into place.

- I did something pretty horrible in 3b13cbe, inside `tools/doxfilter.py`. What I needed to do was to ref a generic page (the wtstats tool page), from per-language specific pages, and I couldn't figure out any way to do that. @ddanderson, if there's some other way to do that, would you please clean up my mess? If not, it seems like something we could reasonably add.

- For the record, I think the current license page is OK, there's nothing we need to change because none of these files are included in the library binary, it all comes under the `3rd party software included in the WiredTiger distribution` category.

@agorrod, @sue

**Comment by keithbostic** [comment]
@ddanderson: never mind -- I found `ref_single`!

**Comment by agorrod** [comment]
> It requires a new step when building a release, you have to run the dist/s_wtstats script from the dist directory, that updates the tools/wtstats/wtstats.html.template file (installing npm as necessary), then you have to commit that file if it changed. The s_wtstats script downloads everything you need... I didn't update the creating-a-release Wiki page, but I will once this is merged.

I'm behind the 8 ball here - so please forgive if I'm asking duplicate questions..

> you have to commit that file if it changed

Is the generated template always going to be committed in the tree now? If so why is this step part of the release build? If not - will the template be committed to the tree only on the master branch? It makes me nervous to commit a generated file into the tree, but to only update it once a release cycle.

Or is this more like the build_posix/reconf step? If so could it be added to the ```dist/s_release``` script so that there aren't any additional manual steps?

**Comment by keithbostic** [comment]
> Is the generated template always going to be committed in the tree now?

Yes.

> If so why is this step part of the release build? If not - will the template be committed to the tree only on the master branch? It makes me nervous to commit a generated file into the tree, but to only update it once a release cycle.

If it's part of the release process (before the release tree is copied), and committed, so the template file appears in the develop branch.

The template file is dependent on other tools (for example, npm). Like automake, it's something you should build/update before a release, but it won't generally be updated unless we're doing a release.

However, as part of building the template file, we download a bunch of other files into the tree, and those aren't updated or shipped. If we build the template file in the release tree we'd have to remove a bunch of files from the release tree, which isn't something we do now. (Maybe we could fix it to build in /tmp or something, I didn't think of trying that at the time.)

Regardless, I do want the template file in the develop branch, it's useful to have the template file around when checking-out a random development tree (re-building the template file takes some time and means installing tools we don't otherwise need.)

Anyway, if someone has a better idea, that'd be cool with me.

**Comment by agorrod** [comment]
If the file is in the develop tree, sounds to me like it should be in ```s_all```. If we are concerned about some machines not being able to do the ```s_wtstats``` step, we could print out a warning in ```s_all``` if ```s_wtstats``` fails, but not make it fatal.

**Comment by keithbostic** [comment]
Unless I misunderstand the release process, `s_all` gets run in the release tree, and running `s_wtstats` creates a bunch of files in the tree that aren't shipped or committed. So, adding `s_wtstats` to `s_all` has its own problems.

**Comment by agorrod** [comment]
The ```s_release``` script does a ```make distclean``` step, that I believe is designed to solve that problem. We could remove the uncommitted ```s_wtstats``` artefacts in that step.

TBH It seems a bit odd to me that we are pulling those Node packages into a local directory in the WiredTiger tree and not a node install directory, but I'm in deeper than my understanding now.

**Comment by keithbostic** [comment]
Yeah, that's kind of where I am, too (deeper than my understanding). Maybe the right thing is to build in a temporary area, then copy the template file into place, in which case we can make it part of s_all.

The only down-side is it takes awhile to build/run and not having npm can't be a fatal error, so building a release has to be cognizant of that, anyway...

**Comment by agorrod** [comment]
I think the amount of time to build could be alleviated by switching from ```cd tools/template && npm install``` to ```cd tools/template && npm install -g```. Then the node pacakges will be installed globally, not in a local subdirectory.

@rueckstiess is there a reason why the node packages would need to be installed locally?

**Comment by rueckstiess** [comment]
@agorrod, when installing globally you may run into issues with root access (default path is `/usr/local/lib/node_modules`) and with different conflicting versions of the same module. npm is designed around having all build dependencies installed locally by default, like Python's (non-default) virtualenv. AFAIK global installation is only recommended for modules you want to use in the shell as standalone utilities, not to resolve build dependencies.

I'm not familiar with WT release process so I don't have a better suggestion atm.

**Comment by michaelcahill** [comment]
OK, after discussion, we'll try with the template in the tree, updated each release.  It provides convenience for WiredTiger developers who check out a develop tree and want to generate statistics graphs on a test server.  It also means that the template will go into the MongoDB tree without further effort.

If that turns out to be a problem, we will revisit.

**Pull request merged**
