### PR TITLE
Fix a typo, add what will be a description section for pydoc

### PR DESCRIPTION
**Pull request by pgunn**
Starting to make "pydoc wiredtiger" give better results.

### CODE REVIEW

**Comment by wtbuild** [comment]
autobuild: Can one of the admins verify this patch?

**Comment by michaelcahill** [comment]
autobuild: add to whitelist

**Comment by michaelcahill** [comment]
autobuild: test this please

**Comment by michaelcahill** [comment]
Thanks, @pgunn -- lgtm.  I'll merge.

**Pull request merged**
