### PR TITLE
WT-11194 Fixing format load when reverse is enabled.

### PR DESCRIPTION
**Pull request by mickgraham-mongodb**
WT-11194 Fixing format load when reverse is enabled by committing more frequently during the load. Increasing the chances of reverse being enabled.

### CODE REVIEW

**Review by korteland — COMMENTED** [review]
I think there's something I'm missing here - there's already an entry in `config.sh` giving it a minimum value of 10, so I didn't think we needed code that manually did this.

Secondly, taking another look at the existing config code, it appears that mirroring will always disable reverse collation, even if explicitly set - is this worth revising?

**Comment by mickgraham-mongodb** [comment]
> I think there's something I'm missing here - there's already an entry in `config.sh` giving it a minimum value of 10, so I didn't think we needed code that manually did this.

The likelihood setting for reverse is 10 in config.sh (i.e. it should be randomly enabled 10% of the time). But due to reverse not being compatible with mirroring and only being used on row store, its practically far less. The change is to increase the likelihood by setting it more frequently on row store. The same could be achieved by just increasing the value from 10 to say 20 or even 30. 

> 
> Secondly, taking another look at the existing config code, it appears that mirroring will always disable reverse collation, even if explicitly set - is this worth revising?

Probably not as its not a key MongoDB use case (reverse) and it would be a much larger change.

**Comment by korteland** [comment]
>  But due to reverse not being compatible with mirroring and only being used on row store, its practically far less.

Ah, that makes sense now - thanks. Manually altering these probabilities isn't something we do for other configs, and it adds a reverse-specific thing to check if you're trying to figure it out, so I'd prefer to bump the probability than manually tweak it again.

> Probably not as its not a key MongoDB use case (reverse) and it would be a much larger change.

That's surprising to me - couldn't we just convert the `break` in `config_mirror` (in the section where we check if reverse collation is enabled) to a `return` (and alter the warning message)?

**Comment by mickgraham-mongodb** [comment]
Changed the probability instead of overriding the setting of reverse. Agreed with @korteland to leave the mirror behaviour as is.

**Review by korteland — APPROVED** [review]
LGTM! Thanks for fixing this.

**Pull request merged**
