### PR TITLE
WT-7202 Check for no count in assertion.

### PR DESCRIPTION
**Pull request by sueloverso**

### CODE REVIEW

**Review by keitharnoldsmith — COMMENTED** [review]
`conn->recovery_ckpt_snapshot_count` is initialized on a different conditional path than the one where we allocate `conn->recovery_ckpt_snapshot`.  

I don't know the specifics of how the metadata is set here. Is there any possibility we could wind up initializing the count but not the array?

**Comment by keitharnoldsmith** [comment]
FWIW, a simple alternative would be:

`WT_ASSERT(session, 
           conn->recovery_ckpt_snapshot == NULL ||
             (conn->recovery_ckpt_snapshot_count == counter &&
               conn->recovery_ckpt_snapshot[0] == conn->recovery_ckpt_snap_min &&
               conn->recovery_ckpt_snapshot[counter - 1] < conn->recovery_ckpt_snap_max));`

**Comment by sueloverso** [comment]
This is new code that I'm not familiar with. But my best reading is that there is a system-related k/v pair inserted into the metadata and this code reads that configuration string for the system information. Presumably that string is generated correctly in the sense that if it has a count as an item and that count is non-zero then there are non-zero other pieces of information. If the count string does not exist at all in the metadata, the `conn->recovery_ckpt_snapshot_count` is not set in `txn_recover.c` and it is zero from the calloc of the connection structure.

**Review by keitharnoldsmith — APPROVED** [review]
LGTM.  

I trust your judgement.

**Pull request merged**
