### PR TITLE
WT-6466 Closing a HS store cursor incorrectly clears WT_SESSION operation timers.

### PR DESCRIPTION
**Pull request by keithbostic**
@sulabhM, if we close a HS cursor it clears the per-WT_SESSION timers, and so operations that should be rolled back because they're pinning the system will continue to stall the system. Here's the typical stack:

```
__wt_btcur_search()
__cursor_func_init()
__cursor_reset()
__wt_page_release()
__wt_page_release_evict()
__wt_evict()
__wt_hs_cursor_close()
session->hs_cursor->close() (__curfile_close())
API_END_RET()
API_END()
__wt_op_timer_stop()
```

I changed the timer functions to ignore the call if the `WT_SESSION_IMPL.WT_SESSION_HS_CURSOR` flag is set, but that feels sloppy to me. I don't think the `WT_SESSION_HS_CURSOR` flag is particularly useful at this point, I think we'd be better served by testing/setting `WT_SESSION_IMPL.hs_cursor` against NULL as needed, and perhaps a per-cursor flag that indicates it's a HS cursor.

@agorrod, this bug may be worth fixing, it will prevent MongoDB cursors from being rolled back when they're pinning the system (but note that's limited to MongoDB cursors that have done updates because we can't roll back MongoDB readonly cursors).

KB EDIT:
The above statement is incorrect; this bug fix will not affect any MongoDB workload, it will only affect WiredTiger format testing, so we shouldn't merge it until the tree is generally open.

### CODE REVIEW

**Comment by keithbostic** [comment]
@keitharnoldsmith, I know you've been looking at HS cursor support, flagging you on this change.

**Comment by keithbostic** [comment]
Converting to draft until develop opens.

**Comment by agorrod** [comment]
> The above statement is incorrect; this bug fix will not affect any MongoDB workload, it will only affect WiredTiger format testing, so we shouldn't merge it until the tree is generally open.

@keithbostic I can believe that this won't alter the behavior of killing off old operations, I do think it'll mean that MongoDB per operation tracking will be broken.
Given that this change is simple, I'm inclined to get it in as-is now (assuming stress and MongoDB testing passes). Then follow up with a more elegant solution.

**Comment by keithbostic** [comment]
@agorrod 
> I do think it'll mean that MongoDB per operation tracking will be broken.

I'm confused how this is the case, can you please explain further?

**Comment by agorrod** [comment]
@keitharnoldsmith would you mind taking another look at this change? You've done some work related to history store cursors recently, it would be good to check that there isn't overlap.

Sorry for sitting on my reply @keithbostic I had been thinking about a different timing mechanism in my initial feedback. This change seems very reasonable to me.

**Comment by tammybailey** [comment]
evergreen retry

**Comment by agorrod** [comment]
The only stress testing failure was WT-6544, @tammybailey could we go ahead and merge this one?

**Comment by tammybailey** [comment]
@agorrod there's several failures in the MongoDB tests that I'd like to go through first.

**Comment by keitharnoldsmith** [comment]
@agorrod: I don't see any problems here.  As @keithbostic says in his original comment, the `WT_SESSION_HS_CURSOR` flag isn't particularly useful.  So much so that I've removed it in my PR for WT-6463!  So either this change or mine will have to update the checks against that flag to check instead against `session->hs_cursor != NULL`. But that's a trivial change.

**Comment by tammybailey** [comment]
@keitharnoldsmith are you saying that this PR requires changes before it can be merged? Or that one of the PRs (this one or WT-6463) requires changes to be compatible with each other?

**Comment by keitharnoldsmith** [comment]
> @keitharnoldsmith are you saying that this PR requires changes before it can be merged? Or that one of the PRs (this one or [WT-6463](https://jira.mongodb.org/browse/WT-6463)) requires changes to be compatible with each other?

Sorry I wasn't clear, @tammybailey. Either this or WT-6463 will have to change to be compatible.  I suggest going ahead and merging this PR as it. It will be trivial to update WT-6463 to address the use of the {{WT_SESSION_HS_CURSOR}} flag here.

**Comment by tammybailey** [comment]
Thank you @keitharnoldsmith! I'm going to merge this change and unblock you on WT-6463.

**Pull request merged**
