### PR TITLE
WT-2691 remove/disallow 'char' declarations without 'unsigned'.

### PR DESCRIPTION
**Pull request by ddanderson**
Also added casts so that -Wsign-conversion can be used on clang/OSX.

### CODE REVIEW

**Comment by ddanderson** [comment]
@keithbostic, this was slightly more disruptive than I'd hoped. I think it's worth it, what do you think?

I modified your egrep slightly, it should detect char arguments, but made no attempt to detect char x[10].

**Comment by keithbostic** [comment]
Thanks, @ddanderson.

I agree it's more disruptive than expected, but given the difficulty with detecting these errors, I'm inclined toward taking this change.

@michaelcahill, @agorrod, what do you think?

I tried futzing with gcc's `-fsigned-char` and `-funsigned-char` flags to see if I could get better error reporting, but I didn't find anything that helped. That said, we could change `--enable-strict` to set the `-fsigned-char` flag on gcc, it seems to me running tests with `-fsigned-char` should enable us to see these failures sooner?

**Comment by michaelcahill** [comment]
@keithbostic, @ddanderson -- I tried similar compiler flag combinations on GCC and clang and couldn't find anything that generated a warning for the original bug.

To be clear, what I believe is problematic is the conversion from ambiguous `char` to `int`, where values greater than unsigned 127 may or may not map to negative `int`s.  The issue is that from the compiler's point of view, there is no possible loss of information, since regardless of whether `char` is signed, `int` can hold the full range of possible values.

At the moment, the rule we are enforcing here seems somewhat arbitrary to me: as noted in the ticket, it's still easy to call `isprint` with a signed char and get undefined behavior.  If the proposal was to not allow bare calls to the functions in `ctype.h` and instead provide inline wrappers that take `u_char` args, I'd have more confidence that we're really avoiding the issue in future.

**Comment by keithbostic** [comment]
I guess I agree with the wrapper approach -- I don't have anything better to suggest.

There are roughly 20 "portable" ctype functions, I can't think of anything better than checking for all of them in `dist/s_style`.

It's tempting to disallow including `<ctype.h>` in any source files except the one wrapping the ctype functions we're actually using, but that means we don't inline the functions any more, which might hit performance?

**Comment by ddanderson** [comment]
I'm going to close this pull request, as I've implemented the wrapper approach, see #2818.

**Pull request closed without merging**
