### PR TITLE
WT-2630 Rename pluggable filesystem methods to avoid reserved names.

### PR DESCRIPTION
**Pull request by michaelcahill**
Use "fstr" consistently as the variable name and prefix for WT_FSTREAM.

### CODE REVIEW

**Comment by daveh86** [comment]
retest this please

**Comment by daveh86** [comment]
retest this please

**Comment by daveh86** [comment]
retest this please

**Comment by michaelcahill** [comment]
@keithbostic, can you please review this one?

**Comment by keithbostic** [comment]
Lgtm.

You didn't rename the `WT_FSTREAM.close` and `WT_FILE_HANDLE.close` methods, and close is potentially an issue. If that was deliberate, I won't argue (if `close` were ever to become a problem, we're in trouble, changing `WT_CURSOR.close`, or `WT_CURSOR.remove`, would be painful).

**Comment by michaelcahill** [comment]
@keithbostic, thanks for the review.  I did think about `close`, but as you note, we're already relying on that working in `WT_CURSOR`.  I'll merge...

**Pull request merged**
