### PR TITLE
WT-7634 Disable man page generation in Doxygen

### PR DESCRIPTION
**Pull request by lukech**
The test failure reported in the ticket was related to the recent Doxygen version upgrade change, that when the `test/evergreen/configure_combinations.sh` script is called the "make install" step found non-existed manpage directory (doc build was skipped due to unsupported Doxygen version 1.8.13 running on the Ubuntu 18.04 host). 

Had a discussion with @keithbostic and we think the man pages built by Doxygen are not very useful nowadays. We'd like to get it disabled in Doxygen configuration file as a way to address the test failure. The related makefile and s_docs contents are removed as well.

### CODE REVIEW

**Review by ddanderson — APPROVED** [review]
LGTM

**Review by keithbostic — APPROVED** [review]
lgtm

**Comment by keithbostic** [comment]
@alisonfel, this change removes man page creation & installation in the autoconf/automake world, does it require changes in the CMake build?

**Comment by alisonfel** [comment]
> @alisonfel, this change removes man page creation & installation in the autoconf/automake world, does it require changes in the CMake build?

@keithbostic This change won't impact the CMake build. The CMake build doesn't currently perform creation or installation steps for the man page docs.

**Pull request merged**
