### PR TITLE
WT-11875 Improve ex_access

### PR DESCRIPTION
**Pull request by y123456yz**
Background:
A friend investigated the performance of WT and wanted to try to use WT as the storage engine of their self-developed timing database. They consulted ex_access for read and write performance test. After the data was written in and the process was restarted, they did not know how to load the existing data.

As we can see from this example, loading existing history tables is a strong requirement, so it is recommended that ex_access be perfected

### CODE REVIEW

**Comment by y123456yz** [comment]
https://jira.mongodb.org/browse/WT-11875

**Comment by korteland** [comment]
Hi @y123456yz - thanks again for the pull requests. Just so you know, we've got an internal event on this week, so we likely won't be able to start reviewing your PRs until next week. Apologies in advance for the delay.

**Comment by y123456yz** [comment]
> Apologies in advance for the delay.

got it, thanks very much.

**Comment by korteland** [comment]
Closing this as mentioned on the Jira ticket.

**Pull request closed without merging**
