### PR TITLE
WT-2769 Update documentation to reflect correct limits of memory_page_max

### PR DESCRIPTION
**Pull request by sulabhM**

### CODE REVIEW

**Comment by sulabhM** [comment]
@agorrod : Please take a look

**Comment by agorrod** [comment]
Thanks @sulabhM. The change looks good to me - could you also add a comment into the source code where the limits are calculated, letting the user that they should update the API documentation if they make changes in the future?

**Comment by sulabhM** [comment]
@agorrod : Sure will update the pull request with the comment added.

**Comment by sulabhM** [comment]
@agorrod : Please take a look.

**Pull request merged**
