### PR TITLE
WT-8649 WT_SESSION methods cannot release scratch buffers unless reset or closing

### PR DESCRIPTION
**Pull request by keithbostic**
Don't release transactional information or scratch buffers if there are open cursors, they might still be in use.

@luke-pearson, I found this one when I pushed the fix for WT-8198 (#7404). In that ticket I changed the bulk load cursor to use a scratch buffer, and `test_bulk02` does a checkpoint while the bulk cursor is open. If checkpoint discards the session's scratch buffers, subsequent bulk cursor actions error out trying to use or close the scratch buffer.

I changed the session resource-discard function to leave the session's transactional information alone if there are cursors open, as well as the scratch buffers. I can't think of a way that would go wrong (given the session can't currently be in a transaction when we get into the session resource-discard function), but that could change in the future and I'd just as soon not debug that one if I'm wrong.

### CODE REVIEW

**Comment by keithbostic** [comment]
@AlexeyAnisimovAU, @luke-pearson is OOO, can you please review this one? -- Thanks!

**Comment by AlexeyAnisimovAU** [comment]
I don't know much about scratch buffers but I can see that `__wt_session_release_resources` is also called during eviction: https://github.com/wiredtiger/wiredtiger/blob/719945d56d3c7691106faaa8d31172df3f78b927/src/evict/evict_lru.c#L1134 I wonder how it works in that scenario? I assume it was working fine before WT-8198 (#7404).
Also, will this change increase RAM usage? Would it make sense to discard only `!WT_ITEM_INUSE` buffers?

**Comment by keithbostic** [comment]
> I don't know much about scratch buffers but I can see that `__wt_session_release_resources` is also called during eviction:
> 
> https://github.com/wiredtiger/wiredtiger/blob/719945d56d3c7691106faaa8d31172df3f78b927/src/evict/evict_lru.c#L1134
> 
> I wonder how it works in that scenario? I assume it was working fine before [WT-8198](https://jira.mongodb.org/browse/WT-8198) (#7404).

Because an eviction thread should have no open cursors, I don't expect to see any change in behavior. (But if eviction should open a cursor in the future, the same rules should apply.)

> Also, will this change increase RAM usage? Would it make sense to discard only `!WT_ITEM_INUSE` buffers?

This change will only increase RAM usage in the case of open cursors during a compaction or checkpoint call, which seems remarkably unlikely (and this has been broken forever).

We could certainly only discard `WT_ITEM_INUSE` buffers, but that seems more fragile to me.

I'm happy to find another reviewer if you aren't comfortable doing this one! I agree it's somewhat tricky -- it took a long time to find. :)

**Review by AlexeyAnisimovAU — APPROVED** [review]
Thank you for the explanation, LGTM!

**Pull request merged**
