### PR TITLE
WT-12781 Add the 8.0 branch in compatibility testing and doc generation

### PR DESCRIPTION
**Pull request by quchenhao**

### CODE REVIEW

**Comment by quchenhao** [comment]
patch build https://spruce.mongodb.com/version/661de7f78963380007dca4da/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

**Comment by etienneptl** [comment]
@lukech, are those steps defined in the wiki when creating a new release branch?

**Review by etienneptl — APPROVED** [review]
LGTM thanks for taking care of it

**Review by etienneptl — APPROVED** [review]

**Comment by etienneptl** [comment]
Please re-run a full patch build with the compat testing

**Comment by quchenhao** [comment]
Path test https://spruce.mongodb.com/version/66568527518a810007723b54/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC passes.

**Pull request merged**
