### PR TITLE
WT-2737 Scrub dirty pages rather than evicting them

### PR DESCRIPTION
**Pull request by keithbostic**
@agorrod, @michaelcahill, here is an initial set of changes, that re-instantiates pages resulting from multi-block reconciliations.

### CODE REVIEW

**Comment by daveh86** [comment]
retest this please

**Comment by daveh86** [comment]
retest this please

**Comment by daveh86** [comment]
retest this please

**Comment by sueloverso** [comment]
FTR - There is a bug in wtperf that is fixed on this branch.  The `create=false` configuration with `database_count=<greater than 1>` was broken.  The multiple-database code in `start_all_runs` always removed all subdirs unconditionally.

**Comment by agorrod** [comment]
@keithbostic The wtperf changes look good to me.

**Comment by daveh86** [comment]
retest this please

**Comment by daveh86** [comment]
retest this please

**Comment by michaelcahill** [comment]
Thanks @keithbostic, these changes lgtm.  I'll merge.

**Pull request merged**
