### PR TITLE
WT-5693 Re-enabling test_wt4105

### PR DESCRIPTION
**Pull request by luke-pearson**

### CODE REVIEW

**Comment by luke-pearson** [comment]
I linked 3 patch builds on the jira ticket where the test ran successfully, I restarted them all so there were 6x runs with a pass. Let me know if I need to do anything more here.

**Comment by quchenhao** [comment]
@luke-pearson You also need to change the timeouts in the test. It was 1 sec before.
```
while (++j < MODIFY_COUNT) {
        for (i = 0; i < NUM_DOCS; i++) {
            /* Position the cursor. */
            testutil_check(session2->begin_transaction(session2, "isolation=snapshot"));
            c->set_key(c, i);
            modify_entry.data.data = "abcdefghijklmnopqrstuvwxyz";
            modify_entry.data.size = strlen(modify_entry.data.data);
            modify_entry.offset = offset;
            modify_entry.size = modify_entry.data.size;
            /* FIXME-WT-6113: extend timeout to pass the test */
            (void)alarm(7);
            testutil_check(c->modify(c, &modify_entry, 1));
            (void)alarm(0);
            testutil_check(session2->commit_transaction(session2, NULL));
        }
        /*
         * Modify operations are done similar to append sequence. This has no bearing on the test
         * outcome.
         */
        offset += modify_entry.data.size;
        offset = offset < DATASIZE ? offset : 0;
        if (opts->verbose)
            printf("modify count %" PRIu64 "\n", j * NUM_DOCS);
    }

```

**Comment by luke-pearson** [comment]
@quchenhao the ticket description says the alarm should be increased to 15 seconds, which obviously doesn't need to happen anymore so I'll see how low we can get in evergreen. Or if we should just keep it as is.

**Comment by quchenhao** [comment]
@luke-pearson If we can't set it back to 1 sec, then we have a regression in this workload compared to 4.2.

**Comment by luke-pearson** [comment]
@quchenhao I agree, hence why I'll go experiment.

**Comment by quchenhao** [comment]
@luke-pearson One more thing, you need to enable the test in evergreen as well.

**Comment by luke-pearson** [comment]
@quchenhao unless I'm looking in the wrong place it is enabled on evergreen.

**Comment by quchenhao** [comment]
@luke-pearson OK, it is already enabled in evergreen.

**Pull request merged**
