### PR TITLE
Fix a bug in checkpoint where we committed the transaction too early.

### PR DESCRIPTION
**Pull request by agorrod**
It's not safe to commit the transaction before the files have been
synced to disk - if we do that the checkpoint can be rolled forward
in recovery before the checkpoint in the file has been updated.

Refs SERVER-18316

### CODE REVIEW

**Comment by agorrod** [comment]
@sueloverso I'm hoping this will help with the latest failure from SERVER-18316.

There was a window where we could roll forward a commit of the checkpoint data before the checkpoints had all been flushed to disk in the files.

**Comment by agorrod** [comment]
The test failure is weird to me. I haven't seen a bus error in forever.

The stack trace is:

```
#0  0x00007f0de3db8b77 in __wt_readlock (session=session@entry=0x1594fb0, 
    rwlock=0x61632c3d726f7373) at ../src/os_posix/os_mtx_rw.c:105
105		me = WT_ATOMIC_FETCH_ADD8(l->u, (uint64_t)1 << 32);
(gdb) where
#0  0x00007f0de3db8b77 in __wt_readlock (session=session@entry=0x1594fb0, 
    rwlock=0x61632c3d726f7373) at ../src/os_posix/os_mtx_rw.c:105
#1  0x00007f0de3db18d5 in __wt_lsm_tree_readlock (
    session=session@entry=0x1594fb0, lsm_tree=lsm_tree@entry=0x7f0dcc0da420)
    at ../src/lsm/lsm_tree.c:1132
#2  0x00007f0de3db2e52 in __wt_lsm_get_chunk_to_flush (
    session=session@entry=0x1594fb0, lsm_tree=0x7f0dcc0da420, force=0, 
    chunkp=chunkp@entry=0x7f0dd3ffeec0) at ../src/lsm/lsm_work_unit.c:81
#3  0x00007f0de3db3c8d in __lsm_worker_general_op (
    completed=<synthetic pointer>, cookie=0x15b7538, session=0x1594fb0)
    at ../src/lsm/lsm_worker.c:55
#4  __lsm_worker (arg=0x15b7538) at ../src/lsm/lsm_worker.c:122
```

I don't see how a change to when checkpoint commits a transaction would alter an atomic operation in LSM.

**Comment by agorrod** [comment]
autobuild: retest this please

**Comment by michaelcahill** [comment]
Thanks, @agorrod, lgtm.  Merging.

**Pull request merged**
