### PR TITLE
WT-8425 Push updates with the same commit timestamps in the out_of_order_ts_updates vector in hs_rec.c.

### PR DESCRIPTION
**Pull request by Siddhartha8899**

### CODE REVIEW

**Review by quchenhao — APPROVED** [review]
Why you remove the test?

**Comment by Siddhartha8899** [comment]
> Why you remove the test?

The python test test_prepare17.py and the code([here](https://github.com/wiredtiger/wiredtiger/pull/7413/files#diff-6149c4b4e4fb8725de1ee45f3093451b0598f1123ccdd792577fb6f347ab0053L257)) were written as part of WT-8151. 

The test was mainly testing the code changes made([here](https://github.com/wiredtiger/wiredtiger/pull/7413/files#diff-6149c4b4e4fb8725de1ee45f3093451b0598f1123ccdd792577fb6f347ab0053L257)). Since the code is removed as part of this PR, there is no need for the test itself.

The reason that part of the code is removed is that instead of changing the durable timestamps it is better for the assertion to hit if the timestamps are used incorrectly. For instance, it seems reasonable to assert if OOO durable_timestamps were provided.

**Review by kommiharibabu — APPROVED** [review]
LGTM

**Review by bvpvamsikrishna — APPROVED** [review]
lgtm

**Pull request merged**
