### PR TITLE
WT-11941 Fix incorrect timing information for reconciliation time

### PR DESCRIPTION
**Pull request by korteland**
The eviction generation check in `__wt_evict` is insufficient. We can arrive in reconciliation via checkpoint, in which case the eviction generation will still be zero. Thus, we clear the stats halfway through `__wt_reconcile`, leading to the start time of zero and ridiculous reported reconciliation times (e.g. 18 days on the ticket).

This fixes it by keeping the reconciliation start time on the stack, and only setting the shared structure's value after the opportunity for a reentrant eviction call has passed.

It also only reads the values once, I don't think other threads can trample these values but this makes it easier to reason about in any case.

### CODE REVIEW

**Comment by korteland** [comment]
PR failure appears to be the `clang-analyser` thing and unrelated to these changes.

**Review by ruby-oujo — APPROVED** [review]

**Comment by quchenhao** [comment]
Well done Will for solving the mystery. I think with your change,  the recorded timeline in the session structure may still be inconsistent.

I'm now questioning whether the entire timeline structure should live in the session. Can we declare the timeline structures on the stack? For example, in __wt_evict we declare the eviction timeline and in __reconcile, we declare the reconcile timeline. Then we pass the structures to the underlying function calls that fill the values. The reentrant calls will fill the values only for the reentrant calls. In this way, we can keep the main call and reentrant calls different and retain their information at the same time. I haven't thought this through and I'm not sure this can work. Sorry I'm in holiday mode (I'm typing on my phone) and cannot do more. Since it the information in the structure is only useful in a core dump so I think it is OK to move the entire structure to the stack.

**Comment by korteland** [comment]
> I'm now questioning whether the entire timeline structure should live in the session. Can we declare the timeline structures on the stack? For example, in __wt_evict we declare the eviction timeline and in __reconcile, we declare the reconcile timeline. Then we pass the structures to the underlying function calls that fill the values. The reentrant calls will fill the values only for the reentrant calls. In this way, we can keep the main call and reentrant calls different and retain their information at the same time. I haven't thought this through and I'm not sure this can work. Sorry I'm in holiday mode (I'm typing on my phone) and cannot do more. Since it the information in the structure is only useful in a core dump so I think it is OK to move the entire structure to the stack.

I really like this suggestion, and had a go. Unfortunately there are a couple of details that make it hard - eviction wants to log the image build and HS wrapup timings, so it accesses the reconciliation timeline. And it would be pretty ugly to pass this timeline structure all the way down, from all the places eviction can get called. So I think it needs to live in the session structure.

I can keep pursuing it if you want, but I think it's a harder change than it looks.

**Comment by quchenhao** [comment]
> > I'm now questioning whether the entire timeline structure should live in the session. Can we declare the timeline structures on the stack? For example, in __wt_evict we declare the eviction timeline and in __reconcile, we declare the reconcile timeline. Then we pass the structures to the underlying function calls that fill the values. The reentrant calls will fill the values only for the reentrant calls. In this way, we can keep the main call and reentrant calls different and retain their information at the same time. I haven't thought this through and I'm not sure this can work. Sorry I'm in holiday mode (I'm typing on my phone) and cannot do more. Since it the information in the structure is only useful in a core dump so I think it is OK to move the entire structure to the stack.
> 
> I really like this suggestion, and had a go. Unfortunately there are a couple of details that make it hard - eviction wants to log the image build and HS wrapup timings, so it accesses the reconciliation timeline. And it would be pretty ugly to pass this timeline structure all the way down, from all the places eviction can get called. So I think it needs to live in the session structure.
> 
> I can keep pursuing it if you want, but I think it's a harder change than it looks.

Thanks for the exploration.

**Comment by korteland** [comment]
@quchenhao I made the changes we discussed IRL, or at least my understanding of them. I think they're correct, but it does mean the stats are no longer timing the `__wt_page_is_modified` check (in debug mode), locking the page, or the `__wt_page_can_evict` check. Just thought you should be aware of that tradeoff here.

**Comment by quchenhao** [comment]
> @quchenhao I made the changes we discussed IRL, or at least my understanding of them. I think they're correct, but it does mean the stats are no longer timing the `__wt_page_is_modified` check (in debug mode), locking the page, or the `__wt_page_can_evict` check. Just thought you should be aware of that tradeoff here.

Thanks. I think not timing those checks is acceptable.

**Review by quchenhao — APPROVED** [review]
lgtm

**Review by ruby-oujo — APPROVED** [review]
LGTM :)

**Comment by korteland** [comment]
evergreen merge

**Pull request merged**
