### PR TITLE
WT-2999 Added test case that demonstrates a leak in cursor joins with custom extractors

### PR DESCRIPTION
**Pull request by ddanderson**

### CODE REVIEW

**Comment by ddanderson** [comment]
This is the user contributed test case (cleaned up) that demonstrates the leak for this ticket.

**Comment by ddanderson** [comment]
retest this please

**Comment by ddanderson** [comment]
@michaelcahill, can you review this please?

**Comment by michaelcahill** [comment]
Thanks @ddanderson, lgtm.  I'll merge.

**Pull request merged**
