### PR TITLE
WT-10082 failed: unit-test on macos-1014 [wiredtiger @ 8e8d4be3] (v6.1 backport)

### PR DESCRIPTION
**Pull request by svc-bot-sebb**
7310a360968bc47e9e99f6b9067723324ae8b357

### CODE REVIEW

**Review by quchenhao — APPROVED** [review]
lgtm

**Comment by quchenhao** [comment]
evergreen retry

**Comment by quchenhao** [comment]
@lukech How to authorize the evergreen patch build?

**Comment by lukech** [comment]
@quchenhao simply click into the Evergreen patch link, and hit the "authorise patch" button on the page.

**Pull request merged**
