### PR TITLE
WT-8509 Calling cleanup function is not required within tasks in evergreen.yml

### PR DESCRIPTION
**Pull request by Siddhartha8899**

### CODE REVIEW

**Review by lukech — COMMENTED** [review]
Are those `upload artifact` func calls are also duplication that could be removed?

**Comment by etienneptl** [comment]
> upload artifact

I think we cannot remove the `upload artifacts` call until we have found a solution. The `upload artifacts` calls within a task is different than the one called in the `post` section. In the `post` section, we append the `postfix` variable that represents the iteration we are currently executing.
It would be great to find a solution soon as we are currently uploading everything twice, which consumes space and time.
@Siddhartha8899 may have additional information.

**Review by etienneptl — APPROVED** [review]
LGTM

**Comment by Siddhartha8899** [comment]
> Are those `upload artifact` func calls are also duplication that could be removed?

Unlike the `upload artefact` function call embedded in the tasks, the `upload artefact` function call at the post-stage (or after the completion of the task), appends the `execution` suffix to the remote file name.
This implies that if the compile tasks rely on the post-stage to cache the WiredTiger binaries, then the remote-file name will have the execution suffix to it. Consequently, this forces us to add the execution suffix to the remote-file name when fetching these cached binaries and that creates other problems.
For instance, if only the dependent task is restarted, it will look for the binaries in the wrong place (will look for the remote file with execution suffix 1).
Also, we cannot get rid of the execution argument that is appended to the remote-file name at the post-stage as it is essential to cache directories from each execution. That said, having the upload artifact function in the compile tasks seems to be a good workaround for the same issues.

**Review by etienneptl — CHANGES_REQUESTED** [review]
@Siddhartha8899, @ajmorton and I found out that we should keep those cleanup commands.
As you see, we call `upload artifact` and then `cleanup`. This means that the `upload artifact` in the `post` commands does not upload anything. Effectively, if you look at the logs, it errors out.
Now we have removed the `cleanup` commands in each task, the `upload artifact` from the `post` commands will work and we will simply upload twice the same thing.
I think we should cancel that PR and don't make those changes.

**Comment by lukech** [comment]
@etienneptl @Siddhartha8899 thanks for the detailed analysis. Agreed we'd better not make changes. It would be nice to document the findings in the Jira ticket for our future selves.

**Comment by Siddhartha8899** [comment]
As per the comments above, I am closing the PR.

**Pull request closed without merging**
