### PR TITLE
WT-11184 Use explicit transaction in test/huge to prevent pinning of large page

### PR DESCRIPTION
**Pull request by RoeyMaor**
**Description of the issue:** (why test_huge fails)
1) Application thread does some cursor operation (like update) which causes a page in the btree to be referenced (active hazard pointer maintained for it after the end of the btree search walk). The page referenced is the one updated during the operation, lets call it page A.
2) At the end of the operation (for example at the end of __curfile_update), a call to CURSOR_UPDATE_API_END_STAT is made. This causes the transaction associated with the operation to be committed.
3) At the end of the transaction commit operation, while a reference to A is still maintained from step 1), a check for cache eviction is made.
4) Assume A is very large, such that it alone exceeds a cache threshold (let it be clean/update/dirty thresholds). This causes the thread that runs the txn commit to decide it needs to block until enough space has been evicted from the cache (this decision is made in __wt_cache_eviction_check). The thread will loop until it manages to find a page to evict (or until timeout and hard abort)
5) But, since evicting A is required to free enough space in the cache on the one hand, but evicting it is impossible due to the active reference, we are in a deadlock. The txn thread will loop until timeout and cause hard abort.

The same description above could be relevant even if there isn't one single huge page, but several smaller pages that are being referenced by several different sessions in parallel, such that all those sessions call wt_txn_commit.

**Solution suggestion:**
Just started to get into WT, so there is a good chance I missed some important spots. Would love your opinion and help in coming up with possible alternative solutions.

The following are 4 possible options to deal with this. This PR implements idea number 2).

1) Do not call __wt_cache_eviction_check at all at the end of wt_txn_commit, or in any other location where the same thread that calls it could be the one that holds references to a large enough amount pages (by memory size) - such that those force the cache eviction

2) before calling __wt_cache_eviction_check, which is a blocking call if the cache is above thresholds, traverse the session's active hazard pointers, and sum up their memory footprint. using this memory footprint decide if there is a danger of a deadlock (relative to the cache thresholds). **We won't call eviction at the end of transactions of sessions that reference a "majority" of the cache**. a "majority" of the cache is considered everything that is more than (1 / number of sessions) part of any cache threshold trigger.
The reason for this calculation is that we need to protect ourselves from the worst case in which N sessions each have some pages referenced (locked from eviction), and then try to evict to free up cache in a blocking manner. If all other pages are themselves referenced by other sessions, we are in a deadlock between the session threads as no page will be found for eviction.

3) Same as 2) but insert this logic inside __wt_cache_eviction_check, and not inside specific txn functions.

4) instead of calculating memory footprint from the hazard pointers, simply say that if there is any active hazard pointer for the session, don't call eviction from application threads.

https://jira.mongodb.org/browse/WT-11184

### CODE REVIEW

**Comment by RoeyMaor** [comment]
See discussion in https://jira.mongodb.org/browse/WT-11184
For the meantime, we opted to do a work around the problem in test_huge

**Review by ajmorton — COMMENTED** [review]
The change looks good. I'm not sure if our test suite results are public so I've added comments for the reported compiler warnings/typos.

**Comment by RoeyMaor** [comment]
@ajmorton fixed remarks.

**Comment by ajmorton** [comment]
Thanks @RoeyMaor. There's just one last formatting tweak that our clang-format tasks picked up with the new comment.
Could you navigate into `wiredtiger/dist` and run `./s_all`? After that we're good to go 👍

**Comment by RoeyMaor** [comment]
> Thanks @RoeyMaor. There's just one last formatting tweak that our clang-format tasks picked up with the new comment. Could you navigate into `wiredtiger/dist` and run `./s_all`? After that we're good to go 👍

done

**Comment by ajmorton** [comment]
All tests are passing, the changes look good, and the Contributors agreement has been signed.
I'll get this merged. Thank you @RoeyMaor for all your work!

**Review by ajmorton — APPROVED** [review]
LGTM

**Pull request merged**
