### PR TITLE
WT-11031 Fix RTS to skip tables with no time window information in the checkpoint (v6.0 backport)

### PR DESCRIPTION
**Pull request by svc-bot-sebb**
af1fb31f4ecfa4d8e267c1856d159e84e70c70b4

### CODE REVIEW

**Comment by etienneptl** [comment]
@kommiharibabu @korteland, are the three new files expected?

**Comment by kommiharibabu** [comment]
No. Something wrong with the backport. I will create a manual backport.

**Comment by etienneptl** [comment]
> No. Something wrong with the backport. I will create a manual backport.

Probably because those files don't exist on 6.0.

**Comment by kommiharibabu** [comment]
Wrong backport. Closing it to open a new one.

**Pull request closed without merging**
