### PR TITLE
WT-5682 Ensure that we can't apply modifies on top of tombstones

### PR DESCRIPTION
**Pull request by tetsuo-cpp**
I wasn't able to hit the condition where we apply modifies on top of an on-page value with a set time pair (I get `WT_NOTFOUND` when trying to modify). After chatting with @michaelcahill, we think that this case shouldn't be possible and may have existed from when the rules around modifies were laxer.

### CODE REVIEW

**Comment by tetsuo-cpp** [comment]
One of those blocks in `hs.c` was getting used as I'm now hitting my new assertion. Doesn't happen locally for me even when running `stress` on my other cores and it only seems to happen on Windows hosts. Frustrating...

I will look into it more later.

**Comment by agorrod** [comment]
Could we split up the cleaning of content in `hs.c` code into a different ticket if it's causing issues?

**Comment by tetsuo-cpp** [comment]
> Could we split up the cleaning of content in `hs.c` code into a different ticket if it's causing issues?

I think if we're hitting one of the asserts in `hs.c` then it should be possible to hit the asserts in `bt_ret.c`.

**Comment by tetsuo-cpp** [comment]
retest this please

**Comment by tetsuo-cpp** [comment]
retest this please

**Comment by tetsuo-cpp** [comment]
@michaelcahill @quchenhao 
I think this is ready to go in. The failure that I saw earlier doesn't reproduce locally or in Jenkins. Also, the other two red commits are due to some issue at the compilation stage (seems like a transitory Evergreen failure). I've run the PR testing a few more times and haven't seen the issue again. It's a bit difficult because there was no core dump in the artifacts for that job, but I don't think there's anything to suggest that it's related to this change.

**Pull request merged**
