### PR TITLE
Stop testing for compression library existance in test/format.

### PR DESCRIPTION
**Pull request by agorrod**
We now support builtin compression libraries, so it's possible to have compression without the separate libraries present.

### CODE REVIEW

**Comment by agorrod** [comment]
@keithbostic Does this change bother you? I tend to build with ```configure --with-builtins=snappy,zlib,bzip2``` but if I do that ```test/format``` complains and exits (even though it would work fine).

**Comment by michaelcahill** [comment]
Thanks, @agorrod, I'm a big fan.

**Comment by keithbostic** [comment]
Yeah, +1 here.

**Comment by agorrod** [comment]
autobuild: retest this please

**Comment by agorrod** [comment]
@keithbostic I've noticed recently that some configurations run for an extremely long time with test format (usually with a cache less than 10MB and large values configured). It'd be nice to limit these so they don't cause super long runs of the stress testing.

I've added in functionality to limit the runtime of a single test/format run to 20 minutes default (changed via the timeout configuration setting). I arbitrarily chose 20 minutes. I could have re-used the timer configuration but that didn't feel right to me.

Feel free to tweak and merge if you are OK with the functionality.

**Comment by keithbostic** [comment]
@agorrod, it makes sense to me to use the `timer` configuration:

- if ops == 0 and timer != 0, we run for a period of time,
- if ops != 0 and timer == 0, we run for a set of ops,
- if ops != 0 and timer != 0, we run for a set of ops, but not longer than a period of time,
- if ops == 0 and timer == 0, we do a bulk load and no operations.

**Pull request merged**
