### PR TITLE
WT-11883 Use C11's static_assert instead of WT_STATIC_ASSERT

### PR DESCRIPTION
**Pull request by ajmorton**
Code cleanup: Replace the `WT_STATIC_ASSERT` macro with C11's `static_assert` macro. 
I've chosen the naming style `static_assert` over `_Static_assert` as the latter will be deprecated in C23.
There's also a few other cleanup tasks, such as replacing the asserts that check structs begin with an `iface` field with a dedicated `WT_VERIFY_OPAQUE_POINTER` including a comment with why this is necessary.
Working through commit by commit may be easier for this PR. I've added commit message comments for any non-obvious changes.

### CODE REVIEW

**Review by etienneptl — APPROVED** [review]
LGTM! Nice cleanup. Please check trigger those asserts to make sure they work correctly.

**Review by clarissecheah — APPROVED** [review]
LGTM

**Comment by ajmorton** [comment]
Confirmed manually that each `static_assert` fires when I tweak the relevant values.
evergreen merge

**Comment by ajmorton** [comment]
evergreen merge

**Pull request merged**
