### PR TITLE
WT-9759 Bring down longest-running Pull Request task duration to below 25mins

### PR DESCRIPTION
**Pull request by lukech**
Changes include:

- add a new bucket to the existing unit-test-bucket tasks to offload some tests.
- add a new bucket to the existing unit-test-long-bucket tasks to match the above change.
- set `test_truncate20.py` to a long test (runs over 10mins), so that it's not triggered in PR builds. 

With the above changes, the longest-running task in a PR patch build (unit-test-bucket02) was below 25 mins.

### CODE REVIEW

**Comment by lukech** [comment]
@kommiharibabu I took a simple approach by setting the existing `test_truncate20.py` to a long test. If you see value in having a shorter-running version included in PR builds (assuming with smaller number of rows), I'm happy to support it.

**Review by ddanderson — APPROVED** [review]
LGTM!

**Review by kommiharibabu — APPROVED** [review]
LGTM

**Comment by luke-pearson** [comment]
On the latest commit windows testing still took 36 minutes, so there may be more work to do here.

**Comment by lukech** [comment]
@luke-pearson, yes this PR will help with reducing runtime for the `unit-test-bucket06` task on Windows builder. I left a comment on WT-10479.

**Pull request merged**
