### PR TITLE
Revert "WT-6301 Add short running stress jobs"

### PR DESCRIPTION
**Pull request by raviprakashgiri29**
Reverts wiredtiger/wiredtiger#5740

### CODE REVIEW

**Comment by raviprakashgiri29** [comment]
Reverting this change because `smoke.sh` gets executed in OS X machine and there is an issue of running `nohup` command in that machine. I will create another test which runs {{format test script}} for 10 minutes and tag it to "pull_request" to be part of PR testing.

**Comment by tammybailey** [comment]
@lukech did you want a Jira ticket created for reverting git commits?

**Comment by lukech** [comment]
WT-6301 had been included in a released version (i.e. 4.4.0-rc8), so we cannot reopen the ticket on Jira (the normal reverting process). I saw there's a follow-on ticket WT-6368 created so we should be fine (i.e. no need to write another Jira ticket for revert).

**Comment by raviprakashgiri29** [comment]
Thanks, @lukech & @tammybailey .

**Pull request merged**
