### PR TITLE
WT-4943 Fix  a bug where uncommitted updates could be discarded (BACKPORT - 4.0)

### PR DESCRIPTION
**Pull request by kommiharibabu**

### CODE REVIEW

**Comment by kommiharibabu** [comment]
This pull request must be merged once #4791 is merged

**Comment by kommiharibabu** [comment]
retest this please

**Comment by kommiharibabu** [comment]
@michaelcahill, There are some minor conflicts when applying this patch to 4.0

**Comment by bvpvamsikrishna** [comment]
@kommiharibabu this has to be rebased to mongodb-4.0 to resolve the conflict.

**Pull request merged**
