### PR TITLE
WT-7831 Clear transaction ids from previous run when repack the cell

### PR DESCRIPTION
**Pull request by kommiharibabu**
To support transaction id based rollback to stable, WT didn't reset
the transaction ids stored on the pages by not incrementing the
base_write_gen of each btree upon page access until rollback to stable
operates on that page. Once RTS operates on that page and reset the
remaining transaction ids that are present on the page that are stable.

### CODE REVIEW

**Review by quchenhao — APPROVED** [review]
lgtm

**Comment by hbokhari** [comment]
LGTM!

**Review by tetsuo-cpp — APPROVED** [review]
LGTM!

**Review by raviprakashgiri29 — APPROVED** [review]
Great finding @kommiharibabu.  Changes LGTM

**Pull request merged**
