### PR TITLE
WT-3930 Set the recovery timestamp at the end of recovery.

### PR DESCRIPTION
**Pull request by sueloverso**
We need to set it no matter if recovery actually ran or not.
@agorrod Please review. It is a fix for a bug @dgottlieb discovered where the recovery timestamp information was not set if `wt` was run in between.

### CODE REVIEW

**Comment by sueloverso** [comment]
autobuild: retest this please

**Comment by sueloverso** [comment]
@agorrod don't merge this yet. @dgottlieb is still seeing his problem so my changes have not yet effectively captured the situation he's seeing.

**Comment by sueloverso** [comment]
@agorrod please review. @dgottlieb and I discussed this and he's happy to get this merged.

**Comment by agorrod** [comment]
Thanks @sueloverso lgtm

**Pull request merged**
