### PR TITLE
WT-3336 Enable statistics by default in wtperf

### PR DESCRIPTION
**Pull request by daveh86**
Statistics gathering enabled on a 1s basis and output in JSON.

### CODE REVIEW

**Comment by daveh86** [comment]
@bvpvamsikrishna can you review this?

**Comment by bvpvamsikrishna** [comment]
@daveh86 changes are fine with me. No comments from my side.

**Comment by agorrod** [comment]
@daveh86 Is there a reason why you chose not to pull the `statistics=(fast)` configuration option out of the individual runners as well?

**Comment by daveh86** [comment]
@agorrod This was an oversight on my part due to WT-3456. I incorrectly did not believe we would need a mode set.

**Comment by agorrod** [comment]
Can you take the explicit `statistics=` lines out of the wtperf runners as well?

**Comment by daveh86** [comment]
Certainly. I had thought it best to leave those in to keep those tests explicit. Thinking further, this is wtperf, so we do not depend on the statistics configuration for anything within the run. Removing

**Comment by agorrod** [comment]
Thanks @daveh86 lgtm

**Pull request merged**
