### PR TITLE
WT-5380 Changed cursor_insert to cursor_update

### PR DESCRIPTION
**Pull request by andym03**
ticket: https://jira.mongodb.org/browse/WT-5380

Made the requested change, updating `cursor_insert` to be `cursor_update`

### CODE REVIEW

**Comment by wtbuild** [comment]
autobuild: Can one of the admins verify this patch?

**Comment by lukech** [comment]
ok to test

**Comment by lukech** [comment]
ok to test

**Comment by andym03** [comment]
retest this please

**Comment by boboeee** [comment]
LGTM.

**Pull request merged**
