### PR TITLE
WT-9774 Modify test_truncate15 to lessen cache pressure

### PR DESCRIPTION
**Pull request by mm-ng**
As `test_stat08.py` does not focus on testing the cache, it is fine to increase the cache size for this test.
For `test_truncate15.py`, instead of having a long-running transaction that could overflow the cache, break it down into one transaction per operation.

### CODE REVIEW

**Review by etienneptl — APPROVED** [review]

**Comment by etienneptl** [comment]
evergreen merge

**Review by agorrod — APPROVED** [review]
LGTM - thanks

**Comment by etienneptl** [comment]
The branch name is misleading, this PR only addresses test_truncate15.

**Comment by etienneptl** [comment]
We decided to close this PR. It needs more work.

**Pull request closed without merging**
