### PR TITLE
WT-12197 Improve assert error reporting for shell command call

### PR DESCRIPTION
**Pull request by ershov**

### CODE REVIEW

**Review by korteland — COMMENTED** [review]
I think the change is technically fine. But I'd like to talk (either here or offline) about the overall goal of the PR - this is all example code, and I think the clarity of seeing that we're doing a `system` call is worth the tradeoff in error reporting. But I can certainly have my mind changed on this.

**Comment by ershov** [comment]
Thanks @korteland for bringing up the fact that a similar PR was merged recently.

I'm re-working it to use the newly added functionality.

@adelinexchen Can you please review it :)

**Review by adelinexchen — APPROVED** [review]
lgtm :)

**Review by korteland — APPROVED** [review]
Glad the suggestion turned out to be useful :-)

LGTM!

**Comment by ajmorton** [comment]
evergreen merge

**Pull request merged**
