### PR TITLE
WT-11705 Fix name of history_store config item in __wt_verbose_config

### PR DESCRIPTION
**Pull request by y123456yz**
hs verbos bux fix,  check hs verbos config failed

### CODE REVIEW

**Comment by y123456yz** [comment]
[1695116465:107608][83310:0x7f176577a800], wiredtiger_open: [WT_VERB_DEFAULT][ERROR]: __config_check, 228: Value 'hs' not a permitted choice for key 'verbose': Invalid argument
ex_access: FAILED: access_example/52: wiredtiger_open(home, NULL, "create,cache_size=1M, statistics=(all),create,verbose=[    api=5,backup=5, block=5, block_cache=5, checkpoint=5, checkpoint_cleanup=5,checkpoint_progress=5,compact=5,    compact_progress=5,error_returns=5,evict=5,evict_stuck=5,evictserver=5,fileops=5,generation=5,handleops=5,log=5,    hs=5, history_store_activity=5,lsm=5,lsm_manager=5,metadata=5,mutex=5,out_of_order=5,overflow=5,read=5,reconcile=5,recovery=5,     recovery_progress=5,rts=5, salvage=5, shared_cache=5,split=5,temporary=5,thread_group=5,timestamp=5,tiered=5,transaction=5,verify=5,    version=5,write=5]  ", &conn): Invalid argument

**Comment by y123456yz** [comment]
https://jira.mongodb.org/browse/WT-11705

**Comment by ajmorton** [comment]
Hi @y123456yz thanks for your submissions! The verbose API is used by MongoDB's logging infrastructure so we'll need to make sure any changes don't impact the MongoDB layer for both this PR and https://github.com/wiredtiger/wiredtiger/pull/9654. I'll investigate this and get back to you.

**Comment by y123456yz** [comment]
@ajmorton 
got it, thanks.

**Comment by ajmorton** [comment]
@y123456yz `history_store` is one of the categories exposed to MongoDB for their systemLog.component.storage.verbosity config item so we'd prefer to leave this unchanged. It's also easier for external users to see the full name `history_store`rather than the shorthand `hs`. 

Is the motivation for this change that we use `history_store` for the configuration but `WT_VERB_HS` for the internal flag?

**Comment by y123456yz** [comment]
@ajmorton 
I'm not sure if the test code use verbose=[hs:xx] , If it does, we need to be compatible with both configurations(history_store and hs).

I run the test program to see the results.

thanks.

**Comment by y123456yz** [comment]
> @y123456yz `history_store` is one of the categories exposed to MongoDB for their systemLog.component.storage.verbosity config item so we'd prefer to leave this unchanged. It's also easier for external users to see the full name `history_store`rather than the shorthand `hs`.
> 
> Is the motivation for this change that we use `history_store` for the configuration but `WT_VERB_HS` for the internal flag?

I have run the unit test, it's ok.

**Review by ajmorton — APPROVED** [review]
Thanks @y123456yz! LGTM

**Comment by ajmorton** [comment]
evergreen merge

**Pull request merged**
