### PR TITLE
WT-10648 Return error on invalid timestamp usage for non standalone builds

### PR DESCRIPTION
**Pull request by kommiharibabu**

### CODE REVIEW

**Comment by kommiharibabu** [comment]
@agorrod and @mickgraham-mongodb I will create an MDB patch build to confirm that returning a failure on an invalid usage doesn't break anything.

**Review by agorrod — COMMENTED** [review]
Thanks @kommiharibabu - I'm keen to push this type of correctness checking to MongoDB as well as the standalone build.
OTOH: the decisions weren't made lightly regarding which were feasible when these changes were made originally. Could you find more context about why this enforcement wasn't possible with MongoDB last year, and describe in the ticket why it's safe now?

**Review by agorrod — APPROVED** [review]
LGTM - though I think we need to watch carefully for fallout in MongoDB.

**Review by mickgraham-mongodb — APPROVED** [review]
LGTM

**Comment by kommiharibabu** [comment]
evergreen merge

**Pull request merged**
