### PR TITLE
WT-8544 clang UBSAN failure

### PR DESCRIPTION
**Pull request by keithbostic**

### CODE REVIEW

**Review by AlexeyAnisimovAU — APPROVED** [review]
LGTM! It doesn't seem that crashes in `evergreen/ubuntu2004-asan` are related to the change.

**Review by acmorrow — APPROVED** [review]
This LGTM. I pulled the change locally and I'm running the UBSAN build. I'll follow up here with results.

**Comment by keithbostic** [comment]
With these changes, "make check" passes with the new UBSAN messages in the V4 toolchain.

@AlexeyAnisimovAU, @jeremythorp, would you please do another review pass, and then I'll merge?

**Comment by acmorrow** [comment]
This LGTM for my part. We are still seeing UBSAN issues in the server regression suite with V4, but the errors are no in the mongodb code, not arising in WT.

**Review by AlexeyAnisimovAU — APPROVED** [review]
LGTM!

**Pull request merged**
