### PR TITLE
WT-5702 Disable test_txn21.py temporarily

### PR DESCRIPTION
**Pull request by lukech**

### CODE REVIEW

**Comment by lukech** [comment]
Interestingly, after making the change to disable `test_txn21.py` on the test class level, the [unit-test-bucket07 task](https://evergreen.mongodb.com/task/wiredtiger_ubuntu1804_unit_test_bucket07_patch_907640ededf071b9effd369cb5350d758c155a6c_5e584dde32f41771b71b1b52_20_02_27_23_16_48) had run for over 1hr, seems stuck at the same test (though being disabled):

> [2020/02/28 10:22:43.256] test_txn21.test_txn21.test_operation_timeout_conn (subunit.RemotedTestCase)
> [2020/02/28 10:22:43.256] test_txn21.test_txn21.test_operation_timeout_conn ... skipped u'Temporarily disabled, see WT-5702 for context\n'

**Comment by lukech** [comment]
evergreen retry

**Comment by lukech** [comment]
evergreen retry

**Comment by lukech** [comment]
evergreen retry

**Comment by lukech** [comment]
I tried another 3 PR patch builds, one of them ran into the same issue. 
Pushed another change to disable the test on the function level (instead of the class level). Will see how the PR testing goes.

**Comment by lukech** [comment]
evergreen retry

**Comment by lukech** [comment]
evergreen retry

**Comment by lukech** [comment]
That function level disable change did not seem to help. Both of the 2 PR patch builds ([here](https://evergreen.mongodb.com/task/wiredtiger_ubuntu1804_unit_test_bucket07_patch_907640ededf071b9effd369cb5350d758c155a6c_5e5883ed3627e02a886d085a_20_02_28_03_07_26) and [here](https://evergreen.mongodb.com/task/wiredtiger_ubuntu1804_unit_test_bucket07_patch_907640ededf071b9effd369cb5350d758c155a6c_5e588407d1fe075029f300be_20_02_28_03_07_52)) seems ran into the same stuck/timeout issue. 
@agorrod @ddanderson do you have any idea?

**Comment by sueloverso** [comment]
@lukech I'm not familiar with evergreen enough, but in Jenkins, I'd log into one of the stuck machines while it is stuck and look at the directory to see what directory existed in `~jenkins/jenkins/workspace/<test-name>/build_posix/WT_TEST/test_<stuck-test>` and have an answer. Can you do the equivalent in Evergreen?

**Comment by ddanderson** [comment]
@lukech, I look a look at all the outputs, and wrote a script to match up lines with `....subunit.RemotedTestCase)` to lines with `....ok` or `....skipped`.  It looks like everything matches up - that is, I can't see any cases where a test has been "remoted" and hasn't given output claiming it completed. Specifically for the two tests that you disabled, it does show in the output that they are "skipped".

Could the test framework be losing track?  Hard to say. 

I created https://jira.mongodb.org/browse/WT-5709 to explore putting timeouts on functions, which may help in cases like this.

**Comment by lukech** [comment]
@sueloverso thanks. I downloaded the Evergreen artifacts, and found there's a directory `build_posix/WT_TEST/test_txn07.test_txn07.test_ops\(row.trunc-start.t1c.none\).4`, within which both the stderr.txt and stdout.txt files are blank. I guess that means it was `test_txn07` instead of the `test_txn21` got stuck.

**Comment by lukech** [comment]
@ddanderson Thanks for creating the ticket. I found a few cases that some tests timed out after 2 hrs in Evergreen. Putting some default timeout in Python tests should be able to help with pinpoint which test is timing out.

**Comment by lukech** [comment]
@agorrod is working on a fix through WT-5692. There's no point to follow up on disabling the test, so I'm going to close this PR.

**Pull request closed without merging**
