### PR TITLE
WT-2611 Modify wtperf to handle escaped quotes.

### PR DESCRIPTION
**Pull request by ddanderson**
This simple solution allows backquotes to get into the WT config parsing, where they are accepted but not transformed (see the JIRA comments), and then unescape them when we get them back from the parser.  

Question for reviewer: it may be preferred to put the unescape code in the config parsing within WiredTiger.  If we go that route, we probably need to allocate a buffer when needed (probably hanging off of WT_CONFIG) to hold the unescaped text.

Also wanted to make sure I wasn't missing some other way of escaping quotes before I went for a more involved solution.

### CODE REVIEW

**Comment by ddanderson** [comment]
@sueloverso, can you try this out?  If it works, there are ways to refine it.  Thanks!

**Comment by sueloverso** [comment]
Thanks @ddanderson.  I tried with a single backslash to escape a double-quote within a wtperf config file.  It is working as expected!  That is really helpful.  If you want to refine it, go ahead.

**Comment by sueloverso** [comment]
@ddanderson You mentioned wanting to refine this change possibly.  Is this PR ready for review and merge or is it still in-progress?

**Comment by michaelcahill** [comment]
@sueloverso, this seems okay to me: can you please do the review?

**Comment by sueloverso** [comment]
@ddanderson and @michaelcahill I did review and I am good with the current code.  Don mentioned wanting to refine the change.  I am happy to get this merged or to wait for that change.

**Comment by ddanderson** [comment]
@michaelcahill, my thought was that a better solution might be to put the unescape code in the config parsing within WiredTiger. Then anyone using config parsing gets the benefit. If we go that route, we probably need to allocate a buffer when needed (probably hanging off of WT_CONFIG) to hold the unescaped text.

Is it worth it? Should we merge this one in the meantime?

**Comment by sueloverso** [comment]
While that may be something to consider, I think we should merge this in the meantime.  If we want to move it into the library we can make the necessary changes here too at that time.

**Pull request merged**
