### PR TITLE
WT-2194: Java close callbacks should handle cursors that Java code did not open.

### PR DESCRIPTION
**Pull request by ddanderson**
This can now happen, as WiredTigerLAS.wt is opened internally.

### CODE REVIEW

**Comment by ddanderson** [comment]
@agorrod, can you review?

One thing to consider is whether the close callback should ever see cursors (like for WiredTigerLAS.wt) that were not explicitly opened by the application.  At the moment, "probably" only the Java/Python glue code uses the close callbacks so it doesn't matter much - I don't know if that will continue to be true?  So another solution would be to tag the WiredTigerLAS.wt cursor so it doesn't get sent to the callback.

**Comment by agorrod** [comment]
Thanks @ddanderson I think your solution is valuable, but ideally we wouldn't be making a callback for LAS cursors either. At the moment LAS cursors are special - so I think it would be good to exclude them from the callback as well.

That should be a matter of adding a clause to the cursor close loop in ``__session_close``, skipping any cursor with a URI that matches the ``WT_LAS_URI`` string.

**Comment by ddanderson** [comment]
@agorrod, I just pushed the change you described.  Tested it independently of the other fix to make sure it too would fix the problem.  Can you review?

**Comment by agorrod** [comment]
Thanks @ddanderson lgtm, I'll merge.

**Pull request merged**
