### PR TITLE
WT-4233 Change log corruption errors to warnings and truncate log

### PR DESCRIPTION
**Pull request by ddanderson**
Most reports of log corruption will now be reported as messages,
and they will not stop recovery from succeeding.

### CODE REVIEW

**Comment by ddanderson** [comment]
Not ready for review yet.

**Comment by ddanderson** [comment]
retest this please

**Comment by ddanderson** [comment]
@sueloverso can you please review?

**Comment by agorrod** [comment]
Thanks @ddanderson this lgtm - @sueloverso should review as well, and consider how this plays into the work in WT-4156.

**Comment by sueloverso** [comment]
My only issue is the use of the word `verbose` in several places (comments, test, etc). That has connotations to the `verbose=(log,recovery...)` settings to me. Should this function only print when some verbose setting is set? If not, maybe:
s/verbose/warning

**Pull request merged**
