### PR TITLE
WT-11602 Hide expected eviction failures from the application and don't rollback in case of errors

### PR DESCRIPTION
**Pull request by sulabhM**
The change addresses to issues:
1. __wt_cache_eviction_worker() loops for several times to evict page(s) and make space in cache. When exiting the loop, it reset the return code from the eviction as the caller/application doesn't need to handle the expected eviction failures. When we exit the loop early, as there is a timeout set, we are not hiding the eviction return codes from the caller. This could leak the expected eviction failures like EBUSY/WT_NOTFOUND to the application. This change moves the timeout check before eviction errors could occur.
2. When a timeout is set, we check if the application needs rollback to create more space in cache. If we do, a WT_ROLLBACK error is returned with a reason for the rollback set. The agreement is that a rollback reason will only be set when the API call fails with WT_ROLLBACK return code. To do so, we should check if the application needs a rollback only if there is no other error set. Before this change, we could return an internal error from eviction with a rollback set, which breaks the API expectations.

### CODE REVIEW

**Comment by sulabhM** [comment]
`azure-gcp-tiered-test-small` failure is unrelated to the change.

**Comment by luke-pearson** [comment]
It seems at least historically that callers of `__wt_cache_eviction_check` were supposed to handle the error themselves. Certainly both `__wt_txn_commit` and `__wt_txn_rollback` wrap the call in `WT_IGNORE_RET`. Is issue more a case of a caller not handling an error being thrown?

**Comment by sulabhM** [comment]
> It seems at least historically that callers of __wt_cache_eviction_check were supposed to handle the error themselves. Certainly both __wt_txn_commit and __wt_txn_rollback wrap the call in WT_IGNORE_RET. Is issue more a case of a caller not handling an error being thrown?

Specifically it is wt_page_in_func() calls __wt_cache_eviction_check() which calls __wt_cache_eviction_worker(). An error in worker then goes all the way to the application.

If you consider that the loop in worker is designed to reset the return code to 0 each time, it executes:
``for (initial_progress = cache->eviction_progress;; ret = 0) {```

I believe the intention there was to suppress ```EBUSY``` and ```WT_NOTFOUND``` and not return them to the callers of the worker function. It has likely that when we bail out of the loop early because a timeout is reached, we fail to set ret to 0.

**Comment by luke-pearson** [comment]
> I believe the intention there was to suppress EBUSY and WT_NOTFOUND and not return them to the callers of the worker function. It is likely that when we bail out of the loop early because a timeout is reached, we fail to set ret to 0.
We only ever bail out of the loop via break statement, so I don't think that the intent is that you leave the loop with ret = 0; there is no loop terminating condition.

**Comment by sulabhM** [comment]
> We only ever bail out of the loop via break statement, so I don't think that the intent is that you leave the loop with ret = 0; there is no loop terminating condition.

Ya, you are right. Let me think of an alternative solution.

**Comment by luke-pearson** [comment]
There is another potentially error code generating bit of this function further up:
``` WT_ERR(__wt_curhs_cache(session));```
Have you validated what error codes could be generated there?

**Comment by sulabhM** [comment]
> There is another potentially error code generating bit of this function further up:
>  WT_ERR(__wt_curhs_cache(session));
> Have you validated what error codes could be generated there?

I thought about errors from getting the HS cursor; we could get many error codes there. We potentially open the HS file from the disk and position and close the cursor - so, theoretically, we can get many errors. But, I decided that all those errors are not expected and should be passed to the caller. In all the cases, we should be able to get the HS cursor.

Do you disagree ?

**Comment by luke-pearson** [comment]
> Do you disagree ?

I think an error opening the HS cursor would certainly be bad, but a lot of the callers would swallow it anyway. I think for this PR it is okay but we may want to describe the semantic in further detail in another ticket. For example if failing to open a history store cursor is bad should we tell the caller of `__wt_txn_commit`?

**Review by luke-pearson — APPROVED** [review]
LGTM.

**Comment by sulabhM** [comment]
evergreen merge

**Comment by sulabhM** [comment]
> I think an error opening the HS cursor would certainly be bad, but a lot of the callers would swallow it anyway. I think for this PR it is okay but we may want to describe the semantic in further detail in another ticket. For example if failing to open a history store cursor is bad should we tell the caller of __wt_txn_commit?

I will create a separate ticket to consider refactoring and answering these questions.

**Pull request merged**
