### PR TITLE
WT-7407 test/format failure classifier

### PR DESCRIPTION
**Pull request by raviprakashgiri29**
This ticket is created as part of the Skunkworks project and is aimed to assist the test/format failure analysis/triaging with a “classifier” to generate a human-readable output for critical configuration properties.

### CODE REVIEW

**Comment by keithbostic** [comment]
@raviprakashgiri29, I took myself off the review list. I'm not the intended audience for the fix, and I don't have any opinions on it either way.

**Comment by lukech** [comment]
@raviprakashgiri29 thanks for working on it. It would be helpful to include a sample log output. 

The changes try to re-dump the list of format configuration parameters, which is a highlight for those mostly concerned format configuration parameters. I still feel it's not very human-readable. Could a section be appended right after the detailed configuration dump, something like
```
==========================
test/format run configuration highlights
==========================
Data source:                   file
Data type:                       row-store
Timestamp enabled:    yes
Prepared transaction:  yes
Backup:                           no
```
We can even skip dumping those parameters with "no" as the value, to make the highlight dump shorter. 

I believe the ultimate goal is to make the experience of triaging test/format failures better.

**Comment by raviprakashgiri29** [comment]
> @raviprakashgiri29 thanks for working on it. It would be helpful to include a sample log output.
> 
> The changes try to re-dump the list of format configuration parameters, which is a highlight for those mostly concerned format configuration parameters. I still feel it's not very human-readable. Could a section be appended right after the detailed configuration dump, something like
> 
> ```
> ======================================
> test/format run configuration highlights
> ======================================
> Data source:                   file
> Data type:                       row-store
> Timestamp enabled:    yes
> Prepared transaction:  yes
> Backup:                           no
> ```
> 
> We can even skip dumping those parameters with "no" as the value, to make the highlight dump shorter.
> 
> I believe the ultimate goal is to make the experience of triaging test/format failures better.

Thanks @lukech for flagging this.

Sample output below from format.sh run locally.

```
############################################
test/format run configuration highlights
############################################
backup=0
ops.prepare=0
runs.source=file
runs.type=row-store
transaction.isolation=snapshot
transaction.rollback_to_stable=0
transaction.timestamps=1
############################################
```

**Review by tammybailey — APPROVED** [review]
@raviprakashgiri29 this looks like a good start! I would suggest writing up a summary of the project and it's intended goal and getting feedback from the team on any additional information that could make this more useful. We could always merge this work and make a ticket for follow-up suggestions.

**Review by lukech — APPROVED** [review]

**Pull request merged**
