### PR TITLE
WT-2720 Change the return codes in run.py to flag on fails

### PR DESCRIPTION
**Pull request by daveh86**

### CODE REVIEW

**Comment by daveh86** [comment]
@agorrod, mind taking a look at this? It's a number of changes to the return codes for the unit-test suite.

**Comment by agorrod** [comment]
@daveh86 nice catch. I see two other suspicious uses of sys.exit in our Python suite:

```
test/suite/wttest.py
554:    sys.exit(not result.wasSuccessful())

test/suite/run.py
321:    sys.exit(not result.wasSuccessful())
```

Did you consider those and decide they were reasonable?

**Comment by daveh86** [comment]
@agorrod, those two seem alright to me.

The issue was that a return of False, meant returning 0. In two cases above, the False would only be the exit value when wasSuccessful() is True, this should be the correct behaviour.

**Comment by agorrod** [comment]
lgtm

**Pull request merged**
