### PR TITLE
WT-7876 Update rollback to stable test to use correct boolean values and update statistic checking logic.

### PR DESCRIPTION
**Pull request by Siddhartha8899**
…se in the restart options.

### CODE REVIEW

**Comment by Siddhartha8899** [comment]
@kommiharibabu The assumption made here is that after the shutdown (not crash) the rollback-to-stable on startup will not abort the updates since the updates would have already been aborted during the shutdown. Hence, the stats for the shutdown scenario for the keys removed, updates aborted and history store removed will be 0. 

But then, how do we ensure that the prepared updates were removed after the shutdown?

**Review by kommiharibabu — APPROVED** [review]
LGTM.

**Comment by kommiharibabu** [comment]
@Siddhartha8899 We are verifying the data that is present on the table is the way to verify there are no prepared updates written. If there are uncommitted prepared updates, the check with fail with `prepared conflict`.

**Review by luke-pearson — APPROVED** [review]
LGTM.

**Pull request merged**
