### PR TITLE
Update the sync_lsn after sync'ing and closing an earlier log file.

### PR DESCRIPTION
**Pull request by sueloverso**
Update the sync_lsn after sync'ing and closing an earlier log file and
make sure archive doesn't try to remove a file that is still in use.
Refs #1555 .

@michaelcahill We should talk this over.  Please review.

### CODE REVIEW

**Comment by wtbuild** [comment]
Test PASSed.

**Comment by wtbuild** [comment]
Test PASSed.

**Comment by wtbuild** [comment]
Test PASSed.

**Comment by wtbuild** [comment]
Test PASSed.

**Comment by michaelcahill** [comment]
Thanks, @sueloverso -- this lgtm.  I'll merge.

**Pull request merged**
