### PR TITLE
WT-8958 Improvements to ARM and other stress tests on evergreen

### PR DESCRIPTION
**Pull request by ajmorton**
The PR contains two changes:
- Enable SIMD instrinsics on x86 and ARM platforms when they are available so that WiredTiger tests are more in line with the mongo test configurations, and
- Add a new compiler flag `NON_BARRIER_DIAGNOSTIC_YIELDS` to remove the full memory barrier on diagnostic yields in case these barriers are suppressing memory sync issues in the surrounding code. New stress tests have been added to the ARM and x86 buildvariants with this flag enabled.

The final task in this ticket to clean up usage of `posix_configure_flags` in `evergreen.yml` has been split off into [WT-8986](https://jira.mongodb.org/browse/WT-8986) due to its large scope.

### CODE REVIEW

**Review by sulabhM — APPROVED** [review]
This is great work. Thanks @ajmorton

**Comment by sulabhM** [comment]
It looks good, and I have approved. The only concern is that it is difficult to see how SIMD instrinsics make a difference to the generated code?
@ajmorton, were you able to get a good sense of how the generated code differs?

**Comment by ajmorton** [comment]
> It looks good, and I have approved. The only concern is that it is difficult to see how SIMD instrinsics make a difference to the generated code? @ajmorton, were you able to get a good sense of how the generated code differs?

Thanks! 
SIMD instrinsics are limited in use. They're only present in [btree_cmp_inline.h](https://github.com/wiredtiger/wiredtiger/blob/develop/src/include/btree_cmp_inline.h) for faster comparison of large keys in `__wt_lex_compare` and `__wt_lex_compare_skip`. There's no changes in control flow, just an additional handful of lines for optimised compares.

**Review by agorrod — COMMENTED** [review]
Thanks - the change looks good to me. Does the documentation in src/docs/build-posix.dox also need to be updated?

**Comment by ajmorton** [comment]
Good point! `build-posix.dox` and `build-windows.dox` have been updates in [b731a44](https://github.com/wiredtiger/wiredtiger/pull/7707/commits/b731a44712784c0b3d023355a6675bfcd81166a6)

**Review by agorrod — APPROVED** [review]
lgtm

**Pull request merged**
