### PR TITLE
WT-2764 Fix a bug calculating the dirty percentage of cache.

### PR DESCRIPTION
**Pull request by michaelcahill**
Also fix the statistic measuring the total time for checkpoint
scrubbing.

### CODE REVIEW

**Comment by agorrod** [comment]
Lgtm. I believe it is possible for the cache size to be zero sometimes, but not when the eviction server is doing this calculation.

**Comment by michaelcahill** [comment]
autobuild: retest this please

**Comment by michaelcahill** [comment]
autobuild: please retest this

**Comment by michaelcahill** [comment]
autobuild: retest this please

**Comment by michaelcahill** [comment]
Thanks, @agorrod, I've refined checkpoint scrubbing some more to avoid slowness in cases where the cache is mostly clean but still wait for long enough to start making progress.  I've also rolled back the change that bumped the checkpoint generation of the metadata tree.

I'll go ahead and merge so this gets stress testing overnight.

**Comment by sueloverso** [comment]
@michaelcahill I'll keep an eye on things today and dig into them as tests run.

**Pull request merged**
