### PR TITLE
WT-13596 Create a Jupyter notebook that can simulate tree shapes and transitions

### PR DESCRIPTION
**Pull request by agorrod**
Implement a tool that can be extended to answer questions about internal tree-changing algorithms in WiredTiger

### CODE REVIEW

**Comment by agorrod** [comment]
@korteland and @ershov I'd appreciate if you can review this tools change. There is some more context about what the code is doing in the attached PR, or it should be possible for you to load the ipynb into Jupyter and give it a try. Let me know if you'd prefer for me to walk you through that instead.

**Comment by korteland** [comment]
@agorrod is this identical to the one we were using for disagg? I vaguely remember that one differed from the current WiredTiger in some way.

**Comment by agorrod** [comment]
It's identical to the one you saw a few weeks ago. It doesn't exactly match how a WiredTiger tree is built, but it's got the building blocks that we could make it close(r)

**Comment by korteland** [comment]
Fair enough - yeah if it's useful, people will likely pick it up and enhance it. LGTM :-)

**Review by korteland — APPROVED** [review]

**Comment by agorrod** [comment]
@ershov  - you asked via Slack if I could add a README. I've done that now - could you take another look?

**Review by ershov — APPROVED** [review]
It's a great starting point to learn about it interactively, thanks Alex

**Pull request merged**
