### PR TITLE
WT-7557 Fix wiredtiger-perf-long backup max latency

### PR DESCRIPTION
**Pull request by jiechenbo**
This ticket involves fixing a regression in latency total warnings graph inside the jenkins plot.

### CODE REVIEW

**Comment by jiechenbo** [comment]
Currently locally running the test again, to look at how many warnings are produced.

**Comment by jiechenbo** [comment]
This produces no warnings anymore, since upgrading twice the usual `max_latency`, @lukech let me know if you are good with this change

**Comment by lukech** [comment]
It may worth testing in the impacted Jenkins jobs by switching branch to your PR branch, if the workload concerned can be impacted by the hardware spec. Btw, do you mind updating PR title to describe the change made instead of the issue signature?

**Comment by jiechenbo** [comment]
@lukech I have removed the latency, since we don't need to track the number of warnings anyways. It is more of a config to test the performance of reads and writes on the machine compared to the normal run. I have verified that this change introduces no regression on the jenkin's plot. let me know if I can merge.

**Comment by lukech** [comment]
`max_latency` is currently configured in multiple other wtperf runners as well. I'm not quite sure about the impact of removing it. @sulabhM you may have a better idea than me, do you think it's safe to remove the parameter in the workload config here?

**Comment by sulabhM** [comment]
I am not really sure what is the intention of removing the parameter. If there are roughly N1 operations that consistently take longer than `max_latency`, and all of a sudden the warnings increase to N2, it means there is a perf regression. If we remove the configuration, how are we going to catch these regressions.

Maybe the intention of the ticket should be to find why warnings have increased and trying to get back to the former state.

**Comment by jiechenbo** [comment]
@sulabhM  Sorry the title of the ticket is misleading. Will definitely change the title. The context behind this ticket, is that the regression was introduced through adding a backup wtperf config from the backup project. This was later removed as a result of having not enough disk space in the machine. Since then, the machine has been upgraded to have more disk space, which allows the backup wtperf config to be added into the machine again. This will introduce the regression again. The aim of this ticket is to remove the regression introduced by the backup wtperf config. Since the backup wtperf config is mainly to be measured against the normal run. Therefore it seems more plausible to remove the max_latency introduced by backup wtperf config (since it will definitely increase the total warnings due to backup being configured)

**Comment by sulabhM** [comment]
Ok, if we expect the regression, I am okay with both 1. letting it be 2. setting a new max_latcncy so that total warnings in graphs remains the same. I do not think removing warnings altogether is the correct solution. Lets talk on zoom if I am still not getting it.

**Comment by jiechenbo** [comment]
Closing this PR, the jenkins plot shows little warnings now since re-adding the backup configuration in jenkins. This might be due to the fact of WT-7676. Will open again if warnings jump again.

**Pull request closed without merging**
