### PR TITLE
WT-8848 Add session statistics that counts a transaction's dirty bytes.

### PR DESCRIPTION
**Pull request by sueloverso**

### CODE REVIEW

**Review by ddanderson — APPROVED** [review]
LGTM

**Comment by sulabhM** [comment]
@sueloverso , this overall looks good to me. Have you tried running a MongoDB patch with the change? It is likely it will break the per operation statistics for slow operations. I looked at the relevant code. If you look at [WiredTigerOperationStats::fetchStats()](https://github.com/mongodb/mongo/blob/master/src/mongo/db/storage/wiredtiger/wiredtiger_recovery_unit.cpp#L102), and the next function `WiredTigerOperationStats::toBSON()` which converts the session statistics to bson. There is a map of statistics to bson fields which will cause an invariant failure if we add a new statistic. The mapped statistics also get listed in the documentation: https://www.mongodb.com/docs/manual/reference/database-profiler/#mongodb-data-system.profile.storage.

Another concern I have is that on completion of the slow operations a reset on the sessions statistics is called (at the end of the fetch function). In the case of MongoDB transactions that could have multiple WiredTiger operations the sessions statistics get reset often and MongoDB collects them and adds them to report to logging. Even if we exclude the bytes-dirtied statistic from the above bson mapping, we will have to think about the reset to 0 at the time of fetch call when the MongoDB transaction has not yet ended.

We will need a server ticket to research some of this.

**Review by sulabhM — APPROVED** [review]

**Comment by sueloverso** [comment]
@sulabhM can this be merged? Will it break MongoDB? Although I opened the PR, you could merge when everything is ready,

**Comment by sulabhM** [comment]
@sueloverso, this will break MongoDB at the moment. I am making a change in SERVER-68853 to allow WT-8848 to proceed. I will take care of merging WT-8848 when we get there.

**Comment by sulabhM** [comment]
Thanks, @sueloverso , I have merged the changes.

**Pull request merged**
