### PR TITLE
Modify log_scan callback args to send in next LSN. #1837

### PR DESCRIPTION
**Pull request by sueloverso**
@ddanderson Please review this change for the fix for log cursors and records that are compressed.

### CODE REVIEW

**Comment by ddanderson** [comment]
@sueloverso, I reviewed, the implementation changes looks good to me.

Looking at test_cursor08.py, I made a couple changes and pushed to this branch:
- The file had CR/LF throughout (an artifact of our email exchange I suppose), I changed to LF.
- Fixed how 'none' compressor is loaded, so it isn't skipped.
- Changed keys from 5 to 500.

I'm listing the changes here because the first one changed every line.

About the last change.  If I set nkeys = 5000 it still works.  If I set  nkeys = 50000 it doesn't work: all tests after bzip2 report
```
Traceback (most recent call last):
  File "/Users/dda/wt/git/log-cursor-compression/test/suite/test_cursor08.py", line 122, in test_log_cursor
    self.assertEqual(count, self.nkeys)
AssertionError: 0 != 50000
```
As I increase nkeys, it seems somewhere after nkeys=6500 I start seeing errors on some of the tests.

**Comment by sueloverso** [comment]
> As I increase nkeys, it seems somewhere after nkeys=6500 I start seeing errors on some of the tests.

Don, do you see a similar effect in either cursor07 (log cursor test) or txn07 (log compression test) if you increase the keys there?

**Comment by ddanderson** [comment]
Yes!  Here's with nkeys = 50000
```
$ wt-testsuite -v 2 cursor07
test_cursor07.test_cursor07.test_log_cursor ... FAIL
ERROR in test_cursor07.test_cursor07.test_log_cursor
test_cursor07.test_cursor07.test_log_cursor ... FAIL
ERROR in test_cursor07.test_cursor07.test_log_cursor

======================================================================
FAIL: test_cursor07.test_cursor07.test_log_cursor
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dda/wt/git/log-cursor-compression/test/suite/test_cursor07.py", line 99, in test_log_cursor
    self.assertEqual(count, self.nkeys)
AssertionError: 0 != 50000

======================================================================
FAIL: test_cursor07.test_cursor07.test_log_cursor
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dda/wt/git/log-cursor-compression/test/suite/test_cursor07.py", line 99, in test_log_cursor
    self.assertEqual(count, self.nkeys)
AssertionError: 0 != 50000

----------------------------------------------------------------------
Ran 2 tests in 1.579s
```

**Comment by sueloverso** [comment]
I see this running cursor07 on the master with 50000 keys too.  So this change did not introduce this bug.  I'll open a new issue.

**Comment by ddanderson** [comment]
The new issue #1840 existed before, and is independent of, this change.  Everything else looks good so I'm merging.

**Pull request merged**
