### PR TITLE
Don't allow "readonly" to be reconfigured on cursors.

### PR DESCRIPTION
**Pull request by michaelcahill**
refs #1467

### CODE REVIEW

**Comment by michaelcahill** [comment]
@keithbostic, are you okay with this?  If so, let's close out #1467.

**Comment by wtbuild** [comment]
Test FAILed.

**Comment by wtbuild** [comment]
Test PASSed.

**Comment by keithbostic** [comment]
@michael, this looks good to me, a couple of minor cleanups, I'll merge this as soon as it passes.

**Comment by wtbuild** [comment]
Test PASSed.

**Pull request merged**
