### PR TITLE
WT-5170 Enable mmap for all data files

### PR DESCRIPTION
**Pull request by fedorova**
To enable using mmap for all data files, set environment like so: 

   export WIREDTIGER_CONFIG="mmap=true"

The "mmap" option in WiredTiger was used to enable mmap on read-only checkpoints. I renamed that option to "mmap-checkpoint". If you use "mmap" in this branch, all data files will be accessed via mmap.

### CODE REVIEW

**Comment by fedorova** [comment]
autobuild: retest this please

**Comment by fedorova** [comment]
autobuild: retest this please

**Comment by keithbostic** [comment]
autobuild: retest this please

**Comment by keithbostic** [comment]
autobuild retest this please

**Comment by keithbostic** [comment]
autobuild retest this please

**Pull request closed without merging**
