### PR TITLE
Add functionality to test/thread to vary the number of operations on different tables, test sweep.

### PR DESCRIPTION
**Pull request by agorrod**
Add functionality to test/thread to vary the number of operations on different tables. Hopefully it'll let us construct workloads where tables are closed by sweep.

Refs #1870

### CODE REVIEW

**Comment by agorrod** [comment]
@keithbostic I decided it would be useful to have a test case where we are triggering sweep via a "real" workload. That prompted me to make the changes in here to test/thread (it was the best candidate of existing code I could find).

I don't yet have the workload sorted out, but it might be a good candidate if you get back to https://github.com/wiredtiger/wiredtiger/pull/1870#discussion_r28214500 today.

**Comment by keithbostic** [comment]
@agorrod, I agree (I hacked it into test/fops, though, instead of test/thread).

Maybe we should add multiple files to test/format instead? It would probably be interesting to get both backup and transactional testing across multiple files, and that should trigger sweeps as well?

**Comment by agorrod** [comment]
> into test/fops, though, instead of test/thread

fops was a candidate, but it doesn't add data into the files - I think the sweep changes are most interesting with relatively large files.

> Maybe we should add multiple files to test/format instead

I'm struggling a bit with testing some of these workloads. It feels to me as though we could use a new test tool, or possibly spend the energy to shuffle the test code to have some shared utilities (e.g: logging, timing, reporting, key/value generators and command line configuration) - that would make it simpler to create new testers rather than continually adding complexity to the ones we have.

I've had a desire for a couple of workloads that are difficult to replicate using our current set of tools:

* An oplog like workload with appending writes, while there are readers iterating through (via search), and dropping content from the beginning.
* Other collections coming and going some with lots of data, some with a small amount of data.
* Cursor operations that are short lived, but can span tables.
* Multiple threads

The above is a brain dump, and not that relevant to this particular pull request. I quite like the enhancements to test/thread, and I'll spend some more time today generating a setup that triggers sweep and gets handles thrown out. I think part of that will likely be adding throttling to operations.

**Comment by agorrod** [comment]
I've been running this updated test/thread code with:

```
./test/thread/t -R 10 -W 10 -v -F -n 50000000 -C ",file_manager=(close_handle_minimum=0,close_idle_time=1,close_scan_interval=1),checkpoint=(wait=5),cache_size=5GB,statistics=[all,clear],statistics_log=(wait=5)" -k 1000000
```

The configuration does:
* Creates 10 tables  (this is -F) with 10 million key/value pairs each.
* Sets the sweep server to operate aggressively.
* Enables checkpoints to ensure that sweep looks for handles to close
* Has 10 read (-R 10) and 10 write (-W 10) threads. The write threads do updates to the existing key space.
* Has a dataset that fits in cache (it's about 1GB total).
* Readers cycle through the tables. Thus if there are 20 readers and 10 writers, each table will have 2 readers and one writer.
* Allocates a certain number of ops to each thread (-v). The first write thread gets nops, then each subsequent writer gets half as many ops (min 1000). The process is repeated for reader threads. Tables that have a small number of writer ops end up with a small number of reader ops.
* Once a thread finishes it's allocated ops, it releases all resources and terminates.

The idea here is that the tables that have a small number of ops done to them will become idle, but there will be ongoing load on the other tables.

**Comment by agorrod** [comment]
I spent a fair while chasing #1886 when running this workload. It turned out that sweep wasn't considering files because bulk load left a ```session_inuse``` reference around.

**Comment by agorrod** [comment]
@keithbostic Could you review this, and merge it if you are happy? It's got nothing to do with the title of the pull request any more.

**Comment by keithbostic** [comment]
@agorrod, lgtm.

**Pull request merged**
