### PR TITLE
WT-11886 Cleanup expressions using boolean options

### PR DESCRIPTION
**Pull request by y123456yz**
bool Judgment comparison perfect，It is not appropriate to compare the bool type with 0

### CODE REVIEW

**Comment by y123456yz** [comment]
https://jira.mongodb.org/browse/WT-11886

**Comment by marcbutler** [comment]
HI @y123456yz ,

In `wtperf_inline_opt.h` the macro `#define DEF_OPT_AS_BOOL` expands to `int <name>` and not `bool <name>` nor `_Bool <name>`. So there is no type mismatch, given C unambiguously threats `0` as false, and not `0` as true. Using integers is this way a historical and still common idiom in C, though `bool` is now typically preferred.

I request the comparison be removed entirely.  There is already examples of this in the code for similarly declared variables `max_latency_fatal`, `log_like_table`, etc.

**Comment by y123456yz** [comment]
> HI @y123456yz ,
> 
> In `wtperf_inline_opt.h` the macro `#define DEF_OPT_AS_BOOL` expands to `int <name>` and not `bool <name>` nor `_Bool <name>`. So there is no type mismatch, given C unambiguously threats `0` as false, and not `0` as true. Using integers is this way a historical and still common idiom in C, though `bool` is now typically preferred.
> 
> I request the comparison be removed entirely. There is already examples of this in the code for similarly declared variables `max_latency_fatal`, `log_like_table`, etc.

@marcbutler 
I have optimized the code and unified the code style

**Review by marcbutler — APPROVED** [review]
LGTM

**Pull request merged**
