### PR TITLE
WT-6430 and WT-7028 backported through BACKPORT-8558 and BACKPORT-8526

### PR DESCRIPTION
**Pull request by sulabhM**

### CODE REVIEW

**Comment by sulabhM** [comment]
@sueloverso , this was not a clean backport since 4.0 has different flags than 4.2/4.4. Please have a quick review for these two changes.

**Review by sueloverso — APPROVED** [review]
LGTM. These appear to be the same as the 4.2 unclean backport.

**Comment by lukech** [comment]
The 2 commits being cherry-picked have `v4.2 backport` text included in the commit message, which is a bit confusing for a v4.0 backport. Is it easy to get it removed?

**Comment by sulabhM** [comment]
@lukech , I did not notice those v4.2 mentions in the message. I created another PR and removed those messages. Closing this PR in favour of https://github.com/wiredtiger/wiredtiger/pull/6338

**Pull request closed without merging**
