### PR TITLE
WT-6666 Start op timer when we configure it in rollback and commit

### PR DESCRIPTION
**Pull request by luke-pearson**

### CODE REVIEW

**Comment by luke-pearson** [comment]
This one is particularly difficult to write a unit test for, so I'd be interested in suggestions there.

**Review by keitharnoldsmith — APPROVED** [review]
LGTM!

**Comment by keitharnoldsmith** [comment]
Regarding testing:

I don't see how you can add testing in the current python framework.  

The existing test {{test_txn21.py}}, merely makes sure that you can set {{operation_timeout_ms}} without error.  It doesn't test that setting it causes WT to timeout long-running operations. So I suppose you could argue that you aren't changing the client API, so the existing tests of the client API cover this change.

Even if you wanted to test that {{operation_timeout_ms}} correctly interrupts long-running operations you'd need a way to inject appropriate delays (maybe work for PM-1991?) and you would need to know what behavior to expect.  FWIW, the {{wiredtiger_open()}} documentation says that if the timeout is exceeded, "an operation **may** return a WT_ROLLBACK error."  So even if we could create a scenario where the timeout would trigger, how do you know if you should/shouldn't expect WT_ROLLBACK?

**Comment by luke-pearson** [comment]
@keitharnoldsmith, when configured for rollback or checkpoint it'll never return WT_ROLLBACK, it'll only time out the cache eviction check. But I agree that this is too difficult to test.

**Pull request merged**
