### PR TITLE
WT-10135 Bump WiredTiger version to 11.2.0

### PR DESCRIPTION
**Pull request by lukech**
(This is the 2nd try after the initial merge got reverted)

Bump the WiredTiger version to 11.2.0 right after cutting the 11.1.0 release.
Add coverage for version 11.2 in Python compatibility tests (required for minor version bumps).

### CODE REVIEW

**Review by etienneptl — APPROVED** [review]
LGTM

**Comment by lukech** [comment]
evergreen merge

**Comment by lukech** [comment]
evergreen merge

**Comment by lukech** [comment]
The test failure (WT-10148) is not related to changes in this PR.

**Pull request merged**
