### PR TITLE
WT-3486 Discard obsolete updates as part of re-instantiating updates based on the lookaside table.

### PR DESCRIPTION
**Pull request by agorrod**

### CODE REVIEW

**Comment by agorrod** [comment]
I've opened this branch again since the first attempt at merging led to a stress test failure:
http://build.wiredtiger.com:8080/job/wiredtiger-test-format-stress-sanitizer-ppc/3152

**Comment by keithbostic** [comment]
I'm sorry about the failure, @agorrod.

I pushed a fix in 8118951.

**Comment by keithbostic** [comment]
@agorrod, I can't request you as a reviewer on #3561 because you opened the PR. I think it's ready to merge if you agree with the fix.

**Comment by agorrod** [comment]
lgtm

**Pull request merged**
