### PR TITLE
Don't create bloom filters on the oldest chunk unless configured.

### PR DESCRIPTION
**Pull request by agorrod**
The recent bulk load change meant that we sometimes created a bloom
filter on the oldest chunk when running compact.

Caused performance to drop by 50% in wtperf medium lsm compact job.

### CODE REVIEW

**Comment by agorrod** [comment]
@sueloverso Could you review this change for me please? Hopefully it isn't controversial. It fixes the performance drop in:
http://build.wiredtiger.com:8080/job/wiredtiger-perf-med-lsm-compact/plot/

In my local testing

**Comment by sueloverso** [comment]
@agorrod thanks.  lgtm although it took a bit to wrap my head around it.  I'll merge and we'll watch the plots.

**Comment by sueloverso** [comment]
It looks like this change made evict-lsm and medium-lsm-compact happy.  The one that did not change and is still going slow after the bulk load change is medium-lsm-multi.

**Comment by agorrod** [comment]
Thanks @sueloverso

> it took a bit to wrap my head around it

Was it the horrible condition statement that was confusing, or where I put the fixes? I probably could have been clearer that the change to compact is actually just an optimization - the key change was the one in the work unit.

**Comment by sueloverso** [comment]
Since you asked, there were two things: First, the conditional in lsm_tree.c took a bit because I didn't see the set of parens at first glance and so I spent a while being confused.  Second, the comments talk about "the oldest chunk" and the code looks at the WT_LSM_BLOOM_OLDEST flag.  I initially forgot that the flag meant the `bloom_oldest` config setting.

**Comment by agorrod** [comment]
Thanks @sueloverso. I've pushed a change to simplify the conditional.

**Pull request merged**
