### PR TITLE
WT-9953 Fix call to obsolete flush_tier API from within tiered hook.

### PR DESCRIPTION
**Pull request by ddanderson**

### CODE REVIEW

**Review by keitharnoldsmith — APPROVED** [review]
LGTM. Thanks!

**Comment by ddanderson** [comment]
@keitharnoldsmith, here's a quick fix for the recent failure.  I added the extra (normally post-PR) hook tests to the set of tests running here.  I'm out for about 4 hours, so if you like, and it looks good, feel free to merge.

**Comment by keitharnoldsmith** [comment]
@ddanderson: Apparently I can't add you as a reviewer on a PR you created :-)

There were a few additional failures uncovered by your change. See my comments on the Jira ticket. I'll let you review my changes and decide whether you'd rather handle the failing tests differently.

**Comment by ddanderson** [comment]
evergreen merge

**Pull request merged**
