### PR TITLE
WT-13396 Review eviction logging categories

### PR DESCRIPTION
**Pull request by raviprakashgiri29**
This pull request has the following changes: 
- To enhance readability and maintainability, combine all eviction-related messages under a single category WT_VERB_EVICTION.

### CODE REVIEW

**Comment by quchenhao** [comment]
@raviprakashgiri29 Is there any change needed in the Mongodb after this change?

**Comment by ershov** [comment]
I like this change. Having multiple categories for eviction was confusing.

**Comment by raviprakashgiri29** [comment]
> Is there any change needed in the Mongodb after this change?

@quchenhao Yes, to align with the WiredTiger logging changes, the MongoDB logging configuration should be adjusted to use "eviction" instead of the obsolete categories "evict," "evict_stuck," and "evictserver.

**Review by kommiharibabu — APPROVED** [review]
LGTM

**Comment by raviprakashgiri29** [comment]
I plan to make the changes in another ticket [WT-13415](https://jira.mongodb.org/browse/WT-13415)

**Pull request closed without merging**
