### PR TITLE
WT-11121 Check if a transaction is running in op timer fired.

### PR DESCRIPTION
**Pull request by luke-pearson**

### CODE REVIEW

**Comment by ajmorton** [comment]
This isn't part of the current change set, but while we were investigating this ticket I got caught out by the `API_RETYRABLE_END` macro using a `do {} while(1)` loop. It wasn't obvious to me as I'm used to our `do {} while(0)` boilerplate and didn't look carefully for the `while(1)`. Can we add a comment inside this macro that highlights we're using `while(1)` instead of `while(0)`?

**Comment by luke-pearson** [comment]
> Can we add a comment inside this macro that highlights we're using `while(1)` instead of `while(0)`?

I think that's a good idea I'll add that change.

**Comment by luke-pearson** [comment]
@ajmorton added in [281a336](https://github.com/wiredtiger/wiredtiger/pull/9307/commits/281a336cbca1d25b9b33fcc078a050ef54ccd219)

**Comment by luke-pearson** [comment]
@ddanderson I have confirmed that the issue doesn't reproduce.

**Review by ddanderson — APPROVED** [review]
LGTM!

**Review by bvpvamsikrishna — APPROVED** [review]
lgtm

**Comment by luke-pearson** [comment]
evergreen merge

**Pull request merged**
