### PR TITLE
WT-8701 Fix test_backup07.py to test the creation of new tables when backup cursor is open

### PR DESCRIPTION
**Pull request by jiechenbo**
From #6291, The ticket involved refactoring all the backup tests to use a class in the means to simplify all the backup tests. This however caused backup07 to lose the flavour for the original of its testing. I have fixed this and still used the refactored portions.

### CODE REVIEW

**Review by sueloverso — CHANGES_REQUESTED** [review]
These changes are correct but two other things are needed.

**Comment by jiechenbo** [comment]
Thanks! @sueloverso, I realised when modifying the test that I have potentially hit a bug. I have closed the backup cursor before closing the log backup cursor. This hits an assert inside `__backup_stop` function when closing the backup cursor. What should the expected behaviour in this case?

**Comment by sueloverso** [comment]
@jiechenbo you should make sure you close the duplicate cursor before closing the backup cursor. The assert is checking for correct usage. However, it could be argued that it could be reasonable to return an error instead. I think that should be a new ticket.

**Comment by jiechenbo** [comment]
Thanks! @sueloverso, I have created a ticket around that edge case [WT-8760](https://jira.mongodb.org/browse/WT-8760). The PR is ready to be reviewed as well.

**Review by fionaochee — APPROVED** [review]
LGTM!

**Pull request merged**
