### PR TITLE
WT-5255 configuring format with direct I/O support on Evergreen can take an excessive time to run

### PR DESCRIPTION
**Pull request by keithbostic**

### CODE REVIEW

**Comment by keithbostic** [comment]
jenkins - retest this please
evergreen - evergreen retry

**Comment by keithbostic** [comment]
@lukech, @tammybailey: I'm not sure what to do about this Evergreen failure in`test_stat08`. It's failing consistently on Evergreen, but all of my changes are in `format`, it's hard to understand how there could be overlap. Is there something I'm missing?

**Comment by tammybailey** [comment]
@keithbostic it looks like that Windows test has been failing intermittently for a while.

**Comment by lukech** [comment]
evergreen retry

**Comment by lukech** [comment]
evergreen retry

**Comment by agorrod** [comment]
@keithbostic is this change waiting for anything else? It looks good to me.

**Comment by keithbostic** [comment]
@agorrod 
>  is this change waiting for anything else? It looks good to me.

@lukech pushed back on this (at my request), and I think he's right, the solution is a bit fragile. I'm trying to do something better, I'll get it pushed shortly.

**Comment by keithbostic** [comment]
@tammybailey, @lukech, I think this is a more robust solution, using signals.

Each phase of a format run is limited to a 5 minute timer, and if we don't complete in that period of time, the run exits. In the case of a `direct I/O` configuration, we'll exit success after a timer fires, so we won't see noise, otherwise, we'll exit with a failure and drop core.

Hopefully, that will prevent hitting the Evergreen timeout.

**Comment by tammybailey** [comment]
I don't think we need to send a successful return if the timer is exceeded. (Ideally the Evergreen waterfall page could display status other than PASS/FAIL, but that's a whole different topic.)

**Comment by keithbostic** [comment]
@tammybailey 
> I don't think we need to send a successful return if the timer is exceeded.

Pushed in fee76e63b.

**Pull request merged**
