### PR TITLE
WT-9958 Add quick evergreen tests for PR testing of tiered, timestamp hooks

### PR DESCRIPTION
**Pull request by ddanderson**

### CODE REVIEW

**Comment by ddanderson** [comment]
@lukech can you please review this evergreen addition?

**Review by lukech — COMMENTED** [review]
LGTM. I can see the new "quick" task was included as part of your PR patch build.

**Comment by ddanderson** [comment]
Hey @lukech, it sounds like you approve?  If so, can you "approve" the review?  Thanks!

**Review by lukech — APPROVED** [review]

**Comment by lukech** [comment]
Sorry Don! I thought I selected the approve option but looks not. Here you go!

**Comment by ddanderson** [comment]
np!

**Pull request merged**
