### PR TITLE
WT-11358 Create tests for the background compaction server

### PR DESCRIPTION
**Pull request by etienneptl**
This test creates:

- One table with the first 20% of keys deleted.
- Two other tables with the first 90% of keys deleted.

It checks that:

- There is more available space in the last two tables.
- The background compaction server only compacts the last two tables when the threshold set is
above the available space of the first table.
- Foreground compaction can be executed and can compact the first file with the lowest threshold.

### CODE REVIEW

**Review by kommiharibabu — APPROVED** [review]
LGTM

**Review by mm-ng — APPROVED** [review]
LGTM

**Review by Sean04 — APPROVED** [review]
LGTM, thanks for fixing this up.

**Comment by etienneptl** [comment]
evergreen merge

**Pull request merged**
