### PR TITLE
WT-8021 remove unused cache lookaside score and cache hs score

### PR DESCRIPTION
**Pull request by bingx1**
_cache_lookaside_score_ and _cache_hs_score_ statistics are no longer used by MongoDB. The python test `test_hs05.py` is now obsolete as it was used to verify  _cache_hs_score_ was working correctly.

### CODE REVIEW

**Review by keitharnoldsmith — COMMENTED** [review]
It looks like there is no code that consumes the `cache->evict_hs_score` value. Can you also remove that field from the `WT_CACHE` structure along with the code that updates it (i.e., `__wt_cache_update_score()`) and the places that call that function.

**Comment by bingx1** [comment]
Hi @keitharnoldsmith   - I removed  `cache->evict_hs_score` and `__wt_cache_update_score` and references to these - can you let me know if it looks good now?

**Review by keitharnoldsmith — APPROVED** [review]
Thanks for the additional changes, Bing.

LGTM!

**Review by quchenhao — APPROVED** [review]
lgtm

**Pull request merged**
