### PR TITLE
WT-8788 Use a larger arm64 instance to run long unit test

### PR DESCRIPTION
**Pull request by quchenhao**

### CODE REVIEW

**Review by korteland — APPROVED** [review]
LGTM, but one question - do we know for sure this is the problem, or is it an experiment? It sounds from the ticket like we're not sure yet.

**Comment by quchenhao** [comment]
> LGTM, but one question - do we know for sure this is the problem, or is it an experiment? It sounds from the ticket like we're not sure yet.

Yes, I'm trying to try increasing the memory solves it or not.

**Comment by tammybailey** [comment]
How difficult would it be to log memory usage or other diagnostics in an attempt to root cause? Using the bigger machine is an okay short term solution but there's a $ cost involved in doing so.

**Comment by quchenhao** [comment]
> How difficult would it be to log memory usage or other diagnostics in an attempt to root cause? Using the bigger machine is an okay short term solution but there's a $ cost involved in doing so.

We can enable the wiredtiger stats for this test but it only records the cache usage of each test. It is possible that the issue happens when multiple test running in parallel. Therefore, we need a way to record the physical memory usage of the tests. Not sure how to do that easily. It may help if we can get the syslog of the original failure on the host running it.

**Comment by quchenhao** [comment]
> @quchenhao I am okay to submit this as a temporary fix provided we create a follow-up ticket to spend time on root causing the issue. Would you mind creating one, please?

Created WT-9583

**Comment by quchenhao** [comment]
evergreen merge

**Pull request merged**
