### PR TITLE
WT-11605 Add failure config to our known failing configurations

### PR DESCRIPTION
**Pull request by jiechenbo**

### CODE REVIEW

**Review by etienneptl — APPROVED** [review]

**Comment by ajmorton** [comment]
@jiechenbo we need to be careful about having WT-11507 in the commit message here. This will result in Githook commit messages being written to the WT-11507 ticket as well as WT-11605.

**Comment by jiechenbo** [comment]
Thank you! I have reworded the title and ticket

**Comment by jiechenbo** [comment]
evergeen merge

**Comment by jiechenbo** [comment]
evergreen merge

**Pull request merged**
