### PR TITLE
WT-3628 Fix function and macro usage for new assert flags.

### PR DESCRIPTION
**Pull request by sueloverso**
Going to run on the failing job too.  When that passes then it will be ready for review.

### CODE REVIEW

**Comment by sueloverso** [comment]
@agorrod This is ready for review.  That job is now failing in `test_timestamp07.py` with mismatches with/without leading zeroes.  That is past the compilation error that this addresses.

**Comment by sulabhM** [comment]
@sueloverso , The compilation issue got fixed when Michael moved the function outside "WT_TIMESTAMP_SIZE == 8" condition with his changes for WT-3435:
https://github.com/wiredtiger/wiredtiger/commit/c227e057#diff-7577e91ba5a655b27a2a2837384d1582

I created ticket WT-3631 to fix all the cases where leading zeros cause test failures.

**Comment by michaelcahill** [comment]
autobuild: retest this please

**Comment by bvpvamsikrishna** [comment]
@sueloverso @agorrod 
As per my understanding these changes are not required after WT-3435 is merged, or am I missing something ?

**Comment by sueloverso** [comment]
There was definite overlap between failures, opening tickets, merges, etc.  I will close this branch.

**Pull request closed without merging**
