### PR TITLE
WT-3250 Have one function initializing the WT portion of the spinlock.

### PR DESCRIPTION
**Pull request by sueloverso**
@agorrod and @michaelcahill Here are my suggested changes for the spin lock fix.

### CODE REVIEW

**Comment by sueloverso** [comment]
@agorrod The merge of the earlier branch caused `wiredtiger-test-spinlock` test to fail because the spinlock for `SPINLOCK_GCC` doesn't contain the `name` or `initialized` fields.  Do you recall why we don't want or have those there?  I have pushed a separate change to fix that by unifying the structures, but it seems quite intentional in code I haven't touched much.
@keithbostic Can you look at these changes?

**Comment by sueloverso** [comment]
autobuild: retest this please

**Comment by keithbostic** [comment]
> Do you recall why we don't want or have those there?

I don't think there's any reason those fields weren't there, other than they weren't used (for example, since gcc spinlocks can't ever fail, there wasn't any opportunity to use the name as part of an error message).

This approach looks good to me.

**Comment by sueloverso** [comment]
autobuild: retest this please

**Comment by agorrod** [comment]
Thanks @sueloverso - this change is a good improvement - sorry I merged the original change from underneath you.

**Pull request merged**
