### PR TITLE
WT-10873 WT-11060 WT-11424 WT-11423 WT-11638 (v7.0 backport)

### PR DESCRIPTION
**Pull request by mm-ng**

### CODE REVIEW

**Comment by luke-pearson** [comment]
The first commit and the last commit look correct, the WT-11424 cherry pick seems invalid. It is calling `qsort` and commenting out parts of the dist scripts. I think you can just remove that commit altogether. As long as the WT-11060 cherry pick is compiles, it should be enough, which means you won't need WT-11424.

**Comment by mm-ng** [comment]
> The first commit and the last commit look correct, the [WT-11424](https://jira.mongodb.org/browse/WT-11424) cherry pick seems invalid. It is calling `qsort` and commenting out parts of the dist scripts. I think you can just remove that commit altogether. As long as the [WT-11060](https://jira.mongodb.org/browse/WT-11060) cherry pick is compiles, it should be enough, which means you won't need [WT-11424](https://jira.mongodb.org/browse/WT-11424).

@luke-pearson  If we don't want those changes I can definitely remove them, though I wonder if we'd still like to change this assert here?
`    WT_RET_ASSERT(session, WT_DIAGNOSTIC_PREPARED, *updp != NULL || op->btree->collator == NULL,
      WT_NOTFOUND, "unable to locate update associated with a prepared operation");`

**Comment by luke-pearson** [comment]
Monica you'll need to backport WT-11638 as part of this, need to get the backport approved first.

**Comment by mm-ng** [comment]
> Monica you'll need to backport [WT-11638](https://jira.mongodb.org/browse/WT-11638) as part of this, need to get the backport approved first.

@luke-pearson Thanks for raising this, I've just backported that commit now.

**Review by luke-pearson — APPROVED** [review]
LGTM.

**Pull request merged**
