### PR TITLE
WT-6473 format configuration with tiny caches can result in empty objects

### PR DESCRIPTION
**Pull request by keithbostic**

### CODE REVIEW

**Comment by keithbostic** [comment]
Converting to draft until develop opens.

**Comment by agorrod** [comment]
autobuild: retest this please

**Comment by agorrod** [comment]
@keithbostic would you mind merging up the latest develop into this one? It would be good to see testing go green before merging.

**Comment by tammybailey** [comment]
@bvpvamsikrishna can you review for merge approval, please?

**Pull request merged**
