### PR TITLE
WT-8047 Add mixed mode deletes to test checkpoint

### PR DESCRIPTION
**Pull request by luke-pearson**

### CODE REVIEW

**Comment by quchenhao** [comment]
@luke-pearson I'm not sure we should merge this to develop.

**Comment by luke-pearson** [comment]
> 
> 
> @luke-pearson I'm not sure we should merge this to develop.

Why not?

**Review by quchenhao — APPROVED** [review]
lgtm

**Review by kommiharibabu — APPROVED** [review]
LGTM

**Pull request merged**
