### PR TITLE
WT-12262 Fix the evict stuck condition 

### PR DESCRIPTION
**Pull request by y123456yz**
when cache flag is WT_CACHE_EVICT_ALL, we shold determine if evict is blocked.

### CODE REVIEW

**Comment by y123456yz** [comment]
WT-12262

**Review by kommiharibabu — APPROVED** [review]
LGTM. Thanks.

**Comment by kommiharibabu** [comment]
@Siddhartha8899 This change can let the eviction go into an aggressive mode if it doesn't make any progress. But it was expected to do the same, and it wasn't due to the wrong macro usage. This change may cause some fallout in MongoDB testing and performance. I will run the patch builds. You can also review the change.

**Comment by Siddhartha8899** [comment]
@kommiharibabu, I always believed that eviction follows this hierarchy: `target`, `trigger`, `aggressive`, and `stuck`.

Is there a compelling reason that we wish to change this, given that this hierarchy has persisted for a long time?

**Comment by kommiharibabu** [comment]
Thanks, @Siddhartha8899 for the details. I agree with you that we do not need to change it now. This change can unnecessarily lead to cache-stuck scenarios before the eviction spends much time in HARD mode.

@y123456yz Closing this PR as this change is not required.

**Comment by y123456yz** [comment]
@kommiharibabu @Siddhartha8899 
Thank you for your explanation.

But I think aggressive mode uses WT_CACHE_EVICT_ALL would be better, because the stuck mode(see function __wt_cache_stuck) has WT_CACHE_EVICT_HARD check. 
Progressive mode using WT_CACHE_EVICT_ALL, The main advantages are:

1. Enter aggressive mode as early as possible to avoid unnecessary walks by evict server threads, save CPU overhead, and also reduce some lock overhead

2. Through logs("unable to reach eviction goal") and cache_Revision_Slow statistics allow us to detect evict woker thread blocking issues earlier

Maybe there are many things I didn't understand, I hope you can guide me.

**Pull request closed without merging**
