### PR TITLE
WT-8437 Fix "No space left on device" issue

### PR DESCRIPTION
**Pull request by AlexeyAnisimovAU**
Do not make a copy of the working database in wt8246_compact_rts_data_correctness because it's not used anywhere and not deleted after the test is finished.

### CODE REVIEW

**Review by korteland — APPROVED** [review]
Nice work! I only got as far as figuring out which test was leaving files around, and couldn't figure out where they came from. Thanks for picking this up.

**Comment by AlexeyAnisimovAU** [comment]
> Nice work! I only got as far as figuring out which test was leaving files around, and couldn't figure out where they came from. Thanks for picking this up.

Thanks for giving me the clue!

**Review by raviprakashgiri29 — APPROVED** [review]
LGTM

**Comment by AlexeyAnisimovAU** [comment]
https://github.com/wiredtiger/wiredtiger/pull/7318/files fixed the garbage issue. But we still need this change because we don't need to copy the database.

**Pull request merged**
