### PR TITLE
WT-2104 New log_flush API to control the flushing or syncing of the log.

### PR DESCRIPTION
**Pull request by sueloverso**
@keithbostic and @michaelcahill Please review.  You can see the implementation and we can debate naming.  I chose `log_flush` since I also support forcing a write-no-sync and use `sync` for the configuration name to match the `sync` config parameter on other APIs.  I offer `background, sync, write` as the choices for `sync` (which is different from `commit_transaction`).

### CODE REVIEW

**Comment by sueloverso** [comment]
I am open to suggestions, because although `sync=background` and `sync=write` are fine, I find `sync=sync` a bit awkward.

**Comment by michaelcahill** [comment]
autobuild: retest this please

**Comment by michaelcahill** [comment]
autobuild: please retest this

**Comment by michaelcahill** [comment]
autobuild: test this please

**Comment by wtbuild** [comment]
testing...

**Comment by michaelcahill** [comment]
autobuild: retest this please

**Comment by michaelcahill** [comment]
autobuild: retest this please

**Comment by michaelcahill** [comment]
autobuild: retest this please

**Comment by michaelcahill** [comment]
autobuild: test this please

**Comment by michaelcahill** [comment]
autobuild: retest this please

**Comment by michaelcahill** [comment]
@sueloverso, this generally looks okay, but can we make the API `sync=background|on|off`, matching `commit_transaction`?

**Pull request merged**
