### PR TITLE
WT-11121 Check if a transaction is running in op timer fired. (6.0) (#9307) (#9366)

### PR DESCRIPTION
**Pull request by etienneptl**
(cherry picked from commit 009c4741ed988759e99e8c4cacc3f26b4ade2630)

Co-authored-by: Luke Pearson <luke.pearson@mongodb.com>
(cherry picked from commit 1a84cb8a31abb36d743d4fafffb5959009fa8647)

### CODE REVIEW

**Comment by etienneptl** [comment]
@luke-pearson @mm-ng, [WT-11202](https://jira.mongodb.org/browse/WT-11202) was not backported to 6.0 as it may be reverted by WT-11372. Let me know if this is not ok not to have it.

**Comment by luke-pearson** [comment]
They're independent so I think it's okay.

**Review by luke-pearson — APPROVED** [review]
LGTM.

**Review by mm-ng — APPROVED** [review]
LGTM

**Pull request merged**
