### PR TITLE
WT-3277 Change assert in discard of updates

### PR DESCRIPTION
**Pull request by daveh86**

### CODE REVIEW

**Comment by agorrod** [comment]
autobuild: retest this please

**Comment by daveh86** [comment]
autobuild: retest this please

**Comment by daveh86** [comment]
Any commit on the MongoDB-3.0 branch will never pass windows testing. We would need to backport the changes in WT-2815

**Comment by michaelcahill** [comment]
@daveh86 what's the plan here: are you going to attempt to backport the test changes to `mongodb-3.0`, or have `wiredtiger-pull-request-windows` report success immediately when run against a pull request where the base branch in `mongodb-3.0`?

**Comment by daveh86** [comment]
I tried to backport the commit(s) needed to get the parallel suite working on Windows. This wasn't enough. I also tried a direct copy and that caused failures. I think we have to go with option 2, report success when the base is mongodb-3.0

**Comment by daveh86** [comment]
retest this please

**Comment by daveh86** [comment]
retest this please

**Comment by daveh86** [comment]
retest this please

**Comment by daveh86** [comment]
Okay. This is now passing, as I have disabled the unit testing on Windows

**Comment by agorrod** [comment]
@daveh86 I've asked for some more information in the JIRA ticket - once you've added that I should have enough context to do a review.

**Comment by daveh86** [comment]
@agorrod. Added details to the ticket.

**Comment by agorrod** [comment]
Thanks @daveh86 lgtm - I'll go ahead and merge

**Pull request merged**
