### PR TITLE
WT-7957 Check the local system if a bucket object isn't found (yet).

### PR DESCRIPTION
**Pull request by sueloverso**
Also remove WT_ prefix from extension code macros.

### CODE REVIEW

**Review by ddanderson — APPROVED** [review]
Changes LGTM.

**Comment by ddanderson** [comment]
@sueloverso @keitharnoldsmith

I expect the reason we need this is that when we do the switch, the tiered data structure then says obj id 5 is now the current object so everything lower than that must be managed by the storage source.  But that's not true, since at the switch, we just queued for obj 4 to move to the cloud.  Until the item is pulled from the work queue, the storage source has no knowledge of it, so of course it won't find it.

If we want to clean this up, one way, would be tiered data structure will need to know the current object (as currently), and have a list of objects that are "in the queue" (TBD if we limit that to just 1).  Another way would be to have something like WT_STORAGE_SOURCE->flush_tier_start(), which is called synchronously to the switch, and copies the file into the cache of the storage source.  Then we could switch ownership immediately.  But I think the second solution seems too slow, since the switch code has things locked.  Either way, it's a little bit of a bigger deal, appropriate for a followon ticket.

**Review by keitharnoldsmith — APPROVED** [review]
LGTM

Thanks for the thoughts about the how we might avoid the need to guess where the file is while it's being flushed @ddanderson.  I agree that any further work along those lines could be a separate ticket.  And even then it might be good to hold off until we resolve how we do locking of the file handles (WT-7470) and whether a Btree has one WT_BLOCK or many (WT-7872).

**Comment by sueloverso** [comment]
@ddanderson I might open a ticket that implements the original thought I had that objects would stay in the local database directory for `local_retention` amount of time, even after being copied to the shared storage area. As long as the object is copied before `local_retention` expires it would serve as a cache. Anyway for now, this will move things forward.

**Pull request merged**
