### PR TITLE
WT-9036 Add flags to WT_CONFIG, to allow quotes to be preserved

### PR DESCRIPTION
**Pull request by ddanderson**
Also see alternative solutions:
#7983, #7984

### CODE REVIEW

**Comment by ddanderson** [comment]
@keitharnoldsmith and @sueloverso .  You asked for this weeks ago, sorry it took so long to deliver.  There are three alternative solutions to the config parser problem for embedded quotes.  Let's pick the one you like first (if any), then I'll assign them to you to review.  The others are #7983, #7984 .

**Comment by sueloverso** [comment]
@ddanderson in looking through this one, I don't see anything using the `set_flags` new API anywhere. Can it be removed and simplify this PR?

**Comment by ddanderson** [comment]
@sueloverso, `set_flags` is part of a public API.  Since we allow applications to parse configuration strings in a standalone way (see ex_config_parse.c), and this is something that could come up, I included it in the public API.  If we went with this, we could add example code to show how it is used.

OR....  If we don't feel the need to make it public, we could certainly remove it and simplify all the way down.

**Comment by ddanderson** [comment]
Closing this in favor of #7983.

**Pull request closed without merging**
