### PR TITLE
WT-3533 eviction handle walk can race with handle re-open

### PR DESCRIPTION
**Pull request by keithbostic**

### CODE REVIEW

**Comment by keithbostic** [comment]
autobuild: retest this please

**Comment by keithbostic** [comment]
autobuild: retest this please

**Comment by keithbostic** [comment]
autobuild: retest this please

**Comment by keithbostic** [comment]
autobuild: retest this

**Comment by keithbostic** [comment]
autobuild: retest this please

**Comment by keithbostic** [comment]
@agorrod, I think this one is ready for review/merge.

It's another potentially destabilizing one, since a mistake will likely cause an eviction hang.

**Comment by michaelcahill** [comment]
Thanks, @keithbostic -- lgtm.  I'll merge and we'll see if there are any issues with stress testing.

**Pull request merged**
