### PR TITLE
WT-2276 decode checkpoints via 'wt list -c' and via standalone Python utility.

### PR DESCRIPTION
**Pull request by ddanderson**
`wt list -c` now decodes checkpoints.  Also created a python utility to do the same.

### CODE REVIEW

**Comment by sueloverso** [comment]
Hi Don,

Thanks!  When I run this branch with the `wt` command against the db sent in WT-2275, I get this error:
```
build_posix$ ./wt -h ~/2275 list -c
metadata:
colgroup:main
lt-wt: config_parser.get: WT_NOTFOUND: item not found
```
What am I doing wrong?  However, if I pull out the `addr` shown in the metadata via hexdump, the python script works great!

**Comment by sueloverso** [comment]
FYI, thanks - this is exactly what I had in mind:
```
build_posix$ python ../tools/wt_ckpt_decode.py `cat /tmp/a`
018d81e47263333d8e81e44e1322b38f81e484fb2c76808080e3011fc0e3590fc0: 
    root offset          57344  (0xe000)
    root size             4096  (0x1000)
    root cksum      1919112061  (0x7263537d)

    alloc offset         61440  (0xf000)
    alloc size            4096  (0x1000)
    alloc cksum     1309885171  (0x4e1342f3)

    avail offset         65536  (0x10000)
    avail size            4096  (0x1000)
    avail cksum     2231061686  (0x84fb4cb6)

    discard offset           0  (0x0)
    discard size             0  (0x0)
    discard cksum            0  (0x0)

    file size            81920  (0x14000)
    checkpoint size    5844992  (0x593000)
```

**Comment by ddanderson** [comment]
@sueloverso, this commit should fix the problem. It was bailing for legal entries (like colgroup:) that didn't have allocation_size set.

FYI, `wt list -c` will only show `offset,size,cksum` for `root` not for `alloc, avail or discard`. You asked for just 3 things, so that's what I did in `wt list`. Let me know if you prefer having everything listed as the python tool does.

**Comment by agorrod** [comment]
@sueloverso Are you happy with this change now? If so please go ahead and merge.

**Comment by sueloverso** [comment]
Thanks!  Merged.  I had forgotten about this.

**Pull request merged**
