### PR TITLE
WT-6719 Split hs.c to multiple files

### PR DESCRIPTION
**Pull request by quchenhao**

### CODE REVIEW

**Comment by hbokhari** [comment]
@quchenhao - I am bit confused on what is the criteria here to divide the code between `hs_cursor.c` and `cur_hs.c`? Are we just following an example from other modules?

**Comment by quchenhao** [comment]
> @quchenhao - I am bit confused on what is the criteria here to divide the code between `hs_cursor.c` and `cur_hs.c`? Are we just following an example from other modules?

I was following the example of bt_cursor.c. The cursor api functions are put into `cur_std.c` and the implementation of search and modify are in bt_cursor.c. So I put hs cursor api in `cur_hs.c` and the search and modify implementation in `hs_cursor.c`

**Comment by hbokhari** [comment]
Ideally, do want all HS access through functions listed in `cur_hs.c`, i.e., using cursor interface? I understand there are quite few calls to functions defined in `hs_cursor.c` but I am assuming this ticket doesn't cover that and we will have more tickets to tackle that (cc: @bvpvamsikrishna )?

**Comment by quchenhao** [comment]
> Ideally, do want all HS access through functions listed in `cur_hs.c`, i.e., using cursor interface? I understand there are quite few calls to functions defined in `hs_cursor.c` but I am assuming this ticket doesn't cover that and we will have more tickets to tackle that (cc: @bvpvamsikrishna )?

Yes, I think so.

**Review by hbokhari — APPROVED** [review]
LGTM

**Review by bvpvamsikrishna — APPROVED** [review]
lgtm

**Pull request merged**
