### PR TITLE
WT-8649 WT_SESSION methods cannot release scratch buffers unless reset or closing (v5.0 backport)

### PR DESCRIPTION
**Pull request by svc-bot-sebb**
799d1c7ff250039f4b22133aa94a996a538a2b1d

### CODE REVIEW

**Comment by lukech** [comment]
autobuild: Can one of the admins verify this patch?

**Comment by jiechenbo** [comment]
evergreen retry

**Comment by jiechenbo** [comment]
LGTM! The backport looks clean to me @keithbostic, please review just to make sure

**Review by jiechenbo — APPROVED** [review]

**Review by keithbostic — APPROVED** [review]
lgtm

**Pull request merged**
