### PR TITLE
WT-7860 Improve code coverage reporting

### PR DESCRIPTION
**Pull request by jeremythorp**

### CODE REVIEW

**Comment by jeremythorp** [comment]
This PR is ready for review. 

The code coverage results (high level and detailed) can be found in the test results here: https://spruce.mongodb.com/task/wiredtiger_code_statistics_coverage_report_patch_da48c1b3a1a7a2bf0334ce78f5c53bc9ff7b0489_60f8b45e850e615e8effb7c4_21_07_21_23_57_19/files?execution=0 . Click the [1 Coverage report main page](https://build_external.s3.amazonaws.com/wiredtiger/code-statistics/da48c1b3a1a7a2bf0334ce78f5c53bc9ff7b0489/coverage_report_wiredtiger_code_statistics_patch_da48c1b3a1a7a2bf0334ce78f5c53bc9ff7b0489_60f8b45e850e615e8effb7c4_21_07_21_23_57_19-0/1_coverage_report_main.html) link on that page to see them.

**Comment by lukech** [comment]
@jeremythorp thanks much for making the improvement! Our existing code coverage task is pretty basic. I like the HTML details generated for each file that's evaluated. 

In terms of exclusion of various "non-src" directories, I think it's generally a good idea, though I'm sort of on the fence regarding the `test` and `example` directories. Testing coverage for the `test` directory could to some degree reflect how effective our testing code logic is used, and we do have tests to verify the few `example` tests.

With regard to the visualization of the main HTML page, can we make "src/" be part of the filename in the 1st column? As there's HTML link on each of the src files, it feels a bit redundant to archive & show artifacts of those HTML files for each individual source ("2_coverage_report.*") on the patch build page.

@tammybailey, you may want to take a look and share your opinion? 

FYI - besides improving the usefulness of the coverage report HTML page, a trend graph that shows the coverage result over time might help us from a different angle. [EVG-12781](https://jira.mongodb.org/browse/EVG-12781) was created a while ago for that purpose.

**Comment by jeremythorp** [comment]
Hi @lukech , thanks for reviewing the PR and for your feedback (and adding Tammy :-) ) . Here are my thoughts:
1. re the `test` and `example` directories, for example, there could be some value in having those too (especially `example`). However, the specific aim for having a report for only the `src` directory is that there is a lot of value in having the summary stats for the `src` directory specifically at the top of the main page (ie that, for these tests, we have 86.7% line overage and 58.0% branch coverage for `src'). If having coverage for other directories is useful, then I think we should create an additional page to include them (so we keep the overall stats for `src` seperate).
2. re having all the individual pages appear on the patch page, I agree it would be nicer if they weren't there. The key change I made in this PR was to capture the details for each file, and then make them clickable from the main report page (I don't want people needing to download an archive of the report, then unzip it before they can see the details). As far as I'm aware, this is only possible if we put each details page into the patch page. The '1_` and '2_` is to force the sort order to be make it easy to find the main page easily.
3. A trend graph would be awesome. I've used them in Jenkins in the past to great effect (but there were pre-built plugins available to help). We should look at adding that later.

The current report format is highly constrained by the output of the `covr` tool. You get lots for 'free' as long as you stick to what `covr` provides. Going beyond that would be a quite a bit more work, and I'm keen that we get the value asap from what we can do quickly, and then add more later f required.

Happy to chat more.

Cheers, Jeremy

**Comment by lukech** [comment]
@jeremythorp 

> re having all the individual pages appear on the patch page, I agree it would be nicer if they weren't there. The key change I made in this PR was to capture the details for each file, and then make them clickable from the main report page (I don't want people needing to download an archive of the report, then unzip it before they can see the details). As far as I'm aware, this is only possible if we put each details page into the patch page. The 1_ and 2_ is to force the sort order to be make it easy to find the main page easily.

I'm not sure if it's possible to push files to s3 (to keep the per-file links clickable) but not have them displayed as artifacts on the Evergreen task page - the Evergreen team should be able to answer that. By checking the wiki pages I found this [s3.put with multiple files](https://github.com/evergreen-ci/evergreen/wiki/Project-Commands#s3-put-with-multiple-files) command which could be relevant.

**Review by lukech — APPROVED** [review]

**Review by tammybailey — CHANGES_REQUESTED** [review]
I agree on keeping separate directories in separate reports.

From what I understand, this "test" doesn't actually fail if the coverage falls below a specified threshold (but it will fail if one of the format runs generating the coverage data fails). It uploads a report (and with this change, an additional 200+ files) that isn't reviewed anywhere near as often as it is generated. A lot of our code doesn't get changed all that often, so we are using resources doing a lot of repeated work that isn't currently being used. I suggest reducing the cadence of this test until we have a solid plan for how to use the results. There's no need to run it every day.

**Comment by tammybailey** [comment]
This is a super useful change, but we need to figure out what we actually want to do with this data.  Maybe consider reducing the cadence to weekly or fortnightly until we have a need for daily updates.

**Comment by jeremythorp** [comment]
I'll change the frequency to once per week for now. We can adjust again later if needed. Once we are able to achieve higher coverage then we can turn on failure-if-too-low to stop coverage regressions.

**Review by tammybailey — APPROVED** [review]

**Pull request merged**
