### PR TITLE
WT-10329 Don't check the python coding standard for files in .git

### PR DESCRIPTION
**Pull request by sonar3ddy**
Changed a line in s_python to not include git files.

### CODE REVIEW

**Comment by Siddhartha8899** [comment]
Nitpick: Good to have the ticket number prepended for the first commit. [a5328ff](https://github.com/wiredtiger/wiredtiger/pull/8597/commits/a5328ffd2793eb05322256c0aba303c52a5cc9c7)

Something like:
`WT-10239 changed to not include git in s_python`

**Comment by Siddhartha8899** [comment]
evergreen retry

**Review by Siddhartha8899 — APPROVED** [review]
Well done! LGTM!

**Review by ruby-oujo — APPROVED** [review]
LGTM! Nice job on your first ticket :)

**Pull request merged**
