### PR TITLE
Update the session get btree busy check:

### PR DESCRIPTION
**Pull request by agorrod**
Only wait for ebusy if requesting exclusive access.

### CODE REVIEW

**Comment by agorrod** [comment]
@michaelcahill This is more a discussion point at this stage. The stat server is a kind of special case. Checkpoint has some complex logic around applying itself to handles in various states - stat is less critical, so IMO it's better to keep the code simple.

**Comment by agorrod** [comment]
Refs #1779, #1404

**Comment by agorrod** [comment]
@michaelcahill I'm happy with this change and it fixes the format configurations I've been running. Could you merge it if you are happy?

**Comment by michaelcahill** [comment]
Thanks, @agorrod -- lgtm.

**Pull request merged**
