### PR TITLE
WT-11224 Rename __wt_exclusive_handle_operation to reflect what the function does

### PR DESCRIPTION
**Pull request by etienneptl**

### CODE REVIEW

**Review by keitharnoldsmith — COMMENTED** [review]
@etienneptl. I think it's equally confusing to have "exclusive" in the name of the function, when it doesn't always perform operations with exclusive access.

How about renaming the function to `__wt_execute_handle_operation()` (or something similar). There are only a handful of call points, so it shouldn't take much work. 

Then I would make the comment something like:
```
Apply a function to a handle, getting exclusive access if requested.
```

I'm worried that in your wording a reader might find "Optionally" ambiguous. I.e., is getting exclusive access optional, or is both exclusive access and applying the function optional?

**Comment by etienneptl** [comment]
> I'm worried that in your wording a reader might find "Optionally" ambiguous. I.e., is getting exclusive access optional, or is both exclusive access and applying the function optional?

I could see this coming! I agree that this is ambiguous.
I am not sure how ok it is to rename an external API though.

**Comment by keitharnoldsmith** [comment]
> I am not sure how ok it is to rename an external API though.

It's not part of the API to applications, so there shouldn't be external dependencies on the function name. The {{__wt}} prefix just means that it's visible to code in other files. It's fine to change the name as long as you also change the code that calls it.

**Review by keitharnoldsmith — APPROVED** [review]
LGTM! Thanks for spotting this, Etienne!

**Comment by etienneptl** [comment]
evergreen merge

**Pull request merged**
