### PR TITLE
Cache a maximum of 2MB per session for scratch buffers

### PR DESCRIPTION
**Pull request by michaelcahill**
(configurable via an undocumented "session_scratch_max" config).

SERVER-16623

### CODE REVIEW

**Comment by wtbuild** [comment]
Test FAILed.

**Comment by michaelcahill** [comment]
autobuild: retest this please

**Comment by michaelcahill** [comment]
@agorrod, can you please review?

**Comment by wtbuild** [comment]
Test PASSed.

**Comment by agorrod** [comment]
Thanks @michaelcahill lgtm, I'll merge.

**Pull request merged**
