### PR TITLE
WT-11845 Fix transaction visibility issue with truncate (#9841) (#10105)

### PR DESCRIPTION
**Pull request by etienneptl**
(cherry picked from commit 3fab6ef75fe5308171118c6e52bdbde302358981)

Co-authored-by: jchen <29520270+jiechenbo@users.noreply.github.com>
(cherry picked from commit 5befa70cfa53bdaaef312076678532f78e0bcd65)

### CODE REVIEW

**Comment by etienneptl** [comment]
Note that the config for WT-11507 is added here as WT-11507 was not backported. This ticket added temporary testing / debugging code.

**Comment by etienneptl** [comment]
I had to backport functions introduced by [WT-11241](https://jira.mongodb.org/browse/WT-11241), such as `__wt_txn_snap_min_visible`.

**Review by kommiharibabu — APPROVED** [review]
LGTM

**Review by lukech — APPROVED** [review]

**Review by jiechenbo — APPROVED** [review]
LGTM

**Pull request merged**
