### PR TITLE
WT-6190 review time window validation

### PR DESCRIPTION
**Pull request by keithbostic**

### CODE REVIEW

**Comment by keithbostic** [comment]
@bvpvamsikrishna, @kommiharibabu, would you please take a look at the time window validation code in this PR before I open it up for general review?

Specifically, in `src/support/timestamp.c` there are two new routines, `__wt_time_aggregate_validate()` and `__wt_time_value_validate()`.

They are split into two parts: the first part does internal checking of the time window, the second part checks the time window against a parent's time window.

There are at least two open issues:

First, in yesterday's meeting, I thought we decided that `newest_stop_durable_ts < oldest_start_ts ` was an error, but that check fires for me pretty quickly, with:
```
1589386026:779849][37753:0x7f9e1d7fa700], t, file:wt.wt, WT_SESSION.checkpoint:
__wt_time_aggregate_validate, 181: aggregate time window has a newest stop durable time
before its oldest start time; time aggregate newest durable: (0, 89300)/(0, 0)
oldest start: (0, 24200)/18118 newest stop (4294967295, 4294967295)/18446744073709551605:
Invalid argument
```
Maybe I got the test wrong?

Second, yesterday's meeting didn't cover the checks we should make when comparing a value time window against its parent's time window. I copied the existing code into place, but we didn't discuss if there are other assertions we can make that would tighten up this code.

**Comment by keithbostic** [comment]
@bvpvamsikrishna, the PR tests with:
```
[2020/05/13 21:38:46.765] [1589405926:715802][21948:0x7fecc1152700], t, file:wt.wt, eviction-server: __wt_time_value_validate, 270: value time window has a durable start time after its durable stop time; time window start: (0, 44544)/(0, 44544)/13504 stop: (0, 0)/(4294967295, 4294967295)/18446744073709551605: Invalid argument
```
which looks real to me as well.

**Comment by kommiharibabu** [comment]
```
1589386026:779849][37753:0x7f9e1d7fa700], t, file:wt.wt, WT_SESSION.checkpoint:
__wt_time_aggregate_validate, 181: aggregate time window has a newest stop durable time
before its oldest start time; time aggregate newest durable: (0, 89300)/(0, 0)
oldest start: (0, 24200)/18118 newest stop (4294967295, 4294967295)/18446744073709551605:
Invalid argument
```
@keithbostic, The failure is because there is no stop timestamps in the cell (no remove operations), so the durable stop timestamp is assigned with a default value of WT_TS_NONE. Applying the comparison with `oldest_start_ts` only when durable timestamp is WT_TS_NONE.

**Comment by kommiharibabu** [comment]
```
[2020/05/13 21:38:46.765] [1589405926:715802][21948:0x7fecc1152700], t, file:wt.wt,
eviction-server: __wt_time_value_validate, 270: value time window has a durable start
time after its durable stop time; time window start: (0, 44544)/(0, 44544)/13504
stop: (0, 0)/(4294967295, 4294967295)/18446744073709551605: Invalid argument
```
I feel we shouldn't compare durable start with durable stop except for the value cell. The comparison of durable start with durable stop with a parent to child or aggregated values can go wrong. As durable timestamps aggregated values are the maximum value of start/stop present on the page. Those comparisons across cell values can go wrong.

**Comment by keithbostic** [comment]
@kommiharibabu,
> I feel we shouldn't compare durable start with durable stop except for the value cell.

The current code only compares `(tw->durable_start_ts > tw->durable_stop_ts)`, for the value cell, in `__wt_time_value_validate()`, and the failure in the eviction-server was in "the value time window".

Or am I misunderstanding you?

That raises another point, please let me know if the terminology I used is bad, for example, "newest durable start time" might not be your preferred way of referring to these values.

**Comment by keithbostic** [comment]
@agorrod, @quchenhao, I believe @kommiharibabu and @bvpvamsikrishna have at least briefly looked at this PR.

Chenhao, would you please do the full review?

And, please consider both if the current set of assertions are correct and if there are additional assertions we could add that would tighten up our ability to detect incorrect timestamp usage.

**Comment by keithbostic** [comment]
This PR is passing tests, the only failures are known and aren't part of this change.

**Pull request merged**
