### PR TITLE
WT-2117 Set a minimum of 1MB cache per thread in test/format

### PR DESCRIPTION
**Pull request by agorrod**

### CODE REVIEW

**Comment by agorrod** [comment]
@keithbostic What do you think of this change?

**Comment by keithbostic** [comment]
@agorrod, I think I'm in favor of it -- otherwise, we end up with "bug fixes" that lead to other problems, and we waste time on workloads that just aren't sensible.

**Comment by michaelcahill** [comment]
+1 from me, too -- shall I merge?

**Comment by agorrod** [comment]
Yes please.

**Pull request merged**
