### PR TITLE
Vectorize search

### PR DESCRIPTION
**Pull request by keithbostic**
Add support for vector instructions in the Btree key comparison code.

### CODE REVIEW

**Comment by ddanderson** [comment]
@keithbostic, see #1824 for a fix on the issue about `#include <3rdparty/sse/xmmintrin.h>`

**Comment by fedorova** [comment]
@keithbostic: Hi Keith, I finish testing this branch and I am happy with your changes. I am seeing 9-27% performance improvements on 40-100-128 byte keys on AMD machines. The weird performance dip for 100 byte keys that I was seeing on one server is gone, thanks to a307a61. 

On Intel machines, I am seeing 2-9% performance improvements for the same set of key sizes. Also, on Intel machines I am seeing a couple percent performance loss for keys that we are not vectorizing. That is because of an extra branch. I thought that this could be that the code for non-vectorized comparison is in the "else" clause, so when we are evaluating a branch, that code is not in the pipeline. However, when I changed the clauses around, nothing changed. I also tried using __builtin_expect, but that did not help either. I am not surprised: in my tests we are running a bunch of operations with the same key size, so the branch predictor would have figured out that we are never taking that branch. So I don't see what else can be done. I think we should swallow that overhead, because the gains on larger key sizes are so much bigger. 

I also tried setting the threshold for vectorization to one vector. That decreased performance for 1-2% on several machines, so I think we should leave the threshold as is. 

So overall, I think it's good to go. Thanks for integrating the code and making it more efficient!

Please let me know if you'd like me to run insert tests before the merge.

**Comment by keithbostic** [comment]
@michaelcahill, this one is ready to go if we're prepared to trade-off 1-2% performance loss on keys less than 32B, vs. larger performance gains on keys larger than 32B. We haven't measured performance in the insert path (skip lists vs. on-disk page images), but my assumption is the insert path will be at least as good, if not better, because we don't skip leading bytes that are similar, so we'll be generally be comparing longer keys in the insert paths.

**Comment by michaelcahill** [comment]
This seems worthwhile to me.

How confident are we about the `#ifdef` logic for portability?

Also, this is a change that I think should not appear in a MongoDB 3.0 patch release, so once this is merged, we're cherry-picking any future changes for 3.0...

**Comment by keithbostic** [comment]
I'm reasonably confident the #idef logic works -- it's OK on Windows, gcc, clang, and a variety of Linux and FreeBSD hardware, as well as OS X.

If the change pays off, I don't see a reason not  to include it in a patch release, I think it's unlikely to be destabilizing (although it might not make it through the full build tests without alteration, so there's potential confusion there).

We can certainly leave the change out for now, there's no hurry to include the change and it won't be difficult to keep it current.

**Pull request merged**
