### PR TITLE
WT-7026 Atomically read and set ref->addr in case of race.

### PR DESCRIPTION
**Pull request by sueloverso**

### CODE REVIEW

**Comment by sueloverso** [comment]
evergreen retry

**Comment by sueloverso** [comment]
evergreen retry

**Comment by sueloverso** [comment]
evergreen retry

**Review by ddanderson — APPROVED** [review]
LGTM.  Nice comment and analysis in the ticket.

**Review by keitharnoldsmith — APPROVED** [review]
LGTM!

**Pull request merged**
