### PR TITLE
Windows error string support.

### PR DESCRIPTION
**Pull request by keithbostic**
@markbenvenuto: this is the structure I'm thinking will work, would you please take a look and tell me what you think?

If you agree with this approach, I think what's left is to add the mapping for the Windows' System Error Codes.

### CODE REVIEW

**Comment by wtbuild** [comment]
Test FAILed.

**Comment by wtbuild** [comment]
Test PASSed.

**Comment by keithbostic** [comment]
@markbenvenuto, @michaelcahill: I've reworked this change to keep `wiredtiger_strerror` as thread-safe as possible, we're not falling back to a static-buffer unless there's no other choice.

Mark, this is for your review and Windows testing.
Michael, as far as I'm concerned, this can be merged when you're happy with it.

**Comment by markbenvenuto** [comment]
@keithbostic The changes look good to me, and the unit tests pass on Windows.

**Comment by keithbostic** [comment]
@michaelcahill, can you say more about what you mean by:
> an interface where error messages are attached to a session.

**Comment by michaelcahill** [comment]
We could avoid these issues about buffers if there was a version of `wiredtiger_strerror` that takes a session, and has the session own the buffer.  I don't want to change the global `wiredtiger_strerror`, but we could have `WT_SESSION::strerror` as the common case instead of `wiredtiger_strerror_r`.

**Comment by keithbostic** [comment]
Obviously, this is an easy change to make -- let me know if you want this done, I'll put it in so we don't have to have both.

**Comment by keithbostic** [comment]
@michaelcahill, I'm assuming this can/should wait for now, it just has to be decided before our next standalone WiredTiger release -- let me know if that's wrong.

**Pull request merged**
