### PR TITLE
WT-3204 eviction changes cost LSM performance

### PR DESCRIPTION
**Pull request by keithbostic**

### CODE REVIEW

**Comment by keithbostic** [comment]
@agorrod, here's a simple test that shows the failure:
```
import wiredtiger, wttest
class test_xxx(wttest.WiredTigerTestCase):
    uri = 'table:test_bug013'
    def test_xxx(self):
        self.tty('== 1')
        self.session.create(self.uri, 'key_format=S,value_format=S,type=lsm')
        cursor = self.session.open_cursor(self.uri, None, None)
        cursor['key1'] = 'value1'
        cursor.close()

        self.tty('== 2')
        self.session.verify(self.uri, None)

        self.tty('== 3')
        cursor = self.session.open_cursor(self.uri, None)
        cursor['key2'] = 'value2'
        cursor.close()

        self.tty('== 4')
        cursor = self.session.open_cursor(self.uri, None, None)
        i = 0
        for v in cursor:
            i += 1
        cursor.close()
 
if __name__ == '__main__':
    wttest.run()
```
When I run it, I set breakpoints in `__wt_btree_open` and `__lsm_switch_primary_off`. Here's the first interesting open:
```
== 2
[Switching to Thread 802006400 (LWP 100897/python2.7)]

Breakpoint 4, __wt_btree_open (session=0x8070298a0, op_cfg=0x7fffffffcc50)
    at src/btree/bt_handle.c:75
75		dhandle = session->dhandle;
$72 = (WT_BTREE *) 0x80782e380
$73 = 1             <<< WT_BTREE.evict_disabled is set
$74 = true          <<< WT_BTREE.lsm_primary is set
(gdb) where
#0  __wt_btree_open (session=0x8070298a0, op_cfg=0x7fffffffcc50)
    at src/btree/bt_handle.c:75
#1  0x0000000803b016d9 in __wt_conn_btree_open (session=0x8070298a0, 
    cfg=0x7fffffffcc50, flags=2097160) at src/conn/conn_dhandle.c:343
#2  0x0000000803bce59c in __wt_session_get_btree (session=0x8070298a0, 
    uri=0x807812060 "file:test_bug013-000002.lsm", checkpoint=0x0, 
    cfg=0x7fffffffcc50, flags=2097160) at src/session/session_dhandle.c:531
#3  0x0000000803bce240 in __wt_session_get_btree_ckpt (session=0x8070298a0, 
    uri=0x807812060 "file:test_bug013-000002.lsm", cfg=0x7fffffffcc50, 
    flags=2097160) at src/session/session_dhandle.c:335
#4  0x0000000803bbf1e3 in __wt_schema_worker (session=0x8070298a0, 
    uri=0x807812060 "file:test_bug013-000002.lsm", 
    file_func=0x803ad4d80 <__wt_verify>, name_func=0, cfg=0x7fffffffcc50, 
    open_flags=2097160) at src/schema/schema_worker.c:58
#5  0x0000000803b71fa1 in __wt_lsm_tree_worker (session=0x8070298a0, 
    uri=0x8020184f0 "lsm:test_bug013", file_func=0x803ad4d80 <__wt_verify>, 
    name_func=0, cfg=0x7fffffffcc50, open_flags=2097160)
    at src/lsm/lsm_tree.c:1381
#6  0x0000000803bbf4a4 in __wt_schema_worker (session=0x8070298a0, 
    uri=0x8020184f0 "lsm:test_bug013", file_func=0x803ad4d80 <__wt_verify>, 
    name_func=0, cfg=0x7fffffffcc50, open_flags=2097160)
    at src/schema/schema_worker.c:76
#7  0x0000000803bbf6b6 in __wt_schema_worker (session=0x8070298a0, 
    uri=0x8007d5b0c "table:test_bug013", file_func=0x803ad4d80 <__wt_verify>, 
    name_func=0, cfg=0x7fffffffcc50, open_flags=2097160)
    at src/schema/schema_worker.c:96
#8  0x0000000803bc8f1d in __session_verify (wt_session=0x8070298a0, 
    uri=0x8007d5b0c "table:test_bug013", config=0x0)
    at src/session/session_api.c:1372
```
as part of the open we're going to clear that stuff, and then we switch that same handle out of primary mode:
```
Breakpoint 3, __lsm_switch_primary_off (session=0x80702a520)
    at src/lsm/lsm_work_unit.c:274
274		cache = S2C(session)->cache;
(gdb) p btree
$81 = (WT_BTREE *) 0x80782e380
(gdb) where
#0  __lsm_switch_primary_off (session=0x80702a520)
    at src/lsm/lsm_work_unit.c:274
#1  0x0000000803b73f22 in __wt_lsm_checkpoint_chunk (session=0x80702a520, 
    lsm_tree=0x802043d80, chunk=0x80780e0b0) at src/lsm/lsm_work_unit.c:410
#2  0x0000000803b7565f in __lsm_worker_general_op (session=0x80702a520, 
    cookie=0x8023e2ae8, completed=0x7fffdf5f8f7e) at src/lsm/lsm_worker.c:64
#3  0x0000000803b7530a in __lsm_worker (arg=0x8023e2ae8)
    at src/lsm/lsm_worker.c:121
#4  0x0000000800827855 in pthread_create () from /lib/libthr.so.3
```
I'm hoping you can tell me why a primary LSM chunk is being re-opened as something else by a verify without LSM noticing? I've been staring at it some and I'm just not seeing it!

**Comment by agorrod** [comment]
@keithbostic Your analysis was right, verify was grabbing the handle exclusive and then LSM was re-using the handle as primary without `evict_disable`` being at the expected counter. The solution was to avoid allowing a non-bulk-loadable handle to become a primary chunk - which results in a force switch within LSM (aka a new primary)

**Comment by agorrod** [comment]
autobuild: retest this please

**Comment by agorrod** [comment]
@keithbostic The code in this branch appears correct now, but the pull-request tests are running surprisingly slowly with the changes.

**Comment by keithbostic** [comment]
> The solution was to avoid allowing a non-bulk-loadable handle to become a primary chunk - which results in a force switch within LSM (aka a new primary)

Thank you, Alex.

Can we talk this over the next time we're both online? I'd like to understand what is the "quality" LSM is looking for in a primary chunk: `WT_BTREE.bulk_load_ok` means "newly created without any inserted data", and I'm not sure how neatly that maps to LSM's requirements. Perhaps a better approach would be to add a configuration that leaves eviction turned off whenever LSM opens an object?

I'd like to avoid LSM looking at `WT_BTREE.bulk_load_ok`: or maybe we rename it to mean something a little more general to match LSM's needs.

**Comment by keithbostic** [comment]
> The code in this branch appears correct now, but the pull-request tests are running surprisingly slowly with the changes.

I've done some measurements, and the first commit in this branch, c9cd825 gets us back to "normal" LSM performance, it's roughly equivalent to develop before WT-3199 went in. But, the change in f5a1c87 (the one fixing the problems in that commit around verify acquiring an exclusive handle), drops the `parallel-pop-lsm` performance off a cliff:
```
Starting 5 populate thread(s) for 10000000 items
543827 populate inserts (543827 of 10000000) in 5 secs (5 total secs)
1700 populate inserts (545527 of 10000000) in 5 secs (10 total secs)
1700 populate inserts (547227 of 10000000) in 5 secs (15 total secs)
1998 populate inserts (549225 of 10000000) in 5 secs (20 total secs)
1781 populate inserts (551006 of 10000000) in 5 secs (25 total secs)
```

**Comment by agorrod** [comment]
@keithbostic I didn't get back to this one today - the next step is on my plate.

**Comment by michaelcahill** [comment]
@keithbostic, I pushed a commit here that I think gets the effect we want, can you please review?

I'm happy for `btree->bulk_load_ok` to be renamed, maybe something like `btree->empty` or `btree->pristine`?

**Comment by keithbostic** [comment]
@michaelcahill 

This change looks great, and the performance appears at least as good as before WT-3199 went in.

I've renamed `btree->bulk_load_ok` to be `btree->original`, hope that works for you. (I didn't want to use "empty", because the tree is still potentially "empty" on subsequent opens).

I'll merge once the tests pass.

**Pull request merged**
