### PR TITLE
WT-8511 Remove unnecessary steps in evergreen

### PR DESCRIPTION
**Pull request by etienneptl**
This ticket is part of WT-8498, the initial PR is #7300, this PR aims at merging the same changes to the develop branch.

### CODE REVIEW

**Review by ajmorton — APPROVED** [review]
LGTM. 
Discussion about further improvements to only fetch artifacts and not recompile in each step is taking place in [WT-8525](https://jira.mongodb.org/browse/WT-8525)

**Review by lukech — APPROVED** [review]
LGTM. 

Since we've migrated to CMake, did anyone try the "fetching artifact but not re-compile" setup to see if it works? I believe the directory issue with Autoconf was the reason we introduced the re-compile initially.

**Comment by etienneptl** [comment]
> LGTM.
> 
> Since we've migrated to CMake, did anyone try the "fetching artifact but not re-compile" setup to see if it works? I believe the directory issue with Autoconf was the reason we introduced the re-compile initially.

That's a good question. I will try to give it a go.

**Comment by etienneptl** [comment]
> > LGTM.
> > Since we've migrated to CMake, did anyone try the "fetching artifact but not re-compile" setup to see if it works? I believe the directory issue with Autoconf was the reason we introduced the re-compile initially.
> 
> That's a good question. I will try to give it a go.

I tried and it did not work. We will need to investigate further in WT-8525.

**Comment by lukech** [comment]
Thanks for the quick check @etienneptl

**Pull request merged**
