### PR TITLE
WT-7857 Change run.py to use absolute LD_LIBRARY_PATH for --asan

### PR DESCRIPTION
**Pull request by sonar3ddy**
Rewriting the LD_LIBRARY_PATH using absolute paths.

### CODE REVIEW

**Comment by sonar3ddy** [comment]
I am not sure if we want to set the LD_LIBRARY_PATH above here in run.py:86-100
`# If we built with libtool, explicitly put its install directory in our library
# search path. This only affects library loading for subprocesses, like 'wt'.
libsdir = os.path.join(wt_builddir, '.libs')
if os.path.isdir(libsdir):
    append_env_path('LD_LIBRARY_PATH', libsdir)
    if sys.platform == "darwin":
        append_env_path('DYLD_LIBRARY_PATH', libsdir)`

**Comment by ddanderson** [comment]
@sonar3ddy, I wanted to make sure you were able to 1) reproduce the original problem and that 2) this change fixes the problem.  If you've done that, my apologies, but we usually put this information (about reproducing and verifying) in the JIRA  ticket and/or this PR.  If you trouble reproducing, ping me or Keith.

If I'm not mistaken, using `'.libs'` makes sense when building "the old way" with libtools, but is not relevant for building with cmake.

I _think_ what we want to do here is write a python function that takes an env variable (like "LD_LIBRARY_PATH"), which might have a value of "/some/dir:another/dir:a/third/dir" and break it up into its colon separated parts, and for each one that is a "relative path" (does not start with '/') turn it into an absolute path with the current directory in front.  So for the example, we want "/some/dir:/current/directory/another/dir:/current/directory/a/third/dir".  I suspect that will solve the issue (but of course, reproduce and verify).

Working with ASAN from the python script is a little tricky, and I don't know your Python experience level. I'm happy to talk through any of this as needed!

**Review by ddanderson — COMMENTED** [review]
This looks like it may work when building with libtools (that is, not with cmake) and also if running from the build_posix directory.  See my other comment, I'd like to know that the problem has been reproduced and the fix verified.  Also it would be good to try it with cmake, as we should be pretty much switched from libtool development.

**Comment by sonar3ddy** [comment]
> @sonar3ddy, I wanted to make sure you were able to 1) reproduce the original problem and that 2) this change fixes the problem. If you've done that, my apologies, but we usually put this information (about reproducing and verifying) in the JIRA ticket and/or this PR. If you trouble reproducing, ping me or Keith.
> 
> If I'm not mistaken, using `'.libs'` makes sense when building "the old way" with libtools, but is not relevant for building with cmake.
> 
> I _think_ what we want to do here is write a python function that takes an env variable (like "LD_LIBRARY_PATH"), which might have a value of "/some/dir:another/dir:a/third/dir" and break it up into its colon separated parts, and for each one that is a "relative path" (does not start with '/') turn it into an absolute path with the current directory in front. So for the example, we want "/some/dir:/current/directory/another/dir:/current/directory/a/third/dir". I suspect that will solve the issue (but of course, reproduce and verify).
> 
> Working with ASAN from the python script is a little tricky, and I don't know your Python experience level. I'm happy to talk through any of this as needed!

@ddanderson Here are the steps I have done:
1. build with command:
cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/mongodbtoolchain_v3_gcc.cmake -DCMAKE_INSTALL_PREFIX=$(pwd)/LOCAL_INSTALL -DCMAKE_BUILD_TYPE=ASan -DCC_OPTIMIZE_LEVEL="-O0" -G "Ninja" ./..

2. run shell script repro.sh:

```#!/bin/sh
PYTHONPATH="$PYTHONPATH:../lang/python:lang/python:../test/suite"
export PYTHONPATH
python3 ../test/suite/run.py $@
```
3. git diff of run.py:

[diff.patch](https://github.com/wiredtiger/wiredtiger/files/10273505/diff.patch)

4. screenshot showing difference of LD_LIBRARY_PATH in asan:
Screen Shot 2022-12-21 at 10 23 21 am



Let me know if this is the right approach :) Thanks for taking time to review!

**Comment by sonar3ddy** [comment]
Problem no longer exists, JIRA ticket has been closed.

**Pull request closed without merging**
