### PR TITLE
WT-5902 No need to release the page if we end up with the same page in __tree_walk_internal

### PR DESCRIPTION
**Pull request by quchenhao**

### CODE REVIEW

**Comment by sulabhM** [comment]
@quchenhao can you please update the ticket with the root cause of the bug.

**Comment by keithbostic** [comment]
@quchenhao, this code has been unchanged for quite some time, what has changed that makes this change necessary?

**Comment by quchenhao** [comment]
> @quchenhao, this code has been unchanged for quite some time, what has changed that makes this change necessary?

I don't know. My hypothesis is that we never return the same page that we start with in __tree_walk_internal before durable history. Some changes in durable history makes it no longer true.

**Comment by quchenhao** [comment]
The theory that __tree_walk_internal returns the same page when it starts is wrong. So abort this PR.

**Pull request closed without merging**
