### PR TITLE
WT-8000 Allow s_docs to compile even if doxygen version is not supported.

### PR DESCRIPTION
**Pull request by Siddhartha8899**
The changes in the PR allow both Doxygen versions (1.8.13 and 1.8.17) to run successfully and generate documentation. 

- Removed unsupported (v1.8.13) tags.
- Replaced ^^ with @_linebr, seems to work for both versions as the documentation generated contains the images.

### CODE REVIEW

**Review by keithbostic — APPROVED** [review]
Instead of trying to create a Doxyfile that's supported by all of the versions of doxygen that we use, why don't we create a Doxyfile per version of doxygen that  we run? Then, change the `s_docs` script to use the appropriate Doxyfile for the version of doxygen being run. That seems simpler than this approach and less likely to get us into trouble as new versions of doxygen come out and we find out we're running on more versions of doxygen that we think we are.

Otherwise, I'm the wrong person to review this change, I don't know anything about doxygen or making it portable.

**Comment by tammybailey** [comment]
I'm not sure what we are trying to accomplish with this ticket? Why not check if we are using a supported {{doxygen}} version (not a huge deal as we only support two versions) rather than removing the check completely?

**Comment by Siddhartha8899** [comment]
> I'm not sure what we are trying to accomplish with this ticket? Why not check if we are using a supported {{doxygen}} version (not a huge deal as we only support two versions) rather than removing the check completely?

@tammybailey as part of this ticket, I am trying to successfully run the s_docs script, including the generation of the documents (which was not the original intent), with the older Doxygen version (v1.8.13), and in order to achieve that I have made changes to the Doxyfile (to make it compatible with the older version v1.8.13). 

Also, I agree that the check shouldn't be removed, I will make that change. Thanks.

**Comment by jiechenbo** [comment]
@Siddhartha8899 if we are planning to add the skip in, I'm not sure if we need to worry about making changes to the Doxyfile and making it compatible to v1.8.13.

**Comment by Siddhartha8899** [comment]
> @Siddhartha8899 if we are planning to add the check in, I'm not sure if we need to worry about making changes to the Doxyfile and making it compatible to v1.8.13. What do you think?

That sounds good @jiechenbo, I do not see much use of it either. I will make the changes, thanks.

**Review by tammybailey — APPROVED** [review]
LGTM

**Review by jiechenbo — APPROVED** [review]
LGTM!

**Pull request merged**
