### PR TITLE
WT-8689 Switch Evergreen zSeries builder to RHEL distro (v5.0 backport) (#7649)

### PR DESCRIPTION
**Pull request by etienneptl**
* Changed zseries test from ubuntu-1804-zseries-test to rhel80-zseries-test

(cherry picked from commit 324fdee42e1e5a99c274fc2e552c007aa786c523)

### CODE REVIEW

**Review by Siddhartha8899 — APPROVED** [review]

**Comment by etienneptl** [comment]
@lukech, it is not part of the backport but I believe we should add the following changes on top of this backport:
```
diff --git a/test/evergreen.yml b/test/evergreen.yml
index fe10f399b..8bacdab7d 100755
--- a/test/evergreen.yml
+++ b/test/evergreen.yml
@@ -4237,10 +4237,10 @@ buildvariants:
   - name: ".stress-test-zseries-2"
   - name: ".stress-test-zseries-3"
 
-- name: ubuntu1804-zseries-cmake
-  display_name: "* Ubuntu 18.04 zSeries CMake"
+- name: rhel8-zseries-cmake
+  display_name: "* RHEL8 zSeries CMake"
   run_on:
-  - ubuntu1804-zseries-test
+  - rhel80-zseries-test
   batchtime: 10080 # 7 days
   expansions:
     test_env_vars:
```
What do you think?

**Comment by lukech** [comment]
@etienneptl I agree - the purpose of this backport is to move away from using the Ubuntu zseries distro.

**Comment by lukech** [comment]
Should the `big-endian` builder be updated as well?

**Comment by etienneptl** [comment]
> Should the `big-endian` builder be updated as well?

@lukech, it looks like this task was updated through WT-9968, see [here](https://github.com/wiredtiger/wiredtiger/pull/8634/files#diff-42f20e21217bd7d4b14489056e1ea24ea2b87599c85413d49182a3b0b721c132R5157).

**Review by lukech — APPROVED** [review]
LGTM

**Review by Siddhartha8899 — APPROVED** [review]

**Pull request merged**
