### PR TITLE
Column store name-space gap handling.

### PR DESCRIPTION
**Pull request by keithbostic**
@agorrod, this change avoids performance problems in column-store WT_CURSOR.next and reconciliation when applications create large gaps in the name-space.

Reference #1807.

### CODE REVIEW

**Comment by agorrod** [comment]
@keithbostic This looks good to me, but I've got some general questions about how deleted records/key-gaps are treated in column stores before I'm confident about merging it.

* What do we store on disk for deleted keys?
* Do we figure out when reading a column store page if there are deleted keys?
* Does the column store skip list contain deleted keys?

I couldn't find this covered in the documentation anywhere. I'd be happy to chat on the phone - since I suspect there might be some follow up questions.

**Comment by keithbostic** [comment]
FTR:
- Deleted keys on disk are "deleted" cells, so `unpack.type == WT_CELL_DEL`.
- When reading a column-store page we don't check for deleted keys explicitly, they are just handled whenever a future request touches on a page slot where a deleted cell appears.
- A column-store skip list does contain deleted keys, but that's different. It's not a cell, it's a WT_UPDATE structure where `WT_UPDATE_DELETED_ISSET(upd)` will return true.

**Comment by agorrod** [comment]
@keithbostic Following up from our phone call this morning, I attempted to capture some information about what is stored on disk for variable length column stores in a picture:

https://github.com/wiredtiger/wiredtiger/wiki/Reconciliation-overview#variable-length-column-store-disk-layout

Would you mind taking a look and letting me know if I got the content right?

**Comment by agorrod** [comment]
@keithbostic The ball is in my court here - sorry I didn't get through the review today - it's high on my list tomorrow.

**Comment by keithbostic** [comment]
@agorrod, it's not quite right w.r.t. keys. All that's stored on the page are RLE and value pairs, one pair per cell. (If you look at the top of the `include/cell.i` file, there's some more discussion.) Keys are stored as a starting key for the page, so the first RLE/value pair on the page is the RLE/value for the page's starting record number, the second RLE/value pair on the page is the page's starting record number plus the RLE count for the first RLE/value pair, and so on.

So, if the page's starting record number is 37, and the page's RLE/value pairs look like this: `5:V1, 2:V2, 4:deleted, 3:V3`, then records 37-41 have value V1, records 42-43 have value V2, records 44-47 are deleted, and records 48-50 have value V3.

**Comment by agorrod** [comment]
Thanks @keithbostic lgtm - I'll merge.

I've updated the picture - could you take another look?

**Comment by keithbostic** [comment]
@agorrod, wouldn't the RLE for the deleted chunk be `3999`, not `4000`?

**Pull request merged**
