### PR TITLE
WT-11125 Remove WT_DHANDLE_DISCARD flag usage in RTS

### PR DESCRIPTION
**Pull request by kommiharibabu**

### CODE REVIEW

**Comment by agorrod** [comment]
This makes sense to me - I've asked a question in the Jira ticket.

**Review by agorrod — APPROVED** [review]
lgtm

**Review by korteland — APPROVED** [review]
LGTM, going to split the discussion about what to do with a large number of dhandles into a different ticket.

**Comment by kommiharibabu** [comment]
evergreen merge

**Pull request merged**
