### PR TITLE
Log more of what we're doing during the long waits

### PR DESCRIPTION
**Pull request by pgunn**
If this looks good, I'll have a Python port of this for you soon.

### CODE REVIEW

**Comment by wtbuild** [comment]
autobuild: Can one of the admins verify this patch?

**Comment by michaelcahill** [comment]
autobuild: add to whitelist

**Comment by michaelcahill** [comment]
autobuild: ok to test

**Comment by michaelcahill** [comment]
@pgunn, my only comment is that `fprintf(stdout, ...` looks a little weird to me.  I see we already have a couple of cases in `ex_backup.c`, but why not just `printf(...`?

**Comment by michaelcahill** [comment]
That build failure probably isn't obvious.  The important part is at the end:

```
RE-RUN dist/s_all and resubmit
```

**Comment by pgunn** [comment]
@michaelcahill It looked weird to me too, but I didn't want to question your existing coding practices. New patch is on its way shortly.

**Comment by michaelcahill** [comment]
@pgunn, can you please merge with develop?  @keithbostic changed the lines as you over the weekend :-(

**Pull request merged**
