### PR TITLE
WT-9176 Set operation rate to 10ms for update threads (v6.0 backport) 

### PR DESCRIPTION
**Pull request by bvpvamsikrishna**
…est (#7828)

(cherry picked from commit 484656b0971c16e5fb45c46589c6bd94ebeb9eb4)

### CODE REVIEW

**Review by etienneptl — APPROVED** [review]

**Comment by etienneptl** [comment]
@bvpvamsikrishna, @lukech:
This change may break the test while it passing now on the mongodb-6.0 branch. We may want to wait before backporting otherwise we will run into WT-9115.

**Comment by bvpvamsikrishna** [comment]
> @bvpvamsikrishna, @lukech: This change may break the test while it is passing now on the mongodb-6.0 branch. We may want to wait before backporting otherwise we will run into [WT-9115](https://jira.mongodb.org/browse/WT-9115). I have added the stress testing to the PR testing, let's see the results when it's done.

@etienneptl, Thank you.

**Comment by etienneptl** [comment]
Indeed, we are now failing due to the size being too big. This makes sense as we do way more updates. @ajmorton, should we disable the check too then?

**Comment by ajmorton** [comment]
> Indeed, we are now failing due to the size being too big. This makes sense as we do way more updates. @ajmorton, should we disable the check too then?

I'm in favour of it. On develop we're only reporting these stats to Charts and Evergreen, making them de facto perf metrics.
Given the checks can't fail on dev and we don't track perf on older branches removing the checks makes sense to me.

**Comment by lukech** [comment]
Please ignore the Jenkins test result as it's not meant to be triggered.

**Comment by etienneptl** [comment]
> > Indeed, we are now failing due to the size being too big. This makes sense as we do way more updates. @ajmorton, should we disable the check too then?
> 
> I'm in favour of it. On develop we're only reporting these stats to Charts and Evergreen, making them de facto perf metrics. Given the checks can't fail on dev and we don't track perf on older branches removing the checks makes sense to me.

Then we will need to backport WT-8152 which means reopen BACKPORT-12475 (@jiechenbo)

**Comment by lukech** [comment]
Looks like [BACKPORT-12475](https://jira.mongodb.org/browse/BACKPORT-12475) had been merged. @bvpvamsikrishna should we merge it in (from `mongodb-6.0`) to get the failed test pass?

**Comment by bvpvamsikrishna** [comment]
> Looks like [BACKPORT-12475](https://jira.mongodb.org/browse/BACKPORT-12475) had been merged. @bvpvamsikrishna should we merge it in (from `mongodb-6.0`) to get the failed test pass?

I think we should merge, @etienneptl , do you agree ?

**Comment by etienneptl** [comment]
> I think we should merge, @etienneptl , do you agree ?

Yes, please proceed @bvpvamsikrishna !

**Pull request merged**
