### PR TITLE
WT-11423 Skip releasing a page if our session has prepared

### PR DESCRIPTION
**Pull request by luke-pearson**
This isn't the best fix. WT-10873 made prepare resolution cheaper by pinning the page. It also allows the validation logic to be less complex. But as a result of a check buried in `cursor_page_pinned` we sometimes release that page. This is done for cache eviction as we only do it if `READGEN` is oldest. Personally I do not like this check as it circumvents what I would consider the point of a pinned page. It's also a bit subtle, would you expect calling `pinned_page` to release it? I didn't. But instead of removing it outright I have opted to skip it once a transaction has called `prepare`. 

There is an alternative solution in which we weaken the validation logic to only happen in diagnostic mode and unpack the row key / value. The upside is we no longer need to guarantee correctness of keeping the page pinned the downside is that it isn't a check we could use always due to performance concerns.

### CODE REVIEW

**Review by kommiharibabu — APPROVED** [review]
LGTM

**Comment by luke-pearson** [comment]
Going to hold off on this PR until we get to a good conclusion on WT-11424, if it becomes clear that sorting correctly is too expensive then this work will be cancelled.

**Review by agorrod — APPROVED** [review]
lgtm - this approach seems very reasonable.

**Comment by luke-pearson** [comment]
evergreen merge

**Pull request merged**
