### PR TITLE
WT-12096 __rec_validate_upd_chain(): Do not return EBUSY if globally visible (v8.0 backport)

### PR DESCRIPTION
**Pull request by tod-johnson-mongodb**
Backport WT-12096 from develop to 8.0.

cherry-picked 17358cb5eb93b59b931c66fe753e3059bedd7a7a from branch develop.

WT-12096 Don't validate timestamp against the on-page value if the update is globally visible (#10905)

If an update is globally visible it can be evicted and EBUSY should not be returned. Thus the check for EBUSY should be skipped if an update is globally visible. The bug is the check for EBUSY was not skipped if an update is globally visible.

This was backed out since it made the occurrence of WT-12602 more frequent. Now it is no longer necessary to wait for WT-12602 and some BFs need this. So it is time to put this back. The original PR was PR #10595.

There is bug fixing and code readability improvements included beyond the original PR.

---------

### CODE REVIEW

**Comment by tod-johnson-mongodb** [comment]
Draft because full patch build is running right now.

**Comment by tod-johnson-mongodb** [comment]
This is ready to merge.  Patch https://spruce.mongodb.com/version/66b12aba030f0100073fc31f/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC has some failures none of which matter.
* spinlock-gcc-test is https://jira.mongodb.org/browse/WT-13250 which is in version 8.1 but not 8.0.
* format-stress-sanitizer-test-1 is https://jira.mongodb.org/browse/WT-13290 which is in 8.1 but not 8.0
* s-outdated-fixmes is a test marked "Infrequent tests"  that is not usually run.
* make-check-test is WT-12813 and is marked "KNOWN ISSUE".

**Review by quchenhao — APPROVED** [review]
lgtm

**Comment by jiechenbo** [comment]
LGTM! For backport pull request names, we want the title to match the original ticket with the backport. E.g. format should be _WT-12096 __rec_validate_upd_chain(): Do not return EBUSY if globally visible (v8.0 backport)_

**Review by jiechenbo — APPROVED** [review]

**Pull request merged**
