### PR TITLE
WT-3994 Avoid GCC-7 and Clang errors for mongodb-3.2 branch (#3989)

### PR DESCRIPTION
**Pull request by lukech**
Add GCC 7 and Clang warning settings to avoid build errors.

(cherry picked from commit 5efdaecd1ce7f610d5f40d0b12d73b3b5abede29)

### CODE REVIEW

**Comment by lukech** [comment]
autobuild: retest this please

**Comment by lukech** [comment]
@keithbostic can you help to look at the failure in this PR? You removed the content of this test as part of BACKPORT-1152. Do you still remember why?

**Comment by lukech** [comment]
Hello @keithbostic, @sueloverso, @agorrod:
Please help to review the changes which include below 3 parts (commits):

- Added GCC 7 and Clang warning settings to avoid build errors
- Reverted commit 46c2f8f which accidentally reverted a set of commits on mongodb-3.2 branch
- Reapplied commit 095efd2/0831e04 i.e. the desired changes in WT-3284

**Comment by agorrod** [comment]
lgtm

**Comment by lukech** [comment]
Thanks @keithbostic @sueloverso @agorrod, I will go ahead to merge (without squash).

**Pull request merged**
