### PR TITLE
WT-2807 Change the memory allocator for wtperf performance tests.

### PR DESCRIPTION
**Pull request by agorrod**
Not for merging.

### CODE REVIEW

**Comment by agorrod** [comment]
Our current performance jobs are based on the default Ubuntu jemalloc 3.3 build - try running them against a custom 4.2.1 build.

**Comment by sueloverso** [comment]
The eviction tests are happy with this branch.  The 4 thread version is finally running a bit faster than the single thread version.

**Comment by agorrod** [comment]
autobuild: retest this please

**Comment by michaelcahill** [comment]
@agorrod, @sueloverso is now a good time to merge this one?

**Comment by agorrod** [comment]
@michaelcahill I think so. I've switched the Jenkins perf tests over to the branch to make sure the path is right - if the tests look OK I'm inclined to merge.

**Pull request merged**
