### PR TITLE
WT-3296 BACKPORT-1135 Port LAS improvements to mongodb-3.4

### PR DESCRIPTION
**Pull request by sulabhM**
cherry pick b9bfe41b26db9acb53d37f5919b7d2bbe29db275 into mongodb-3.4

### CODE REVIEW

**Comment by sulabhM** [comment]
@autobuild recheck this please

**Comment by sulabhM** [comment]
@autobuild retest this please

**Comment by sulabhM** [comment]
@keithbostic can you have a look at this backport. Let me know if this looks right to you. If you agree to the changes please do NOT merge them into mongodb-3.4 through github. Doing so might cause some complications in tracking through JIRA.

**Comment by sulabhM** [comment]
@michaelcahill , please have a look.

**Comment by keithbostic** [comment]
lgtm.

**Comment by michaelcahill** [comment]
Thanks @sulabhM, this set of changes lgtm.  I'll merge.

**Pull request merged**
