### PR TITLE
WT-6713 Remove transaction support from custom data sources

### PR DESCRIPTION
**Pull request by kommiharibabu**
WiredTiger providing transaction support for custom data sources
doesn't handle all scenarios, instead pass the transaction support
to the custom data sources itself instead of WT handling them.

### CODE REVIEW

**Review by sueloverso — APPROVED** [review]
LGTM. My only question is whether there are any documentation changes that are needed.

**Review by raviprakashgiri29 — APPROVED** [review]
Changes LGTM

**Comment by kommiharibabu** [comment]
@sueloverso Thanks for the doc comment. I didn't find any documentation that needs to be removed, but I felt it is better to add small details of transaction responsibility by the custom data sources.

**Comment by kommiharibabu** [comment]
evergreen retry

**Review by sueloverso — APPROVED** [review]
LGTM

**Pull request merged**
