### PR TITLE
WT-12877 Extend PR testing for ARM variants

### PR DESCRIPTION
**Pull request by etienneptl**
- Sorted tasks for ubuntu2004-arm64 and amazon2-arm64
- Added format-stress-pull-request-test to both variants

### CODE REVIEW

**Comment by etienneptl** [comment]
evergreen retry

**Comment by etienneptl** [comment]
evergreen retry

**Comment by etienneptl** [comment]
evergreen retry

**Comment by etienneptl** [comment]
evergreen retry

**Review by lukech — APPROVED** [review]
LGTM. Assume you'll add the `format-stress-pull-request-test` task to the PR testing section on the Evergreen project configuration page.

**Comment by etienneptl** [comment]
evergreen retry

**Comment by etienneptl** [comment]
evergreen retry

**Comment by etienneptl** [comment]
evergreen retry

**Comment by etienneptl** [comment]
evergreen retry

**Comment by etienneptl** [comment]
> LGTM. Assume you'll add the `format-stress-pull-request-test` task to the PR testing section on the Evergreen project configuration page.

@lukech, it took me a few attempts but in the last PR testing you can see the new tests:

- [Amazon Linux 2 ARM64](https://spruce.mongodb.com/version/6670f8203644aa0007dc0aa2/tasks?page=0&sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC&variant=%5Eamazon2-arm64%24)
- [~ Ubuntu 20.04 ARM64](https://spruce.mongodb.com/version/6670f8203644aa0007dc0aa2/tasks?page=0&sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

**Review by agorrod — APPROVED** [review]

**Pull request merged**
