### PR TITLE
WT-2645 Moved the complexity of dump from the dump utility to the metadata cursor

### PR DESCRIPTION
**Pull request by ddanderson**
Opening a metadata cursor with `"create"` folds column group metadata into the table for simple tables (those with no named column groups), and for more non-simple tables, each column group has its source entry folded in.

This has been tested by comparing the output files from `test_dump*` and `test_jsondump*` (e.g. `dump.out` and `jsondump.out`) from those of previous runs.  The only difference (other than spacing in JSON) was a bug fix: previously calling `wt dump index:table_name:index_name` would result in two output entries for the named index.

### CODE REVIEW

**Comment by ddanderson** [comment]
@michaelcahill, this is ready for review.

**Comment by ddanderson** [comment]
@michaelcahill, this is ready for review now.

**Comment by michaelcahill** [comment]
Thanks @ddanderson, and apologies for the delay on this one.  I've been trying to get things stable for a stable, feature-complete merge into MongoDB...

I'll do a careful review tomorrow.

**Comment by michaelcahill** [comment]
@ddanderson, this is looking good -- I'm sorry to say that I still haven't done a complete review.  I'll try to get you some concrete feedback on Monday.

**Comment by michaelcahill** [comment]
@ddanderson, I made some cosmetic changes as part of a review, this is now looking good to me.  I'll merge.  Thanks!

**Pull request merged**
