### PR TITLE
WT-7525 Add key order check after hs insert

### PR DESCRIPTION
**Pull request by quchenhao**

### CODE REVIEW

**Comment by kommiharibabu** [comment]
@quchenhao Can you run stress tests and MongoDB patch build to check if it can reproduce now itself before we merge this issue? So that it will be good to fix the problem.

**Review by kommiharibabu — APPROVED** [review]
LGTM

**Comment by quchenhao** [comment]
> @quchenhao Can you run stress tests and MongoDB patch build to check if it can reproduce now itself before we merge this issue? So that it will be good to fix the problem.

Sure

**Comment by quchenhao** [comment]
stress test:
https://spruce.mongodb.com/version/609db9179ccd4e56a978b4db/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
mongodb patch build:
https://spruce.mongodb.com/patch/609dba283627e06d5f98e587/configure/tasks

**Pull request merged**
