### PR TITLE
WT-11637 Always increment background compaction failure stat when compaction does not succeed

### PR DESCRIPTION
**Pull request by etienneptl**
Previously, `background_compact_fail` was not incremented when `WT_ERROR` was returned from the `compact` call.

### CODE REVIEW

**Review by Siddhartha8899 — APPROVED** [review]

**Comment by etienneptl** [comment]
The failure has nothing to do with the changes.

**Comment by etienneptl** [comment]
The commit [910d840](https://github.com/wiredtiger/wiredtiger/pull/9624/commits/910d840fc97496fbba64751d465076f81aebadb7) removes an unused variable as described in WT-11640.

**Review by kommiharibabu — APPROVED** [review]
LGTM

**Review by Sean04 — APPROVED** [review]
LGTM

**Pull request merged**
