### PR TITLE
WT-7928 VLCS checkpoint and additional test suite improvements (redux)

### PR DESCRIPTION
**Pull request by sauclovian-wt**
Second go, with a fix for the ubsan issue that cropped up (WT-7951)

### CODE REVIEW

**Comment by lukech** [comment]
autobuild: Can one of the admins verify this patch?

**Comment by keithbostic** [comment]
@kommiharibabu, this is the PR you reverted yesterday, with the UBSAN error in WT-7951 fixed. Do you want to merge, or is there additional testing we should do?

**Comment by luke-pearson** [comment]
I think we could kick off a full patch build prior to merge @kommiharibabu.

**Comment by kommiharibabu** [comment]
All tests are passed.

**Comment by sauclovian-wt** [comment]
Cool, thanks.

**Pull request merged**
