### PR TITLE
Fix errors in java examples preventing them from running.

### PR DESCRIPTION
**Pull request by ddanderson**
Refs #1524.

### CODE REVIEW

**Comment by ddanderson** [comment]
The current commit fixes ex_thread.  More fixes to come for other examples.

**Comment by wtbuild** [comment]
Test PASSed.

**Comment by wtbuild** [comment]
Test PASSed.

**Comment by wtbuild** [comment]
Test PASSed.

**Comment by agorrod** [comment]
@ddanderson Is this branch ready for review?

**Comment by ddanderson** [comment]
@agorrod Yes, ready for review.

**Comment by agorrod** [comment]
Thanks @ddanderson. This looks good to me, well done figuring out the log cursor one - it took me a while to figure out why it was necessary.

**Comment by ddanderson** [comment]
@agorrod, anytime we're manufacturing cursor results that aren't already raw we need to handle the raw case.  I see that we do this in a couple other places (stats and recno), maybe it's worth refactoring with a varargs function? I'll put it together and see how it looks.

**Pull request merged**
