### PR TITLE
Minor restructuring of fields in the WT_PAGE structure to reduce cache misses in the row-store search routine.

### PR DESCRIPTION
**Pull request by keithbostic**

### CODE REVIEW

**Comment by michaelcahill** [comment]
I'm happy with this change, do we have confirmation yet that it helps?

**Comment by keithbostic** [comment]
@michaelcahill, no, we don't have confirmation yet.

**Comment by fedorova** [comment]
I have confirmed that this change reduces the last-level cache miss rate by 1.1% for the small-btree test case. The change is small, but significant, as the standard deviation for the miss rate across runs is practically zero. I also found that moving "WT_ROW *d" to be just above "uint32_t entires" in struct row of the union gives another 0.5% of significant reduction to the last-level cache miss rate. Since the miss-rate reduction is small, there is no measurable impact on performance one way or the other.

**Comment by keithbostic** [comment]
Thanks, @fedorova, I'll go ahead and apply those changes to the tree.

**Pull request merged**
