### PR TITLE
WT-4360 Explore getting core dumps from ASAN builds

### PR DESCRIPTION
**Pull request by guddnjs91**
Try to generate a core dump when ASAN failure occurs.

### CODE REVIEW

**Comment by wtbuild** [comment]
autobuild: Can one of the admins verify this patch?

**Comment by sulabhM** [comment]
autobuild: add to whitelist

**Comment by sulabhM** [comment]
autobuild: ok to test

**Comment by sulabhM** [comment]
This pull request was to check if clang address sanitizer builds are dumping core. Having done that, I am closing this pull request.

**Pull request closed without merging**
