### PR TITLE
WT-9643 Fix pthread_mutex_destroy() failure during test_checkpoint.

### PR DESCRIPTION
**Pull request by ddanderson**
We need to wait to destroy the lock protecting the stable timestamp
until all threads using that lock have exited.

### CODE REVIEW

**Comment by ddanderson** [comment]
@keitharnoldsmith, can you please review?

**Review by keitharnoldsmith — APPROVED** [review]
LGTM

But is there any reason not to join the `checkpoint_thread` before the `clock_thread`. Then there would only need to be a single check of `g.use_timestamps`.

**Comment by ddanderson** [comment]
I think you're right. The clock thread is trivial, and changing the join order shouldn't make any different.  I'll fix.

**Review by keitharnoldsmith — APPROVED** [review]
LGTM

**Comment by ddanderson** [comment]
The PR failure seems entirely independent (a test/format error) I just ticketed as WT-9669.

**Comment by ddanderson** [comment]
evergreen merge

**Pull request merged**
