### PR TITLE
WT-10487 Adding V4 toolchain to path env for many-collection-test

### PR DESCRIPTION
**Pull request by mickgraham-mongodb**

### CODE REVIEW

**Review by etienneptl — APPROVED** [review]
Looks good! Thanks for finding this so quickly.
Seems that the v4 definition in the `test_env_vars` section of the build variant `large-scale-tests` is useless now but we could still leave it just in case.

**Comment by mickgraham-mongodb** [comment]
Its possible that there have been updates to the distro that we use and we need to explicitly set the PATH. I'm running an updated test that will use the values from test_env_vars (because they aren't used in many-collection-test).

**Review by etienneptl — APPROVED** [review]
LGTM, thanks for all the testing to find out the root cause.

**Comment by mickgraham-mongodb** [comment]
The unittest failure is a known issue.

**Pull request merged**
