### PR TITLE
WT-3489 Add an API to set the tracked commit_timestamp.

### PR DESCRIPTION
**Pull request by michaelcahill**
This is required during rollback, because the commit_timestamp determines how much of the oplog is visible.

### CODE REVIEW

**Comment by michaelcahill** [comment]
Note: the initial commit is the code change only.  Tests that set `commit_timestamp` are required before this is ready for review.

**Comment by michaelcahill** [comment]
autobuild: retest this please

**Comment by agorrod** [comment]
Thanks @michaelcahill - I agree that this deserves a test, but the code change looks OK to me from inspection.

**Comment by agorrod** [comment]
Thanks @michaelcahill lgtm

**Pull request merged**
