### PR TITLE
WT-9381 Remove checkpoint reserved transaction id

### PR DESCRIPTION
**Pull request by quchenhao**

### CODE REVIEW

**Comment by quchenhao** [comment]
@kommiharibabu @bvpvamsikrishna With WT-9805 and other fixes for WT-9268, it's time to remove this.

**Review by kommiharibabu — APPROVED** [review]
LGTM

**Review by bvpvamsikrishna — APPROVED** [review]
lgtm

**Comment by quchenhao** [comment]
evergreen merge

**Pull request merged**
