### PR TITLE
WT-11340 Improve wtperf chunk cache functionality

### PR DESCRIPTION
**Pull request by korteland**
See the ticket comment for results. I wasn't particularly rigorous about it, just some sanity checking.

This PR contains some improvements I made along the way:
* I fixed the `wtperf` configs to actually generate read-only tiered objects. So the automated perf tests will now be testing the right thing, and regressions there should start to be looked at.
* `wtperf` can now automatically create the bucket directory with the new `tiered_bucket` config.
* We also no longer need to restart WiredTiger for the testing to work - this didn't need any changes, but is now possible after several previous improvements to the chunk cache code.
* `__wt_chunkcache_get` now always initialises `cache_hit`
* Some whitespace fixes in the Python tests

### CODE REVIEW

**Comment by Siddhartha8899** [comment]
I believe it is best to change the PR title, to reflect the work that is actually done.

**Comment by korteland** [comment]
> I believe it is best to change the PR title to reflect the work that is actually done.

Fair enough - I've changed it now, hopefully that's better.

**Review by Siddhartha8899 — APPROVED** [review]
Thanks for these changes @korteland! 

I believe that 'reopen_connection' is set to 'true' by default. As a result, there is a restart that occurs between the populate and workload phases. Based on the config below - 
```
DEF_OPT_AS_BOOL(
  reopen_connection, 1, "close and reopen the connection between populate and workload phases")
```

**Comment by Siddhartha8899** [comment]
Although 'reopen_connection' is initially configured as 'true' by default in wtperf testing, I think it should be explicitly set to 'true' in the config, should the default behavior change in the future.

**Comment by korteland** [comment]
> Although 'reopen_connection' is initially configured as 'true' by default in wtperf testing, I think it should be explicitly set to 'true' in the config, should the default behavior change in the future.

Yeah, no harm in it - done in 13d89ce.

**Review by ruby-oujo — APPROVED** [review]
LGTM

**Comment by korteland** [comment]
evergreen merge

**Pull request merged**
