### PR TITLE
WT-4438 Use accurate statistics for cursor cache totals in connection.

### PR DESCRIPTION
**Pull request by ddanderson**

### CODE REVIEW

**Comment by ddanderson** [comment]
@agorrod, can you please review?

**Comment by agorrod** [comment]
@ddanderson did you consider using the `WT_STAT_*_ATOMIC` macros instead of a shared variable in the connection? Those macros have the benefit of using a set of values - so should lead to less contention.

**Comment by ddanderson** [comment]
@agorrod, thanks, that's a great idea.  I've made that change.

**Comment by agorrod** [comment]
Thanks @ddanderson lgtm

**Pull request merged**
