### PR TITLE
WT-10292 Turn off redact option from test format when using wt verify

### PR DESCRIPTION
**Pull request by bzm-jas**
Changed __wt_debug_page unreadact option to true.

### CODE REVIEW

**Comment by jiechenbo** [comment]
@bzm-jas Can you post the before and after of your changes?

**Comment by Siddhartha8899** [comment]
Nit pick: Good to have the ticket number in the first commit [c31646a](https://github.com/wiredtiger/wiredtiger/pull/8594/commits/c31646aa20716a36fbf1e1e7a8dcbe22a51db3f8) :)

**Comment by Siddhartha8899** [comment]
Do we know why we wanted to page to be redacted in the first place?

**Comment by bzm-jas** [comment]
before redact turned off:

`

0x22de9900: row-store leaf
--
0x22de9900, memory, leaf
disk 0x2d87e000, dsk_mem_size 90624, write_gen: 218654, entries 617, clean, disk-alloc, memory-size 95656
K {REDACTED}
value: {REDACTED}
K {REDACTED}
value/short: {REDACTED}

`

after:

`last successful match was 7039
mirror: 7041/7041 mismatch: table:T00001: {0000007041.00/opqrstuvwxyzabcdefghijkl}/{000000704}, table:T00002: {0000007041.00/opqrstuvwxyzabcdefghijklmnopq}/{000000704}
last successful match was 7040
mirror: 7042/7042 mismatch: table:T00001: {0000007042.00/opqrstuvwxyzabcdefghijklmn}/{0000007042/QMNOPQRST}, table:T00002: {0000007042.00/opqrstuvwxyzabcdefghijklmnopqrstu}/{0000007042/QMNOPQRST}`

**Review by Siddhartha8899 — APPROVED** [review]
Great Job! LGTM

**Comment by jiechenbo** [comment]
> Do we know why we wanted to page to be redacted in the first place? I think there may be a reason.
So I added in the redact functionality, I may have missed this case and just defaulted it to redact and realised it was a bug.

**Review by jiechenbo — APPROVED** [review]
LGTM!

**Pull request merged**
