### PR TITLE
Row search simplify

### PR DESCRIPTION
**Pull request by keithbostic**
@michaelcahill, I made a change I've been thinking about for awhile, splitting up the object types in the Btree cursor code and removing some of the `btree->type == BTREE_ROW` branches in the code, I thought it might make a difference.

The following branch gets me about 4% improvement in the row-store cursor lookup path (pixiebob, clang 3.3 with -O3, running a microbenchmark doing 100M WT_CURSOR.set_key and WT_CURSOR.search pairs).

I can't get too excited about 4% -- I think it depends if you think this architecture is at least as clean, understandable and maintainable as the old one? If you like the old structure better, I'm happy to discard the branch, otherwise, I'm happy to take the 4%.

Obviously, we could keep going down this path (split up fixed-length vs. variable length column store, for example), this was just an experiment in making row-store searches faster.

### CODE REVIEW

**Comment by michaelcahill** [comment]
@keithbostic, I'm going to need to stare at this one some more -- it isn't obvious to me that calling through a function pointer is better than branching for something like __wt_kv_return (which could otherwise be inlined).

**Comment by keithbostic** [comment]
@michaelcahill, understood -- as I said, the gain isn't compelling.

FTR, I tried inlining `__wt_kv_return` (passing in `BTREE_ROW` so the compiler could discard all but the relevant parts of the switch). It was slightly faster than the function call, but it wasn't significant in my testing.

**Comment by michaelcahill** [comment]
@keithbostic, I'd like to close this out.  In particular, I'd prefer not to make changes to the public `WT_CURSOR` API for these implementation details and the performance improvements weren't compelling.  Is there anything here you'd like to keep?

**Comment by keithbostic** [comment]
@michaelcahill, there are a couple of things I'll probably take -- if it's OK, I'll review this one in a few days, cherry-pick a few changes and then close it.

**Comment by michaelcahill** [comment]
@keithbostic, sure -- if there are changes to keep, please open jira tickets for them.

**Comment by keithbostic** [comment]
Discard this branch -- the performance improvements aren't compelling, it's not worth doing for now.

**Pull request closed without merging**
