### PR TITLE
WT-3635 Coverity 1381606 & Friday builds & lint.

### PR DESCRIPTION
**Pull request by keithbostic**
@sulabhM, would you be kind enough to do the review?

The individual commits should be descriptive and easier than reviewing the changes as a whole.

### CODE REVIEW

**Comment by keithbostic** [comment]
autotest: rebuild this please

**Comment by keithbostic** [comment]
autobuild: test this please

**Comment by keithbostic** [comment]
autobuild: retest this please

**Comment by sulabhM** [comment]
@keithbostic these changes look good to me. I will let you decide if you are ready to merge these into develop.

**Pull request merged**
