### PR TITLE
WT-4892 Improve statistics about forced eviction (#4732) (v4.0 backport)

### PR DESCRIPTION
**Pull request by lukech**
Don't assume all forced eviction not caused by a page with a too-large footprint was caused by large numbers of deleted items on a page.

Re-word the statistics related to forced eviction so that they sort better and their meaning is clearer. Add in a few more statistics.

(cherry picked from commit 99e0760cc5f11440b21184874d8dd2ae5bde23d6)

### CODE REVIEW

**Comment by lukech** [comment]
@sulabhM This is mostly a clean cherry-pick. I ran `s_all` to fix the conflict in `wiredtiger.in` file. Could you help to take a look? Thanks.

**Comment by lukech** [comment]
Merged `mongodb-4.0` in to resolve the conflict.

**Comment by lukech** [comment]
retest this please

**Comment by tetsuo-cpp** [comment]
Superseded by #4837.
I'm closing this PR but will keep the branch around. Once you're happy with the migrated branch, please delete this one.

**Pull request closed without merging**
