### PR TITLE
WT-13287 Incorporate checkpoint as part of test_cc_base.wait_for_cc_to_run()

### PR DESCRIPTION
**Pull request by etienneptl**

### CODE REVIEW

**Review by mm-ng — COMMENTED** [review]
Just to make sure my understanding is correct, we want to delay taking a checkpoint until after we have checked the statistic so that we don't hang? I think it would be worth adding a comment into the `wait_for_cc_to_run ` and `check_cc_stats ` functions describing this.

There are also a bunch of comments in various tests saying to take a checkpoint. It's not really obvious that a checkpoint will be taken as part of `wait_for_cc_to_run ` or `check_cc_stats `, hence why I think some additional comments would be useful.

**Comment by etienneptl** [comment]
> Just to make sure my understanding is correct, we want to delay taking a checkpoint until after we have checked the statistic so that we don't hang? I think it would be worth adding a comment into the `wait_for_cc_to_run ` and `check_cc_stats ` functions describing this.
> 
> There are also a bunch of comments in various tests saying to take a checkpoint. It's not really obvious that a checkpoint will be taken as part of `wait_for_cc_to_run ` or `check_cc_stats `, hence why I think some additional comments would be useful.

Thank you for the feedback, please see 002c38b73214072887e0f7a2bfab1ca959db6ff8 and 13ad50bd9304d59958d4c48945c5e2c0669e232e.

**Review by mm-ng — APPROVED** [review]
LGTM

**Review by kommiharibabu — APPROVED** [review]
LGTM

**Pull request merged**
