### PR TITLE
WT-2202: release of the "current" page is wrong.

### PR DESCRIPTION
**Pull request by keithbostic**
We're releasing the "current" page if (leaf != NULL), and that's wrong, we should only release the current page if no leaf-page WT_REF was specified.  The test could be (leaf == NULL), but I think (leaf != current) is a little more obvious.

@agorrod, @michaelcahill, would one of you please do a review? Thanks!

### CODE REVIEW

**Comment by agorrod** [comment]
@keithbostic I buy that this change is correct, but do you understand why the bug isn't causing things to break everywhere (or anywhere)?

**Comment by agorrod** [comment]
> The test could be (leaf == NULL), but I think (leaf != current) is a little more obvious.

I disagree with this. It makes more sense to choose the behavior based on the input parameter, since that is presumably how the caller will decide.

If we error out from ``__wt_row_search`` after a call with a non-null ``leaf`` parameter, that has moved on from leaf, won't that cause other problems? i.e: we'll release the ``leaf`` ref twice, but never release the ref the search is sitting on?

**Comment by keithbostic** [comment]
> I buy that this change is correct, but do you understand why the bug isn't causing things to break everywhere (or anywhere)?

It's code that's only called on error in a function that never sees an error.

**Comment by keithbostic** [comment]
>> The test could be (leaf == NULL), but I think (leaf != current) is a little more obvious.

> I disagree with this. It makes more sense to choose the behavior based on the input parameter, since that is presumably how the caller will decide.

OK, fine with me, I've pushed the change.

> If we error out from __wt_row_search after a call with a non-null leaf parameter, that has moved on from leaf, won't that cause other problems? i.e: we'll release the leaf ref twice, but never release the ref the search is sitting on?

If leaf is non-null, we don't move on, the search is constrained to the leaf page, and the caller of the search function is responsible for discarding the page.

**Comment by agorrod** [comment]
Thanks @keithbostic lgtm. I added a comment and an assertion. I'll merge.

**Pull request merged**
