### PR TITLE
WT-6924 Heuristics to limit cache growth beyond size limit

### PR DESCRIPTION
**Pull request by hbokhari**
Existing mechanisms for eviction are very fair system. WT queues pages for pages based on the relative space each btree is occupying in the cache. Moreover, the queues are sorted often to evict the least recently used (LRU) pages first. This all worked relatively well before history store (HS) architecture landed. With HS, reconciling a non-HS page can generate even more HS contents. Therefore, any mechanism that evicts non-HS in hope for reducing cache pressure might make the situation even worse. Therefore, my current approach is to introduce some prioritisation for HS pages when cache pressure is high.

### CODE REVIEW

**Comment by hbokhari** [comment]
@agorrod @sulabhM @bvpvamsikrishna 

This is an initial version of changes. I am still playing with some parameters but with the existing parameters I can bring down the max cache usage down to ~110%.

**Comment by agorrod** [comment]
Is this waiting on me?

**Comment by hbokhari** [comment]
@agorrod I will close this PR in favour of #6144. Instead of explicitly increasing the priority for HS pages, we plan to use urgent eviction method.

**Comment by hbokhari** [comment]
Closing this in favour of #6144.

**Pull request closed without merging**
