### PR TITLE
WT-2196 Fix error handling in size only statistics.

### PR DESCRIPTION
**Pull request by agorrod**
Error codes from failed calls to __wt_filesize_name should not be propagated.

Also add a new test case to test fast stats.

### CODE REVIEW

**Comment by agorrod** [comment]
@keithbostic Would you mind taking a look at this branch? I'm open to suggestions if you would prefer a different error handling solution in ``schema_stat.c``.

**Comment by keithbostic** [comment]
@agorrod, lgtm.

**Comment by keithbostic** [comment]
@agorrod, we could do better if we just called `__wt_exist` instead of `__wt_filename`?

(No, I guess that doesn't work, drop could race with the exist call.)

**Comment by agorrod** [comment]
>  I guess that doesn't work, drop could race with the exist call

Yup - that was my chain of thought.

**Pull request merged**
