### PR TITLE
WT-3693 Add a callback for when the all_committed timestamp changes.

### PR DESCRIPTION
**Pull request by michaelcahill**

### CODE REVIEW

**Comment by michaelcahill** [comment]
Does not yet need review: being used to help diagnose test failures initially.

**Comment by agorrod** [comment]
@michaelcahill where are we at with this branch? Should I go ahead and review?

**Comment by michaelcahill** [comment]
That's really a question for @dgottlieb -- is there any value in this change for diagnosing issues with MongoDB's use of timestamps?  Otherwise, I'm happy to toss it.

**Comment by dgottlieb** [comment]
I think we can toss it.

**Pull request closed without merging**
