### PR TITLE
WT-11036 Add test of incremental backup after files are closed (6.0)

### PR DESCRIPTION
**Pull request by etienneptl**
I had to backport WT-10909 and WT-10920 to have a clean backport of WT-11036.

### CODE REVIEW

**Comment by etienneptl** [comment]
@keitharnoldsmith, when importing your test, I have the following error:

```
Traceback (most recent call last):
  File "/home/ubuntu/wiredtiger/test/suite/test_backup29.py", line 200, in test_backup29_sweep
    self.assertEqual(nfile, final_nfile)
AssertionError: 4 != 5
```

I understand we have fewer opened files than expected, I am not sure how to check which one is missing.

**Review by sueloverso — APPROVED** [review]
LGTM

**Comment by sueloverso** [comment]
While the change/backport looks fine in the diff, all three backports failed in the changed test in the same way. So that needs to be addressed before merging.

**Comment by keitharnoldsmith** [comment]
> @keitharnoldsmith, when importing your test, I have the following error:
> 
> ```
> Traceback (most recent call last):
>   File "/home/ubuntu/wiredtiger/test/suite/test_backup29.py", line 200, in test_backup29_sweep
>     self.assertEqual(nfile, final_nfile)
> AssertionError: 4 != 5
> ```
> 
> I understand we have fewer opened files than expected, I am not sure how to check which one is missing.

@etienneptl. The statistics file is the one that is missing. 

I copied this bit of the test from `test_sweep01.py`. In 6.0 (and earlier, I assume), that test sets `final_nfile = 4`. So you should be able to make the same change here. I'd do something like:
```
         sleep = 0
         max = 20
         # The only files sweep won't close should be the metadata, the history store, the
-        # lock file, the statistics file, and our active file.
-        final_nfile = 5
+        # lock file, and our active file.
+        final_nfile = 4
```

**Review by keitharnoldsmith — APPROVED** [review]
LGTM!

As mentioned in a separate comment the fix for the test failures in this (and the other) backports looks minor. Assuming that works, no need for me to re-review.

**Pull request merged**
