### PR TITLE
WT-6280 Checkpoint history store may race with eviction removing contents from the history store

### PR DESCRIPTION
**Pull request by tetsuo-cpp**

### CODE REVIEW

**Comment by quchenhao** [comment]
@tetsuo-cpp I think there is another problem here in the reconciliation of the history store. Currently we don't do any visibility check in `__rec_update_select` for the history store so we still writes nothing to the disk even we pass on txnids to the tombstones.

If we start to do visibility check for the history store, we still need to decide what we should write to the disk. If the update chain has T@0 -> T@20 ->U@10, I think we need to write the update with time window (10, 20) and pin the T@0 in cache. Otherwise the checkpoint will still have the wrong value.

**Comment by tetsuo-cpp** [comment]
> @tetsuo-cpp I think there is another problem here in the reconciliation of the history store. Currently we don't do any visibility check in `__rec_update_select` for the history store so we still write nothing to the disk even we pass on txnids to the tombstones.
> 
> If we start to do visibility check for the history store, we still need to decide what we should write to the disk. If the update chain has T@0 -> T@20 ->U@10, I think we need to write the update with time window (10, 20) and pin the T@0 in cache. Otherwise the checkpoint will still have the wrong value.

@quchenhao 
Sure, thanks. This is marked as a draft because it isn't ready yet.
I'll add you as a reviewer later.

**Comment by quchenhao** [comment]
Sorry for the post. I just want to clarify the problem.

**Comment by tetsuo-cpp** [comment]
> Sorry for the post. I just want to clarify the problem.

No problem! Sorry, I didn't mean to come off like that.

I hadn't figured that out yet so your comment is definitely helpful. At the moment, I'm exploring whether I can trigger this in a test. I'm thinking that I could have a `csuite` test that continuously resets keys with non-timestamped updates and runs checkpoints whilst another thread tries to read historical updates.

**Pull request closed without merging**
