### PR TITLE
WT-3862 invalid diagnostic assertion during checkpoint reconciliation

### PR DESCRIPTION
**Pull request by keithbostic**
Remove invalid diagnostic assertion.

### CODE REVIEW

**Comment by keithbostic** [comment]
autobuild: retest this please

**Comment by lukech** [comment]
autobuild: rebuild this please

**Comment by michaelcahill** [comment]
autobuild: retest this please

**Comment by keithbostic** [comment]
autobuild: retest this please

**Comment by michaelcahill** [comment]
Thanks @keithbostic, lgtm.  I'll merge.

**Pull request merged**
