### PR TITLE
WT-4185 Don't remove all lookaside entries when reading a page.

### PR DESCRIPTION
**Pull request by nehakhatri5**
The lookaside sweep code removes entries in the background so stop removing lookaside entries when reading pages from lookaside tree.

### CODE REVIEW

**Comment by agorrod** [comment]
@nehakhatri5 please run some Evergreen correctness and perf tests on this branch

**Comment by agorrod** [comment]
This change is potentially destabilising, am going to hold off moving forward with it for now.

**Comment by michaelcahill** [comment]
@sulabhM, how does WT-4218 currently prevent prepared updates in lookaside from being removed by sweep?

**Comment by sulabhM** [comment]
@michaelcahill , there was no change as part of WT-4218 to prevent prepared updates in lookaside from being removed, that change already exists here in __wt_las_sweep():

```
                /*                                                               
                 * If this entry isn't globally visible or if it is a part of a  
                 * prepared transaction, then we cannot remove it. Otherwise,    
                 * perform additional checks to see whether it has aged out of a 
                 * live file.                                                    
                 */                                                              
                if (!__wt_txn_visible_all(session, las_txnid, val_ts) ||         
                    prepare_state == WT_PREPARE_INPROGRESS) {                    
                        saved_key->size = 0;                                     
                        continue;                                                
                }   
```  

While working on WT-4218 we had a discussion about whether we need to do something special for prepared transactions so that sweep will clear them out. The conclusion from there was that it is okay for sweep to ignore these entries because commit/rollback will read them back in, and the read will remove them from lookaside.

**Comment by michaelcahill** [comment]
Thanks @sulabhM.

@agorrod, is there some testing we could do to unblock this change?

**Comment by agorrod** [comment]
I'm good to go with this now that we've made a drop to master, I'll go ahead and merge.

**Pull request merged**
