### PR TITLE
WT-4812 Fix the Python distribution script for Python3 changes.

### PR DESCRIPTION
**Pull request by ddanderson**
SWIG generated Python files are now installed in build_posix, so the script needed to be adjusted.

### CODE REVIEW

**Comment by ddanderson** [comment]
@lukech, can you please review?  The change is simple, but equally important is the procedure for building.  I discovered that if whatever `python` is in your `PATH` happens to be version 2.X, then you can run the script without error, you can install the result (with Py2 or Py3), you can run a program that calls into WT and prints the version number, but you WON'T be able to run a program that does anything real with WT (at least with Py3, it works with Py2).  If instead you have a `python` in your `PATH` that is version 3.X, that you can configure/build/setup_pip.py and end up with a distribution that works with either Py2 or Py3.  To help prevent the error, I put a check in this script.  I also overhauled the github Wiki page.  Can you try the procedure again as outlined in https://github.com/wiredtiger/wiredtiger/wiki/HOWTO:UploadAReleaseForPythonInstalls , using this changed script?  Thanks!

**Comment by lukech** [comment]
@ddanderson Thanks much for the note and fix! I will test the procedure and let you know.

**Comment by lukech** [comment]
@ddanderson Today I checked out this PR branch `wt-4812-pip-py3` and ran through the updated Python release guide. Did not run `git checkout tags/${WTVER} -b ${WTVER}` step to avoid losing the fix in this PR branch. The `python setup_pip.py sdist` step passed which is great! 

However, the running of test program `testbase.py` failed to import _wiredtiger module. I tried in both a python2 and a python3 virtual environments, with both having a successful `pip install dist/wiredtiger-${WTVER}.tar.gz` step. 

In the Python2 virtualenv: 
> $ pip list
> DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
> Package    Version
> ---------- -------
> pip        19.1.1
> setuptools 41.0.1
> wheel      0.33.4
> wiredtiger 3.2.0
> $ python testbase.py
> Traceback (most recent call last):
>   File "testbase.py", line 1, in <module>
>     import wiredtiger, shutil, os
>   File "/mnt/data0/lchen/work/wiredtiger-release2/lang/python/wiredtiger.py", line 35, in <module>
>     _wiredtiger = swig_import_helper()
>   File "/mnt/data0/lchen/work/wiredtiger-release2/lang/python/wiredtiger.py", line 34, in swig_import_helper
>     return importlib.import_module('_wiredtiger')
>   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
> ImportError: No module named _wiredtiger

In the Python3 virtualenv:
> $ pip list
> Package    Version
> ---------- -------
> pip        19.1.1
> setuptools 41.0.1
> wheel      0.33.4
> wiredtiger 3.2.0
> $ python testbase.py
> Traceback (most recent call last):
>   File "/mnt/data0/lchen/work/wiredtiger-release2/lang/python/wiredtiger.py", line 32, in swig_import_helper
>     return importlib.import_module(mname)
>   File "/home/lchen/venv-py3/lib/python3.7/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
> ModuleNotFoundError: No module named '_wiredtiger'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "testbase.py", line 1, in <module>
>     import wiredtiger, shutil, os
>   File "/mnt/data0/lchen/work/wiredtiger-release2/lang/python/wiredtiger.py", line 35, in <module>
>     _wiredtiger = swig_import_helper()
>   File "/mnt/data0/lchen/work/wiredtiger-release2/lang/python/wiredtiger.py", line 34, in swig_import_helper
>     return importlib.import_module('_wiredtiger')
>   File "/home/lchen/venv-py3/lib/python3.7/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
> ModuleNotFoundError: No module named '_wiredtiger'

Another 2 unrelated thinkings:
- `$ sh makemake --clean-and-make` did not seem to take any effect. It looks the `--clean-and-make` option is not supported in the makemake script? 
- Can `testbase.py` be put into code repo so that we can reuse it more easily in the future?

**Comment by ddanderson** [comment]
@lukech, I see the following wiredtiger files installed in my virtual environment:

```
$ pwd
/home/dda/tmp/venv-mdbtoolchain-py2-x
(venv-mdbtoolchain-py2-x) dda@margay-aws:~/tmp/venv-mdbtoolchain-py2-x$ find . -type f -print | grep wiredtiger
./lib/python2.7/site-packages/wiredtiger-3.2.0.dist-info/WHEEL
./lib/python2.7/site-packages/wiredtiger-3.2.0.dist-info/INSTALLER
./lib/python2.7/site-packages/wiredtiger-3.2.0.dist-info/top_level.txt
./lib/python2.7/site-packages/wiredtiger-3.2.0.dist-info/METADATA
./lib/python2.7/site-packages/wiredtiger-3.2.0.dist-info/RECORD
./lib/python2.7/site-packages/wiredtiger-3.2.0.dist-info/LICENSE
./lib/python2.7/site-packages/wiredtiger/packutil.py
./lib/python2.7/site-packages/wiredtiger/fpacking.py
./lib/python2.7/site-packages/wiredtiger/wiredtiger.py
./lib/python2.7/site-packages/wiredtiger/packing.py
./lib/python2.7/site-packages/wiredtiger/intpacking.py
./lib/python2.7/site-packages/wiredtiger/setup.pyc
./lib/python2.7/site-packages/wiredtiger/_wiredtiger.so
./lib/python2.7/site-packages/wiredtiger/packing.pyc
./lib/python2.7/site-packages/wiredtiger/intpacking.pyc
./lib/python2.7/site-packages/wiredtiger/fpacking.pyc
./lib/python2.7/site-packages/wiredtiger/__init__.pyc
./lib/python2.7/site-packages/wiredtiger/packutil.pyc
./lib/python2.7/site-packages/wiredtiger/setup.py
./lib/python2.7/site-packages/wiredtiger/__init__.py
./lib/python2.7/site-packages/wiredtiger/wiredtiger.pyc
$ cd ../venv-mdbtoolchain-py3-x/
$ find . -type f -print | grep wiredtiger
./lib/python3.7/site-packages/wiredtiger-3.2.0.dist-info/WHEEL
./lib/python3.7/site-packages/wiredtiger-3.2.0.dist-info/INSTALLER
./lib/python3.7/site-packages/wiredtiger-3.2.0.dist-info/top_level.txt
./lib/python3.7/site-packages/wiredtiger-3.2.0.dist-info/METADATA
./lib/python3.7/site-packages/wiredtiger-3.2.0.dist-info/RECORD
./lib/python3.7/site-packages/wiredtiger-3.2.0.dist-info/LICENSE
./lib/python3.7/site-packages/wiredtiger/packutil.py
./lib/python3.7/site-packages/wiredtiger/_wiredtiger.cpython-37m-x86_64-linux-gnu.so
./lib/python3.7/site-packages/wiredtiger/fpacking.py
./lib/python3.7/site-packages/wiredtiger/wiredtiger.py
./lib/python3.7/site-packages/wiredtiger/packing.py
./lib/python3.7/site-packages/wiredtiger/intpacking.py
./lib/python3.7/site-packages/wiredtiger/__pycache__/wiredtiger.cpython-37.pyc
./lib/python3.7/site-packages/wiredtiger/__pycache__/setup.cpython-37.pyc
./lib/python3.7/site-packages/wiredtiger/__pycache__/intpacking.cpython-37.pyc
./lib/python3.7/site-packages/wiredtiger/__pycache__/fpacking.cpython-37.pyc
./lib/python3.7/site-packages/wiredtiger/__pycache__/__init__.cpython-37.pyc
./lib/python3.7/site-packages/wiredtiger/__pycache__/packutil.cpython-37.pyc
./lib/python3.7/site-packages/wiredtiger/__pycache__/packing.cpython-37.pyc
./lib/python3.7/site-packages/wiredtiger/setup.py
./lib/python3.7/site-packages/wiredtiger/__init__.py
```
I assume you using a virtual environment?  Just to make sure, you have it in effect when you do the pip install, and also when running the program?  Can you try the above `find` command to make sure wiredtiger got installed in the virt env?  Also, do you have either `PYTHONPATH` or `LD_LIBRARY_PATH` in your environment, that may be gumming up the works.

What should be happening (using Python2 as an example), is the import of `wiredtiger` should be finding `<virtualenv>/lib/python2.7/site-packages/wiredtiger/wiredtiger.py` and not `/mnt/data0/lchen/work/wiredtiger-release2/lang/python/wiredtiger.py`.  Since it's looking elsewhere, it's probably `PYTHONPATH` ?  If that isn't it, let's schedule a time to talk.

**Comment by ddanderson** [comment]
@lukech, I added `testbase.py` and `testpack.py` to the code base (in `~/test/py_install`), I updated the instructions to:
- refer to these new files
- remove extra args from `sh makemake`
- do `unset PYTHONPATH`

**Comment by lukech** [comment]
@ddanderson Yes, I used virtual environments. By following the guide, I created a Python3 virtual env to generate the wiredtiger tarball, and later on a separate Python2 virtual env to install & test the tarball. `PYTHONPATH` and `LD_LIBRARY_PATH` were not set in my environment. 

Here is the `find` output of my Python2 test virtual env:
```
(venv-3.2.0) lchen@nimer:~/work/wiredtiger-release2/lang/python/venv-3.2.0$ find . -type f -print | grep wiredtiger
./lib/python2.7/site-packages/wiredtiger/wiredtiger.py
./lib/python2.7/site-packages/wiredtiger/__init__.pyc
./lib/python2.7/site-packages/wiredtiger/packing.py
./lib/python2.7/site-packages/wiredtiger/setup.py
./lib/python2.7/site-packages/wiredtiger/intpacking.py
./lib/python2.7/site-packages/wiredtiger/setup.pyc
./lib/python2.7/site-packages/wiredtiger/packutil.pyc
./lib/python2.7/site-packages/wiredtiger/packutil.py
./lib/python2.7/site-packages/wiredtiger/intpacking.pyc
./lib/python2.7/site-packages/wiredtiger/fpacking.pyc
./lib/python2.7/site-packages/wiredtiger/_wiredtiger.so
./lib/python2.7/site-packages/wiredtiger/wiredtiger.pyc
./lib/python2.7/site-packages/wiredtiger/fpacking.py
./lib/python2.7/site-packages/wiredtiger/__init__.py
./lib/python2.7/site-packages/wiredtiger/packing.pyc
./lib/python2.7/site-packages/wiredtiger-3.2.0.dist-info/RECORD
./lib/python2.7/site-packages/wiredtiger-3.2.0.dist-info/LICENSE
./lib/python2.7/site-packages/wiredtiger-3.2.0.dist-info/METADATA
./lib/python2.7/site-packages/wiredtiger-3.2.0.dist-info/top_level.txt
./lib/python2.7/site-packages/wiredtiger-3.2.0.dist-info/WHEEL
./lib/python2.7/site-packages/wiredtiger-3.2.0.dist-info/INSTALLER
```

**Comment by ddanderson** [comment]
@lukech, I'm glad you figured that out.  But I'm still wondering why python would look in `~/work/wiredtiger-release2/lang/python/` at all for imports.

**Comment by lukech** [comment]
@ddanderson Today I re-ran the procedure in a clean git checkout on `wt-4812-pip-py3` branch. 

It turned out `(cd ./lang/python; make ../../../lang/python/wiredtiger_wrap.c)` got the `lang/python/wiredtiger.py` file generated. 

Continued generating the tallball, encountered similar issue as initial problem as below:
```(venv-py3) lchen@nimer:~/work/wiredtiger-release3/lang/python$ python setup_pip.py sdist
Traceback (most recent call last):
  File "setup_pip.py", line 331, in <module>
    shutil.copy2(src, os.path.join(stage_dir, f))
  File "/home/lchen/venv-py3/lib/python3.7/shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/lchen/venv-py3/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'build_posix/lang/python/wiredtiger/__init__.py'
```
It looks `build_posix/lang/python/wiredtiger/__init__.py` file was not generated when [this line](https://github.com/wiredtiger/wiredtiger/pull/4718/files#diff-62f26e17a3ce54a4800a38ff06f2bb76R215) was run. A full `make` got the file generated and worked around the problem, and the tarball was gnerated. I think the reason I did not encounter above issue in my previous test is I did a full make at some stage in my `~/work/wiredtiger-release2` directory. 

Then I created a Python2 virtual env to install & test the tarball, which was successful. In order to ensure the tarball (through pip install) was imported (instead of the `lang/python/wiredtiger.py`), I added a few lines in the `testbase.py` program to dump out Python `sys.path` of my environment and the wiredtiger module file being used. 
```
(venv-3.2.0) lchen@nimer:~/work/wiredtiger-release3/lang/python$ git diff
diff --git a/test/py_install/testbase.py b/test/py_install/testbase.py
index a75599815..5c2d880aa 100755
--- a/test/py_install/testbase.py
+++ b/test/py_install/testbase.py
@@ -31,6 +31,11 @@
 import wiredtiger, shutil, os
 from wiredtiger import wiredtiger_open, wiredtiger_version

+import sys
+for idx, path in enumerate(sys.path, 1):
+    print('{} - {}'.format(idx, path))
+print('\nwiredtiger module location - {}'.format(wiredtiger.__file__))
+
 wthome = "WTPY_TEST"
 shutil.rmtree(wthome, ignore_errors=True)
 os.mkdir(wthome)
```
Here is the test output:
```
(venv-3.2.0) lchen@nimer:~/work/wiredtiger-release3/lang/python$ python ../../test/py_install/testbase.py
1 - /mnt/data0/lchen/work/wiredtiger-release3/test/py_install
2 - /mnt/data0/lchen/work/wiredtiger-release3/lang/python/venv-3.2.0/lib/python2.7
3 - /mnt/data0/lchen/work/wiredtiger-release3/lang/python/venv-3.2.0/lib/python2.7/plat-x86_64-linux-gnu
4 - /mnt/data0/lchen/work/wiredtiger-release3/lang/python/venv-3.2.0/lib/python2.7/lib-tk
5 - /mnt/data0/lchen/work/wiredtiger-release3/lang/python/venv-3.2.0/lib/python2.7/lib-old
6 - /mnt/data0/lchen/work/wiredtiger-release3/lang/python/venv-3.2.0/lib/python2.7/lib-dynload
7 - /usr/lib/python2.7
8 - /usr/lib/python2.7/plat-x86_64-linux-gnu
9 - /usr/lib/python2.7/lib-tk
10 - /mnt/data0/lchen/work/wiredtiger-release3/lang/python/venv-3.2.0/local/lib/python2.7/site-packages
11 - /mnt/data0/lchen/work/wiredtiger-release3/lang/python/venv-3.2.0/lib/python2.7/site-packages
12 - /mnt/data0/lchen/work/wiredtiger-release3/lang/python/venv-3.2.0/local/lib/python2.7/site-packages/wiredtiger

wiredtiger module location - /mnt/data0/lchen/work/wiredtiger-release3/lang/python/venv-3.2.0/local/lib/python2.7/site-packages/wiredtiger/wiredtiger.pyc
Expect 200 = 200
['WiredTiger 3.2.0: (May  9, 2019)', 3, 2, 0]
testbase success.
```
The directory where the test program sits was the 1st `sys.path` to be attempted for import. As there's no wiredtiger.py file existed in that directory it went through the rest of paths and finally found the match under the 12th `sys.path`.

I made another test by copying `testbase.py` into `~/work/wiredtiger-release3/lang/python/` and ran it. Here is the test output:
```
(venv-3.2.0) lchen@nimer:~/work/wiredtiger-release3/lang/python$ cp ../../../wiredtiger-release2/lang/python/testbase.py .
(venv-3.2.0) lchen@nimer:~/work/wiredtiger-release3/lang/python$ python testbase.py
Traceback (most recent call last):
  File "testbase.py", line 1, in <module>
    import wiredtiger, shutil, os, sys
  File "/mnt/data0/lchen/work/wiredtiger-release3/lang/python/wiredtiger.py", line 35, in <module>
    _wiredtiger = swig_import_helper()
  File "/mnt/data0/lchen/work/wiredtiger-release3/lang/python/wiredtiger.py", line 34, in swig_import_helper
    return importlib.import_module('_wiredtiger')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _wiredtiger
```
This matched with what I saw in my yesterday's testing, as `~/work/wiredtiger-release3/lang/python/wiredtiger.py` did exist, and was chosen as the import path, which is undesired.

**Comment by ddanderson** [comment]
@lukech, great sleuthing!  Okay, as I understand we have two issues that can be fixed by clarifying the process wiki.  First, you must do a full make.  I was doing that, and didn't notice that it made a difference.  Second, you cannot run the test program from `lang/python`.  That fully explains why it was pulling in the wrong file on the import.

**Comment by ddanderson** [comment]
@lukech, I've updated the wiki to (hopefully) fix these two problems.  Take a look when you have a chance.

**Comment by lukech** [comment]
@ddanderson Thanks for the wiki update. I had another run of the procedure and it's working fine in a fresh git checkout!

A couple of minor updates might be needed in the `Testing the Release` section:
- If creating and switching to `~/pytest` directory, the later `pip install dist/wiredtiger-${WTVER}.tar.gz` step will fail as the relative directory is unexpected in the command. Guess the switch to a clean working env/directory is aimed to avoid interference from files under `lang/python`. I don't mind to keep the initial approach of creating virtual env under `lang/python` considering we've understood the potential problem and its cause. 
- The `testbase.py` program looks located under `test/py_install`, the same as the other test program `testpack.py`.
- Add a `deactivate` step at the beginning of `clean up` procedure to exit the virtual env before removing its directory.

**Comment by ddanderson** [comment]
@lukech thanks for the careful review.  In the wiki, I've fixed the 3 items you identified.  I like using a separate directory for testing, no possibility of that previous error coming up.  Also it makes clean up easier.  So I think this is really done.  At least until next release... :-)

**Comment by lukech** [comment]
@ddanderson thanks a lot for making the wiki page up-to-date!

**Pull request merged**
