### PR TITLE
Give threads names when on non-ancient pthreads

### PR DESCRIPTION
**Pull request by DarkDimius**
These are convenient for quick diagnostics,
in particular in incident situation.

While thread names don't replace backtraces/process dumps/etc,
these names can help build candidate theories about cause of issue faster.

### CODE REVIEW

**Comment by lukech** [comment]
autobuild: Can one of the admins verify this patch?

**Comment by tetsuo-cpp** [comment]
Hey @DarkDimius, nice to meet you. Thanks for submitting this patch!

Before we go ahead and get this merged, could you please:
- Sign our [Contributor Agreement](https://www.mongodb.com/legal/contributor-agreement).
- Provide us with edit permission on your branch. Instructions on how do that can be found [here](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

**Comment by tetsuo-cpp** [comment]
In our workflow, we merge new development work to the `develop` branch rather than `master`. If you can resolve the merge conflicts or rebase against `develop`, we can proceed.

Sorry for the inconvenience. We're planning to change the default branch to `develop` in the future to prevent confusion.

**Comment by tetsuo-cpp** [comment]
I'm closing this since the PR has been inactive for a month. Unfortunately, we can't merge unless the contributor agreement is signed.

@DarkDimius feel free to re-open if you'd like.

**Pull request closed without merging**
