### PR TITLE
WT-6556 Fix internal sessions to use internal session close function than public API to avoid memory leak 

### PR DESCRIPTION
**Pull request by kommiharibabu**
Due to PANIC error set by the recovery failure stops processing
any session operations led to memory leak. Avoid stopping of processing
session operations for the internal sessions can fix the memory leak
and also avoid performing the final checkpoint when the connection
is PANIC state

### CODE REVIEW

**Comment by agorrod** [comment]
@kommiharibabu is it possible to craft a Python test case that covers this scenario?

I'm not a huge fan of allowing sessions to enter APIs when PANIC is set (even internal threads). I see that you explored alternative solutions - did they seem unacceptable?

**Review by tetsuo-cpp — APPROVED** [review]
LGTM.

The code looks fine to me. What is the concern of using the session API directly?

**Comment by kommiharibabu** [comment]
@tetsuo-cpp Using session API doesn't close the session when the connection is in a PANIC state. Due to which all transaction memory that is allocated for the internal sessions gets leaked. To continue the internal sessions to close even when there is an error they use the internal API.

**Review by agorrod — APPROVED** [review]
Thanks @kommiharibabu lgtm, this ended up being a nice simplification.

**Review by bvpvamsikrishna — APPROVED** [review]
lgtm

**Pull request merged**
