### PR TITLE
WT-9205 Correct transaction warning text in documentation

### PR DESCRIPTION
**Pull request by keitharnoldsmith**
Sorry to hit you with another PR, @sueloverso.  I somehow missed your comment on the last one.  This change addresses that.

### CODE REVIEW

**Review by sueloverso — APPROVED** [review]
LGTM

**Comment by sueloverso** [comment]
Sometimes when I see a message (like on the slack bot) that says "X approved your Pull request..." it is easy to just go merge it.

**Comment by keitharnoldsmith** [comment]
> Sometimes when I see a message (like on the slack bot) that says "X approved your Pull request..." it is easy to just go merge it.

Especially when the PR is quite small to start with...

**Comment by keitharnoldsmith** [comment]
Evergreen failure is WT-8431 (again).  Not related to this PR.

**Pull request merged**
