### PR TITLE
WT-11664 Fix test_truncate22 timestamp usage

### PR DESCRIPTION
**Pull request by Sean04**

### CODE REVIEW

**Comment by quchenhao** [comment]
@Sean04 Can you describe what is the problem here?

**Review by Siddhartha8899 — APPROVED** [review]

**Comment by Sean04** [comment]
> @Sean04 Can you describe what is the problem here on the ticket?
I've updated the ticket to explain the fix.
cc. @quchenhao

**Review by quchenhao — APPROVED** [review]
lgtm

**Comment by Sean04** [comment]
evergreen merge

**Pull request merged**
