### PR TITLE
WT-9772 Fix RTS to abort the updates using the recovered checkpoint snapshot  (v6.1 backport)

### PR DESCRIPTION
**Pull request by svc-bot-sebb**
064bbe0878ef559d76339d7812ef141e89436eaa

### CODE REVIEW

**Review by kommiharibabu — APPROVED** [review]
LGTM

**Review by jiechenbo — APPROVED** [review]
LGTM!

**Comment by kommiharibabu** [comment]
evergreen retry

**Comment by kommiharibabu** [comment]
This PR is backported with a bulk bacport.

**Pull request closed without merging**
