### PR TITLE
WT-11913 Include write generation information wt verify dump

### PR DESCRIPTION
**Pull request by adelinexchen**
Have added workgen info to wt-verify dump output.

We have attempted to align the columns for easier reading, it is currently hard coded just as a demonstration to see if this is something that is even wanted (this is not in the ticket scope). Downsides of aligning the columns is mostly that we will be adding unnecessary white space in most columns, which causes the output to wrap on the cmd line (which makes it more difficult to read anyways).

### CODE REVIEW

**Comment by adelinexchen** [comment]
Failed test not related

**Review by Siddhartha8899 — APPROVED** [review]

**Comment by Sean04** [comment]
Sorry to be pedantic here but I noticed:
dump_address (this change) outputs: `write gen: XX`
dump_blocks outputs: `generation XX`
dump_pages output: `write_gen: XX`

I think we should align these messages.

**Comment by Siddhartha8899** [comment]
@Sean04 we are planning to do this as part of [WT-12233](https://jira.mongodb.org/browse/WT-12233) and [WT-12234](https://jira.mongodb.org/browse/WT-12234).

This should be part of these ticket's scope. Let me know what you think.

**Review by Sean04 — APPROVED** [review]
LGTM

**Comment by adelinexchen** [comment]
evergreen merge

**Comment by adelinexchen** [comment]
evergreen merge

**Pull request merged**
