### PR TITLE
WT-12176 ./wt verify support unredacted for dump offsets

### PR DESCRIPTION
**Pull request by y123456yz**
wt verify perfect and bug fix

1. wt dump_blocks should not output leaf page's KV info.
image

3. wt dump_offsets needs to support the dump_app_data configuration.
 
image

### CODE REVIEW

**Comment by y123456yz** [comment]
WT-12176

**Comment by korteland** [comment]
Hi @y123456yz , thanks for the contribution. At the moment we've got a lot of people out of the office for the christmas/new year break, and it's likely the earliest we could get around to this is January.

(The same thing goes for WT-12177, WT-12178, and WT-12179 as well, unfortunately.)

Sorry for the delay, and thanks for your patience.

**Comment by y123456yz** [comment]
> thanks for the contribution. At the moment we've got a lot of people out of the office for the christmas/new year break, and it's likely the earliest we could get around to this is January.
> 
> (The same thing goes for [WT-12177](https://jira.mongodb.org/browse/WT-12177), [WT-12178](https://jira.mongodb.org/browse/WT-12178), and [WT-12179](https://jira.mongodb.org/browse/WT-12179) as well, unfortunately.)
> 
> Sorry for the delay, and thanks for your patience.

@korteland 
Thanks for your reply, I wish you a happy holiday.

**Comment by korteland** [comment]
@y123456yz thanks for your patience here. People are starting to trickle back, but there's a lot of open PRs and we only have so much bandwidth to review them. I'll work on finding reviewers, but I can't guarantee when we can get around to your open PRs sorry.

**Comment by y123456yz** [comment]
Don't worry, you can help take a look when you have time.
thanks.

**Comment by korteland** [comment]
@y123456yz is this still relevant? We recently ran a small project to improve the output of the `wt` tool's dump output, including changing how redaction works. Would you be able to give the new version of the `wt` tool a run and see if it addresses the issues you're looking at here?

**Comment by y123456yz** [comment]
@korteland 
I have done a simple verification using the latest code from the develop branch, but there are still some issues. In a few days, I will merge the develop branch code and @ you can help me review it again.

thanks.

**Comment by luke-pearson** [comment]
Hi @y123456yz sorry for the delay reviewing this. Would you be able to merge in develop?

**Comment by y123456yz** [comment]
> Hi @y123456yz sorry for the delay reviewing this. Would you be able to merge in develop?
@luke-pearson 
got it, thanks
I'll merge the code and let you know in the next few days.

**Comment by y123456yz** [comment]
@luke-pearson 
The latest development branch code has fixed some previous issues, and I have continued to improve the code for this PR. 
The main optimization points in this PR is as follows:
Block_offsets supports clear text display.

**Comment by y123456yz** [comment]
Also, I have a question, what is the design purpose of dump_blocks? What is the main difference between him and dump-address and dump_pages?
Can you help me with that? I don't understand that very well.
thanks.
@korteland @luke-pearson

**Review by luke-pearson — APPROVED** [review]
LGTM

**Comment by korteland** [comment]
@y123456yz to your question about `dump_blocks` and friends, this is listed in the `session->verify` API docs: https://source.wiredtiger.com/develop/struct_w_t___s_e_s_s_i_o_n.html#a0334da4c85fe8af4197c9a7de27467d3

Under the bonnet, the `wt verify` utility is largely calling out to this method.

**Comment by y123456yz** [comment]
> @y123456yz to your question about `dump_blocks` and friends, this is listed in the `session->verify` API docs: https://source.wiredtiger.com/develop/struct_w_t___s_e_s_s_i_o_n.html#a0334da4c85fe8af4197c9a7de27467d3
> 
> Under the bonnet, the `wt verify` utility is largely calling out to this method.

@korteland 
got it, thanks.

**Comment by luke-pearson** [comment]
@y123456yz could you please merge in develop again to see if it resolves the verify issue?

**Comment by y123456yz** [comment]
I merge the latest develop, No conflicts.
thanks.

**Comment by y123456yz** [comment]
I merge latest develop branch, No conflicts.
thanks.

**Comment by luke-pearson** [comment]
@jeremythorp could you look into why this is failing the coverage report?

**Comment by jeremythorp** [comment]
Hi @luke-pearson ,

I it looks like a compile time fail due to an added, but unused, function parameter. It looks like the compilers tasks have failed for the same reason.

For example:
```
[2024/04/15 14:42:48.051] /data/mci/bb072bfd0eb84c9d574367392c38a861/wiredtiger/src/btree/bt_vrfy.c: In function '__verify_config_offsets':
[2024/04/15 14:42:48.051] /data/mci/bb072bfd0eb84c9d574367392c38a861/wiredtiger/src/btree/bt_vrfy.c:122:94: error: unused parameter 'vs' [-Werror=unused-parameter]
[2024/04/15 14:42:48.051]   122 | __verify_config_offsets(WT_SESSION_IMPL *session, const char *cfg[], bool *quitp, WT_VSTUFF *vs)
[2024/04/15 14:42:48.051]       |                                                                                   ~~~~~~~~~~~^~
[2024/04/15 14:42:48.051] cc1: all warnings being treated as errors
[2024/04/15 14:42:48.106] [41/665] Building C object CMakeFiles/wt_objs.dir/src/btree/bt_vrfy.c.o
```
Cheers, Jeremy

**Comment by luke-pearson** [comment]
s-all

**Comment by y123456yz** [comment]
> s-all

complete, thanks.

**Review by luke-pearson — APPROVED** [review]
LGTM.

**Review by luke-pearson — APPROVED** [review]
LGTM.

**Comment by luke-pearson** [comment]
Hi @y123456yz apologies that this one did not get merged. Can we fix the conflicts with develop?

**Comment by y123456yz** [comment]
done @luke-pearson

**Review by luke-pearson — APPROVED** [review]
LGTM.

**Pull request merged**
