### PR TITLE
WT-10192 Fix bug in cursor_prev_skip statistics (v6.2 backport)

### PR DESCRIPTION
**Pull request by svc-bot-sebb**
439cd2fbc72e0a0dcd19e86205feffd5430440c6

### CODE REVIEW

**Comment by jiechenbo** [comment]
Testing storage engine bot

**Review by luke-pearson — APPROVED** [review]
LGTM.

**Comment by jiechenbo** [comment]
Closing this.

**Comment by lukech** [comment]
Reopening this PR as the branch sync today ran into a testing fallout that we'd avoid. Let's fallback to cherry-pick backport for this specific change.

**Pull request closed without merging**
