### PR TITLE
WT-8234 Prevent eviction of internal pages while reconciling leaf pages which could refer to their memory.

### PR DESCRIPTION
**Pull request by luke-pearson**

### CODE REVIEW

**Review by keithbostic — APPROVED** [review]
This makes sense to me. I think the comment needs some enhancement though -- this isn't about "eviction of an internal page", is it? It's more like "don't let the internal page split, because ..."

**Comment by luke-pearson** [comment]
@keithbostic, splitting the internal page is fine its only when the content on the original page gets evicted that we run into problems.

**Comment by keithbostic** [comment]
> splitting the internal page is fine its only when the content on the original page gets evicted that we run into problems.

@luke-pearson, fair enough, I think that's correct, I guess I'm still stuck in the whole mess of the failure path. :)

**Review by sueloverso — APPROVED** [review]
LGTM

**Pull request merged**
