### PR TITLE
WT-12182 Check that the dhandle is open for tiered work.

### PR DESCRIPTION
**Pull request by sueloverso**
Avoid using the structure if it isn't opened. I'm running a tiered schema_abort run overnight, but with this fix it is not failing so far (and it was, 100% of the time).

### CODE REVIEW

**Comment by sueloverso** [comment]
@keitharnoldsmith hold off for the moment as I hit a similar failure after an hour of running. This may have narrowed the window instead of closed it.

**Comment by sueloverso** [comment]
@keitharnoldsmith I think we should go ahead and review/merge this and open a new ticket for the failure. I cannot reproduce it and will set up a longer run. But this one was very specifically because `tiered->obj_config` was NULL. This adds an assert as well as avoids that case so I think the new failure is probably something different.

**Comment by keitharnoldsmith** [comment]
Hey @sueloverso. I'm a bit confused. 

Your comment on the ticket says:
> In wt_tiered_open we have the tiered structure from the dhandle. So the dhandle and/or tiered structure is not getting closed or cleaned up on the error. 

So I was expecting that the PR would address the failure to close/cleanup the tiered structure on that error path. But the PR seems to instead be patching the background operating processing to handle the case where we failed to do that cleanup and we have a tiered/dhandle structure that wasn't properly opened. If I understand correctly, would it be cleaner to fix the issue in `wt_tiered_open`?

**Comment by sueloverso** [comment]
@keitharnoldsmith it turned out that we had a closed dhandle on the global dhandle list and when the work unit is processed, the code assumed it was open.

**Comment by sueloverso** [comment]
Close in favor of fresh branch for simplified change.

**Pull request closed without merging**
