### PR TITLE
WT-7186 Correct expected in-memory abort updates in prepare scenario

### PR DESCRIPTION
**Pull request by kommiharibabu**
Prepared updates are restored on to the page when the page gets loaded
into memory, so it is possible that there can be in-memory abort updates.

### CODE REVIEW

**Review by raviprakashgiri29 — APPROVED** [review]
LGTM

**Comment by raviprakashgiri29** [comment]
@kommiharibabu Can you check if other RTS tests with prepared transactions also need to be changed?

**Comment by kommiharibabu** [comment]
@raviprakashgiri29 I checked all the RTS tests and didn't find any leftover function blocks that allow column store with prepare.

**Review by quchenhao — APPROVED** [review]
lgtm

**Pull request merged**
