### PR TITLE
WT-5626 Remove assert which checks for newer updates in the history store

### PR DESCRIPTION
**Pull request by luke-pearson**

### CODE REVIEW

**Comment by quchenhao** [comment]
Should we skip visibility check in this change to make history store page always evictable?

**Comment by luke-pearson** [comment]
> 
> 
> Should we skip visibility check in this change to make history store page always evictable?

Which visibility check are you referring to? Either way that work sounds like it should be part of a different ticket.

**Comment by quchenhao** [comment]
> > Should we skip visibility check in this change to make history store page always evictable?
> 
> Which visibility check are you referring to? Either way that work sounds like it should be part of a different ticket.

In the discussion, we think for history store there is no need to check the visibility of the updates as they must all have been committed. Thus, we can always evict a history store page. I agree we can address that in a separate ticket.

**Comment by luke-pearson** [comment]
> 
> 
> > > Should we skip visibility check in this change to make history store page always evictable?
> > 
> > 
> > Which visibility check are you referring to? Either way that work sounds like it should be part of a different ticket.
> 
> In the discussion, we think for history store there is no need to check the visibility of the updates as they must all have been committed. Thus, we can always evict a history store page. I agree we can address that in a separate ticket.

Created: WT-5638

**Pull request merged**
