### PR TITLE
WT-12149 Don't erroneously release checkpoint resources in __wt_ckpt_verbose

### PR DESCRIPTION
**Pull request by y123456yz**
__wt_ckpt_verbose bug fix, Resources should not be released destroy

### CODE REVIEW

**Comment by y123456yz** [comment]
https://jira.mongodb.org/browse/WT-12149

**Comment by korteland** [comment]
@y123456yz What problem is this solving? Did you see a crash related to this? As far as I can tell, the original code was correct.

**Comment by y123456yz** [comment]
> @y123456yz What problem is this solving? Did you see a crash related to this? As far as I can tell, the original code was correct.

hi, @korteland 
I'm sorry, maybe I didn't describe it clearly.
The  __wt_ckpt_verbose  function is to print logs， log function should not destroy block_ckpt, This is very dangerous.

For example, let's say __wt_buf_catfmt function has a bug, This can cause serious problems.

 log function should only print log， Should not interfere with other logic.

thanks.

**Comment by korteland** [comment]
Got it, thanks for the explanation @y123456yz.

To print the checkpoint, we need to unpack some information into a structure. Creating this structure allocates memory, and that memory must be freed at the end of the function. With the change you are proposing, this memory will instead be leaked.

To understand this issue in a little more depth, I'd encourage you to take a look at `__wt_block_ckpt_init`. 

I'm willing to be proven wrong and there's every chance I've misunderstood something about how this code works, but as it stands I don't believe this code needs fixing.

**Comment by y123456yz** [comment]
@korteland 
You're right, I'm wrong, I'm looking at it as a function entry variable, it's actually a temporarily variable.
thanks, I close the PR.

**Comment by korteland** [comment]
No worries! Thanks anyway for taking a look.

**Comment by y123456yz** [comment]
> No worries! Thanks anyway for taking a look.

:)

**Pull request closed without merging**
