### PR TITLE
Eviction config cleanup

### PR DESCRIPTION
**Pull request by keithbostic**
@michaelcahill, @agorrod -- this branch has the changes for #1686 (move the big eviction configuration knobs into the configuration file as undocumented values), and #1217 (push the existing eviction configuration knobs into the eviction sub configuration group), if you agree with these changes, I believe we can close both of those issues.

### CODE REVIEW

**Comment by keithbostic** [comment]
One question: we currently split the eviction configuration between the WT_CONNECTION_IMPL structure (worker threads information) and WT_CACHE (everything else). Is there a reason for that?

**Comment by agorrod** [comment]
@keithbostic Have you thought through the backward compatibility consequences of renaming the eviction configuration values? Do they end at keeping the old strings as supported but undocumented? How about loading newer databases using an older version of WiredTiger?

If we do maintain deprecated configuration strings and it's the solution moving forward - does it make sense to add a configuration helper method (or a couple) that can find a value from a set of configuration strings? If there are multiple versions of a configuration present in a configuration string which order do we look for matches in i.e do we:
 * Make it illegal to specify both (I don't like this), 
 * Does the newer form override the older form,
 * Does the older form override the newer form (as in your change) or
 * Do we stick with the last entry in a configuration string

While I'm asking questions: how do we deal with default values from deprecated settings. Do we ensure that config_get is always called without the full configuration stack for deprecated values? Do we make sure deprecated values always have values matching their replacement configuration?

**Comment by keithbostic** [comment]
> Have you thought through the backward compatibility consequences of renaming the eviction configuration values?

Hopefully...

> Do they end at keeping the old strings as supported but undocumented?

Yes.

> How about loading newer databases using an older version of WiredTiger?

As long as you use the older configuration strings it will work; if you were to create a database using the newer configuration strings, then try and open that database using an older version of the library, it won't work, of course.

> If we do maintain deprecated configuration strings and it's the solution moving forward - does it make sense to add a configuration helper method (or a couple) that can find a value from a set of configuration strings?

To be clear, we already do this. I thought a little bit about generalizing it, but the differences between how we handle each deprecated configuration string has some subtlety: for example, "lsm_merge" was deprecated, but there's no single value that replaces it, it wasn't a one-for-one exchange.

> If there are multiple versions of a configuration present in a configuration string which order do we look for matches in i.e do we:
Make it illegal to specify both (I don't like this),
Does the newer form override the older form,
Does the older form override the newer form (as in your change) or
Do we stick with the last entry in a configuration string

I think what I did (the older form overrides the newer form) is correct, at least in this case. If the older form is there, the newer form shouldn't be there, and since it's a one-to-one replacement, it doesn't matter if the newer form is there.

> While I'm asking questions: how do we deal with default values from deprecated settings. Do we ensure that config_get is always called without the full configuration stack for deprecated values? Do we make sure deprecated values always have values matching their replacement configuration?

I reset the default value for these deprecated settings to be an illegal value (0 in this case), so, if the value is illegal, then it's the default and we know it wasn't set by the application. I thought about trying to call config_get with a partial stack (just the application-set values, obviously), but I think that's harder to get right than what I did. If there's no "illegal" value for a configuration value, then we might be in trouble, but the solution is probably to declare the maximum 64-bit unsigned int the "illegal" value, and agree it's never going to be a valid value.

**Comment by agorrod** [comment]
> the differences between how we handle each deprecated configuration string has some subtlety

That really bothers me. If we (WiredTiger developers) need to make choices each time we replace/move/alter a configuration setting we're going to end up with a bunch of code littered around that handles multiple versions of configuration settings in subtly different ways. That will make it difficult to maintain and difficult to document.

> I think what I did (the older form overrides the newer form) is correct, at least in this case. If the older form is there, the newer form shouldn't be there, and since it's a one-to-one replacement, it doesn't matter if the newer form is there.

I'm not convinced that is enough. A common motivator for deprecating configuration strings is exposing new functionality. The ```leaf_page_max``` setting is a good example. Applications that are developed across multiple versions of WiredTiger may want to use the new ```leaf_page_max``` setting, but maintain a single set of configuration values that work across versions of WiredTiger - so they would also keep a setting of ```leaf_item_max``` in their WiredTiger configuration string.

If we say that the old value always overrides the new - we are limiting users from accessing enhanced functionality. If we force them to choose one or the other, we are forcing them to make their WiredTiger code conditional upon the version of WiredTiger they are using.

**Comment by sueloverso** [comment]
I think we need to come up with some kind of plan or guidelines going forward.  We have a customer that wants to be able to switch between a current version and an older version.  We have three Jenkins tests that test backward and forward compatibility up to two releases.  The intent of the Jenkins `compat` jobs is to test on disk formats of tables.  The jobs remove the `.basecfg` file to try to alleviate config string incompatibility issues.  But the metadata also contains config strings that are incompatible and so the `develop` version of that test has been failing anytime LSM is chosen.

We need to come up with a general solution for this otherwise we're going to have this discussion every time.  We need the ability and flexibility to add and alter config strings.  We need to not break existing databases.  We need to be able to maintain and document them in an automated way.  Can we add some deprecated support to the API python scripts?  This probably should be a real issue all on its own.

**Comment by keithbostic** [comment]
> If we (WiredTiger developers) need to make choices each time we replace/move/alter a configuration setting we're going to end up with a bunch of code littered around that handles multiple versions of configuration settings in subtly different ways. That will make it difficult to maintain and difficult to document.

It makes it more difficult to maintain, but I don't see any approach to this problem that doesn't add code complexity. It doesn't make it more difficult to document, it makes it simpler to document.

> A common motivator for deprecating configuration strings is exposing new functionality. The ```leaf_page_max``` setting is a good example. Applications that are developed across multiple versions of WiredTiger may want to use the new ```leaf_page_max``` setting, but maintain a single set of configuration values that work across versions of WiredTiger - so they would also keep a setting of ```leaf_item_max``` in their WiredTiger configuration string.

If you're arguing newer configurations should override older ones and we'd only look for old configurations if new ones aren't found, I think I agree -- for `leaf_page_max`, the newer configs override the older ones, I should have done the same here.

However, with `leaf_page_max`, that was easy because there's no default setting, that is, any non-zero value is an application setting. That's not the case with the eviction settings, there are real defaults, and we can't easily distinguish between the application setting a value and the default value. In other words, there's no way to look for the new configuration string, realize it's a default, and then look for the old configuration string.

We could add that information as part of the configuration retrieval: `cval.application_set == 1`?

We could add an explicit upgrade step as we did for `lsm_merge` (see `__wt_config_upgrade`), but that means additional work on the configuration strings, and will slow things down.

**Comment by keithbostic** [comment]
We're not going to resolve this one, ignore the branch for now.

**Pull request closed without merging**
