### PR TITLE
WT-3034 Add support for named snapshots including updates.

### PR DESCRIPTION
**Pull request by michaelcahill**
This supports a model where one session performs updates in a
transaction after creating a named snapshot and other sessions can use
that snapshot and read the updates.  In other words, they see exactly
what the updating session sees.

### CODE REVIEW

**Comment by michaelcahill** [comment]
autobuild: retest this please

**Comment by michaelcahill** [comment]
autobuild: retest this please

**Comment by michaelcahill** [comment]
@agorrod, can you please review?

**Comment by agorrod** [comment]
@michaelcahill I made some minor changes - otherwise lgtm.

**Comment by michaelcahill** [comment]
Thanks @agorrod, I'll merge.

**Pull request merged**
