### PR TITLE
WT-12263 performance optimization,limit and check walk count, Avoiding potential risks caused by useless evict page traversal and rollback(__evict_list_clear)

### PR DESCRIPTION
**Pull request by y123456yz**
performance optimization,limit and check walk count, Avoiding potential risks caused by useless evict page traversal and rollback(__evict_list_clear)

### CODE REVIEW

**Comment by y123456yz** [comment]
[WT-12263](https://jira.mongodb.org/browse/WT-12263)

**Comment by y123456yz** [comment]
@quchenhao 
Indeed, there were restrictions placed in the area you mentioned
If that's the case, will the following code be meaningless? I don't know if my understanding is correct.

https://github.com/y123456yz/wiredtiger/blob/develop_limit_and_check__walk_count/src/evict/evict_lru.c#L1304-L1305

What is the meaning of this part of the code?

**Comment by quchenhao** [comment]
> @quchenhao Indeed, there were restrictions placed in the area you mentioned If that's the case, will the following code be meaningless? I don't know if my understanding is correct.
> 
> https://github.com/y123456yz/wiredtiger/blob/develop_limit_and_check__walk_count/src/evict/evict_lru.c#L1304-L1305
> 
> What is the meaning of this part of the code?



> @quchenhao Indeed, there were restrictions placed in the area you mentioned If that's the case, will the following code be meaningless? I don't know if my understanding is correct.
> 
> https://github.com/y123456yz/wiredtiger/blob/develop_limit_and_check__walk_count/src/evict/evict_lru.c#L1304-L1305
> 
> What is the meaning of this part of the code?



> @quchenhao Indeed, there were restrictions placed in the area you mentioned If that's the case, will the following code be meaningless? I don't know if my understanding is correct.
> 
> https://github.com/y123456yz/wiredtiger/blob/develop_limit_and_check__walk_count/src/evict/evict_lru.c#L1304-L1305
> 
> What is the meaning of this part of the code?



> @quchenhao Indeed, there were restrictions placed in the area you mentioned If that's the case, will the following code be meaningless? I don't know if my understanding is correct.
> 
> https://github.com/y123456yz/wiredtiger/blob/develop_limit_and_check__walk_count/src/evict/evict_lru.c#L1304-L1305
> 
> What is the meaning of this part of the code?

I'm also not familiar with this code. I think you are right we don't consider WT_EVICT_WALK_BASE when we calculate the max_entries so we may overshoot that target. But that may be intentional as 
```
cache->evict_slots = WT_EVICT_WALK_BASE + WT_EVICT_WALK_INCR;
```
I'm not sure why we set the number of slots larger than WT_EVICT_WALK_BASE but there should be a reason we do this. I'll ask around and get back to you.

**Comment by quchenhao** [comment]
@y123456yz Why you think this can happen?

```
f rolled back, it is likely that these rolled pages will never be selected again by the "evict server" thread.
```

**Comment by y123456yz** [comment]
@quchenhao 
Scenario 1:
Take the real situation on the MongoDB online as an example, the single table data of some mongod nodes occupies the disk 10T. WT's default compression ratio is 4x compression, and the actual real data is 40T. Assuming that the size of a leaf page is 32K, a single btree contains about 1.25 billion pages(40T/32K=1.25billion ).
If the user is in a random update scenario, it is difficult to find the page that needs evict from 1.25 billion, and walk tree will most likely enter the mode of random page selection. In this case, I think it is easy to never find them, and it will be more difficult to find them after rolling back these pages that have been found. Because we skipped these pages.

Scenario 2:
We know that mongodb's primary key _id is incremented, so as data continues to be written, the split page will be added to the right side of B+, and if our disk IO performance is good, we can basically maintain a balance between memory and disk. In extreme cases, our "evict server thread" will only traverse the newly added leaf page, and will not perform random traversal or new traversal from the root directory, because the page selection in this scenario is very efficient, so there is no need for reverse traversal or random traversal. In this case, we btree->evict_ref skip the pages that are rolled back and may never be found.

This is just my own understanding, I am not sure whether it is correct, you can also help me correct if I understand wrong.

Therefore, we should cherish these pages found and try not to do rollback operations.

thanks.
:)

**Comment by quchenhao** [comment]
> @quchenhao Scenario 1: Take the real situation on the MongoDB online as an example, the single table data of some mongod nodes occupies the disk 10T. WT's default compression ratio is 4x compression, and the actual real data is 40T. Assuming that the size of a leaf page is 32K, a single btree contains about 1.25 billion pages(40T/32K=1.25billion ). If the user is in a random update scenario, it is difficult to find the page that needs evict from 1.25 billion, and walk tree will most likely enter the mode of random page selection. In this case, I think it is easy to never find them, and it will be more difficult to find them after rolling back these pages that have been found. Because we skipped these pages.
> 
> Scenario 2: We know that mongodb's primary key _id is incremented, so as data continues to be written, the split page will be added to the right side of B+, and if our disk IO performance is good, we can basically maintain a balance between memory and disk. In extreme cases, our "evict server thread" will only traverse the newly added leaf page, and will not perform random traversal or new traversal from the root directory, because the page selection in this scenario is very efficient, so there is no need for reverse traversal or random traversal. In this case, we btree->evict_ref skip the pages that are rolled back and may never be found.
> 
> This is just my own understanding, I am not sure whether it is correct, you can also help me correct if I understand wrong.
> 
> Therefore, we should cherish these pages found and try not to do rollback operations.
> 
> thanks. :)

We know there are some issues with our eviction walk issue. Sometimes, some pages are always missed and we recently have two changes to fix the known issues. However, I don't think your change improves the situation. What you are trying to do is to add less pages to the queue. Therefore, the pages that are considered are smaller in the first place. While the current implementation considers more pages and then remove some. It is likely that in your change, we will never add the pages to the queue in the first place and thus not really improve the situation.

**Comment by y123456yz** [comment]
There may be some bugs in my code, the whole purpose of this PR is to avoid picking unnecessary pages and causing rollback operations, but I don't think it will reduce page selection here.

If you do have other better ways to deal with it, we can shut down this PR.



In addition, I've always had a question here, I would like to ask a question, why only part of the pages obtained by the "evict server" thread walk enter the candidate? What is the background of the design here?
https://github.com/wiredtiger/wiredtiger/blob/develop/src/evict/evict_lru.c#L1318-L1341

thanks.

**Comment by quchenhao** [comment]
@y123456yz 

There are two queues because at any time one is "owned" by the server thread which is populating more content into it, the other is "shared" by all other threads which pull candidate pages from it.
When the server finishes it's populating pass it swaps the queues over and starts populating the other queue.

**Pull request closed without merging**
