### PR TITLE
WT-12488 Session join API: remove documentation and close old tickets

### PR DESCRIPTION
**Pull request by tod-johnson-mongodb**

### CODE REVIEW

**Comment by tod-johnson-mongodb** [comment]
The only old ticket this closed was: https://jira.mongodb.org/browse/WT-3309.

**Comment by tod-johnson-mongodb** [comment]
Evergreen succeeded https://spruce.mongodb.com/version/6604ccccdc0f2a000792fb94/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC. This is ready for review.

**Review by korteland — APPROVED** [review]
LGTM! Thanks for the quick turnaround.

**Review by ruby-oujo — APPROVED** [review]
LGTM

**Pull request merged**
