### PR TITLE
WT-8344 - Fix Coverity swapped arguments defect

### PR DESCRIPTION
**Pull request by ajmorton**

### CODE REVIEW

**Comment by etienneptl** [comment]
@hbokhari, do we need to review the tests? I am wondering if they were passing for the right reasons since we swapped the args.

**Review by etienneptl — APPROVED** [review]
LGTM

**Comment by hbokhari** [comment]
@etienneptl, you are correct. They are only being used to print debug messages and the change is sufficient.

**Review by hbokhari — APPROVED** [review]
LGTM.

**Pull request merged**
