### PR TITLE
WT-3249 Look at slot_state during force while holding lock.

### PR DESCRIPTION
**Pull request by sueloverso**
We could race an in-progress switch that set a new, empty active slot
but has not yet released the previously active slot and get an
incorrect LSN.

### CODE REVIEW

**Comment by agorrod** [comment]
autobuild: retest this please

**Comment by agorrod** [comment]
autobuild: retest this please

**Comment by agorrod** [comment]
autobuild: retest this please

**Comment by sueloverso** [comment]
@agorrod I pushed the fix for your question about the non-forced case and added a comment.  That was a good catch.

**Comment by agorrod** [comment]
Thanks @sueloverso - this change looks good to me now.

@michaelcahill I'm going to go ahead and merge this change to get it into stress testing. Would you please do a review as well, since it's in subtle code.

**Pull request merged**
