### PR TITLE
WT-10071 Add nonstandalone evergreen tests

### PR DESCRIPTION
**Pull request by quchenhao**
Add tests for non standalone build for:
python
c tests
stress testing

### CODE REVIEW

**Comment by quchenhao** [comment]
The test failure is a known issue in the testing facility.

**Review by agorrod — APPROVED** [review]
Sorry for letting this languish @quchenhao - the change looks good to me. It took a while to figure out how the Python hook worked, but now I have it makes sense.

It's a bit sad that it can't be auto-keyed on the build (i.e: have our test suite auto-detect whether the functionality is enabled), but I understand that would be a bigger change.

**Review by bvpvamsikrishna — APPROVED** [review]
lgtm

**Comment by quchenhao** [comment]
evergreen merge

**Pull request merged**
