### PR TITLE
WT-2177 rand seed

### PR DESCRIPTION
**Pull request by fedorova**
Added a function to optionally initialize a seed, used by __wt_random(), from a random number. Added a call to this function to wtperf. Please take a look.

### CODE REVIEW

**Comment by wtbuild** [comment]
autobuild: Can one of the admins verify this patch?

**Comment by agorrod** [comment]
autobuild: test this please

**Comment by agorrod** [comment]
Thanks @fedorova let me know if you need a hand diagnosing any of the esoteric build failures.

**Comment by michaelcahill** [comment]
Hi @fedorova, thanks for pushing this change.  We need a pull request with the base branch set to "develop", so I'll close this one and open a new one...

**Pull request closed without merging**
