### PR TITLE
WT-8948 Fix run.py to not crash on empty test_*.py files in the test suite

### PR DESCRIPTION
**Pull request by sauclovian-wt**

### CODE REVIEW

**Comment by lukech** [comment]
autobuild: Can one of the admins verify this patch?

**Comment by keithbostic** [comment]
@ddanderson, this is an external PR, can you please merge & close the ticket when you're happy?

**Review by ddanderson — APPROVED** [review]
LGTM

**Comment by ddanderson** [comment]
@sauclovian-wt and @keithbostic: thanks, I'll merge&close when the evergreen checks have passed.

**Pull request merged**
