### PR TITLE
WT-2715 random abort failed with partial write

### PR DESCRIPTION
**Pull request by sueloverso**
@michaelcahill Please review this change to fix the random-abort recovery test program.  I actually made three substantive changes:
* Fix a bug in counting the total records.
* Added a `-v` option to only run the data verification phase of the test (needed for me to test this fix on the database that failed).
* Fixed the verification code to detect the partially written record.

### CODE REVIEW

**Comment by sueloverso** [comment]
autobuild: retest this please

**Comment by sueloverso** [comment]
@michaelcahill Although the fix has been working well for a few days, it occurred to me that a better fix is probably to just set line buffering on the side file rather than no buffering.  The file with the partial line was truncated on a 4k boundary.

**Comment by sueloverso** [comment]
This is ready for review.  I moved to line buffering and removed the check for partial data that I added.  I have restarted the test.

**Comment by agorrod** [comment]
Thanks @sueloverso lgtm - I'll merge.

**Pull request merged**
