### PR TITLE
WT-8017 Re-enable VLCS format stress testing in evergreen.

### PR DESCRIPTION
**Pull request by keithbostic**
Re-enable VLCS format stress testing in evergreen.

### CODE REVIEW

**Comment by keithbostic** [comment]
@lukech, @tammybailey, I think this one should be on hold until we can resolve WT-8019, there's a periodic snapshot-isolation failure in format stress testing with VLCS.

**Review by lukech — APPROVED** [review]
I think we should run a stress test patch build before merging this PR, to make sure no fallout is introduced.

**Comment by tammybailey** [comment]
I'm okay to put this on hold until WT-8019 is resolved!

**Comment by keithbostic** [comment]
@tammybailey, WT-8019 has been resolved.

I'll try and kick off a stress test tomorrow.

**Comment by keithbostic** [comment]
stress test: https://spruce.mongodb.com/version/612e7a253627e0129dd8fdfe/tasks

**Comment by keithbostic** [comment]
@lukech, I ran one set of stress tests -- link above this comment in the PR. Is there anything else we should test before this merge?

**Review by tammybailey — APPROVED** [review]
lgtm - thanks for the extended testing!

**Review by lukech — APPROVED** [review]
Thanks Keith, the patch build has a good coverage. I'm happy for this PR to merge.

**Pull request merged**
