### PR TITLE
WT-6568 Fix split generation use (v4.2 backport)

### PR DESCRIPTION
**Pull request by AlexeyAnisimovAU**
Splits rely on a generation (aka epoch) to prevent data structures being freed when they are reachable by a reader. The pattern when overwriting needs to be: (1) overwrite a data structure; (2) read the current generation; (3) queue old data structures to be freed; (4) (optional) switch to a new generation.

That is, we need to accept during splits that data structures cannot be freed immediately. Also, since other threads may be splitting in parallel, the global split generation can be incremented at any time (and new readers can start in the new generation). So it is critical that we read the generation after all new data has been published. Subsequent readers (in at least that generation) will see the new data.

Incrementing the split generation could be deferred until a thread is performing garbage collection. However, since every eviction involves some garbage collection and we don't want any thread to wait for all readers to drain, this change bumps the generation after the split has completed (and all overwritten data is queued to be freed in the current generation).

**Note:** During backport I had to replace `F_ISSET(ref, WT_REF_FLAG_INTERNAL)` with `WT_PAGE_IS_INTERNAL(ref->page)` since in 4.2 WT_REF structure doesn't have `flags` data member. It was added in https://github.com/wiredtiger/wiredtiger/commit/12ef251cbbeaabf5ecb6ba5e587265f85579cec9

### CODE REVIEW

**Comment by AlexeyAnisimovAU** [comment]
@keithbostic I added you as a reviewer because you added `flags` to `WT_REF` here https://github.com/wiredtiger/wiredtiger/commit/12ef251cbbeaabf5ecb6ba5e587265f85579cec9 But it's not available in 4.2.
Could you please verify that the modified checks are correct in `src/btree/bt_discard.c` and `src/evict/evict_page.c`. What I did, I replaced `F_ISSET(ref, WT_REF_FLAG_INTERNAL)` in the original change with `WT_PAGE_IS_INTERNAL(ref->page)`.

**Review by keithbostic — APPROVED** [review]
@AlexeyAnisimovAU sorry to take so long to do the review. I only skimmed the change except for the parts you flagged for me: those both look fine, I don't see any problems in your change.

**Comment by AlexeyAnisimovAU** [comment]
> @AlexeyAnisimovAU sorry to take so long to do the review. I only skimmed the change except for the parts you flagged for me: those both look fine, I don't see any problems in your change.

@keithbostic It's OK, I understand that you're super busy. I appreciate your time.

**Review by sueloverso — APPROVED** [review]
LGTM.

**Comment by sueloverso** [comment]
@AlexeyAnisimovAU while these changes look fine, they also introduce the code/comment problem that was solved yesterday in WT-7871/7874. I don't know if our backport process allows for backporting more than one ticket in a backport branch all at once. We certainly want to backport both 7871 and 7874 together, not separately, so maybe that means we can add them into this branch. @lukech what do you think?

**Comment by lukech** [comment]
Thanks for flagging it @sueloverso. I think it's fine to include the changes of 7871 and 7874 into this branch as they are follow-on changes of 6568.

**Comment by AlexeyAnisimovAU** [comment]
Thank you for the review!
@lukech has created two backport tickets for us
https://jira.mongodb.org/browse/BACKPORT-10067
https://jira.mongodb.org/browse/BACKPORT-10068

**Pull request merged**
