### PR TITLE
WT-3121 Make all ROTN encryption tests skipable

### PR DESCRIPTION
**Pull request by daveh86**

### CODE REVIEW

**Comment by daveh86** [comment]
@agorrod , can you take a look at this?

It makes the ROTN tests skip correctly as they did pre-patch.

**Comment by daveh86** [comment]
restest this please

**Comment by agorrod** [comment]
@ddanderson Would you mind taking a look at this please? It looks correct to me.

**Comment by daveh86** [comment]
Retest this please!

**Comment by daveh86** [comment]
Retest this please!

**Comment by ddanderson** [comment]
@daveh86, @agorrod This looks great!  I'll merge.

My bad, I should have caught this (and thought about Windows w.r.t. how extensions work).

**Pull request merged**
