### PR TITLE
WT-3120 Fix ordering problem in connection_close for custom filesystem loaded via shared lib

### PR DESCRIPTION
**Pull request by ddanderson**
@michaelcahill, this is ready for review.  I have a test case (extension file system + caller), but it's somewhat integrated in work I'm doing for WT-2909.  If you'd like it as part of this one, I can include it.

### CODE REVIEW

**Comment by ddanderson** [comment]
retest this please

**Comment by ddanderson** [comment]
@michaelcahill, please hold off until I can figure out what the cause of the windows build failure is.

**Comment by ddanderson** [comment]
@daveh86, I wonder if you could help, please?  I've looked at this, and built/run this branch on Windows, and I just don't see why it's failing in the pull request build.  Do you have any ideas?

**Comment by daveh86** [comment]
@ddanderson Fixed.

**Comment by ddanderson** [comment]
@michaelcahill, this is ready to review.  For the test, I've included a test file system extension that I intend to also use for WT-2909.

**Comment by ddanderson** [comment]
@daveh86, thanks for your help in understanding the error on this.

**Comment by agorrod** [comment]
I'm a bit concerned about the cross-platform consequences of this change. @daveh86 Could you make sure that this branch passes testing on all our supported platforms, including Windows, PPC and zSeries?

**Comment by daveh86** [comment]
retest this please

**Comment by daveh86** [comment]
@agorrod, have confirmed that things are finw on Windows (with the unit suite) and on zSeries. PPC is still running.

**Comment by daveh86** [comment]
The PPC run was also a success. So this test has passed unit testing on PPC, Win and zSeries

**Comment by michaelcahill** [comment]
Thanks @ddanderson, this change lgtm -- I'm going to go ahead and merge it.

For the record, we don't currently build or test DLL loading on Windows, or any of the `csuite` tests.  Given that, I think it's okay to have a POSIX filesystem extension for testing.

**Pull request merged**
