### PR TITLE
Remove the WT_ATOMIC_CAS_VAL family of macros

### PR DESCRIPTION
**Pull request by michaelcahill**
Use the boolean versions everywhere.  Having both makes my head hurt, and (unless I'm missing something) doesn't add any more functionality.

refs WT-1938

### CODE REVIEW

**Comment by michaelcahill** [comment]
@keithbostic, @sueloverso what do you think of this change?

**Comment by keithbostic** [comment]
This change looks correct to me, I'm OK to merge it.

A couple of minor optimization.

Is there any reason not to use the boolean form of `__sync_val_compare_and_swap`?
```
diff --git a/src/include/gcc.h b/src/include/gcc.h
index 3ebc0da..817eafa 100644
--- a/src/include/gcc.h
+++ b/src/include/gcc.h
@@ -98,7 +98,7 @@
        (WT_STATIC_ASSERT(sizeof(v) == (n)), __sync_fetch_and_add(&(v), val))
 #define        __WT_ATOMIC_CAS(v, old, new, n)                                 \
        (WT_STATIC_ASSERT(sizeof(v) == (n)),                            \
-       __sync_val_compare_and_swap(&(v), old, new) == (old))
+       __sync_bool_compare_and_swap(&(v), old, new))
 #define        __WT_ATOMIC_STORE(v, val, n)                                    \
        (WT_STATIC_ASSERT(sizeof(v) == (n)),                            \
        __sync_lock_test_and_set(&(v), val))
```
We're also repeatedly reading a volatile and doing multiple CAS calls I think we could avoid, if that's interesting:
```
diff --git a/src/log/log_slot.c b/src/log/log_slot.c
index 6d78559..687fd73 100644
--- a/src/log/log_slot.c
+++ b/src/log/log_slot.c
@@ -354,21 +354,18 @@ __wt_log_slot_grow_buffers(WT_SESSION_IMPL *session, size_
t newsize)
        __wt_spin_lock(session, &log->log_slot_lock);
        for (i = 0; i < WT_SLOT_POOL; i++) {
                slot = &log->slot_pool[i];
-               /* Avoid atomic operations if they won't succeed. */
-               if (slot->slot_state != WT_LOG_SLOT_FREE &&
-                   slot->slot_state != WT_LOG_SLOT_READY)
-                       continue;
+
                /* Don't keep growing unrelated buffers. */
                if (slot->slot_buf.memsize > (10 * newsize) &&
                    !F_ISSET(slot, WT_SLOT_BUF_GROW))
                        continue;
-               if (WT_ATOMIC_CAS8(
-                   slot->slot_state, WT_LOG_SLOT_FREE, WT_LOG_SLOT_PENDING))
-                       orig_state = WT_LOG_SLOT_FREE;
-               else if (WT_ATOMIC_CAS8(
-                   slot->slot_state, WT_LOG_SLOT_READY, WT_LOG_SLOT_PENDING))
-                       orig_state = WT_LOG_SLOT_READY;
-               else
+
+               /* Avoid atomic operations if they won't succeed. */
+               orig_state = slot->slot_state;
+               if ((orig_state != WT_LOG_SLOT_FREE &&
+                   orig_state != WT_LOG_SLOT_READY) ||
+                   !WT_ATOMIC_CAS8(
+                   slot->slot_state, orig_state, WT_LOG_SLOT_PENDING))
                        continue;

                /* We have a slot - now go ahead and grow the buffer. */
```

**Comment by agorrod** [comment]
> Is there any reason not to use the boolean form of __sync_val_compare_and_swap?

Yup, clang has a compiler optimizer bug related to the bool version:
https://github.com/wiredtiger/wiredtiger/blob/develop/src/include/gcc.h#L91

**Comment by keithbostic** [comment]
@agorrod, can you please add a pretty big comment? I almost pushed that change without further thought.

**Comment by michaelcahill** [comment]
I've moved the comment and split the clang-specific implementation out.  I hope that makes it clearer.

**Comment by keithbostic** [comment]
Thank you -- since I so obviously had forgotten the clang bug, and missed the relevant comment, that will help (at least) me.

**Comment by keithbostic** [comment]
BTW, while we're on the topic of that clang bug -- [the clang folks asked for more information](https://llvm.org/bugs/show_bug.cgi?id=21499) a few months back.

Where did you see this failure, it looks like tinderbox has clang 3.4, not 3.5?

**Pull request merged**
