### PR TITLE
WT-10900 Fix mac crash for python tests. (v6.0 backport) (#9032)

### PR DESCRIPTION
**Pull request by Siddhartha8899**
(cherry picked from commit 7b89b15c8968b9064a6892530acceacc8089e0d7)

### CODE REVIEW

**Comment by Siddhartha8899** [comment]
Just a heads up, I've resolved a few conflicts in this PR. Would appreciate it if you could take a closer look. Thanks!

**Comment by Siddhartha8899** [comment]
Compilation failure due to the following error - 
`bash: line 17: /usr/bin/python3: No such file or directory`

I will change it back to python3, to see if that works.

**Comment by Siddhartha8899** [comment]
After the above-mentioned change, all the tests seem to be passing. @ddanderson let me know what your think.

**Review by lukech — APPROVED** [review]

**Review by ddanderson — APPROVED** [review]
LGTM!

**Pull request merged**
