### PR TITLE
WT-2989 Instrumented build with asserts added

### PR DESCRIPTION
**Pull request by sulabhM**

### CODE REVIEW

**Comment by sulabhM** [comment]
autobuild recheck this please

**Comment by sulabhM** [comment]
autobuild: rebuild this please

**Comment by sulabhM** [comment]
autobuild: retest this please

**Comment by michaelcahill** [comment]
@sulabhM, do you think these changes are worth keeping long term, or are they only interesting for attempting to diagnose the associated failure?

**Comment by sulabhM** [comment]
@michaelcahill , I did not realise that this pull request is still open.
I don't see any benefit of keeping these changes. I am closing this pull request.

**Pull request closed without merging**
