### PR TITLE
WT-6926 Update WiredTiger source code to include 2021 copyright notices (v4.2 backport)

### PR DESCRIPTION
**Pull request by AlexeyAnisimovAU**

### CODE REVIEW

**Review by etienneptl — CHANGES_REQUESTED** [review]
It should be `present` instead of `2021`

**Comment by AlexeyAnisimovAU** [comment]
> It should be `present` instead of `2021`

My main intention was precisely to replace `2020` with `present`. Did I miss some file?

**Comment by etienneptl** [comment]
> > It should be `present` instead of `2021`
> 
> My main intention was precisely to replace `2020` with `present`. Did I miss some file?

I don't think you did, my bad. I cannot open the files one by one on GitHub, I will check out your branch and check this way. I will get back to you soon.

**Comment by AlexeyAnisimovAU** [comment]
> > > It should be `present` instead of `2021`
> > 
> > 
> > My main intention was precisely to replace `2020` with `present`. Did I miss some file?
> 
> I don't think you did, my bad. I cannot open the files one by one on GitHub, I will check out your branch and check this way. I will get back to you soon.

No worries. I struggled reviewing my changes too. GitHub is not happy with these big PRs. Thank you for your time!

**Review by etienneptl — APPROVED** [review]
LGTM!

**Comment by tammybailey** [comment]
I removed myself as reviewer, I think Etienne's LGTM is sufficient!

**Pull request merged**
