### PR TITLE
WT-9657 Use the absolute path for the python binary in Evergreen for print_stack_trace.py

### PR DESCRIPTION
**Pull request by etienneptl**

### CODE REVIEW

**Comment by etienneptl** [comment]
The suggested solution does not work according to [the logs](https://evergreen.mongodb.com/task_log_raw/wiredtiger_ubuntu2004_tiered_test_small_patch_a378ba8dbf31a0eece393d3e0f8c048f104600bc_62ea50ec0ae60603eb2d5e22_22_08_03_10_41_49/0?type=T&text=true):
```
[2022/08/03 10:54:08.694] $(pwd)/venv/bin/python3 ../../../test/evergreen/print_stack_trace.py --format -e ./t -c . -l .
[2022/08/03 10:54:08.695] sh: 8: /data/mci/413a280926dc31ca68ab71eb46c2ee2b/wiredtiger/cmake_build/test/format/venv/bin/python3: not found
```

**Comment by etienneptl** [comment]
I thought I could keep the `cd/format` but it did not work. I removed that command in the last set of changes.

**Review by korteland — APPROVED** [review]
LGTM, although I can't check it from a working PR build - could you put a link to a patch build on the ticket please?

**Comment by etienneptl** [comment]
> LGTM, although I can't check it from a working PR build - could you put a link to a patch build on the ticket please?

If you look for the `tiered-test-small` on `! Ubuntu 20.04` on our Evergreen page, you will see in the logs the following:
```
[2022/08/03 04:55:35.835] # Look through the stress format directory for any coredumps.
[2022/08/03 04:55:35.835] cd test/format
[2022/08/03 04:55:35.835] venv/bin/python3 ../../../test/evergreen/print_stack_trace.py --format -e ./t -c . -l .
[2022/08/03 04:55:35.836] sh: 8: venv/bin/python3: not found
```
See this [example](https://evergreen.mongodb.com/task/wiredtiger_ubuntu2004_tiered_test_small_a378ba8dbf31a0eece393d3e0f8c048f104600bc_22_08_03_04_31_24).
If you look at the [PR testing](https://spruce.mongodb.com/task/wiredtiger_ubuntu2004_tiered_test_small_patch_a378ba8dbf31a0eece393d3e0f8c048f104600bc_62ea6c4c30661576815352d0_22_08_03_12_38_37/logs?execution=0):
```
[2022/08/03 12:57:53.728] # Parse through any failures inside the WT_TEST directory.
[2022/08/03 12:57:53.728] $(pwd)/venv/bin/python3 ../test/evergreen/print_stack_trace.py --unit_test -e $(pwd)/venv/bin/python3 -c WT_TEST -l .
[2022/08/03 12:57:53.764] # Look through the stress format directory for any coredumps.
[2022/08/03 12:57:53.764] $(pwd)/venv/bin/python3 ../test/evergreen/print_stack_trace.py --format -e ./test/format/t -c test/format/. -l test/format/.
[2022/08/03 12:57:53.800] Finished 'shell.exec' in "dump stacktraces" in 73.017316ms
```
There is no more errors.

**Comment by korteland** [comment]
(After a little more discussion, there's no need for a patch build that generates a core dump since `run tiered storage test` doesn't run `test/format`.)

**Comment by etienneptl** [comment]
> (After a little more discussion, there's no need for a patch build that generates a core dump since `run tiered storage test` doesn't run `test/format`.)

It's still great to prove it works. To do so, I triggered the following [patch build](https://spruce.mongodb.com/task/wiredtiger_ubuntu2004_tiered_test_small_patch_a378ba8dbf31a0eece393d3e0f8c048f104600bc_62eb263b2a60ed0e6b180faf_22_08_04_01_52_08/logs?execution=0) with [those changes](https://spruce.mongodb.com/version/62eb263b2a60ed0e6b180faf/changes?duration=DESC):
I am calling `test/format` in the `run tiered storage test` function and added an `abort` call to `t.c`.
In the patch build, the core is found and stacktace printed out:

```
[2022/08/04 02:04:00.900] # Look through the stress format directory for any coredumps.
[2022/08/04 02:04:00.900] $(pwd)/venv/bin/python3 ../test/evergreen/print_stack_trace.py --format -e ./test/format/t -c test/format/. -l test/format/.
[2022/08/04 02:04:00.934] +---------------------------------+
[2022/08/04 02:04:00.934] | test/format/./dump_t.11545.core |
[2022/08/04 02:04:00.934] +---------------------------------+
[2022/08/04 02:04:02.739] [New LWP 11545]
[2022/08/04 02:04:02.739] [Thread debugging using libthread_db enabled]
[2022/08/04 02:04:02.739] Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[2022/08/04 02:04:03.781] Core was generated by `./t'.
[2022/08/04 02:04:03.781] Program terminated with signal SIGABRT, Aborted.
[2022/08/04 02:04:03.781] #0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
[2022/08/04 02:04:03.787] #0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
[2022/08/04 02:04:03.787] #1  0x00007f7a1f29e859 in __GI_abort () at abort.c:79
[2022/08/04 02:04:03.839] #2  0x00007f7a1f6641f6 in __wt_abort (session=<optimized out>) at ../src/os_common/os_abort.c:30
[2022/08/04 02:04:03.839] #3  0x000056242b635d75 in main (argc=1, argv=<optimized out>) at ../test/format/t.c:243
```

**Comment by korteland** [comment]
Awesome! Thanks for checking that :-)

**Pull request merged**
