### PR TITLE
WT-7025 Coverity: Unused value op_ts

### PR DESCRIPTION
**Pull request by Siddhartha8899**

### CODE REVIEW

**Review by tetsuo-cpp — APPROVED** [review]
LGTM.

I think another alternative is to use `WT_NOT_READ` to assign to `op_ts`. Do you have a preference for this @quchenhao?

**Review by quchenhao — APPROVED** [review]
lgtm

**Comment by quchenhao** [comment]
> LGTM.
> 
> I think another alternative is to use `WT_NOT_READ` to assign to `op_ts`. Do you have a preference for this @quchenhao?

I think using HAVE_DIAGNOSITC is clearer.

**Comment by tetsuo-cpp** [comment]
Great work @Siddhartha8899. 🎉

**Pull request merged**
