### PR TITLE
WT-10282 Fix MSan optimisation level

### PR DESCRIPTION
**Pull request by korteland**

### CODE REVIEW

**Review by mickgraham-mongodb — COMMENTED** [review]
Are there other clang build variants that we should also do this for and not just sanitizer builds?

**Comment by korteland** [comment]
> Are there other clang build variants that we should also do this for and not just sanitizer builds?

As far as I know, this is everything using the Clang toolchain. That first change for `configure_flags_address_sanitizer_mongodb_v4_clang_with_builtins` is used in various format stress tests rather than for sanitisers.

**Comment by korteland** [comment]
Fixed the RHEL PPC variant in 249d0a9 - thanks for spotting that!

**Review by mickgraham-mongodb — APPROVED** [review]
LGTM

**Review by agorrod — APPROVED** [review]
Thanks Will! LGTM

**Pull request merged**
