### PR TITLE
Pythonic way for samples

### PR DESCRIPTION
**Pull request by JulienBalestra**
Light changes to fit PEP8 (py-RFC) and best practices of Python language
More about it here: http://legacy.python.org/dev/peps/pep-0008/

### CODE REVIEW

**Comment by wtbuild** [comment]
autobuild: Can one of the admins verify this patch?

**Comment by JulienBalestra** [comment]
You also may use "%d" instead of recast value with str( int or float )

**Comment by michaelcahill** [comment]
autobuild: ok to test

**Comment by michaelcahill** [comment]
Thanks for these cleanups, @JulienBalestra -- they look good to me, I will merge them now.

**Pull request merged**
