### PR TITLE
WT-6173 Change __wt_time_window_ functions to macros

### PR DESCRIPTION
**Pull request by sulabhM**

### CODE REVIEW

**Comment by tetsuo-cpp** [comment]
@sulabhM 
Before you merge this, can you let me play around with it a bit?
It'd be better if we can encourage the compiler to inline since we get to keep type safety and better compiler errors.

**Comment by sulabhM** [comment]
@tetsuo-cpp , sure. I will still like to get this merged today. So keep me posted.

**Comment by tetsuo-cpp** [comment]
> @tetsuo-cpp , sure. I will still like to get this merged today. So keep me posted.
> Edit:
> It will be useful to get this sorted before the next drop to mongodb.

@sulabhM 
I've had trouble reproducing the improvement so maybe just go ahead and merge and I can figure it out later. I built this branch just then but it gives me a regression for `medium-btree` when compiled with `clang-8`. If the results look better across the board, no worries though.

**Comment by sulabhM** [comment]
@tetsuo-cpp ,

> I built this branch just then but it gives me a regression for medium-btree when compiled with clang-8. If the results look better across the board, no worries though.

Develop has couple of changes that this branch doesn't. Those changes improve things massively.

**Pull request merged**
