### PR TITLE
WT-10081 Fix failure format configs for older branch (#8528) (v5.0 backport)

### PR DESCRIPTION
**Pull request by lukech**
(cherry picked from commit f0ff3ca5c8e3ebe1147059e4200b26dd58e420e4)

### CODE REVIEW

**Review by kommiharibabu — APPROVED** [review]
LGTM

**Comment by lukech** [comment]
@quchenhao are you going to remove the WT-9805 format config as part of #8545? If not we may need to wait for your PR to merge first, and add the format config removal change in this PR.

**Comment by quchenhao** [comment]
I'll remove that config

**Comment by lukech** [comment]
Thanks, @quchenhao. I will merge this PR once testing passes then.

**Pull request merged**
