### PR TITLE
WT-2076 wtperf slowdown.

### PR DESCRIPTION
**Pull request by keithbostic**

### CODE REVIEW

**Comment by keithbostic** [comment]
@michaelcahill, in 6b2f6fb, you added this code:
```
/* Don't split a page that is pending a multi-block split. */
if (F_ISSET(page->modify, WT_PM_REC_MULTIBLOCK))
        return (0);
```
Do you remember what was going on, the commit doesn't say much.

**Comment by keithbostic** [comment]
There are some workloads that still aren't fixed by this change (`log-append.wtperf` fails for me, `parallel-pop-stress` fails on OS X for Sue); however, they exhibit the same symptoms: we are failing to do in-memory splits on pages where appends are happening. I'm becoming convinced that what happened is we made it more likely for other types of eviction to succeed and so now regular eviction is happening when it didn't before, and it's significantly slower for these workloads than in-memory splits.

**Comment by michaelcahill** [comment]
@keithbostic, the basic problem with doing in-memory splits on a page that was split during its last reconciliation is that as part of the in-memory split, we end up creating two pages in memory.  It wasn't clear to me what to do with the original `page->modify->mod_multi` at that point, so I avoided doing in-memory splits at all in that case.

More generally, in-memory splits were designed to be done in preference to ordinary eviction, because they move I/O out of application operations.  I'm happy to be convinced otherwise, but I think these performance results are telling us that trying an in-memory split before eviction was the right call.

**Comment by michaelcahill** [comment]
I'm not in a good state to review this today -- @keithbostic, if there are no more changes to make on this branch, can you please have @agorrod review?

**Comment by agorrod** [comment]
@keithbostic I've been digging into this today. I don't think it's the right solution for the performance degradation. It appears to me as though the earlier code was succeeding in doing an in-memory split via ```EVICT_UPDATE_RESTORE```, wheras this workload is failing to let ```EVICT_UPDATE_RESTORE``` evictions finish. I think I've figured out why - I'll push it into a separate branch.

**Comment by agorrod** [comment]
I've pushed an alternative code change into https://github.com/wiredtiger/wiredtiger/pull/2167

**Pull request closed without merging**
