### PR TITLE
WT-6884 Clarify README to explain that PRs should target develop

### PR DESCRIPTION
**Pull request by tetsuo-cpp**
Most external PRs are based on master so we almost always have to retarget the PR and get the contributor to resolve merge conflicts or rebase the changes.

We should add a line to the `README` to make this more clear.

### CODE REVIEW

**Comment by tetsuo-cpp** [comment]
@lukech 
This change also needs to go into `master`.

**Comment by lukech** [comment]
Thanks for making the change @tetsuo-cpp 
Actually, in a recent release discussion with Alex G, we decide to cut the last standalone release on master, and then switch the default branch to 'develop', which should be able to obsolete the need of this change. Do you mind holding off this change a bit?

**Comment by tetsuo-cpp** [comment]
> Thanks for making the change @tetsuo-cpp
> Actually, in a recent release discussion with Alex G, we decide to cut the last standalone release on master, and then switch the default branch to 'develop', which should be able to obsolete the need of this change. Do you mind holding off this change a bit?

Sure, I'll just leave it here. Feel free to close it if it's no longer required.

**Comment by tetsuo-cpp** [comment]
This isn't going to be used so I'm closing it. I'd rather not leave this sitting around.

**Pull request closed without merging**
