### PR TITLE
WT-9480 Handle WT_ROLLBACK in the default remove_operation of the cpp suite

### PR DESCRIPTION
**Pull request by etienneptl**
Two issues are being covered here:

- We now reset the random cursor so we don't pin content
- We handle `WT_ROLLBACK` that can be returned from the `next` cursor call

I have added the cpp stress tests to the PR.

### CODE REVIEW

**Comment by etienneptl** [comment]
The [error](https://spruce.mongodb.com/task/wiredtiger_cppsuite_stress_tests_cppsuite_hs_cleanup_stress_patch_eabc335ef595d527a422d6545407a0a052899df3_62b25da1d1fe0704541a695f_22_06_22_00_09_06/logs?execution=0) from the PR testing is not related to those changes, see [WT-9466](https://jira.mongodb.org/browse/WT-9466)

**Review by clarissecheah — APPROVED** [review]
lgtm!

**Review by luke-pearson — COMMENTED** [review]
LGTM

**Review by jiechenbo — APPROVED** [review]
LGTM!

**Pull request merged**
