### PR TITLE
WT-7387 Replace cluster/member with hostid.

### PR DESCRIPTION
**Pull request by sueloverso**
Naming consideration for this review: I replaced the API with `hostid` but the internal storage is calling it `uniqueid`. Is `hostid` what we really want in the API configuration string? `id`? `uniqueid`? something else?

### CODE REVIEW

**Review by ddanderson — APPROVED** [review]
LGTM

**Comment by ddanderson** [comment]
Hmm, now that I think about this more, I don't think `host` feels correct.  It's really just a prefix, so maybe we call it `prefix` or `bucket_prefix`?  Since all the names we create have that prefix added, and our file system can only "see" names in that bucket with that prefix (and the prefix will be removed before we see it).  It's also "kind of" like a subdirectory.

Also, I have changes to `local_store.c` in review, so maybe we should get that resolved before you commit this?  See: #6421.  (Sorry, I should have pressed the re-review on that a while ago).

**Comment by keitharnoldsmith** [comment]
Regarding naming, I agree that `hostid` doesn't feel right. It suggests that it should be tied to the host where WT is running.  But there is no need for it to have anything to do with the host. And if for some reason a user has multiple instances on the same machine, they need distinct values for this option.

`uniqueid` captures the uniqueness requirement, although it doesn't make it clear what the scope of the uniqueness is. Maybe `unique_prefix`?   

I'd avoid just `id` as being too generic.

**Review by keitharnoldsmith — APPROVED** [review]
LGTM!

**Pull request merged**
