### PR TITLE
WT-3086 Add information about transaction state to cache stuck diagnostics

### PR DESCRIPTION
**Pull request by agorrod**

### CODE REVIEW

**Comment by agorrod** [comment]
The output looks like:

```
==========
transaction state dump
current ID: 8027
last running ID: 7393
oldest ID: 7393
oldest named snapshot ID: 0
checkpoint running? no
checkpoint generation: 0
checkpoint pinned ID: 0
checkpoint txn ID: 0
session count: 25
Dumping transaction state of active sessions
ID: 8024
	session name: WT_CURSOR.insert, pinned ID: 0, metadata pinned ID: 0, snap min: 8019, snap max: 8027
	modification count: 3, flags: 68, isolation: WT_ISO_READ_COMMITTED
ID: 8027
	session name: WT_CURSOR.insert, pinned ID: 8019, metadata pinned ID: 0, snap min: 8019, snap max: 8028
	modification count: 0, flags: 76, isolation: WT_ISO_READ_COMMITTED
ID: 8023
	session name: WT_CURSOR.insert, pinned ID: 8016, metadata pinned ID: 0, snap min: 8016, snap max: 8025
	modification count: 1, flags: 76, isolation: WT_ISO_READ_COMMITTED
ID: 8020
	session name: WT_CURSOR.insert, pinned ID: 8016, metadata pinned ID: 0, snap min: 8016, snap max: 8025
	modification count: 3, flags: 76, isolation: WT_ISO_READ_COMMITTED
ID: 8025
	session name: WT_CURSOR.insert, pinned ID: 8018, metadata pinned ID: 0, snap min: 8018, snap max: 8026
	modification count: 1, flags: 76, isolation: WT_ISO_READ_COMMITTED
ID: 8019
	session name: WT_CURSOR.insert, pinned ID: 8020, metadata pinned ID: 0, snap min: 8020, snap max: 8028
	modification count: 4, flags: 76, isolation: WT_ISO_READ_COMMITTED
ID: 8026
	session name: WT_CURSOR.insert, pinned ID: 8019, metadata pinned ID: 0, snap min: 8019, snap max: 8027
	modification count: 2, flags: 76, isolation: WT_ISO_READ_COMMITTED
ID: 8021
	session name: WT_CURSOR.insert, pinned ID: 8019, metadata pinned ID: 0, snap min: 8019, snap max: 8027
	modification count: 5, flags: 76, isolation: WT_ISO_READ_COMMITTED
```

It's tempting to make the output more machine parseable, but that would be a bigger change.

**Comment by agorrod** [comment]
@michaelcahill Can you think of any other transaction related information it might be interesting to output here? I figured the individual session transaction state might be valuable to see if it's a single old thread of a general tardiness

**Comment by michaelcahill** [comment]
That looks pretty good to me, thanks!

It might be worth trying to make the output a little more compact, switch flags to hex, and I think we should include sessions with `s->pinned_id != WT_TXN_NONE` even if `s->id == WT_TXN_NONE` (i.e., queries can still pin transactions).

My only other question is whether this is thread-safe -- it looks like there could be a race on `conn->sessions[i].name` at least.  Is it expected that we can dump this state when operations are in progress?

**Comment by michaelcahill** [comment]
Thanks @agorrod, lgtm -- I'll merge.

**Pull request merged**
