### PR TITLE
WT-11865 Initialise and teardown chunk cache metadata lock

### PR DESCRIPTION
**Pull request by korteland**
Not sure how this managed to get as far as it did last time around, but oh well. Did a macOS patch build, it's all green now.

### CODE REVIEW

**Comment by korteland** [comment]
FWIW, I think it this happened because macOS uses a different threading API (to the pthreads we use on Linux), which is more picky about initialisation. And we don't run chunk cache tests on Windows, so we didn't spot it there.

**Comment by ajmorton** [comment]
> FWIW, I think it this happened because macOS uses a different threading API (to the pthreads we use on Linux), which is more picky about initialisation. And we don't run chunk cache tests on Windows, so we didn't spot it there.

@korteland do we run chunkcache tests with any of our sanitisers? It's a bit concerning that our Linux suite misses this.

**Review by Siddhartha8899 — APPROVED** [review]

**Comment by korteland** [comment]
@ajmorton I don't think so. All of our chunk cache tests are in Python, which (from memory?) don't run under any sanitisers.

I'm also not sure a sanitiser would catch it - we were mis-using the library, and that's not the type of thing they check. (The memory for the locks themselves was initialised to zero - it appears that happens to be valid for pthreads but not other APIs?)

**Review by ruby-oujo — APPROVED** [review]

**Comment by ajmorton** [comment]
> @ajmorton I don't think so. All of our chunk cache tests are in Python, which (from memory?) don't run under any sanitisers.
> 
> I'm also not sure a sanitiser would catch it - we were mis-using the library, and that's not the type of thing they check. (The memory for the locks themselves was initialised to zero - it appears that happens to be valid for pthreads but not other APIs?)

Yeah the code ran correctly so that sounds reasonable to me. We wrap our locks in the `WT_SPINLOCK` struct so perhaps we could add a diagnostic `is_initialised`, but that's out of scope for this PR. I'll think on this a bit

**Comment by korteland** [comment]
evergreen merge

**Pull request merged**
