### PR TITLE
WT-6410 Remove WT_SESSION.rebalance.

### PR DESCRIPTION
**Pull request by kommiharibabu**

### CODE REVIEW

**Comment by bvpvamsikrishna** [comment]
@kommiharibabu This seems ok, could you remove the word "rebalance" from src/docs/spell.ok file as well. I will flag if it used anywhere else also. will be easier to verify where else it is used.

**Comment by kommiharibabu** [comment]
@bvpvamsikrishna I removed `rebalance` and `Rebalance` from spell.ok file and everything seems to be fine. Removing it from string.ok can lead to failure as it is used in the NEWS file.

**Comment by sueloverso** [comment]
@kommiharibabu I had the same issue with async. It could not be removed from `s_string.ok` because it was used in `NEWS`.

**Review by bvpvamsikrishna — APPROVED** [review]
lgtm

**Review by raviprakashgiri29 — APPROVED** [review]
Changes LGTM.

**Pull request merged**
