### PR TITLE
WT-5513 Don't consider TOMBSTONE updates for history store

### PR DESCRIPTION
**Pull request by kommiharibabu**
Every history update must have a TOMBSTONE or the on-disk
record with a valid stop time pair. The TOMBSTONE update or
the stop time pair should be ignored for the history store
transaction read and later in their corresponding functions
they can be handled. Otherwise, none of the history store
entries are visible to the some of the transaction reads.

### CODE REVIEW

**Comment by kommiharibabu** [comment]
The failures from the hs06 test and it is failing in the durable branch.

**Comment by kommiharibabu** [comment]
I don't think that this change can cause much read overhead. This change is just avoiding reading the TOMBSTONE/stop time pair to decide the visibility, instead, it allowed to go to the full update or start time pair. For transactions, if the TOMBSTONE is visible, the full update is also visible, so the search may not continue further until unless there is a logic to do so, for example - rollback to stable.

**Comment by quchenhao** [comment]
This part of the code is performance critical. We should avoid introducing any branches only if it is really necessary. Mixed reading of data store and history store is expected to be a common case and I'm worried that CPU branch predictions may not work effectively in this case causing more overhead than expected. Generally, I'm more concerned about this as a hack. We should avoid treating things differently as much as possible, especially in the low level functions like this one.

**Comment by tetsuo-cpp** [comment]
My understanding is that we need to do this in order to scan the history store table. The current system works for the regular search case because we have a read timestamp already, however it isn't possible to scan the full set of keys.

@quchenhao How would you prefer this to be solved? I don't love this solution either but I'm not sure that there is a nicer way to get this to work.

**Comment by quchenhao** [comment]
> My understanding is that we need to do this in order to scan the history store table. The current system works for the regular search case because we have a read timestamp already, however it isn't possible to scan the full set of keys.
> 
> @quchenhao How would you prefer this to be solved? I don't love this solution either but I'm not sure that there is a nicer way to get this to work.

@hbokhari Firstly, I don't understand why we need to scan history store without a timestamp. From my understanding, roll_back_to_stable should read the history store using the stable timestamp of the checkpoint, is that correct? If we really need to scan history store, can we implement a different api that directly read the onpage value?

**Comment by kommiharibabu** [comment]
@quchenhao, I feel there can be scenarios where there is no `read_timestamp` associated with every scan. In those cases, the history store scan fails. For example, a table with no timestamp?

Adding a new API for only to this specific case is not a proper choice. I still feel that it doesn't cause any performance problem and maintenance issues than adding a new API. If we find a real performance problem we can revisit it later.

**Comment by quchenhao** [comment]
> @quchenhao, I feel there can be scenarios where there is no `read_timestamp` associated with every scan. In those cases, the history store scan fails. For example, a table with no timestamp?
> 
> Adding a new API for only to this specific case is not a proper choice. I still feel that it doesn't cause any performance problem and maintenance issues than adding a new API. If we find a real performance problem we can revisit it later.

If we have a table with no timestamp, we still can rely on transaction ids to do visibility check. I don't think that is a problem.

**Pull request merged**
