### PR TITLE
Refactoring conditional directives for incomplete if conditions.

### PR DESCRIPTION
**Pull request by wmarquesr**
A suggestion to compile entire statements and expressions, as suggested by code style guidelines from the Linux Kernel and practitioners.

  * [Linux kernel coding style](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/CodingStyle#n892)
  * [Living in the #ifdef Hell](https://www.cqse.eu/en/blog/living-in-the-ifdef-hell/)

It might improve code understanding, maintainability and error-proneness.

### CODE REVIEW

**Comment by wtbuild** [comment]
autobuild: Can one of the admins verify this patch?

**Comment by wmarquesr** [comment]
Of course, i prefer.

**Comment by keithbostic** [comment]
@wmarquesr, in general, I agree with you -- can we get a [contributor agreement](https://www.mongodb.com/legal/contributor-agreement) from you so we can consider your changes?

**Comment by keithbostic** [comment]
Close this branch until we have a contributor agreement from @wmarquesr.

**Comment by wmarquesr** [comment]
I'm sorry for the delay, i'll need submit a new pull request for that?

**Comment by keithbostic** [comment]
No, we can easily resurrect the branch, whenever you're ready.

**Comment by wmarquesr** [comment]
I do the Contributor Agreement, and now?

**Comment by keithbostic** [comment]
Thank you! I'll review the changes the next chance I get.

**Comment by wmarquesr** [comment]
The PR has been revised?

**Pull request closed without merging**
