### PR TITLE
add ex_debug_tree, this is very helpful for us to understand  the btree and debug btree

### PR DESCRIPTION
**Pull request by y123456yz**
add ex_debug_tree example, this is very helpful for us to understand  the btree.

The storage structure of data in memory and disk is the core of wiredtiger, and adding this example can help us understand btree, especially for beginners.

### CODE REVIEW

**Comment by y123456yz** [comment]
https://jira.mongodb.org/browse/WT-11835

**Comment by marcbutler** [comment]
Hi @y123456yz 

Is the purpose of this example to provide an executable which you can run under a debugger to see how the WT B-Tree changes in response to updates?

Thanks, Marc

**Comment by y123456yz** [comment]
hi, @marcbutler 

1. The main purpose of this PR is to facilitate beginners to learn the core of wiredtiger (btree related data structure implementation), through __wt_debug_tree_all function we can easily learn the KV data in memory and disk storage. With the help of debug output information,  it can intuitively output the btree's page information to us. In the end, it can greatly reduce the cost of learning the wiredtiger code.
2. The purpose of adding update is that __wt_debug_tree_all function can output different historical value versions of the same key, whichcan help us understand the management of multiple versions of value in memory. this can cover all processes in the __wt_debug_tree_all, further help us understand btree.

thanks.

**Comment by marcbutler** [comment]
Apologies @y123456yz,
It's been a busy couple of weeks, and I will need some more time.

**Comment by y123456yz** [comment]
> Apologies @y123456yz, It's been a busy couple of weeks, and I will need some more time.

got it, thanks very much.

**Comment by y123456yz** [comment]
> Apologies @y123456yz, It's been a busy couple of weeks, and I will need some more time.

@marcbutler please review this code, thanks.

**Comment by luke-pearson** [comment]
Hi @y123456yz, the purpose of the example code it to demonstrate usages of the API, what you've done is call an internal function by accessing the b-tree using internal macros, and casting to `WT_CURSOR_BTREE*` which is again internal. This isn't a proper example as we wouldn't want people using a function that is only accessable internally, first you'd have to expose the debug function via the external API.

**Comment by luke-pearson** [comment]
To understand and debug a b-tree I suggest using the `wt util` verify functionality. You can for example dump a b-tree of a given file using the following command:
`wt verify -d dump_pages`. This will dump keys / values and the internal page layout.

**Comment by luke-pearson** [comment]
You could consider duplicating the logic found in `util_verify.c` to dump the tree in the example code that should prevent needing to utilize internal components.

**Comment by y123456yz** [comment]
> dump_pages

This feature fully meets the requirements and is what I want.
It is recommended to explain in the document that this will be very helpful for beginners to understand btree.
I close the PR.
thanks.

**Pull request closed without merging**
