### PR TITLE
WT-4352 Backport data corruption fixes

### PR DESCRIPTION
**Pull request by agorrod**
Tagged with a ticket to get PR testing started.

### CODE REVIEW

**Comment by agorrod** [comment]
@michaelcahill and @sueloverso could you please review this backport of the fixes related to WT-4750 and other associated tickets. 

@lukech I traced through the tickets linked to the project and links from those tickets, but sanity checking that I didn't miss any commits/tickets would be worthwhile too.

**Comment by lukech** [comment]
retest this please

**Comment by lukech** [comment]
Python3 pull request testing does not make much sense for a branch based on `mongodb-4.0`. Skipped the `wiredtiger-pull-request-python3` in `wiredtiger-pull-request` multi job config for now.

**Comment by lukech** [comment]
retest this please

**Comment by lukech** [comment]
The list of tickets/commits look good to me - 6 resolved tickets from PM-1378, and 1 follow-on ticket (WT-4759).

**Comment by lukech** [comment]
The pull request build passed, and I triggered an Evergreen patch **full** build to verify changes in this branch, hoping to give us more confidence. 
https://evergreen.mongodb.com/version/5ce3a6603627e0165e512431

**Comment by agorrod** [comment]
> It looks like we might need to manually push these change to mongodb-4.0 to make sure we get a commit for each ticket?

Yes, either that or don't squash when merging. I think it's best if I own merging these and managing the JIRA follow on.

**Pull request merged**
