### PR TITLE
WT-2970 evict lockstats

### PR DESCRIPTION
**Pull request by sueloverso**
@agorrod and @keithbostic this is ready for review.  The one test I ran with, `evict-btree.wtperf` indicated that the `evict_walk_lock` may not be worthwhile as it was taken < 5 times during an eviction test.

### CODE REVIEW

**Comment by sueloverso** [comment]
autobuild: retest this please

**Comment by keithbostic** [comment]
lgtm.

**Comment by agorrod** [comment]
This branch introduces a significant performance degradation in my testing: https://jira.mongodb.org/browse/WT-2970?focusedCommentId=1409780&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1409780

**Comment by sueloverso** [comment]
I moved these under HAVE_DIAGNOSTIC and that restores the performance in non-diagnostic builds.  Diagnostic builds still see a little degradation with the workload you posted.

**Comment by sueloverso** [comment]
@agorrod Here are the changes to only track counts for eviction locks.  This makes the branch equivalent performance with develop.

**Comment by agorrod** [comment]
The code lgtm, but I have asked a question in JIRA [here](https://jira.mongodb.org/browse/WT-2970?focusedCommentId=1417827&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1417827)

**Comment by sueloverso** [comment]
I am going to close this branch.  Thinking about this more, knowing just the counts is not going to tell us much.  We know these locks are taken a lot.  Doing the timing impacts performance.

**Pull request closed without merging**
