### PR TITLE
WT-6819 Allowing sweeping handles with active history.

### PR DESCRIPTION
**Pull request by sulabhM**

### CODE REVIEW

**Comment by sulabhM** [comment]
The single test that failed in PR testing is known issue WT-6935.

**Review by tetsuo-cpp — APPROVED** [review]
The change looks fine. In my opinion, you should add some logging and sanity check that it's actually closing the dhandles you expect and consider checking in a test.

As I mentioned, the code to handle this case exists but it's never been exercised so it's pretty high risk.

**Comment by bvpvamsikrishna** [comment]
This change makes sense to me, I don't think we should keep a handle open if it has an active history.

**Review by bvpvamsikrishna — APPROVED** [review]
lgtm

**Comment by sulabhM** [comment]
@tetsuo-cpp , (PERF-2126) sys-perf is currently affected and I am able to locally reproduce the issue of files never getting closed if oldest timestamp is held back. This change is able to fix that issue, I have tested both locally and on the sys-perf runs. I think that is good evidence that the change works as expected.

**Pull request merged**
