### PR TITLE
WT-2938 Change assembly file extensions to .sx

### PR DESCRIPTION
**Pull request by daveh86**

### CODE REVIEW

**Comment by daveh86** [comment]
@agorrod , all of our platforms seem OK with this change. Can you review?

**Comment by agorrod** [comment]
@daveh86 Will this change require any changes to the MongoDB build? I'd prefer to know before merging.

**Comment by michaelcahill** [comment]
Out of interest, can we do an Evergreen patch build against the WiredTiger project to test this?

**Comment by daveh86** [comment]
To @agorrod's question. No, it shouldnt' as the Scons script mongo uses reads from dist/filelist
to @michaelcahill's question. Running now.

**Comment by agorrod** [comment]
Thanks @daveh86 lgtm

**Pull request merged**
