### PR TITLE
WT-8395 Add a version information to the checkpoint snapshot

### PR DESCRIPTION
**Pull request by kommiharibabu**
Adding a version information flag to identify whether the metadata
have a proper snapshot information or not by comparing the retrieved
version information with the binary version.

With this new flag, all the older versions that don't have this flag
are treated having not proper snapshots and ignored them during rollback
to stable operation.

### CODE REVIEW

**Comment by sueloverso** [comment]
I'm wondering if this approach is going to work. Doesn't it just leave us in the same situation? If a customer upgrades to this version, writes a metadata record with this version, then downgrades to 4.4.1, that version record will remain in the metadata file.

Would it be possible to increment the WiredTiger patch version on each and then check the actual version from the turtle file? We know that information is overwritten by every run. Currently we don't bump the WiredTiger release number between drops but perhaps we could. @lukech, @agorrod

**Comment by agorrod** [comment]
@sueloverso you always know how to find the holes in these things. I agree that a downgrade seems as though it could have a problem where the new field is carried forward "accidentally".

**Comment by lukech** [comment]
> Currently we don't bump the WiredTiger release number between drops but perhaps we could.

@sueloverso @agorrod I think we can consider bumping the patch release number "just for this case" if that could make the solution easier (or even possible). Accordingly, we need to treat `10.0.1` as a not-released (not-announced) version, and start to use `10.0.2` fixversion value from this ticket.

**Comment by kommiharibabu** [comment]
@sueloverso @agorrod Another approach of finding out whether the earlier shutdown is a clean shutdown or not? In a clean shutdown, we don't need to run the RTS. Is there any mechanism from WT logging that can be useful here will be a good idea than writing any additional information to the metadata?

Writing any extra information to the metadata is having the same problem with downgrade versions.

**Comment by kommiharibabu** [comment]
This approach leaves the gap of corruption when the database is downgraded and upgraded again, so closing it.

**Pull request closed without merging**
