### PR TITLE
WT-13092 Perform dirty eviction when the page has obsolete time window (4.4 backport)

### PR DESCRIPTION
**Pull request by kommiharibabu**
Before evicting a clean page, mark the page dirty to perform a dirty eviction instead of clean page eviction when the page has obsolete time window.

---------

Co-authored-by: Hari Babu Kommi <haribabu.kommi@mongodb.com>
(cherry picked from commit 7a4dbfa352a895fdaf35f17d65575d833b4003f3)

### CODE REVIEW

**Review by quchenhao — APPROVED** [review]
lgtm

**Comment by quchenhao** [comment]
@kommiharibabu failed to compile on windows.

**Comment by etienneptl** [comment]
> @kommiharibabu failed to compile on windows.

We don't have the right Python version on Windows for 4.4

**Review by etienneptl — APPROVED** [review]

**Comment by etienneptl** [comment]
The Windows change will be done in BACKPORT-22410.

**Comment by etienneptl** [comment]
BACKPORT-22410 has been pushed to 4.4.

**Pull request merged**
