### PR TITLE
WT-8152 Remove stat_db_size runtime check from operations_test and rename cpp evergreen tasks (v6.0 backport)

### PR DESCRIPTION
**Pull request by svc-bot-sebb**
d20a5bcc72c33638ab70016459f3f9244246612d

### CODE REVIEW

**Comment by lukech** [comment]
autobuild: Can one of the admins verify this patch?

**Comment by etienneptl** [comment]
I have authorized the patch and added cpp stress testing.

**Comment by ajmorton** [comment]
This timeout on [cppsuite-operations-test-stress](https://spruce.mongodb.com/task/wiredtiger_mongo_v6.0_cppsuite_stress_tests_cppsuite_operations_test_stress_patch_5003f657b04bde3df73de6f655cbfbbc081cd252_62620c673e8e866a46a27776_22_04_25_09_17_29) looks like WT-9176. 
We should backport it alongside WT-8152

**Review by jiechenbo — APPROVED** [review]
LGTM! SEBB did a clean backport.

**Review by ajmorton — APPROVED** [review]
LGTM

**Comment by jiechenbo** [comment]
Not merging this ticket, another ticket WT-9041 has fixed the underlying root problem.

**Comment by lukech** [comment]
autobuild: Can one of the admins verify this patch?

**Pull request merged**
