### PR TITLE
WT-2560 Use a rwlock to protect transaction state, don't spin.

### PR DESCRIPTION
**Pull request by michaelcahill**

### CODE REVIEW

**Comment by michaelcahill** [comment]
The thing that makes this change more invasive than ideal is that the transaction calls couldn't fail previously (they returned `void`).  Now that they use ordinary rwlocks, they need to deal with the lock calls failing, which has knock-on effects on other code.

**Comment by michaelcahill** [comment]
@agorrod, this looks pretty good in testing.  Can you please review?

**Comment by michaelcahill** [comment]
@agorrod belay that, there were failures in stress testing overnight, leading to WT-2561.

**Comment by michaelcahill** [comment]
This is currently waiting on WT-2566 (adding barriers to locks).

**Comment by michaelcahill** [comment]
OK, @agorrod, I think this one is finally ready for review.  Can you please take a look?

**Comment by agorrod** [comment]
Thanks @michaelcahill I like this change - I'll go ahead and merge.

**Pull request merged**
