### PR TITLE
WT-11767 Use bash in dist/s_* scripts

### PR DESCRIPTION
**Pull request by ershov**
Summary of changes in `dist/` directory:

* Upgrade `s_*` scripts from `sh` to `bash`.
* Add missing hashband `#!` to all scripts as a manifest of language used.
* Fix invalid use of `break` in shell's `case` clause (probably was copy-pasted).

### CODE REVIEW

**Comment by agorrod** [comment]
@ershov I asked a few questions on the Jira ticket - would you mind adding some additional context there before this gets merged?

**Comment by agorrod** [comment]
I also recommend running a patch build (or extending the integrated testing) to include all of our builds and platforms before merging.

**Review by ajmorton — APPROVED** [review]
LGTM pending the above comments 👍

**Comment by ershov** [comment]
@agorrod Hey Alex thanks you for your input. I've answered your comment in the ticket and added you as a reviewer to this PR.

**Review by agorrod — APPROVED** [review]
I'm happy with this change, as long as it works on all of our test platforms.

**Comment by ershov** [comment]
evergreen merge

**Pull request merged**
