### PR TITLE
WT-2835 WT_CONNECTION.leak-memory can skip memory map and cache cleanup

### PR DESCRIPTION
**Pull request by keithbostic**
@agorrod, for your review/consideration.

### CODE REVIEW

**Comment by keithbostic** [comment]
@agorrod, @michaelcahill:

It would be pretty easy to introduce this problem again, if we updated some cache information in a function page-discard calls, there's nothing to ensure page-discard functions do nothing other than free memory.

What would you think of:
```
diff --git a/src/os_common/os_alloc.c b/src/os_common/os_alloc.c
index cfc7b80..101f873 100644
--- a/src/os_common/os_alloc.c
+++ b/src/os_common/os_alloc.c
@@ -301,8 +301,12 @@ __wt_free_int(WT_SESSION_IMPL *session, const void *p_arg)
         * !!!
         * This function MUST handle a NULL WT_SESSION_IMPL handle.
         */
-       if (session != NULL)
+       if (session != NULL) {
                WT_STAT_FAST_CONN_INCR(session, memory_free);
 
+               if (F_ISSET(S2C(session), WT_CONN_LEAK_MEMORY))
+                       return;
+       }
+
        free(p);
 }
```
It's a cache miss in every free call, but **shrug**?

**Comment by agorrod** [comment]
@keithbostic The change lgtm, I'll go ahead and merge. In regards to your other question in the ticket - won't that mean we never free any memory? I don't think that's a good idea - it would lead to ENOMEM in a bunch of new situations.

**Comment by keithbostic** [comment]
> In regards to your other question in the ticket - won't that mean we never free any memory? I don't think that's a good idea - it would lead to ENOMEM in a bunch of new situations.

@agorrod, I think it means we won't free any memory after we call WT_CONNECTION.close with leak_memory configured (that's what sets WT_CONN_LEAK_MEMORY), otherwise nothing changes. Or am I missing something?

**Comment by agorrod** [comment]
Oh, sorry. I didn't check when the flag was set - I'd presumed it was set when the option is configured (i.e: at startup). Regardless I'd probably rather keep free simpler - surprisingly I have seen free contribute significantly to performance profiles on some workloads - that's generally in the allocator not our code - but I'd rather not add to the complexity.

**Pull request merged**
