### PR TITLE
WT-3224 LSM assertion failure pindex->entries == 1

### PR DESCRIPTION
**Pull request by keithbostic**
Don't do in-memory splits on the LSM primary.

### CODE REVIEW

**Comment by keithbostic** [comment]
@agorrod, @michaelcahill, here's the stack from when we did an in-memory split in the LSM primary:
```
(gdb) thread 13
[Switching to thread 13 (Thread 0x7ff212ffd700 (LWP 3697))]
#0  0x00007ff22312cba3 in select () from /lib64/libc.so.6
(gdb) where
#0  0x00007ff22312cba3 in select () from /lib64/libc.so.6
#1  0x0000000000452714 in __wt_sleep (seconds=10, micro_seconds=0)
    at src/os_posix/os_sleep.c:24
#2  0x0000000000487079 in __wt_attach (session=0x1638400)
    at src/support/global.c:125
#3  0x000000000044b797 in __wt_abort (session=0x1638400)
    at src/os_common/os_abort.c:22
#4  0x0000000000486b93 in __wt_assert (session=0x1638400, error=0, 
    file_name=0x5679b7 "src/btree/bt_split.c", line_number=1769, 
    fmt=0x567802 "%s") at src/support/err.c:484
#5  0x00000000004cdab9 in __split_insert (session=0x1638400, 
    ref=0x7ff20c3a1610) at src/btree/bt_split.c:1769
#6  0x00000000004ce885 in __wt_split_insert (session=0x1638400, 
    ref=0x7ff20c3a1610) at src/btree/bt_split.c:2108
#7  0x00000000004333b4 in __evict_review (session=0x1638400, 
    ref=0x7ff20c3a1610, flagsp=0x7ff212ffb880, closing=false)
    at src/evict/evict_page.c:481
#8  0x000000000043267c in __wt_evict (session=0x1638400, ref=0x7ff20c3a1610, 
    closing=false) at src/evict/evict_page.c:129
#9  0x000000000043242c in __wt_page_release_evict (session=0x1638400, 
    ref=0x7ff20c3a1610) at src/evict/evict_page.c:78
#10 0x00000000004bc889 in __wt_page_in_func (session=0x1638400, 
    ref=0x7ff20c3a1610, flags=256, file=0x569850 "src/btree/row_srch.c", 
    line=446) at src/btree/bt_read.c:603
#11 0x00000000004e375d in __wt_page_swap_func (session=0x1638400, 
    held=0x7ff20c044448, want=0x7ff20c3a1610, flags=256, 
    file=0x569850 "src/btree/row_srch.c", line=446)
    at ./src/include/btree.i:1442
#12 0x00000000004e4db2 in __wt_row_search (session=0x1638400, 
    srch_key=0x7ff1d807d4d8, leaf=0x0, cbt=0x7ff1d807d400, insert=true)
    at src/btree/row_srch.c:445
#13 0x000000000053ab76 in __cursor_row_search (session=0x1638400, 
    cbt=0x7ff1d807d400, leaf=0x0, insert=true) at src/btree/bt_cursor.c:344
#14 0x000000000053b2e5 in __wt_btcur_search_near (cbt=0x7ff1d807d400, 
    exactp=0x7ff212ffbc14) at src/btree/bt_cursor.c:515
#15 0x00000000004f5491 in __curfile_search_near (cursor=0x7ff1d807d400, 
    exact=0x7ff212ffbc14) at src/cursor/cur_file.c:222
#16 0x000000000051441f in __clsm_next (cursor=0x7ff1d8039010)
    at src/lsm/lsm_cursor.c:894
#17 0x0000000000407fc3 in nextprev (cursor=0x7ff1d8039010, next=1) at ops.c:942
#18 0x00000000004076dc in ops (arg=0x34dbc50) at ops.c:718
```
I've put what I thought was the obvious change in this pull request, if we don't want to let LSM primary trees split in-memory, but happy to defer to you two.

**Comment by keithbostic** [comment]
There's another failure I'm seeing in this branch, although it's a lot rarer (twice today, in maybe 15,000 runs).
```
5: lsm, row-store (9 seconds)                                              
t, file:wt-000041.lsm, lsm-worker: src/evict/evict_file.c, 100:
    F_ISSET(session->dhandle, WT_DHANDLE_DEAD) || __wt_page_can_evict(session, ref, NULL)
t, file:wt-000041.lsm, lsm-worker: aborting WiredTiger library
t, file:wt-000041.lsm, lsm-worker: process ID 15183: waiting for debugger...
```
Here's the stack:
```
#0  0x00007efec3cd1ba3 in select () from /lib64/libc.so.6
#1  0x0000000000452746 in __wt_sleep (seconds=10, micro_seconds=0)
    at src/os_posix/os_sleep.c:24
#2  0x00000000004870c4 in __wt_attach (session=0x1e66e08)
    at src/support/global.c:125
#3  0x000000000044b7c9 in __wt_abort (session=0x1e66e08)
    at src/os_common/os_abort.c:22
#4  0x0000000000486bde in __wt_assert (session=0x1e66e08, error=0, 
    file_name=0x578cec "src/evict/evict_file.c", line_number=100, 
    fmt=0x578ce9 "%s") at src/support/err.c:484
#5  0x000000000050f355 in __wt_evict_file (session=0x1e66e08, 
    syncop=WT_SYNC_DISCARD) at src/evict/evict_file.c:98
#6  0x00000000004d21ef in __wt_cache_op (session=0x1e66e08, op=WT_SYNC_DISCARD)
    at src/btree/bt_sync.c:319
#7  0x000000000049a6b5 in __wt_checkpoint_close (session=0x1e66e08, 
    final=false) at src/txn/txn_ckpt.c:1677
#8  0x00000000004eb11d in __wt_conn_btree_sync_and_close (session=0x1e66e08, 
    final=false, force=false) at src/conn/conn_dhandle.c:203
#9  0x00000000004ebf13 in __wt_conn_dhandle_close_all (session=0x1e66e08, 
    uri=0x7efe7c0cdc50 "file:wt-000041.lsm", force=false)
    at src/conn/conn_dhandle.c:523
#10 0x000000000046f109 in __drop_file (session=0x1e66e08, 
    uri=0x7efe7c0cdc50 "file:wt-000041.lsm", force=false, cfg=0x7efeb9ffadb0)
    at src/schema/schema_drop.c:33
#11 0x000000000046f796 in __wt_schema_drop (session=0x1e66e08, 
    uri=0x7efe7c0cdc50 "file:wt-000041.lsm", cfg=0x7efeb9ffadb0)
    at src/schema/schema_drop.c:181
#12 0x000000000051f667 in __lsm_drop_file (session=0x1e66e08, 
    uri=0x7efe7c0cdc50 "file:wt-000041.lsm") at src/lsm/lsm_work_unit.c:581
#13 0x000000000051f8ca in __wt_lsm_free_chunks (session=0x1e66e08, 
    lsm_tree=0x4ed2c00) at src/lsm/lsm_work_unit.c:672
#14 0x0000000000445b03 in __lsm_worker_general_op (session=0x1e66e08, 
    cookie=0x1e25168, completed=0x7efeb9ffaede) at src/lsm/lsm_worker.c:71
#15 0x0000000000445c1d in __lsm_worker (arg=0x1e25168)
    at src/lsm/lsm_worker.c:121
```

**Comment by keithbostic** [comment]
@michaelcahill, as per our discussion earlier, I think this change is ready for review/merge.

**Comment by michaelcahill** [comment]
@keithbostic, I took a closer look and once I understood that the `WT_BTREE_NO_RECONCILE` flag was involved (and remembered what it does), I moved the test there and renamed the flag.

I'm going to merge and follow up with a bigger change to LSM for WT-3196.

**Pull request merged**
