### PR TITLE
WT-3333 Fixes for zero length strings packed/unpacked in a 'u' format.

### PR DESCRIPTION
**Pull request by ddanderson**

### CODE REVIEW

**Comment by ddanderson** [comment]
@keithbostic, these changes should fix your problems with zero length strings.

**Comment by ddanderson** [comment]
retest this please

**Comment by ddanderson** [comment]
@michaelcahill, could you please take a look at these small changes and merge if they're okay?

**Comment by agorrod** [comment]
Thanks @ddanderson lgtm

**Pull request merged**
