### PR TITLE
WT-9329 Add LoongArch64 architecture port.

### PR DESCRIPTION
**Pull request by huajingyun01**
I ported the Wiredtiger project on LoongArch64 architecture and tested it. So far it works fine, so I want to share the work.

The commit were tested on Loongson-3A5000 processor, I execute " ctest -j$(nproc) " in the build directory，and the test results are as follows:

```
.................
99% tests passed, 1 tests failed out of 106

Label Time Summary:
check                = 8098.89 sec*proc (102 tests)
check;csuite         =   3.79 sec*proc (2 tests)
cppsuite             = 826.84 sec*proc (2 tests)
csuite               = 5558.85 sec*proc (62 tests)
test_checkpoint      = 701.72 sec*proc (25 tests)
test_cursor_order    =  78.64 sec*proc (3 tests)
wtperf               =  21.20 sec*proc (1 test)

Total Test time (real) = 2567.87 sec

The following tests FAILED:
	103 - test_syscall (Failed)
.................
```

The reason for the failure of test_syscall through log information is:
`strace: invalid system call 'open'`
Checked the strace project (https://github.com/strace/strace) and found that the generic syscallent.h file is used in loongarch64 and riscv64 . The system call open is not defined in this file, but opennat is used. So it leads to the test failure.

### CODE REVIEW

**Comment by sulabhM** [comment]
@huajingyun01 , thanks for submitting a change request. The change is in accordance with WiredTiger's coding standards. I am glad to know that it passes testing. I have created a ticket, [WT-9329](https://jira.mongodb.org/browse/WT-9329), for the team to evaluate concerns in merging the change. Please watch that ticket for further updates.

Thanks for using WiredTiger for your projects.

**Comment by huajingyun01** [comment]
> @huajingyun01 , thanks for submitting a change request. The change is in accordance with WiredTiger's coding standards. I am glad to know that it passes testing. I have created a ticket, [WT-9329](https://jira.mongodb.org/browse/WT-9329), for the team to evaluate concerns in merging the change. Please watch that ticket for further updates.
> 
> Thanks for using WiredTiger for your projects.

**Comment by huajingyun01** [comment]
@sulabhM，thanks for your reply，and i will continue to pay attention to the update of this project.
The LoongArch is a new architecture released in 2021. The relevant document about this architecture can be obtained through the link below:
https://github.com/loongson/LoongArch-Documentation

Thanks！

**Comment by korteland** [comment]
Hi @huajingyun01, sorry for the delay in getting back to you about this - it slipped through the cracks somewhat in our planning. We're interested in getting this merged in, with the understanding that we won't be able to test this architecture (as we have no access to the hardware) and as such won't be able to "officially" support it.

If that's reasonable, can I ask that you rebase this on an updated `develop` branch? Then I can run it through our usual tests and work towards getting this merged in.

**Comment by korteland** [comment]
Another update for you, @huajingyun01: we've made a wiki page with a few more details on the process, if you take a look at https://github.com/wiredtiger/wiredtiger/wiki/Contributing-to-WiredTiger then it should be a bit clearer what the required steps are.

**Comment by huajingyun01** [comment]
Hi@korteland，thank you very much for your reply. I will arrange time for verification in the latest develop branch. In addition, i will read this wiki page  carefully , thank you!

**Comment by huajingyun01** [comment]
Hi, @korteland，I have applied I have applied the patch of this RP on the latest develop branch（This PR modification can be applied to the latest develop branch,）, and completed the compilation and test. The verification results are as follows:

```
.................
99% tests passed, 1 tests failed out of 108

Label Time Summary:
check                = 9331.57 sec*proc (104 tests)
check;csuite         =   4.49 sec*proc (2 tests)
cppsuite             = 1666.64 sec*proc (2 tests)
csuite               = 5928.17 sec*proc (63 tests)
test_checkpoint      = 710.90 sec*proc (25 tests)
test_cursor_order    = 112.92 sec*proc (3 tests)
wtperf               =  21.10 sec*proc (1 test)

Total Test time (real) = 3510.33 sec

The following tests FAILED:
	105 - test_syscall (Failed)
.................
```

```
[root@localhost build]# uname -a
Linux localhost.localdomain 5.10.0-106.18.0.52.loongarch64 #11 SMP PREEMPT Sat Oct 29 18:31:13 CST 2022 loongarch64 loongarch64 loongarch64 GNU/Linux
```

 Looking forward to your reply. Thanks.

**Review by korteland — COMMENTED** [review]
Thanks for doing that and running the checks @huajingyun01!

I've run it through our internal tests and I can confirm it's largely passing, but there's one exception which is our internal whitespace checker (known as `s_all`). You can run it yourself (`cd dist/; ./s_all`) and see what it's complaining about, or alternatively, you can apply this patch:

```
diff --git a/dist/s_string.ok b/dist/s_string.ok
index 04408b5f5..1c9e8148a 100644
--- a/dist/s_string.ok
+++ b/dist/s_string.ok
@@ -775,6 +775,7 @@ datalen
 datasets
 datasource
 datastore
+dbar
 dbc
 dbs
 dcalloc
diff --git a/src/include/gcc.h b/src/include/gcc.h
index 1d125e749..3b53a7783 100644
--- a/src/include/gcc.h
+++ b/src/include/gcc.h
@@ -326,17 +326,17 @@ WT_ATOMIC_FUNC(size, size_t, size_t *vp, size_t v)

 #elif defined(__loongarch64)
 #define WT_PAUSE() __asm__ volatile("nop\n" ::: "memory")
-#define WT_FULL_BARRIER()                               \
-    do {                                                \
-        __asm__ volatile("dbar 0" ::: "memory");        \
+#define WT_FULL_BARRIER()                        \
+    do {                                         \
+        __asm__ volatile("dbar 0" ::: "memory"); \
     } while (0)
-#define WT_READ_BARRIER()                               \
-    do {                                                \
-        __asm__ volatile("dbar 0" ::: "memory");        \
+#define WT_READ_BARRIER()                        \
+    do {                                         \
+        __asm__ volatile("dbar 0" ::: "memory"); \
     } while (0)
-#define WT_WRITE_BARRIER()                              \
-    do {                                                \
-        __asm__ volatile("dbar 0" ::: "memory");        \
+#define WT_WRITE_BARRIER()                       \
+    do {                                         \
+        __asm__ volatile("dbar 0" ::: "memory"); \
     } while (0)
 #else
 #error "No write barrier implementation for this hardware"
```

All this is doing is allowing `dbar` for our spellchecker, and trimming some trailing whitespace a bit. I've reviewed the rest of the code and see no further issues, so fixing this + the copyright assignment on that linked wiki page should be enough to get this merged.

**Comment by huajingyun01** [comment]
Hi @korteland ， thank you for doing the internal testing and providing the patch for the current problem.Because this PR commit is old, I recommit a PR based on the latest develop branch, which might help in the follow-up.
New PR is https://github.com/wiredtiger/wiredtiger/pull/8467
In addition, I have signed a "contributor-agreement".
Thanks！

**Comment by korteland** [comment]
Thanks @huajingyun01 , I'll move the conversation over to the other PR. (For next time - we squash all commits when merging PRs, so feel free to have a bunch of messy commits, including merge commits, in a PR.)

**Pull request closed without merging**
