### PR TITLE
WT-7039 Creating test configuration framework using the WiredTiger configuration API

### PR DESCRIPTION
**Pull request by luke-pearson**

### CODE REVIEW

**Comment by luke-pearson** [comment]
This is a large change and i'll try and break it down in this comment for clarity. The intent behind this change is to provide tests written in the new cppsuite a framework for configuration options. We've opted to use the WiredTiger API configuration framework for this however the pieces didn't fit together exactly, which is why this change will seem a bit odd.

The key parts to this change are:
- Modifying `api_config.py` to generate two configurations. The original `config_def.c` which holds wiredtiger api configuration and a new test_config.c which sits in `test/cppsuite/` and holds cpp suite configurations. In order to support a single script being called from s_all I created a script `api_config_gen.py` which call `api_config.py` with the command line option to get the two different outputs.
- Creation of a `__wt_test_config_match` function, as the `__wt_conn_config_match` which is used by `wiredtiger_config_validate` calls a static structure to validate configs. As we didn't want our test config in the wiredtiger api config we didn't want to use that static structure.
- In order to still use the WiredTiger api to validate we're adding a hidden API call for test configuration. `wiredtiger_test_config_validate`. Which validates using `__wt_test_config_match` instead.
- Adding basic configuration parsing wrapping to `configuration_settings.h`

The brackets are formatted wrong in cxx files however that is an issue with clang format so please ignore them in this PR.

**Review by etienneptl — APPROVED** [review]
LGTM

**Review by keitharnoldsmith — APPROVED** [review]
I left a minor note about a comment. But other than that LGTM.

**Review by Sean04 — APPROVED** [review]
LGTM

**Pull request merged**
