### PR TITLE
WT-7583 Coverity analysis defect

### PR DESCRIPTION
**Pull request by AlexeyAnisimovAU**
Added default case to all switch blocks that deal with OPERATION_TYPE and removed boundary check before them.
Also, _s_all_ script fixed some comments.

### CODE REVIEW

**Comment by tammybailey** [comment]
The commit history looks very strange, not sure what's happening there.

**Comment by AlexeyAnisimovAU** [comment]
Yeah, lots of irrelevant commits... Let me check.

**Comment by AlexeyAnisimovAU** [comment]
Converted to draft. Requires more work.

**Comment by AlexeyAnisimovAU** [comment]
There's something wrong with this PR. Going to close it and make another one.

**Pull request closed without merging**
