### PR TITLE
Revert "WT-13609 Add debugging for rare error case on directories."

### PR DESCRIPTION
**Pull request by sueloverso**
Reverts wiredtiger/wiredtiger#11097

### CODE REVIEW

**Comment by sueloverso** [comment]
@pmacko86 and @ddanderson I need to revert this because the buffers are too small. If `wt_snprintf` returns ERANGE then the systems cannot handle it and fail. See details in the original ticket.

**Review by pmacko86 — APPROVED** [review]
LGTM. I was mostly skimming though.

**Comment by sueloverso** [comment]
Thanks @pmacko86 it is a strict "revert" of the original change. All I did was hit the "Revert" button. So there should be no surprises.

**Review by ddanderson — APPROVED** [review]
LGTM

**Pull request merged**
