### PR TITLE
Statistics cursor reset

### PR DESCRIPTION
**Pull request by keithbostic**
@michael, I think this is close to what we need for #1533, two questions:

1. I couldn't think of any way to avoid copying the incoming configuration strings when the cursor is opened.

1. I almost made the change to not initialize the cursor when opening it (if we wait until the first operation after cursor-reset to initialize the cursor, might as well wait until the first operation after cursor-open to initialize the cursor), but for some reason, that makes Python sad, I get;
```
File "/b/bostic/wt.develop/lang/python/wiredtiger/__init__.py", line 337, in __getitem__
raise KeyError
KeyError```

### CODE REVIEW

**Comment by michaelcahill** [comment]
Hi @keithbostic, this seems okay, but I'd like to understand what went wrong when you tried to have cursors start out uninitialized: it seems like that should work, and suggests that `WT_CURSOR::search` may not work properly after a `reset`.

As far as I can see, the only configuration we need from the cursor is the checkpoint name.  Can we extract that once, during the first cursor open, rather than passing around the cfg stack everywhere?

**Comment by michaelcahill** [comment]
Also, this is a behavior change.  I doubt it will cause any problems, but it should have an entry in the upgrading notes.

**Comment by keithbostic** [comment]
@michaelcahill, I've investigated why cursors can't start out uninitialized. I made it work (it was a bug in my code), but ran into a subsequent problem.

Higher level cursors (for example, tables), don't do cursor operations, they simply aggregate the statistics from the underlying handles after making the cursor-open call. We could change those functions to always do a `WT_CURSOR.next` after an open, but I don't see much point in doing that just to delay the initial snapshot to the first operation.

**Comment by keithbostic** [comment]
@michaelcahill:

> As far as I can see, the only configuration we need from the cursor is the checkpoint name. Can we extract that once, during the first cursor open, rather than passing around the cfg stack everywhere?

I think we also need the statistics configuration too, for example, `statistics=(fast,clear)`.

Regardless, I think it's simpler and less fragile to copy the configuration strings than to assume we won't ever need anything else, unless there's a performance question.

We could not-copy the first configuration string (it's the largest, of course), it's not much additional complexity to avoid that.

**Comment by michaelcahill** [comment]
Thanks, @keithbostic -- let's see if copying the config stack is noticeable in workloads like #1634 and if so, we can worry about it then.

**Pull request merged**
