### PR TITLE
Add MCI project definition

### PR DESCRIPTION
**Pull request by jbreams**
This PR adds a MCI project file so we can add the wiredtiger develop branch into our CI system. The work is being tracked in https://jira.mongodb.org/browse/BUILD-479. Let me know if you have any questions or concerns.

### CODE REVIEW

**Comment by wtbuild** [comment]
autobuild: Can one of the admins verify this patch?

**Comment by agorrod** [comment]
Thanks @jbreams - this looks OK to me. Would it be possible for the file to live under the dist or test subdirectory instead in the root?

It'd also be good if there was a comment at the start of the file describing what it's purpose is.

**Comment by jbreams** [comment]
I just pushed a commit that moves the file under the test subdirectory and adds a brief explanation of what the file is at the top.

**Comment by agorrod** [comment]
lgtm, I'll merge.

**Pull request merged**
