### PR TITLE
Add flags to wt_fopen/fclose. #1785

### PR DESCRIPTION
**Pull request by sueloverso**
@keithbostic While the code is correct, I added macros for the `__wt_fopen` and `__wt_fclose` calls to better associate the connection between the fopen mode and the arg to fclose.  I agree that wrapping it in an entire new structure (that is different than the `WT_FH` but would be similar enough to be confusing) is overkill.  I think it is a modest improvement over the raw numbers there.

### CODE REVIEW

**Comment by keithbostic** [comment]
@sueloverso, I'm not a big fan, but I don't feel strongly -- if you and @michaelcahill prefer this, it's fbm.

We may need more modes, for example, `r+`, `w+` and `a+`.

**Comment by michaelcahill** [comment]
If we add Windows-specific versions of the macros that append "b" so we can get rid of that code from `__wt_fopen`, them I'm so\ld.

**Comment by keithbostic** [comment]
Maybe we could use `WT_FHANDLE_XXX` as integer values, and then the upper-level open/close calls would use the same argument?

The os code could switch on `WT_FHANDLE_XXX` to pick a mode.

**Comment by sueloverso** [comment]
Both are great ideas.  I have coded that up and this is ready for review.  For now I do not include any of the "+" modes.  We can add as we need them.

**Comment by sueloverso** [comment]
autobuild: retest this please

**Comment by michaelcahill** [comment]
This branch included the zlib changes -- I'll split them out into their own branch.

**Comment by sueloverso** [comment]
Are the zlib changes related to the fopen/fclose changes?  It does not seem so.  @keithbostic did you accidentally commit to this branch?

**Comment by keithbostic** [comment]
Just minor confusion, @michaelcahill and I talked, it's all good.

**Pull request merged**
