### PR TITLE
WT-2910 When running in-memory, only evict dirty pages.

### PR DESCRIPTION
**Pull request by michaelcahill**
Also, don't relax the clean / dirty requirements when we get aggressive:
if application threads are blocked by the dirty limit, evicting a clean
page doesn't unblock them so there's no point trying.

### CODE REVIEW

**Comment by michaelcahill** [comment]
@daveh86, this branch is a version of the changes we talked about today.  I think they're necessary (but may not be sufficient) even if the hang isn't reproducing on the tip of develop.  Let's discuss in person tomorrow.

**Comment by michaelcahill** [comment]
autobuild: please retest

**Comment by michaelcahill** [comment]
autobuild: retest this please

**Comment by daveh86** [comment]
This LGTM

**Comment by michaelcahill** [comment]
Thanks @daveh86, merging.

**Pull request merged**
