### PR TITLE
WT-3030 alternative loop for finding the matching slot.

### PR DESCRIPTION
**Pull request by keithbostic**
WT-3030 alternative loop for finding the matching slot.

### CODE REVIEW

**Comment by keithbostic** [comment]
autobuild: retest this please

**Comment by keithbostic** [comment]
autobuild: retest this please

**Comment by keithbostic** [comment]
autobuild: retest this please

**Comment by michaelcahill** [comment]
@keithbostic, I don't feel strongly that the pointer version is clearer than using indexes, but I'm not going to fight about it.  I'll merge this, but move these changes into a new ticket so WT-3030 stays focussed on the fix (particularly for backports).

**Pull request merged**
