### PR TITLE
WT-10090 Rename wt_verbose_debug -> wt_verbose_debug1

### PR DESCRIPTION
**Pull request by korteland**
It became inconsistent with the other functions after we got debug2 and debug3.

### CODE REVIEW

**Review by luke-pearson — APPROVED** [review]
LGTM.

**Review by luke-pearson — CHANGES_REQUESTED** [review]
On second thoughts I'm not a huge fan of `__wt_verbose_debug1` I understand why we would want it but perhaps now that we have 5 levels we should give up on wrapper macros?

**Comment by korteland** [comment]
That's fair. I don't agree with giving up on wrapper macros entirely since it's a nicer shorthand than constantly writing out `WT_VERBOSE_DEBUG_X`, plus there's a massive amount of code using them.

I think the main loss with this approach is for code that doesn't care about the debug level, but I'd also argue that anything doing debug logging *should* care about the log level.

**Comment by luke-pearson** [comment]
I see we already have a `verbose2` in the codebase, so the only real change here is to bring the default level macro into line with the verbose2 macro?

**Comment by korteland** [comment]
Yeah, that's right.

**Review by luke-pearson — APPROVED** [review]
LGTM.

**Comment by korteland** [comment]
evergreen merge

**Comment by korteland** [comment]
Commit queue failure is unrelated (the failing assertion was about tiered storage not being on the first object when it doesn't have a shared tier).

**Pull request merged**
