### PR TITLE
WT-3336 Enable statistics by default in wtperf

### PR DESCRIPTION
**Pull request by daveh86**

### CODE REVIEW

**Comment by daveh86** [comment]
@michaelcahill would you mind taking a look at this? 

I've added statistics_log to wtperf by default and removed statistics_log from all the runner files.

**Comment by agorrod** [comment]
@daveh86 Did you check the perf jobs to see if this change causes any variation?

**Comment by daveh86** [comment]
This does have a small impact on performance in those tests. To the tune of about 5% in the worst case.

We could change the scope of the initial change to make the stats 5 seconds by default, which would likely alleviate the worst case. @agorrod do you think that the 5% hit is too much?

**Comment by daveh86** [comment]
retest this please

**Comment by agorrod** [comment]
I've moved this conversation to https://jira.mongodb.org/browse/WT-3336

**Comment by daveh86** [comment]
I'm closing this PR based on the discussion in Jira.

**Pull request closed without merging**
