### PR TITLE
WT-5462 Rebalance the Evergreen Python test buckets

### PR DESCRIPTION
**Pull request by agorrod**
Trying to keep PR runtime low.

### CODE REVIEW

**Comment by agorrod** [comment]
@lukech and @raviprakashgiri29 would you mind reviewing this change? I'm not sure if there are concerns with changing the set of tests in a particular bucket, but I think this should lop a few minutes off PR turnaround.

**Comment by lukech** [comment]
In the PR patch build, bucket 04 seems taking over 10 mins in the [Windows build variant](https://evergreen.mongodb.com/build/wiredtiger_windows_64_patch_b18884f9ebb91005e3496a9e7ec5838b8363b87e_5e5c870e0305b95e8a89d9c0_20_03_02_04_09_51). Can we balance some tests from bucket 04 to 05 to reduce the critical path further?

**Comment by lukech** [comment]
Actually, `test_hs0x` took most of the time in bucket 04. The new hs tests may deserve a dedicated bucket.

**Comment by agorrod** [comment]
@lukech and @raviprakashgiri29 I got stalled intending to make this change better, but I think it's an improvement as-is. The history store tests should go from ~26 minutes on Windows to less than 20. I've doubled the number of parallel jobs on Linux which helped reduce runtimes in my testing.
Let's follow up with trying to parallelize Windows testing again in a different ticket, if that's OK with you?

**Pull request merged**
