### PR TITLE
WT-13913 Create a new checkpoint struct dedicated to the checkpoint thread information

### PR DESCRIPTION
**Pull request by etienneptl**
The changes introduce a new struct called `WT_CKPT_THREAD` that contains all the information related to handles needed by the checkpoint. The existing `WT_CKPT_CONNECTION` struct has been updated to use the new struct.

### CODE REVIEW

**Comment by sueloverso** [comment]
A similar thing was done in logging in the original modularization effort. This seems to be pretty consistent with that, but I suggest looking at it in case there is anything noteworthy to see there for this change.

**Comment by etienneptl** [comment]
> A similar thing was done in logging in the original modularization effort. This seems to be pretty consistent with that, but I suggest looking at it in case there is anything noteworthy to see there for this change.

Thank you for sharing, @sueloverso. I believe you are referring to [this](https://github.com/wiredtiger/wiredtiger/pull/11142/files#diff-60db76278e657695cfa3fadeea95eddb354f09b6ed5321fe44d77b5d0e7b5a97R155). I will look into it!

**Comment by etienneptl** [comment]
@sueloverso, I have followed what was done in #11142, see ac9e358f16f6d36ba10e52eeca2805056276974b.

**Review by sueloverso — APPROVED** [review]
LGTM

**Review by Sean04 — APPROVED** [review]
lgtm

**Review by ershov — APPROVED** [review]
This is a good change, thanks Etienne!

**Pull request merged**
