### PR TITLE
Added extractor tests and a small fix for customized extractors.

### PR DESCRIPTION
**Pull request by ddanderson**
To fix WT-1940.

### CODE REVIEW

**Comment by ddanderson** [comment]
@michaelcahill, can you review please?  I've called out a rough spot in cvs_extract() to check out.

**Comment by ddanderson** [comment]
@michaelcahill, thanks. I've modified the code to do a normal copy. Also committed some files that I somehow missed the first time.

**Comment by ddanderson** [comment]
@michaelcahill, please hold off review until I have a chance to track down the test failure.

**Comment by ddanderson** [comment]
@michaelcahill, this is ready for review.

**Comment by michaelcahill** [comment]
Thanks, @ddanderson -- lgtm.  I'll merge.

**Pull request merged**
