### PR TITLE
WT-2976 Add a statistic tracking how long app threads spend reading

### PR DESCRIPTION
**Pull request by agorrod**

### CODE REVIEW

**Comment by agorrod** [comment]
@sueloverso Would you please review this change?

**Comment by agorrod** [comment]
FWIW: I don't like how the statistics naming groups the new stats, but I struggled to word the descriptions in a way that made sense while keeping order. Feel free to make changes to the wording.

**Comment by sueloverso** [comment]
@agorrod I did rework the wording so that they will group together.  See if you like it.

**Comment by agorrod** [comment]
Thanks @sueloverso I did a little more word shuffling, but preserved the order. I'll go ahead and merge.

**Pull request merged**
