### PR TITLE
WT-10764 Adding a message to indicate that rollback to stable has finished (v6.3 backport)(#8934)

### PR DESCRIPTION
**Pull request by mm-ng**
* Updating RTS verifier script to handle the new message.

(cherry picked from commit 83f2b1b94c08e5d7c5b97a0fd77880cbb8989b82)

### CODE REVIEW

**Comment by mm-ng** [comment]
I have backported the main changes related to having the RTS start and stop messages but decided not to include test_rollback_to_stable42.py as I believe that relies on other changes related to RTS to be backported in order for it to work properly. It’s also not directly related to the change we want to backport.

**Review by korteland — COMMENTED** [review]
This is a very large backport for just the single extra change. I don't think it's good value to backport all of the RTS verifier alongside what is conceptually a really simple change (adding a clearer log line) - would it be reasonable to simplify this change down to the two affected log lines?

**Comment by luke-pearson** [comment]
> would it be reasonable to simplify this change down to the two affected log lines?
I agree this should be simplified to avoid pulling in the verifier details.

**Comment by mm-ng** [comment]
> This is a very large backport for just the single extra change. I don't think it's good value to backport all of the RTS verifier alongside what is conceptually a really simple change (adding a clearer log line) - would it be reasonable to simplify this change down to the two affected log lines?

@korteland Did you mean the two lines in `rts_api.c`? I only included the verifier files as the ticket was changing those files as well but I can just delete those files here.

**Review by korteland — APPROVED** [review]
LGTM!

**Review by luke-pearson — APPROVED** [review]
LGTM.

**Pull request merged**
