### PR TITLE
WT-12651 Adjust target pre-compression target page size

### PR DESCRIPTION
**Pull request by y123456yz**
Background:
       A user's online database data was migrated from another database(not MongoDB) to MongoDB. After migrating to MongoDB, the user found that the disk usage increased by about 35%, while the write performance and query (mainly range query) performance decreased to some extent.
    To analyze this issue, I temporarily opened the storage log threshold of Mongo, and the information is as follows:
**db.setLogLevel(2, 'storage');
db.adminCommand({setParameter:1, wiredTigerEngineRuntimeConfig:'verbose=[block=5,write=5]'})**

`
{"t":{"$date":"2024-03-13T21:51:58.068+08:00"},"s":"D2", "c":"WT",       "id":22430,   "ctx":"conn8","msg":"WiredTiger message","attr":{"message":{"ts_sec":1710337918,"ts_usec":68421,"thread":"1732:0x7f2e52053700","session_dhandle_name":"file:user/index/7-3409874514835487866.wt","session_name":"WT_CURSOR.insert","category":"WT_VERB_WRITE","category_id":42,"verbose_level":"DEBUG_2","verbose_level_id":2,"msg":"write: /data/mongodb-data/mongodb-7.0.0/data/user/index/7-3409874514835487866.wt, fd=59, offset=1306624, len=8192"}}}
{"t":{"$date":"2024-03-13T21:51:58.068+08:00"},"s":"D2", "c":"WT",       "id":22430,   "ctx":"conn8","msg":"WiredTiger message","attr":{"message":{"ts_sec":1710337918,"ts_usec":68545,"thread":"1732:0x7f2e52053700","session_dhandle_name":"file:user/index/7-3409874514835487866.wt","session_name":"WT_CURSOR.insert","category":"WT_VERB_WRITE","category_id":42,"verbose_level":"DEBUG_2","verbose_level_id":2,"msg":"write: /data/mongodb-data/mongodb-7.0.0/data/user/index/7-3409874514835487866.wt, fd=59, offset=1249280, len=12288"}}}
{"t":{"$date":"2024-03-13T21:51:58.100+08:00"},"s":"D2", "c":"WT",       "id":22430,   "ctx":"conn8","msg":"WiredTiger message","attr":{"message":{"ts_sec":1710337918,"ts_usec":100613,"thread":"1732:0x7f2e52053700","session_dhandle_name":"file:user/index/7-3409874514835487866.wt","session_name":"WT_CURSOR.insert","category":"WT_VERB_WRITE","category_id":42,"verbose_level":"DEBUG_2","verbose_level_id":2,"msg":"write: /data/mongodb-data/mongodb-7.0.0/data/user/index/7-3409874514835487866.wt, fd=59, offset=1249280, len=12288"}}}
{"t":{"$date":"2024-03-13T21:51:58.113+08:00"},"s":"D2", "c":"WT",       "id":22430,   "ctx":"conn8","msg":"WiredTiger message","attr":{"message":{"ts_sec":1710337918,"ts_usec":113511,"thread":"1732:0x7f2e52053700","session_dhandle_name":"file:user/collection/6-3409874514835487866.wt","session_name":"WT_CURSOR.insert","category":"WT_VERB_WRITE","category_id":42,"verbose_level":"DEBUG_2","verbose_level_id":2,"msg":"write: /data/mongodb-data/mongodb-7.0.0/data/user/collection/6-3409874514835487866.wt, fd=57, offset=4182016, len=4096"}}}
{"t":{"$date":"2024-03-13T21:51:58.114+08:00"},"s":"D2", "c":"WT",       "id":22430,   "ctx":"conn8","msg":"WiredTiger message","attr":{"message":{"ts_sec":1710337918,"ts_usec":114105,"thread":"1732:0x7f2e52053700","session_dhandle_name":"file:user/index/7-3409874514835487866.wt","session_name":"WT_CURSOR.insert","category":"WT_VERB_WRITE","category_id":42,"verbose_level":"DEBUG_2","verbose_level_id":2,"msg":"write: /data/mongodb-data/mongodb-7.0.0/data/user/index/7-3409874514835487866.wt, fd=59, offset=1290240, len=12288"}}}
`

From the mongod.log above, it can be seen that our write disk block size is between 8 and 12K, which is much smaller than maxleafpage (default value of 32K), which is an issue.

### CODE REVIEW

**Comment by y123456yz** [comment]
Through analysis, I found that this problem is caused by the compression adjust algorithm, which results in a lot of useless space in the block, ultimately leading to disk waste and affecting write performance and range query performance.

I simulated a testing program using a test library, and the test code is as follows:
`
    error_check(wiredtiger_open(home, NULL, "create,cache_size=25M, statistics=(all),create,verbose=[write:0, metadata:0, api:0]", &conn));

    /* Open a session handle for the database. */
    error_check(conn->open_session(conn, NULL, NULL, &session));
    /*! [access example connection] */

    /*! [access example table create] */
    error_check(session->create(session, "table:access", "block_compressor=snappy,leaf_page_max=16KB,key_format=q,value_format=u"));
    /*! [access example table create] */

    /*! [access example cursor open] */
    error_check(session->open_cursor(session, "table:access", NULL, NULL, &cursor));
   value_item.data = ""value new @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\0";";
    value_item2.size = strlen(value_item2.data);
    for (i=5500000;i > 0; i--) {
        cursor->set_key(cursor, i); /* Insert a record. */
        cursor->set_value(cursor, &value_item2);
        error_check(cursor->insert(cursor));
    }
`

**Comment by y123456yz** [comment]
Conclusion: Too much unuse write byte  leads to disk waste and performance loss.
Finally, After this PR's code, I rebuild mongo server code, with the new mongod the user conducted a pressure test comparison using the same data and found that disk space was saved by 35%, and writing performance was improved by 25%.

We can temporarily increase the memory_page_image_max configuration to solve the problem, but this is not very realistic for the following reasons:
1. 99.9% of users do not know the true purpose of this parameter
2. During the operation of mongod, we cannot modify the WT parameter by linking to the mongo shell
3. Even if we know the purpose of this configuration, we are not sure how much setting is reasonable

Therefore, the purpose of this PR is dynamically adjust the algorithm to ensure that WT can automatically adjust to the Best value.

thanks.

**Comment by y123456yz** [comment]
WT-12651

**Comment by y123456yz** [comment]
https://www.mongodb.com/community/forums/t/wt-file-expansion-when-mongorestore-in-parallel/194739/10

Perhaps this is also caused by the same issue

**Comment by korteland** [comment]
@y123456yz this is a really interesting pull request - the performance problem is tricky. Nice work tracking that down and identifying a fix! I also agree that finding and understanding the parameter names is hard, even for experienced users.

There's a tradeoff here which hasn't been evaluated, which is that for pages that compress really well, the in-memory size could become much larger than we want. This becomes a problem for point queries, so with this change there's a real risk of a regression for a use case that's quite common. (In general we aim to balance these two needs, while providing the ability to tune specific deployments for specific workloads.)

Unfortunately we can't accept the change as-is, due to that risk of regressions. We can take optimisations, but a change that improves one workload at the expense of another isn't something we can take on.

I want to reiterate that the idea is fundamentally useful, and the Jira ticket can stay open - we definitely want to provide better options for matching configurations to workloads in the future.

Apologies if that's not the news you wanted to hear.

**Comment by y123456yz** [comment]
@korteland 
I agree with your point of view that there is indeed a risk of memory increase in ultra-high compression ratio scenarios. Can we first keep the code counted by block_byte_write_unused here, so as to help users quickly locate the reason for the disk increase.If the user encounters a similar problem, it is up to the user to decide whether to adjust the corresponding configuration.

**Comment by korteland** [comment]
@y123456yz yep, I think a statistic tracking the number of unused bytes written would be worthwhile. Would you be able to do this in another ticket please?

**Comment by y123456yz** [comment]
@korteland 
Okay, there has been a bit of work on my end lately, and there may be some delays here. I expect to create this ticket a few days later.After creating a new ticket, I will @ help you review the code.
thanks.

**Comment by y123456yz** [comment]
I have create a new PR [WT-12839](https://jira.mongodb.org/browse/WT-12839):   session reconfig memory_page_image_max support and add unused padding stastic.

please review again.

thanks.
@korteland

**Comment by y123456yz** [comment]
Also, I have a question, what is the design purpose of dump_blocks? What is the main difference between  dump-address and dump_pages?
Can you help me with that? I don't understand that very well.
thanks.
@korteland @luke-pearson

**Pull request closed without merging**
