### PR TITLE
WT-6064 Enable coverage-report

### PR DESCRIPTION
**Pull request by quchenhao**

### CODE REVIEW

**Review by lukech — COMMENTED** [review]
Do you mind creating 2 tickets for re-enabling lower isolation level and column store tests in coverage-report, and referring to the ticket numbers in the code comment?

**Comment by quchenhao** [comment]
> Do you mind creating 2 tickets for re-enabling lower isolation level and column store tests in coverage-report, and referring to the ticket numbers in the code comment?

Yes, I'll do that.

**Review by lukech — APPROVED** [review]
LGTM

**Comment by tammybailey** [comment]
@quchenhao, have you run a patch test to ensure this test completes successfully?

It looks like the ticket number is wrong in the title (should be WT-6064, I think).

**Comment by quchenhao** [comment]
@tammybailey Nice catch on the ticket number. Yes, it should be WT-6064. The test is running successfully and producing coverage report as expected.

**Review by tammybailey — APPROVED** [review]
LGTM

**Pull request merged**
