### PR TITLE
Remove unnecessary error labels

### PR DESCRIPTION
**Pull request by keithbostic**
@sueloverso, would you please do the review?

Thanks!

### CODE REVIEW

**Comment by sueloverso** [comment]
autobuild: please retest this

**Comment by sueloverso** [comment]
autobuild: retest this please

**Comment by sueloverso** [comment]
This looks fine.  As soon as it passed the pull-request-tester, I'm good to merge.

**Comment by agorrod** [comment]
autobuild: retest this please

**Pull request merged**
