### PR TITLE
WT-13679 Soft link ~/.cache to the /data folder in many-collections-test

### PR DESCRIPTION
**Pull request by ajmorton**
The many-collections test is running out of space on evergreen due to storing bazel's cache in the home directory instead of the `/data` dir. This is an interim fix to resolve test failures while we pursue a proper fix in WT-13607.

### CODE REVIEW

**Comment by ajmorton** [comment]
@etienneptl this resolves the compilation issues with `many-collections-test`, but we have a subsequent failure due coming from WT-13642. I'll add `many-collections-test` to PR testing once the WT-13642 revert is merged.

**Review by etienneptl — APPROVED** [review]

**Comment by ajmorton** [comment]
evergreen retry

**Comment by ajmorton** [comment]
We're hitting an issue where the (unchanged) `fetch mongo repo` step fails in PR testing, but not in patches. I'll investigate

**Comment by ajmorton** [comment]
> We're hitting an issue where the (unchanged) `fetch mongo repo` step fails in PR testing, but not in patches. I'll investigate

This was a pre-existing failure where `many-collections-test` couldn't run in PR testing. The script expects the branch name to be one of `mongodb-*` or `develop`, but PR tests use a branch name `evg-pr-test-*`. Because the branch name didn't match `set -o errexit` triggers and fails the task.

I've updated the check and will merge when tests pass. @etienneptl pinging to let you know there's one more change in this PR, but no need for re-review.

**Pull request merged**
