### PR TITLE
WT-8289 Provide a means to get K/V pair on duplicate key error

### PR DESCRIPTION
**Pull request by keithbostic**
Change WT_DUPLICATE_KEY error returns to leave the current value in the cursor value buffer.

### CODE REVIEW

**Review by sulabhM — APPROVED** [review]

**Comment by sulabhM** [comment]
Ah! seems like the change is failing a few tests, I LGTM-ed too soon!

**Comment by keithbostic** [comment]
@agorrod, this is an API change: can you please review, or appoint someone to make the decision? -- Thanks!

**Comment by keithbostic** [comment]
> Ah! seems like the change is failing a few tests, I LGTM-ed too soon!

Not too surprising. If we decide to go in this direction I'll chase them down.

**Comment by agorrod** [comment]
I like the idea, but have some concern about the API change. I left a comment on the JIRA ticket with more context.

**Comment by sulabhM** [comment]
@keithbostic , is this still up for review. GitHub plugin for lack keeps reminding me to review, but the tests have not passed yet. Let me know if there is a review pending on me.

**Comment by keithbostic** [comment]
Thank you, @sulabhM, I apologize for the nagging. I'll get this one in shortly.

**Comment by keithbostic** [comment]
@sulabhM, this one should be ready fro review -- thanks!

**Review by sulabhM — APPROVED** [review]

**Pull request merged**
