### PR TITLE
Add log code to ensure write-no-sync. #1585

### PR DESCRIPTION
**Pull request by sueloverso**
@michaelcahill Here are code changes to ensure that write-no-sync is enforced when the configuration is `log=(enabled),transaction_sync=(enable,method=none)`.  Please review.  Here are some things of note:
- I changed the default from in-memory buffer to the write-no-sync setting.
- I fixed the tune-durability documentation to correct the setting for `begin_transaction` as well as fix the discussion about the default.  See if you agree/like the doc wording changes too.
- If you don't agree with the default setting change, the doc will need rework.

### CODE REVIEW

**Comment by wtbuild** [comment]
Test PASSed.

**Comment by sueloverso** [comment]
This is waiting on review by Michael.
MongoDB uses the old default configuration setting so if we merge this and it goes into rc7, we either need to change that to retain their old in-memory buffer setting or decide the new default is desired (and will probably be a slower).  Or I undo my change of the default behavior in this code.

**Comment by michaelcahill** [comment]
Hi @sueloverso, I'll take a careful look, but we should also do some benchmarking.  I suspect the impact is minimal for many cases, because they go through `__log_direct_write`.  If that is the case, let's try to get this into RC7.

**Comment by wtbuild** [comment]
Test PASSed.

**Comment by sueloverso** [comment]
@michaelcahill Changing the default and running `wtperf` with the `log_append.wtperf` workload (an insert-only parallel workload) shows a large drop of 50%.  The in-buffer default (old code) completed in 300 seconds and the write-no-sync new default completed in 450 seconds consistently.  I am going to create a sub-branch that reverts the default back to the in-buffer off of this branch.

**Comment by sueloverso** [comment]
I didn't address your comment about `log_direct_write`.  We only use the direct write path up until we see any contention on the lock and start consolidating.  In a multi-threaded load, we'll start consolidating pretty quickly and after that we stay consolidating forever, going forward.  That explains why the performance drops.

**Comment by michaelcahill** [comment]
Thanks for the explanation, @sueloverso -- now that we're not changing the default, I'm happy to merge this one.

**Comment by wtbuild** [comment]
Test PASSed.

**Pull request merged**
