### PR TITLE
The once_control in os_win/os_once.c should be static.

### PR DESCRIPTION
**Pull request by zhengshuxin**

### CODE REVIEW

**Comment by lukech** [comment]
autobuild: Can one of the admins verify this patch?

**Comment by keithbostic** [comment]
This makes sense to me, but I'm not a Windows person, and note the merge is pointed at master, we'll want to merge the change into develop.

**Comment by markbenvenuto** [comment]
As a Windows person, it looks good to me.

**Comment by keithbostic** [comment]
Thank you @zhengshuxin!

We need to merge into the develop branch, so I'm going to close #7500 and I'll merge #7501.

**Pull request closed without merging**
