### PR TITLE
Draft of 2.6.0 release

### PR DESCRIPTION
**Pull request by agorrod**
The changelog isn't complete yet. There were over 3000 lines in the git log - it's a huge release.

### CODE REVIEW

**Comment by michaelcahill** [comment]
Thanks, @agorrod -- I'll have to go through this with you tomorrow and I hope we can get the release done quickly.

**Comment by agorrod** [comment]
@keithbostic Could you do a pass through the change log for the 2.6.0 release? It's a monster of a release, so there is a lot of content in the change log :)

**Comment by pgk2** [comment]
All,

A very large number of changes. When we do a release I usually tweet out
that we have a new release, provide a couple words as a summary and a link
to the release page, all in 140 characters. Are there a couple of words we
would use to summarize this release, i.e. bug fixes, improved performance,
better LSM support, etc. I am sure I can come up with something but would
appreciate any input.

Let me know and I will watch for the email of the actual release. Thanks!

-Paul

**Comment by keithbostic** [comment]
@agorrod, sure, done.

Maybe I can create the change-log next time, so you don't always get stuck with that work?

**Comment by agorrod** [comment]
@pgk2 
> Are there a couple of words we would use to summarize this release

The headline features are:
* Encryption at rest
* Bug fixes for durability guarantees (recovery after system crashes)
* Significant performance improvements

Let me know if that is too much or too little detail.

**Pull request merged**
