### PR TITLE
wtstats tool: added support to parse wtperf files

### PR DESCRIPTION
**Pull request by rueckstiess**
wtperf stats go into a separate "wtperf" section in the sidebar.

Files of either type can be provided at the command line, even mixed in one call. The file type is determined when looking at the first line.

For example, this is a valid call to wtstats:

```
python wtstats.py ./WTPERF_RUN/monitor ../test/WiredTigerStat.fixture
```

Adding the wtperf if conditions all over the code is not very clean, I'd like to build two individual parser classes in the future and clean up that code.

This change would make the old `wtperf_stats` tool obsolete (entire `tools/wtperf_stats/` folder could be removed incl. nvd3 references).

### CODE REVIEW

**Comment by sueloverso** [comment]
@rueckstiess I have reviewed these.  First, I think it is great to have them both combined and able to be viewed together.  That should help a lot to see where high latencies or drops in wtperf throughput coincide with other statistics!

 I have a couple small comments:
1.  When I ran a test, I copied the monitor file and the WiredTigerStat files into a temp directory and then ran wtstats on the directory.  It did not find the monitor file and only processed the WiredTigerStat files.  Can you please add support for finding monitor files in the directory code? I suggest 'monitor*' so that one could have multiple monitor files from different runs.
2.  Can you display the latency values in msecs?  When I displayed only the insert ops/sec and max latency values, the large usec numbers made it impossible to see the ops/sec variability due to the differences in scale.

Otherwise, thanks so much.

**Comment by rueckstiess** [comment]
Hi @sueloverso, thanks, yes I'll make these changes on Monday and will push to this PR.

**Comment by rueckstiess** [comment]
Hi @sueloverso, I made the changes you mentioned and added tests for these cases. I also cleaned up the code a little and made two separate functions to parse the different file types. 

Could you do another review? 

I have not yet removed the `./tools/wtperf_stats` folder in this pull request. Let me know if you'd like me to include that.

**Comment by michaelcahill** [comment]
autobuild: retest this please

**Comment by sueloverso** [comment]
@rueckstiess These look good.  I'll merge.  Let's give this a couple days in  case anything turns up and then we can remove the other folder.

**Pull request merged**
