### PR TITLE
WT-11138 Enhance gdb dump script to dumping checkpoint dhandle

### PR DESCRIPTION
**Pull request by kommiharibabu**

### CODE REVIEW

**Review by korteland — APPROVED** [review]
LGTM - thanks for tweaking this. I'm curious whether you saw anything interesting with it on that core dump?

**Comment by kommiharibabu** [comment]
@korteland We need to implement WT-11139 also to get more information from the core dump on-disk image. I believe that it may be corrupted after the image is loaded into memory, as we are not able to find the same corruption from the on-disk image using the verify.

**Comment by korteland** [comment]
Ack, thanks for the details there @kommiharibabu .

**Review by clarissecheah — APPROVED** [review]
LGTM ! Thanks Hari, this looks super useful.

**Comment by kommiharibabu** [comment]
evergreen merge

**Pull request merged**
