### PR TITLE
 WT-11997 Revert "WT-11398 Refresh application thread snapshot when it performs eviction (#9765)"

### PR DESCRIPTION
**Pull request by Sean04**
This reverts commit 05a375660414d70bcf80351ab34be85b33d68840.

### CODE REVIEW

**Review by kommiharibabu — APPROVED** [review]
LGTM

**Review by bvpvamsikrishna — APPROVED** [review]
LGTM

**Comment by Sean04** [comment]
evergreen merge

**Comment by Sean04** [comment]
evergreen merge

**Pull request merged**
