### PR TITLE
If "bulk" is set on an LSM cursor, avoid logging.

### PR DESCRIPTION
**Pull request by michaelcahill**
refs WT-1922

### CODE REVIEW

**Comment by michaelcahill** [comment]
@agorrod, can you please review?

I'm considering kicking off an MCI build against this branch, does that make sense?

**Comment by agorrod** [comment]
@michaelcahill I'm concerned about the semantic this change introduces. I'm not sure that just turning off logging is enough.

In btree, a bulk load does unlogged writes, but when the cursor is closed a checkpoint is written into the file - so we are sure that the content is stable on disk prior to returning from cursor close.

With this change, we'll do unlogged writes for bulk load cursors but as far as I can tell there is no way to tell that the content is stable on disk when the cursor is closed.

**Comment by michaelcahill** [comment]
@agorrod, I understand your concern.  Can we add code to `__clsm_close` that sets `NEED_SWITCH` and waits for it to be handled?  We could do a full checkpoint of the tree, but that may introduce some handle locking issues that need more thought.

Closing a bulk cursor on a file doesn't actually guarantee that data is stable: we do write the tree from cache but there is no sync in that path, so the file isn't really stable until the next checkpoint...

**Comment by agorrod** [comment]
Sure - I'll take a look at updating the ```__clsm_close``` case to switch the latest chunk. Once I've done that I'll also take a look at the performance of the MongoDB repl13 test to ensure this change fixes the issue.

**Comment by michaelcahill** [comment]
After more discussion, we've decided to try something different here (doing a btree bulk load into the first chunk).

**Comment by michaelcahill** [comment]
#1948 makes this change obsolete, closing.

**Pull request closed without merging**
