### PR TITLE
WT-4470 Minimize testing that requires TESTUTIL_ENABLE_LONG_TESTS

### PR DESCRIPTION
**Pull request by keithbostic**
@lukech, @agorrod, with these changes, I think we're close to getting rid of `TESTUTIL_ENABLE_LONG_TESTS`.

The only remaining uses of `TESTUTIL_ENABLE_LONG_TESTS` are:
```
test/evergreen.yml
test/csuite/time_shift_test.sh
```

@bvpvamsikrishna, I'm not sure what's going on with `time_shift_test.sh`. I can't find any place in the system that runs that shell script, and when I tried to run it, it hung on me.

Most of the commits simply remove checks for `TESTUTIL_ENABLE_LONG_TESTS`, because the tests involved were almost always reasonably fast, there wasn't any point in limiting the tests to "long" runs.

There were two tests I changed in other ways:

* 675b0c8: I increased the run-time of `wt2535_insert_race`, and changed it so the threads were queued behind a gate and didn't start until all of them were ready to run, to avoid them executing serially. This is more of a bug fix than anything else, the test wasn't really doing anything useful.

* 50519a3: I reworked `wt2909_checkpoint_integrity` in a couple of ways, first to reduce the amount of testing done to find a midpoint, and second, to only do a single test run per value near the midpoint. @ddanderson, this probably deserves real review.

### CODE REVIEW

**Comment by ddanderson** [comment]
LGTM.  I mainly looked at changes for `wt2909_checkpoint_integrity`.  I like this change - if a bug in this area appears, we may not catch it quite as fast as running the 'long' version of the original test (doing 3 times at each point), but since we'll be running the test more often as the 'short' version, it should more than even out.

**Comment by agorrod** [comment]
I've switched the PPC Jenkins job to this branch:
http://build.wiredtiger.com:8080/job/wiredtiger-test-unit-ppc/1652/

If the runtime there doesn't change significantly I'm good to go with merging this.

**Comment by lukech** [comment]
@keithbostic Thanks for making the changes to help reducing turnaround time for csuite tests. I'd like to provide some background info for `test/evergreen.yml`:  This file was named `test/mciproject.yml`, and recently I made some updates (including rename the filename) to split csuite tests into separate Evergreen tasks and get `TESTUTIL_ENABLE_LONG_TESTS` set for each applicable test in Evergreen configuration. So, if a decision were made to remove `TESTUTIL_ENABLE_LONG_TESTS` setting for one csuite test, the corresponding line in `test/evergreen.yml` for the same test should be updated (removing the `TESTUTIL_ENABLE_LONG_TESTS` setting).

**Comment by keithbostic** [comment]
@ddanderson, would you please re-review the changes to `wt2909_checkpoint_integrity`? I've made some changes so we shorten the run-time in most cases, but extend the run-time as necessary to ensure the test passes.

**Comment by lukech** [comment]
@keithbostic @agorrod I just pushed a commit to remove the unnecessary TESTUTIL_ENABLE_LONG_TESTS settings for tests/tasks in `test/evergreen.yml` that this PR is touching. Let me know if any comment.

**Comment by lukech** [comment]
I made a Evergreen patch [build](https://evergreen.mongodb.com/build/wiredtiger_ubuntu1404_patch_1a6c5d42ab08da3108ace11e3fcd05164e023206_5c05baa8c9ec440d1badee66_18_12_03_23_22_17) to verify the task turnaround time with changes in this PR, the result is very positive - the longest running `csuite-wt2909-checkpoint-integrity-test` took only 5m 1s to finish.

**Comment by lukech** [comment]
I switched `wiredtiger-test-unit-zseries` job to this feature branch to give us more confidence. http://build.wiredtiger.com:8080/job/wiredtiger-test-unit-zseries/2707/
With the test passed just now, I'm going ahead to merge the changes.

**Pull request merged**
