### PR TITLE
WT-11064 Skip globally visible tombstones as part of update obsolete check

### PR DESCRIPTION
**Pull request by kommiharibabu**
The globally visible tombstones are added to the update chain internally by a prepared transaction rollback and rollback to stable operations. Considering these tombstones as part of the update obsolete check and trimming the update chain can cause problems for the threads that are accessing the updates. To avoid this problem, skip these internally generated globally visible tombstones as part of the update obsolete checks.

Skipping these tombstones can lead to an increase in updates cache usage, but this can be reclaimed when the page gets evicted or any other follow-on update gets globally visible.

### CODE REVIEW

**Review by bvpvamsikrishna — APPROVED** [review]
lgtm

**Review by quchenhao — APPROVED** [review]
lgtm

**Comment by agorrod** [comment]
I'm happy with the shape of this change, but haven't had time to do a full review. Don't wait for me if I'm blocking things.

**Comment by kommiharibabu** [comment]
evergreen merge

**Comment by agorrod** [comment]
The test failure in the PR was WT-11025

**Review by agorrod — APPROVED** [review]

**Pull request merged**
