### PR TITLE
WT-1977 Improve the performance of getting snapshots with many sessions

### PR DESCRIPTION
**Pull request by michaelcahill**

### CODE REVIEW

**Comment by agorrod** [comment]
Thanks @michaelcahill lgtm - should I go ahead and merge?

**Comment by michaelcahill** [comment]
@agorrod yes, please.

**Comment by agorrod** [comment]
@keithbostic Could you take a look through this change please? There was a test failure today (our time) that's possibly related to visibility checks, so I'm doubting my review worthiness..

The test failure was:
http://build.wiredtiger.com:8080/job/wiredtiger-test-format-stress/7663/

**Comment by keithbostic** [comment]
@agorrod, I think I found it and pushed a fix; would you please review 4fe2964?

If you want `WT_BINARY_SEARCH` changed back to using a comparison function/macro, let me know, I can quickly write that loop.

**Pull request merged**
