### PR TITLE
WT-6277 Compatibility tests verify failure in timestamp validation

### PR DESCRIPTION
**Pull request by keithbostic**
@ddanderson, @agorrod, @luke-pearson:

This is a set of changes that appear to fix the 4.2/4.4 upgrade/downgrade issues Luke identified in WT-6277. I've only tested lightly at this point, but it's been working significantly longer than previous test runs.

It's an implementation of Alex's idea: because we can't tell the difference between a 4.2 internal parent cell written with no aggregated time window information and a 4.4 internal parent cell written with default aggregated time window information, whenever we encounter a parent cell with no aggregated time window information, we assert any time information in its children is stable, because that should be true regardless of what release wrote the parent cell.

I'm still testing, but I wanted to give you a heads up in case there's something awful I've missed by taking this approach. I also know this is a lower priority than other tickets, so don't worry if you're not going to get to review soon, there's no rush as far as I know.

Alex, I've made some changes in the time window support, and I  know you care about that. Specifically, commit 1857aa4 changes how aggregated time windows work: the root of the problem is that `WT_TIME_AGGREGATE_IS_EMPTY` was written to return if an aggregated time window matched the `WT_TIME_AGGREGATE_INIT_MAX` state, not the "default" state. I believe we need both behaviors (and we had code that assumed the current is-empty macro behaved differently than it does), so I've tried to make that all work. I also believe I fixed a bug in our original time-window abstraction work in `reconcile/col_var.c`. I don't believe we're aggregating time windows there, I think we're just tracking copies of existing time windows.

Don, this PR changes how format works, to always update the stable timestamp (so checkpoints include recovery timestamp information), and it acquires that information whenever it opens a database and uses it to set `g.timestamp`. I left the code you wrote alone, using `g.timestamp` to set the stable timestamp, but I think that's wrong because I'm pretty sure it can be incremented before operations using it as their commit timestamp have actually been committed, based on my reading of `ops.c:commit_transaction()`. I also think that letting the system stable timestamp lag is probably a better testing scenario than having it be exactly up-to-date. The 73b90d1 commit is probably the only one you care about.

Luke, I think you're the primary reviewer. I'm a little worried about `timestamp.c:__time_stable()`, it seems to me there might be cases where we don't have a recovery timestamp or a stable timestamp, in which case verify might fail. I can't think of one, but I'm not confident of that. The 1857aa4 and 80e7b98 commits are the interesting ones for you, the rest (except for 73b90d1, which is Don's), are uninteresting changes.

### CODE REVIEW

**Comment by luke-pearson** [comment]
Its entirely possible for the user to write timestamped data without writing a stable timestamp, or oldest timestamp. As such we'd get a recovery timestamp of 0 and our aggregated timestamp values would be beyond it. So I think we need to handle if the return from `__time_stable` is 0 then we can't do stable timestamp validation. 

Additionally I think we could lose the checkpoint timestamp information in salvage if we had a corrupt metadata file, resulting in the same scenario where we get a 0 stable / recovery timestamp.

**Comment by keithbostic** [comment]
@luke-pearson 
> As such we'd get a recovery timestamp of 0 and our aggregated timestamp values would be beyond it.

If true, what's our situation moving forward? If we have a recovery timestamp of 0, and start running, what happens to all of the records in the collection that are from some (far distant?) future?

**Comment by luke-pearson** [comment]
> 
> 
> @luke-pearson
> 
> > As such we'd get a recovery timestamp of 0 and our aggregated timestamp values would be beyond it.
> 
> If true, what's our situation moving forward? If we have a recovery timestamp of 0, and start running, what happens to all of the records in the collection that are from some (far distant?) future?

Nothing as we won't run rollback to stable, they just persist as is.

**Comment by keithbostic** [comment]
@luke-pearson 
> Nothing as we won't run rollback to stable, they just persist as is.

Yes; but we report the recovery timestamp to the calling application, at which point it uses that timestamp as the "current" timestamp, and moves forward. That has to go wrong at some point, doesn't it?

**Comment by luke-pearson** [comment]
> 
> 
> @luke-pearson
> 
> > Nothing as we won't run rollback to stable, they just persist as is.
> 
> Yes; but we report the recovery timestamp to the calling application, at which point it uses that timestamp as the "current" timestamp, and moves forward. That has to go wrong at some point, doesn't it?

I think once the application is writing timestamped data without a stable or oldest its already gone "wrong". So, yes? However our API doesn't prevent you from doing that.

**Comment by keithbostic** [comment]
> I think once the application is writing timestamped data without a stable or oldest its already gone "wrong". So, yes? However our API doesn't prevent you from doing that.

I don't see how that is possibly OK.

We could panic and refuse to go further, but loading with time window information in advance of our stable timestamp seems wrong. We either need to shut down immediately, or use the base-version information (which is presumably moving forward?), to somehow get around the problem. I have no idea what the right solution is, I don't know what resources we have. Ideas?

@bvpvamsikrishna?

**Comment by keithbostic** [comment]
@luke-pearson, I got 100 upgrade/downgrade cycles last night, so I believe this branch works.

**Comment by keithbostic** [comment]
@lukech, I wanted to call out this branch to you: if/when we merge it, it will require a simultaneous merge of a new test format program into the mongodb-4.2 branch.

**Comment by bvpvamsikrishna** [comment]
> > I think once the application is writing timestamped data without a stable or oldest its already gone "wrong". So, yes? However our API doesn't prevent you from doing that.
> 
> I don't see how that is possibly OK.
> 
> We could panic and refuse to go further, but loading with time window information in advance of our stable timestamp seems wrong. We either need to shut down immediately, or use the base-version information (which is presumably moving forward?), to somehow get around the problem. I have no idea what the right solution is, I don't know what resources we have. Ideas?
> 
> @bvpvamsikrishna?

My opinion is if the stable timestamp is zero, we need to rollback all the timestamped data. My understanding of WiredTiger guarantee is "no timestamped data greater than the last checkpoint data exists on recovery" so applications can continue the timestamps from last checkpoint timestamp.

Maybe all this confusion is we are using '0' for both "the minimum timestamp" and also as "invalid timestamp". Should we start using '-1' as invalid timestamp?

**Comment by agorrod** [comment]
> My opinion is if the stable timestamp is zero, we need to rollback all the timestamped data. My understanding of WiredTiger guarantee is "no timestamped data greater than the last checkpoint data exists on recovery" so applications can continue the timestamps from last checkpoint timestamp.

I'm pretty much in alignment here. If a user is using timestamps, but hasn't set a stable timestamp, that implies that they don't want to keep any data persistently. Rollback should remove it.

We've tried to make it harder to have a 0 timestamp recently, but run into startup ordering problems which mean we backed off for now. I think this problem will be mitigated from an API point of view in the near future.

> Maybe all this confusion is we are using '0' for both "the minimum timestamp" and also as "invalid timestamp". Should we start using '-1' as invalid timestamp?

Unfortunately that ship has sailed. The reason we have the current scheme is that originally the timestamp format was completely agnostic, and we expected it would change with multi-document transactions (it didn't). We never reserved 0 as an out-of-band value, since we didn't want to put a constraint on the external time system to avoid using an explicit out of band value and ensuring that the one we chose sorted lower than all other values.

**Comment by keithbostic** [comment]
Thanks, @bvpvamsikrishna, @agorrod. If the answer is that rollback will discard all of the data, then I believe the current verification code will do the right thing.

**Comment by luke-pearson** [comment]
I'm not sure this is the correct location to point this out however, rollback to stable makes the decision to not do anything unless we have a stable timestamp:
https://github.com/wiredtiger/wiredtiger/blob/93771eb20246b8d810b2ab004d83e4e2378f76ad/src/txn/txn_rollback_to_stable.c#L990
And recovery won't run rollback to stable if the recovery timestamp is zero.
https://github.com/wiredtiger/wiredtiger/blob/93771eb20246b8d810b2ab004d83e4e2378f76ad/src/txn/txn_recover.c#L781

I'm not trying to debate whether it makes sense to have timestamps that are non zero with no stable timestamp as I certainly agree that it doesn't make sense but the expectation is that rollback will discard the data which currently isn't true.

**Comment by keithbostic** [comment]
@luke-pearson, @ddanderson, @agorrod: I've rebased the `WT-6277 Compatibility tests verify failure in timestamp validation` PR against `rts-test-format` and merged it, it should be ready for real review.

It still needs to pass PR testing, and I'll run separate tests to confirm the branch still fixes the problems Luke and I saw. I'll push any additional changes required by those results, of course.

If you're the wrong person to review the specific code called out in the initial PR request, please let me know and I'll find someone else.

@lukech: As mentioned previously, merging this into any branch that runs the `compatibility_test_for_releases.sh` test requires updating the `mongodb-4.2` branch with a copy of the format program from this branch. I can push that branch any time you want, this branch has the changes necessary to backport format into `mongodb-4.2`, it should be a drop-in replacement.

**Comment by keithbostic** [comment]
evergreen retry

**Comment by keithbostic** [comment]
evergreen retry

**Comment by agorrod** [comment]
@luke-pearson sorry I sat on your question about how to handle unusual timestamp configurations. Would you mind moving it to the JIRA ticket - that feels like a better place to have the conversation.
In fact - maybe a new JIRA ticket? It would be nice to have a ticket that is all about how we handle global timestamp configurations with recovery and rollback to stable.

**Comment by lukech** [comment]
@keithbostic thanks for bringing up the 4.2 backporting dependency topic. I've requested v4.2 backport in Jira and approved it. Though the usual practice is to merge a change to develop firstly before backporting to stable branches, this case is a bit special that we could probably make an exception of merging to  `mongodb-4.2` and `rts-test-format` (nearly) at the same time.

**Comment by agorrod** [comment]
@luke-pearson could we get this merged, and resolve the question(s) about general timestamp usage later?

**Comment by luke-pearson** [comment]
I've spent a fair bit of time looking at this change, and aside from my concerns about the stable timestamp / rollback to stable issue it looks good to me.

**Comment by luke-pearson** [comment]
The follow on ticket to discuss time stamping API issues is: WT-6481

**Comment by tammybailey** [comment]
Hi @keithbostic! Is this ticket ready to merge? Are we waiting on @agorrod ?

**Comment by keithbostic** [comment]
@tammybailey, I don't know, it's been 6 weeks since I even looked at this ticket.

I thought 4.2/4.4 upgrade/downgrade fixes were supposed to make it into the final release and that was part of the point of the rts-test-format branch? In short, I have no idea what's the plan for these changes.

**Comment by keithbostic** [comment]
@tammybailey, realized I may have misunderstood your question: if you're asking if the fix is still appropriate and makes sense, I guess it does? I don't know of any reason we'd have changed our minds on this approach. Maybe it needs another round of review and approval at this point?

**Comment by tammybailey** [comment]
Oh, I overlooked that this was a feature branch merge. We just saw this failure on Evergreen develop today and thought to check back on the status. Let's see what Alex thinks.

While I'm here, a link to the Evergreen failure:
https://evergreen.mongodb.com/task/wiredtiger_compatibility_tests_compatibility_test_for_releases_f0365a5e6013050f204901ee4ba394385c1789cd_20_07_23_13_47_58

**Comment by agorrod** [comment]
@keithbostic please go ahead and merge this into the feature branch.

**Pull request merged**
