### PR TITLE
WT-11849 Remove obsolete skipTest calls in Python tests

### PR DESCRIPTION
**Pull request by etienneptl**

### CODE REVIEW

**Review by ajmorton — COMMENTED** [review]
@etienneptl are we removing these `skipTest`s because the tests still run when they're deleted?
[This commit](https://github.com/wiredtiger/wiredtiger/pull/7496/commits/c77879d45c21ec148bf31fa45faf40afb731f654#diff-aeac17c846a949276ffd5f1cdc643655dfcb6ae192c0482406bacf29e166204f) implies they (used to?) drop core in diagnostic mode.

**Comment by etienneptl** [comment]
> @etienneptl are we removing these `skipTest`s because the tests still run when they're deleted?

Yes, exactly. The code may have changed since then or we never produced cores in those scenarios and it was an error from the beginning.

**Review by ajmorton — APPROVED** [review]
LGTM. To be safe I've updated the PR tests to run more of our python testing in unusual configurations

**Comment by etienneptl** [comment]
evergreen merge

**Pull request merged**
