### PR TITLE
WT-3894 Timestamp queue statistics and usage

### PR DESCRIPTION
**Pull request by lukech**

### CODE REVIEW

**Comment by lukech** [comment]
There's fallout from the initial merge of #4214. Assertion failure during transaction rollback. http://build.wiredtiger.com:8080/job/wiredtiger-test-format-stress-sanitizer/21206/

@sueloverso I recreated this PR based on the old `wt-3894-ts-queues` branch for further work.

**Comment by sueloverso** [comment]
Thank you @lukech I will investigate this.

**Comment by sueloverso** [comment]
@michaelcahill and @agorrod the failure is now fixed. It has run a bunch of iterations of the failing CONFIG successfully. Basically readers needed to walk the `read_timestamp` queue to find a non-cleared txn. I missed the cases originally.

**Comment by agorrod** [comment]
I've switched the Jenkins stress sanitizer job over to run here:
http://build.wiredtiger.com:8080/job/wiredtiger-test-format-stress-sanitizer/

**Comment by agorrod** [comment]
@sueloverso stress testing is looking good on this branch now. I'm happy for it to be merged, but am happy to wait until next week.

**Pull request merged**
