### PR TITLE
WT-4592 OS X build platform doesn't support timer_create() and timer_settime().

### PR DESCRIPTION
**Pull request by keithbostic**
@lukech, would you please confirm this branch works on Evergreen's OS X platform? -- Thanks!

### CODE REVIEW

**Comment by lukech** [comment]
Here is the Evergreen patch build: https://evergreen.mongodb.com/version/5c69fe593627e022a7b83f60
The original compilation errors disappeared, but a new error popped up complaining about unused function `on_alarm`:
> [2019/02/18 14:10:39.814] ../../../test/format/ops.c:73:1: error: unused function 'on_alarm' [-Werror,-Wunused-function]
> [2019/02/18 14:10:39.814] on_alarm(int signo)
> [2019/02/18 14:10:39.814] ^
> [2019/02/18 14:10:39.820] 1 error generated.
> [2019/02/18 14:10:39.820] make[2]: *** [ops.o] Error 1
> [2019/02/18 14:10:39.820] make[2]: *** Waiting for unfinished jobs....

**Comment by keithbostic** [comment]
> The original compilation errors disappeared, but a new error popped up complaining about unused function `on_alarm`.

Thanks, @lukech. I think this will be fixed by merging the current develop branch (which I've just done). Can we test again, please?

**Comment by lukech** [comment]
@keithbostic I created another patch build, and it passed the OS X compile task this time. Will waiting for the remaining tasks (for regression test) to finish before merging. 
https://evergreen.mongodb.com/version/5c6b2f2761837d2cbf9eb990

**Comment by lukech** [comment]
All tasks passed in the patch build. Will merge.

**Pull request merged**
