### PR TITLE
WT-5135 v4.0 backport

### PR DESCRIPTION
**Pull request by jeremytay90**
(cherry picked from commit a68760eb307a0dd7ccd6bef41c37fbd99d35c433)

### CODE REVIEW

**Comment by jeremytay90** [comment]
retest this please

**Comment by jeremytay90** [comment]
`test_rebalance` failing is a known issue in this case. See https://jira.mongodb.org/browse/WT-5325.

**Comment by luke-pearson** [comment]
Holding off on this set of backports until WT-5325 is fixed.

**Comment by lukech** [comment]
WT-5145 was reverted on the `mongodb-4.0` branch. @jeremytay90 can you merge the branch and retest to see if that helps with addressing the test failures you had?

**Comment by jeremytay90** [comment]
retest this please

**Pull request merged**
