### PR TITLE
WT-5215 Add basic randomized test for doing incremental backups. (#5297) (v4.2 backport)

### PR DESCRIPTION
**Pull request by raviprakashgiri29**
Cherry-picked from f188ed87859121bd1fb9d2031e9ee9670356f118

### CODE REVIEW

**Comment by ddanderson** [comment]
@raviprakashgiri29, you will need to apply this commit as well to fix the build error: https://github.com/wiredtiger/wiredtiger/commit/9d41c1f4430157a0d6dc00c4b24e287a6870cdf6
After I committed (merged?) WT-5215, I found that that WT-5700 was needed to fix the build failure.  Sorry, I should have linked the tickets.  It's just a new file  (`test/csuite/incr_backup/smoke.sh`) - I think you can just cherry pick that commit in this branch.

**Comment by raviprakashgiri29** [comment]
> @raviprakashgiri29, you will need to apply this commit as well to fix the build error: [9d41c1f](https://github.com/wiredtiger/wiredtiger/commit/9d41c1f4430157a0d6dc00c4b24e287a6870cdf6)
> After I committed (merged?) WT-5215, I found that that WT-5700 was needed to fix the build failure. Sorry, I should have linked the tickets. It's just a new file (`test/csuite/incr_backup/smoke.sh`) - I think you can just cherry pick that commit in this branch.

@ddanderson : I cherry picked the changes from WT-5215 & WT-5700, but test_incr_backup fails with the below error.

```
Checkpoint 7
--
**** FAILURE
To reproduce, please rerun with: test_incr_backup -S 2581037906978772509
test_incr_backup: FAILED: key_value/180: item->size > value_size
process aborting
Aborted (core dumped)
FAIL incr_backup/smoke.sh (exit status: 134)
```

**Comment by ddanderson** [comment]
Ravi, it looks like you need `eea1ed346f` as well.  That would be WT-5753.   If you go to `test/csuite/incr_backup` in the current `develop` tree, and do `git log .`, you'll see the set of changes that were made to the incremental backup test as we debugged and refined it.  I think you'd want to apply pretty much all of them (or all but the last)?  I think Sue just created a backport ticket for WT-5697 (the last commit), so you can either do that separately or together with this one.  I think we pretty much want to get the `test/csuite/incr_backup` directory copied from `develop` back to 4.2.

**Comment by raviprakashgiri29** [comment]
> @raviprakashgiri29, it looks like you need `eea1ed346f` as well. That would be WT-5753. If you go to `test/csuite/incr_backup` in the current `develop` tree, and do `git log .`, you'll see the set of changes that were made to the incremental backup test as we debugged and refined it. I think you'd want to apply pretty much all of them (or all but the last)? I think Sue just created a backport ticket for WT-5697 (the last commit), so you can either do that separately or together with this one. I think we pretty much want to get the `test/csuite/incr_backup` directory copied from `develop` back to 4.2.

Thank you @ddanderson . Backporting WT-5753 changes fixed the issue. I will check WT-5697 ticket and do it separately.

**Pull request merged**
