### PR TITLE
WT-11710 No space left on ubuntu2004

### PR DESCRIPTION
**Pull request by bzm-jas**
Moving tests that are failing with"no space error" to a larger instance since it prevents the disk from running out of space while still maintaining code coverage.

### CODE REVIEW

**Review by jiechenbo — APPROVED** [review]
LGTM! No need to open up a draft PR, the changes seem quite ready and reasonable to me.

**Comment by jeremythorp** [comment]
Hi Jasmine, the changes to evergreen.yml look good to me! My only suggestion would be to also add your config as a new file in the test/format/failure_configs directory.

**Comment by bzm-jas** [comment]
> Hi Jasmine, the changes to evergreen.yml look good to me! My only suggestion would be to also add your config as a new file in the test/format/failure_configs directory.

sounds good, failure config has been added here: [1dcf4a2](https://github.com/wiredtiger/wiredtiger/pull/10362/commits/1dcf4a20af47d2eca73d48ad5b2ac18eee020796) :)

**Comment by jeremythorp** [comment]
> > Hi Jasmine, the changes to evergreen.yml look good to me! My only suggestion would be to also add your config as a new file in the test/format/failure_configs directory.
> 
> sounds good, failure config has been added here: [ba37e69](https://github.com/wiredtiger/wiredtiger/pull/10362/commits/ba37e690b35cbb2a8b49fbe934b0620dace99b94) :)

Thank you!

**Review by jeremythorp — APPROVED** [review]
Nice - LGTM!

**Review by clarissecheah — APPROVED** [review]
LGTM!

**Pull request merged**
