### PR TITLE
WT-12202 Use macros to replace split magic numbers

### PR DESCRIPTION
**Pull request by y123456yz**
internal splite marcros perfect

### CODE REVIEW

**Comment by y123456yz** [comment]
WT-12202

**Comment by kommiharibabu** [comment]
@y123456yz Thanks for the PR. The code changes are fine. There is something wrong with some of your PRs, as the commit history contains many unnecessary commits. Can you fix them to have a better commit history for the PR?

**Comment by y123456yz** [comment]
@kommiharibabu 
I have solve the Irrelevant comment， please review again, thanks.

**Review by kommiharibabu — APPROVED** [review]
LGTM. Thanks.

**Comment by kommiharibabu** [comment]
evergreen merge

**Pull request merged**
