### PR TITLE
[WT-7709] Unused variable tmp in rec_upd_select

### PR DESCRIPTION
**Pull request by anshans**
Removed variable and __wt_scr_free() function call

### CODE REVIEW

**Comment by lukech** [comment]
autobuild: Can one of the admins verify this patch?

**Comment by mm-ng** [comment]
Hey @anshans , thanks for submitting this patch! This is mostly looking good, although I believe we do need a new line after the end of the function.

**Comment by etienneptl** [comment]
@mm-ng, this PR can probably be closed as the issue has been fixed in 7357.

**Comment by mm-ng** [comment]
@etienneptl Thanks for the heads up! I will close this now.

**Pull request closed without merging**
