### PR TITLE
WT-5131 Fix Evergreen configuration file to use working directory

### PR DESCRIPTION
**Pull request by bsamek**

### CODE REVIEW

**Comment by wtbuild** [comment]
autobuild: Can one of the admins verify this patch?

**Comment by agorrod** [comment]
autobuild: test this please

**Comment by agorrod** [comment]
Thanks @bsamek - the change looks useful to me. I've setup the PR so we can get it in.

@lukech please review and merge if you are happy with the change.

**Comment by lukech** [comment]
This PR was branched out from `master` - redo the same changes in #4885 against `develop` branch. Closing this PR.

**Pull request closed without merging**
