### PR TITLE
WT-2900 scons gcc flags collide with ARM8 CRC32 implementation

### PR DESCRIPTION
**Pull request by keithbostic**
Ready for review/merge.

### CODE REVIEW

**Comment by keithbostic** [comment]
autobuild: retest this please

**Comment by keithbostic** [comment]
@agorrod, these changes allow WiredTiger to build standalone on Ubuntu ARM8, with gcc 5.4.0.

Ready for review/merge.

**Comment by agorrod** [comment]
Thanks @keithbostic lgtm.

**Comment by lidi81** [comment]
I encount the same problem when I build r3.4.0-rc3 on centos7 ARM8 with gcc 5.4.0
Here's the error information:
Compiling build/opt/third_party/wiredtiger/src/btree/row_modify.o
Compiling build/opt/third_party/wiredtiger/src/btree/row_srch.o
Compiling build/opt/third_party/wiredtiger/src/cache/cache_las.o
Compiling build/opt/third_party/wiredtiger/src/checksum/arm64/crc32-arm64.o
Compiling build/opt/third_party/wiredtiger/src/checksum/software/checksum.o
Compiling build/opt/third_party/wiredtiger/src/config/config.o
Compiling build/opt/third_party/wiredtiger/src/config/config_api.o
/tmp/ccu0HlDB.s: Assembler messages:
/tmp/ccu0HlDB.s:34: Error: selected processor does not support `crc32cb w2,w2,w3'
/tmp/ccu0HlDB.s:60: Error: selected processor does not support `crc32cx w2,w2,x4'
/tmp/ccu0HlDB.s:81: Error: selected processor does not support `crc32cb w2,w2,w3'
scons: *** [build/opt/third_party/wiredtiger/src/checksum/arm64/crc32-arm64.o] Error 1
Compiling build/opt/third_party/wiredtiger/src/config/config_check.o
scons: building terminated because of errors.
build/opt/third_party/wiredtiger/src/checksum/arm64/crc32-arm64.o failed: Error 1

**Pull request merged**
