### PR TITLE
WT-3579 workgen: add support for more options in wtperf.py

### PR DESCRIPTION
**Pull request by ddanderson**
Not ready for merge, need to do more testing.

### CODE REVIEW

**Comment by agorrod** [comment]
@ddanderson Is this ready for a review now? I'm happy to get it merged in and have follow up work in a separate branch.

**Comment by ddanderson** [comment]
@agorrod, I'm fixing a few problems found in testing it against wtperf runners.  I think I can wrap it up today.  Thanks!

**Comment by ddanderson** [comment]
@agorrod, this is ready for review.

With these changes we can run to completion (without failures) 27 of the 37 wtperf runner files that are used in Jenkins scripts.  The 10 remaining, that we cannot yet do are: checkpoint-stress, update-checkpoint-{btree,lsm}, update-delta-mix{1,2,3}, update-{grow, shrink}-stress, btree-split-stress, shared-cache-stress.  That's because we don't yet support these wtperf options: checkpoint_interval, checkpoint_threads, value_sz_min, value_sz_max, update_delta, read_range, database_count.

Now with the ones we can run, I still need to compare results from workgen vs. wtperf.  I already know of some anomalies, I can open a separate ticket.

**Comment by agorrod** [comment]
Thanks @ddanderson this change looks good to me. Adding pareto support is a great enhancement in particular.

@michaelcahill would you like to review as well?

**Pull request merged**
