### PR TITLE
WT-9966 Switch toolchain to v4 for WT hang analyzer

### PR DESCRIPTION
**Pull request by lukech**
This change was split from SERVER-62995 as it touches a source file in the wiredtiger repository.

The plan is to merge this PR after SERVER-62995 is merged, and then vendor this change to mongo master via the daily WT release task.

### CODE REVIEW

**Comment by lukech** [comment]
Converting this PR to draft, waiting for [SERVER-62995](https://jira.mongodb.org/browse/SERVER-62995) to merge (which takes time).

**Comment by lukech** [comment]
As SERVER-62995 has been merged, I'm moving this PR out of "draft" (it's ready for review). 
@mickgraham-mongodb mind having a quick check?

**Review by mickgraham-mongodb — APPROVED** [review]
LGTM

**Comment by lukech** [comment]
evergreen merge

**Pull request merged**
