### PR TITLE
WT-7109 Retain no longer supported configuration options for backward compatibility

### PR DESCRIPTION
**Pull request by kommiharibabu**
The removed options that exist as part of metadata of older versions.
using these older configuration string with newer versions can lead to
problems. To avoid unnecessary failures, parse the removed options and
ignore them.

### CODE REVIEW

**Review by agorrod — COMMENTED** [review]
@kommiharibabu this change covers the cases I'm aware of. Now that you know what triggers the failure mode, do you think you could enhance https://github.com/wiredtiger/wiredtiger/blob/develop/test/evergreen/compatibility_test_for_releases.sh to cover this case?

**Comment by kommiharibabu** [comment]
@agorrod Yes it is good to have a test to uncover this scenario much earlier. Using `wt` utility to dump/load objects can cover this scenario. I will add `wt` utility alongside with `format` to the compatibility test.

**Comment by kommiharibabu** [comment]
@agorrod I added a `wt` dump and load test with older version database using the newer version `wt`. I found that `wt` dump is ignoring the removed configuration options as part of the dump. It removed `huffman_key` but missed to remove `assert` configuration items and lead to the error. I add that change to the PR.

I will try to find any another way to dump the `huffman_key` also by the release train. If not will go with the existing test as I already verified manually by editing the dump file with `huffman_key` and it works.

**Comment by kommiharibabu** [comment]
The newly added compatibility test is failing while dump/load the 4.2 database files with 4.4 binary due to the current fix not available in that branch.

**Review by tetsuo-cpp — APPROVED** [review]
LGTM.

**Comment by kommiharibabu** [comment]
@quchenhao The test added as part of the PR fails until this change merged into 4.4 branch. Do you want to remove this test as part of this ticket and add it back once this PR is merged into 4.4? Or If you planning to sync `develop` and `4.4` sooner, I can leave it in this PR itself.

**Comment by kommiharibabu** [comment]
I removed the test in this PR and add it back once this change is merged into 4.4 branch.

**Pull request merged**
