### PR TITLE
Generated tables for config subcategories are qualified by referencing method name.

### PR DESCRIPTION
**Pull request by ddanderson**
Refs #1879.

### CODE REVIEW

**Comment by ddanderson** [comment]
@michaelcahill, can you review?

**Comment by keithbostic** [comment]
@ddanderson, I assume this means we don't "share" config subcategories when they're the same?

I was thinking about a similar approach, but wasn't sure what to do about sharing; that said, maybe we just don't care, sharing isn't common enough to worry about?

**Comment by sueloverso** [comment]
I think if we want to share subcategories, they'd have to be extracted out to a single entity and then referenced in the things that want to use them.  That is the only way to know they're the same.  Do we have support to do that?  Having to specify each, in its entirety more than once is asking for a problem if they're supposed to be the same.

**Comment by ddanderson** [comment]
@keithbostic, what is the purpose of sharing? Is there a behavioral difference beyond what I implemented (or is it compactness)?  Aren't all the generated tables readonly?

**Comment by keithbostic** [comment]
@ddanderson, yeah, I think you're correct -- it's not worth sharing.

**Comment by michaelcahill** [comment]
Thanks, @ddanderson -- lgtm, I'll merge.

**Pull request merged**
