### PR TITLE
WT-11559 Align background compaction terminology

### PR DESCRIPTION
**Pull request by etienneptl**

### CODE REVIEW

**Comment by Sean04** [comment]
`__wt_compact_server_create` -> `__wt_background_compact_server_create` to align with the updated `__background_compact_server` name. Long names I know, but let's keep it consistent.
Same for:
`__wt_compact_server_destroy`
`__wt_compact_signal`

**Comment by etienneptl** [comment]
> `__wt_compact_server_create` -> `__wt_background_compact_server_create` to align with the updated `__background_compact_server` name. Long names I know, but let's keep it consistent. Same for: `__wt_compact_server_destroy` `__wt_compact_signal`

Thanks, good catch. Updated in 9707deb1c88a5516b4033745be568656e163fa35.

**Review by Sean04 — APPROVED** [review]
LGTM

**Comment by etienneptl** [comment]
evergreen merge

**Pull request merged**
