### PR TITLE
WT-4465 Add documentation for a dhandle's lifecycle

### PR DESCRIPTION
**Pull request by sulabhM**

### CODE REVIEW

**Comment by sulabhM** [comment]
The added documentation looks as follows:

dhandle-life
index

**Comment by sulabhM** [comment]
@sueloverso , feel free to edit the document directly if you think it might be easier than the review back and forth.

**Comment by sueloverso** [comment]
@sulabhM I edited the document as that was much easier than typing in my suggested edits anyway. (The diff looks larger because I reformatted the source lines to fit in 80 characters after my changes.) Give it a read.

**Comment by sulabhM** [comment]
Thanks @sueloverso , this looks much better now. I am going to merge it.

**Pull request merged**
