### PR TITLE
WT-7549 change identifiers in block manager to use "objects"

### PR DESCRIPTION
**Pull request by ddanderson**
Identifier change: log_structured -> has_objects
Identifier change: lfh -> ofh
Remove block_allocation=log-structured config.
Changed tests that used log-structured to use tiered tables.
Changed "wt list" from looking at log-structured config to looking at
  "tiered:" uri to decide if the block manager has objects.

### CODE REVIEW

**Comment by ddanderson** [comment]
@keitharnoldsmith and @sueloverso, please review the latest changes.  Note: this PR is a replacement for #6575 (that you reviewed previously, and has been reverted).   The commits up until the last one are identical to #6575.  The final commit in this PR fixes the problem with #6575.

#6575 failed because I changed `test_tiered02.py` to not use log-structured, but use `table:` with tiering.  That "worked" for me (at least it didn't fail) because tiered cursors didn't do the right thing before.  Once @keitharnoldsmith merged WT-7440, `tiered:` cursors are much closer to working, but they need a btree attached to the dhandle, and some other things that are teed up in WT-7514.  So the "new" test_tiered02 changes, that tries to use real tiered cursors, now fails.

I've backed off the test to use `"file:"` instead, that does an end run around the tiered code.  I also left a TODO to follow up (that should be part of WT-7514).

**Review by sueloverso — APPROVED** [review]
LGTM

**Review by keitharnoldsmith — APPROVED** [review]
LGTM!

**Comment by ddanderson** [comment]
evergreen retry

**Pull request merged**
