### PR TITLE
WT-3049 Backport test format

### PR DESCRIPTION
**Pull request by daveh86**
Not ready for review.

### CODE REVIEW

**Comment by daveh86** [comment]
retest this please

**Comment by daveh86** [comment]
retest this please

**Comment by daveh86** [comment]
retest this please

**Comment by daveh86** [comment]
retest this please

**Comment by daveh86** [comment]
retest this please

**Comment by daveh86** [comment]
retest this please

**Comment by daveh86** [comment]
retest this please

**Comment by daveh86** [comment]
@agorrod, would you mind taking a look at this. It was something @michaelcahill  suggested I backport.

**Comment by agorrod** [comment]
I'm happy for test/format to be back-ported. Could you create a JIRA ticket, and add some context about why we are doing the work.

**Comment by daveh86** [comment]
I've raised a new ticket and updated the pull request to match.

**Comment by michaelcahill** [comment]
Thanks @daveh86, I've compared against `test/format` in `develop` and this lgtm.  I'll merge.

**Pull request merged**
