### PR TITLE
WT-8477 Enforce the use of Pymongo 3.12.2 in our Evergreen tests (v5.0 backport). (#7254)

### PR DESCRIPTION
**Pull request by Siddhartha8899**
(cherry picked from commit e57066854acb98f999ed78c7a69c2e999b8268b5)

### CODE REVIEW

**Comment by etienneptl** [comment]
@lukech , do we need this PR as we don't synchronize `5.0` with `develop`?

**Review by etienneptl — APPROVED** [review]
LGTM

**Comment by lukech** [comment]
@etienneptl yes I think we need this backport. The [mongodb-5.0 waterfall page](https://evergreen.mongodb.com/waterfall/wiredtiger-mongo-v5.0) shows those perf jobs failed on the latest commit build.

**Review by lukech — APPROVED** [review]
LGTM. It would be nice to indicate it's a "5.0 backport" on the PR title (not needed for the commit message though).

**Pull request merged**
