### PR TITLE
WT-10974 Typo in wt_cmp_dir script

### PR DESCRIPTION
**Pull request by etienneptl**

### CODE REVIEW

**Review by ddanderson — APPROVED** [review]
LGTM!  @etienneptl Thanks for catching this. When I tried version cursors before I didn't get them to work, it's worth another try.

**Comment by etienneptl** [comment]
> LGTM! @etienneptl Thanks for catching this. When I tried version cursors before I didn't get them to work, it's worth another try.

Hi @ddanderson, what is the easiest way to test version cursors, is there an existing test?

**Comment by etienneptl** [comment]
@ddanderson, I may have reproduced the bug you were having as well and created WT-10980 to fix it.

**Comment by ddanderson** [comment]
Thanks, @etienneptl!

**Pull request merged**
