### PR TITLE
SERVER-20303 Require a minimum item count for in-memory splits.

### PR DESCRIPTION
**Pull request by michaelcahill**
I'm concerned that the first version of this change could split if a single large item is appended to a page.  This version reduces the required count, but only splits if we hit the count *and* the size condition.  

Further, it makes it more explicit that we are sampling by looking at level 2 in the tree.

### CODE REVIEW

**Comment by michaelcahill** [comment]
@keithbostic, I was concerned that the changes in #2233 would split if a single large entry was appended to a page.  I think this version also makes it clearer what is going on by scanning level 2 of the list.  Can you please review?

**Comment by michaelcahill** [comment]
autobuild: retest this please

**Comment by keithbostic** [comment]
@michaelcahill, lgtm, I'll merge it in.

**Comment by agorrod** [comment]
This was back ported to MongoDB 3.0.8

**Pull request merged**
