### PR TITLE
WT-10002 Support Doxygen version 1.9.5

### PR DESCRIPTION
**Pull request by lukech**
Fix a few s_all warnings generated on macOS v12.6:

-  A few deprecated config tag warnings running Doxygen v1.9.5 (default version on macOS v12.6)
-  Complaint about missing `~/.evergreen.yml` config file while running "evergreen validate" command.

The upgrade of the Doxygen config file (src/docs/Doxyfile.9) to v1.9.5 caused quite some "Unexpected token TK_HTMLTAG" errors in some of the .dox files. The solution is to replace the \<code> \</code> HTML tags with "\c".

Please note there's a [known issue](https://github.com/doxygen/doxygen/issues/9552) introduced in Doxygen 1.9.5 that incorrectly reports missing arguments for typedef functions. It causes the below error when running "dist/s_docs":
```
/Users/lchen/workspace/wiredtiger-changes/src/include/wiredtiger.in:4006: error: WT_COLLATOR::compare has @param documentation sections but no arguments (warning treated as error, aborting now)
```
The fix for the Doxygen issue will be included in the newer version 1.9.6.

### CODE REVIEW

**Comment by kommiharibabu** [comment]
@lukech I am getting a different error on my mac by running ./s_all.

```
haribabukommi@M-VX405JJ904 dist % ./s_all
dist/s_all run started...
Updating files that include the package version
sed: navtree.js: No such file or directory
./s_docs: line 125: ../docs/pages.html: No such file or directory
####################### MESSAGE ############################
s_all run of: "./s_docs" resulted in:
    /Users/haribabukommi/work/code/wiredtiger/src/include/wiredtiger.in:4006: error: WT_COLLATOR::compare has @param documentation sections but no arguments (warning treated as error, aborting now)
#######################
dist/s_all run finished
haribabukommi@M-VX405JJ904 dist % 
```

**Comment by kommiharibabu** [comment]
@lukech sorry I missed your commit message. Other than that error, everything is fine. Thanks.

**Review by kommiharibabu — APPROVED** [review]
LGTM

**Comment by korteland** [comment]
One high-level question before digging into the code - is this backwards compatible with the various 1.8 releases we also support?

**Review by korteland — COMMENTED** [review]
Another question, sorry. Why are only some files converted from HTML-style tags to `\c`? For example, I can see that `src/docs/verbose-messaging.dox` still has some HTML-style tags.

**Comment by lukech** [comment]
@kommiharibabu I'm yet able to repro the below issue on my laptop (macOS v12.6, Doxygen v1.9.5). I'll give it another try on my Linux workstation.
```
sed: navtree.js: No such file or directory
./s_docs: line 125: ../docs/pages.html: No such file or directory
```
And the below error is a bit annoying. I did not find a way to work around it. But it won't fail `s_all` and the next version of Doxygen will include the fix.
```
####################### MESSAGE ############################
s_all run of: "./s_docs" resulted in:
    /Users/haribabukommi/work/code/wiredtiger/src/include/wiredtiger.in:4006: error: WT_COLLATOR::compare has @param documentation sections but no arguments (warning treated as error, aborting now)
#######################
```

**Comment by lukech** [comment]
@korteland 

> One high-level question before digging into the code - is this backwards compatible with the various 1.8 releases we also support?

As far as I know, 1.8.17 is the only 1.8.x version we supported in the past, likely because it's the default version for Ubuntu 18.04 - the build hosts we used to adopt. We can consider supporting other 1.8.x versions if there's enough interest and it can be covered in a separate ticket.

For 1.9.x versions a [different Doxygen config file](https://github.com/wiredtiger/wiredtiger/blob/0dd3dbbf1bcef5cc67e303803f05cea601c6ac5d/dist/s_docs#L213-L214) is used (compared to 1.8.17), and this PR only touches the 1.9.x config file. 

> Another question, sorry. Why are only some files converted from HTML-style tags to \c? For example, I can see that src/docs/verbose-messaging.dox still has some HTML-style tags.

Thanks for asking, I should have described it earlier on in the PR description. It seems the newer version of Doxygen (1.9.5) only hates the "<code></code>" HTML tag but not other tags. My strategy was to have the minimal changes needed to get the s_docs check pass and verified the effect by opening the render HTML files to visually spot no difference. I did try to look through Doxygen [changelog](https://www.doxygen.nl/manual/changelog.html) but did not seem any obvious mention about  "<code></code>" HTML tag.

**Review by korteland — APPROVED** [review]
Cool, thanks for answering those questions. Code changes LGTM!

**Comment by lukech** [comment]
evergreen merge

**Comment by lukech** [comment]
evergreen merge

**Comment by lukech** [comment]
evergreen merge

**Pull request merged**
