### PR TITLE
Add insertion-sort to sort snapshots

### PR DESCRIPTION
**Pull request by keithbostic**
@michaelcahill, we're spending cycles calling qsort() on typically small numbers of items, so I inlined the case where we have 2 items (wtperf's common case), and less than 11 items. A good implementation of qsort will simply do an insertion sort on small numbers of items anyway, but that still requires the qsort setup and then repeated calls to the qsort callback function.

### CODE REVIEW

**Comment by sueloverso** [comment]
@keithbostic is this also a problem in `conn_api.c:__log_wrlsn_server`?  That also calls qsort and the maximum size of the array it is sorting is 16 and probably less (i.e. SLOT_POOL).  Would that code also benefit from these changes?

**Comment by keithbostic** [comment]
If you're only sorting 16 items at the most, yeah, I'd drop qsort in favor of something faster/simpler. The BSD qsort looks like it falls back to an insertion sort at 7 items ([here's the source](http://www.opensource.apple.com/source/Libc/Libc-997.90.3/stdlib/FreeBSD/qsort.c)), and when you consider qsort setup, and the additional function calls required to do comparisons, doubling that doesn't seem unreasonable.

**Comment by keithbostic** [comment]
JIRA reference: WT-1902.

**Comment by michaelcahill** [comment]
Thanks, @keithbostic -- lgtm.  Merged.

**Pull request merged**
