### PR TITLE
WT-6922 Add random consolidate testing to incr_backup. (#6137)

### PR DESCRIPTION
**Pull request by Siddhartha8899**
(cherry picked from commit 5b91477f3437adba4d50b538de580698695fbb64)

### CODE REVIEW

**Comment by tammybailey** [comment]
@Siddhartha8899, there two linked backports that must be completed in a particular order. You need to first do BACKPORT-8208, then this one. I'm guessing that is why you are seeing errors in your PR.

The relationship between tickets is on the Jira page, in the "Issue Links" section.

**Comment by sueloverso** [comment]
I have reviewed it and it looks fine, but let's revisit once the other changes are in and PR testing is passing.

**Review by sueloverso — COMMENTED** [review]
Revisit after the other ticket is merged and this can pass testing.

**Comment by raviprakashgiri29** [comment]
> @Siddhartha8899, there two linked backports that must be completed in a particular order. You need to first do BACKPORT-8208, then this one. I'm guessing that is why you are seeing errors in your PR.
> 
> The relationship between tickets is on the Jira page, in the "Issue Links" section.

@tammybailey There were some confusions in the backport ticket links since the dependency link was missing, we figured it out when the PR testing failed. We created a dependency link in the ticket and merged BACKPORT-8208 now. This PR is good to go now once the PR testing passes.

**Review by lukech — APPROVED** [review]
LGTM

**Review by sueloverso — APPROVED** [review]

**Pull request merged**
