### PR TITLE
Struct alignment and packing for MSVC

### PR DESCRIPTION
**Pull request by markbenvenuto**
@keithbostic Here is the alignment and packing changes. 

I also updated the sed scripts. I have one long line as a result but it works. I also wanted to remove WT_GCC_ATTRIBUTE entirely so WT_GCC_FUNC_ATTRIBUTE is now translated into WT_GCC_FUNC_DECL_ATTRIBUTE in exern.h.

Tested - Clang 3.5, VS 2013

### CODE REVIEW

**Comment by wtbuild** [comment]
Test FAILed.

**Comment by wtbuild** [comment]
Test FAILed.

**Comment by wtbuild** [comment]
Test PASSed.

**Comment by keithbostic** [comment]
@markbenvenuto, do you want this in 2.8, or should it wait?

**Comment by markbenvenuto** [comment]
@keithbostic I do not need it for 2.8, it can wait.

**Pull request merged**
