### PR TITLE
WT-7440 Integrate file cursor with tiered storage

### PR DESCRIPTION
**Pull request by keitharnoldsmith**
Add code so we open a file cursor when the user calls open_cursor()
on a "tiered:" uri.

### CODE REVIEW

**Comment by keitharnoldsmith** [comment]
@ddanderson & @sueloverso : Don's code in the WT-7514 PR also includes a check in `__wt_cursor_init()` that clears `WT_CURSTD_CACHEABLE` on `tiered:` uris. I think Michael's original tiered cursor code (for multiple btree tiers) included code like this. Now that we are using a vanilla file cursor on tiered tables, it seems we should be able to cache them?

If it seems like a problem let me know.  It's two lines of code I could easily add.

**Comment by ddanderson** [comment]
@keitharnoldsmith, I'd insert the code to turn off cursor caching.  It didn't work for me, which is why I disabled it, and it's not worth chasing yet.  You could file a ticket or put in Appendix E.

**Review by ddanderson — APPROVED** [review]
LGTM.  I'm curious why you removed the hook_tiered.py?  Was it working before, and stopped working?  If we hope to get it back working eventually, maybe just disable it some other way?

**Comment by keitharnoldsmith** [comment]
> LGTM. I'm curious why you removed the hook_tiered.py? Was it working before, and stopped working? If we hope to get it back working eventually, maybe just disable it some other way?

Fair point.  I thought of it as my test for the tiered cursor (i.e., curtiered). So I removed it along with that code.  But it's probably a good starting point for adding tests for `tiered:` objects, as well.  I'll pull it back into existence.

**Comment by keitharnoldsmith** [comment]
> @keitharnoldsmith, I'd insert the code to turn off cursor caching. It didn't work for me, which is why I disabled it, and it's not worth chasing yet. You could file a ticket or put in Appendix E.

How odd.  

I've added the code to disable cursor caching for `tiered:`.  Maybe as we get more of the infrastructure working, it will work.

**Review by sueloverso — APPROVED** [review]
LGTM

**Pull request merged**
