### PR TITLE
WT-12609 Improve checkpoint cleanup and page eviction logic

### PR DESCRIPTION
**Pull request by kommiharibabu**
Checkpoint reads only internal pages into the cache for the purpose of removing any obsolete pages as part of the checkpoint cleanup. Evicting these internal pages asap can add an overhead to the next checkpoint to read them back again into the cache. Instead of evicting them asap, evict the internal pages read by the checkpoint like a regular page.

It is unnecessary to remove leaf pages tagged as READ WONT_NEED from the cache by the checkpoint because the checkpoint never reads any pages from the leaf pages (apart from history store pages used for reconciliation).  This will avoid the unnecessary slowdown of the checkpoint by evicting the pages that are not read by the checkpoint.

### CODE REVIEW

**Review by etienneptl — APPROVED** [review]

**Review by luke-pearson — APPROVED** [review]
LGTM.

**Comment by agorrod** [comment]
bq. As checkpoint never reads any leaf page into the cache

That is true during the cleanup phase, but not during reconciliation where it can read pages in that require history store content (OTOH: if we are in a pattern of repeatedly reading/updating/evicting history store pages in reconciliation that would be "bad"). If the reconciliation causes updates to be written to those history store pages, it might be enough now to add them to the urgent queue.
Historically (before 4.4) that wasn't enough - since the page would be associated with the tree being checkpointed and no other thread could do an eviction. So the pattern would be that checkpoint would read a page in, make some change to it, and then it could not be evicted until the checkpoint was complete. Which could lead to the cache becoming full of dirty content quickly.

I think we need to construct a test case that causes checkpoint to write a lot of content to the history store, and ensure that adding such pages to the urgent queue is enough for it to be possible to evict them before the checkpoint completes.

**Review by agorrod — COMMENTED** [review]
I added a comment, which serves as a review for now, so I'm going to click the review button to make it clear that this isn't in my active queue.

**Comment by kommiharibabu** [comment]
@agorrod I answered your question in the jira ticket; please check and let me know.

**Comment by kommiharibabu** [comment]
@agorrod and I discussed this change and agreed to merge it.

**Pull request merged**
