### PR TITLE
WT-3769 Enable prefix compression by default for LAS

### PR DESCRIPTION
**Pull request by bvpvamsikrishna**

### CODE REVIEW

**Comment by bvpvamsikrishna** [comment]
Autobuild : retest this please

**Comment by bvpvamsikrishna** [comment]
Autobuild : retest this please

**Comment by bvpvamsikrishna** [comment]
The attached file test.txt (renamed extension from .py to .txt to attach here) subset of test_timestamp04.py will reproduce the failure. 
[test.txt](https://github.com/wiredtiger/wiredtiger/files/1550118/test.txt)

**Comment by keithbostic** [comment]
Slightly trimmed down test:
```
from suite_subprocess import suite_subprocess
import wiredtiger, wttest
from wtscenario import make_scenarios

def timestamp_str(t):
    return '%x' % t

class test_timestamp04(wttest.WiredTigerTestCase, suite_subprocess):
    table_ts_log     = 'table:xxx'

    types = [
        ('row-smallcache', dict())
    ]

    scenarios = make_scenarios(types)

    def setUpConnectionOpen(self, dir):
        return None

    def setUpSessionOpen(self, conn):
        return None

    def ConnectionOpen(self):
        self.home = '.'
        conn_params = 'create,cache_size=1MB' + \
            ',error_prefix="%s" %s' % (self.shortid(), self.conn_config)
        try:
            self.conn = wiredtiger.wiredtiger_open(self.home, conn_params)
        except wiredtiger.WiredTigerError as e:
            print "Failed conn at '%s' with config '%s'" % (dir, conn_params)
        self.session = self.conn.open_session(None)

    def test_xxx(self):
        self.ConnectionOpen()
        self.session.create(self.table_ts_log,
            'key_format=i,value_format=i,memory_page_max=32k,' +\
            'leaf_page_max=8k,internal_page_max=8k')
        c = self.session.open_cursor(self.table_ts_log)

        key_range = 5000
        keys = range(1, key_range + 1)
        for k in keys:
            self.session.begin_transaction()
            c[k] = 1
            self.session.commit_transaction(\
                'commit_timestamp=' + timestamp_str(k))
            # Setup an oldest timestamp to ensure state remains in cache.
            if k == 1:
                self.conn.set_timestamp(\
                    'oldest_timestamp=' + timestamp_str(1))

if __name__ == '__main__':
    wttest.run()
```

**Comment by keithbostic** [comment]
I somehow managed to break this branch, so I'm closing it and re-opening a new branch.

**Pull request closed without merging**
