### PR TITLE
WT-11491 WT-11777 v6.0 group backport

### PR DESCRIPTION
**Pull request by marcbutler**

### CODE REVIEW

**Comment by marcbutler** [comment]
@ajmorton @kommiharibabu @lukech 

Need to circle back and determine what to do about test/suite/test_recovery01.py when @kommiharibabu has returned.

**Review by ajmorton — APPROVED** [review]
LGTM pending the `test_recovery01` discussion.

**Review by ruby-oujo — APPROVED** [review]
LGTM

**Comment by lukech** [comment]
Thanks @marcbutler. 
cc: @korteland who could help vendor this backport if it could be merged early next week. (I'll be on leave)

**Comment by marcbutler** [comment]
Myself Andrew and Hari will be able to sort this out promptly next week.

**Comment by marcbutler** [comment]
@ajmorton @kommiharibabu Would you kindly expedite the review so this can be vendored asap. Thanks.

**Review by kommiharibabu — APPROVED** [review]
LGTM

**Pull request merged**
