### PR TITLE
WT-2546 Evict server decides whether or not to evict

### PR DESCRIPTION
**Pull request by michaelcahill**
See initial discussion in #2648.

### CODE REVIEW

**Comment by fedorova** [comment]
@michaelcahill, your changes look good to me and do not affect my numbers.

**Comment by fedorova** [comment]
@sueloverso, could you please take a look at this change? Jenkins numbers are back up where they used to be, and this also fixes the regression I was seeing with 8 threads.

**Comment by sueloverso** [comment]
FYI, I did switch Jenkins back to the develop branch.  I'll move it back now and we'll let the perf tests run overnight and tomorrow on this branch.

**Comment by michaelcahill** [comment]
Sorry it took me a while to notice this, but don't the Jenkins jobs run with the default settings for statistics (i.e., off)?  If so, using statistics for the calculation isn't going to work...

I've changed the `wiredtiger-perf-evict` job to turn statistics on to see whether that makes a difference.  If so, I think we'll want a different long-term approach that doesn't rely on statistics.

**Comment by sueloverso** [comment]
@michaelcahill that was a good catch!  The plots are looking good this morning.  I'll run on my machine and create a change to calculate without statistics.

**Comment by sueloverso** [comment]
@fedorova  and @michaelcahill I believe this is ready for review and merging.  I removed Michael's temporary stat change in wtperf and made the percent threshold a macro.  Thanks Sasha for running all of your tests too and coming up with the computation that works well for all the thread/core values.  The plots are looking great now.

**Comment by michaelcahill** [comment]
@sueloverso and @fedorova, this lgtm and the performance results so far look good.  I'll merge.

**Pull request merged**
