### PR TITLE
WT-2129 Make cell dump a little safer

### PR DESCRIPTION
**Pull request by daveh86**

### CODE REVIEW

**Comment by daveh86** [comment]
@michaelcahill, do you mind having a further look at this?

**Comment by michaelcahill** [comment]
@daveh86 you mention "dump" in the title but this is changing a low-level routine -- what is driving this change?  Also, is there a ticket?

**Comment by daveh86** [comment]
As part of chasing WT-2129.

When dumping a LAS file its possible that there is no dhandle set, so we can attempt to de-reference a null when calling S2BT.

**Comment by michaelcahill** [comment]
@daveh86 I've updated the title to include the ticket.

Can you get a stack trace when this was failing?

The reason I ask is that this will add a little overhead to some very common cases.

**Comment by agorrod** [comment]
@daveh86 I see what this change was solving, but I'm inclined to push the solution into `bt_debug.c` instead of the cell code. Can we do that face to face tomorrow?

**Comment by daveh86** [comment]
@agorrod, that sounds like a good idea.

**Pull request closed without merging**
