### PR TITLE
WT-9563 Improve code style and readability

### PR DESCRIPTION
**Pull request by mm-ng**

### CODE REVIEW

**Comment by mm-ng** [comment]
I haven't changed the `wt_wrap_open_session` and `wt_wrap_close_session` function declarations because the compiler throws a warning that is treated as an error when the `inline` keyword is removed. It complains that the function is defined but not used. I'm thinking it would be cleaner to keep the `inline` in there rather than suppressing the warnings but let me know if there's another preferred workaround.

**Comment by AlexeyAnisimovAU** [comment]
I think we should make naming in `test/format/timestamp.c` consistent. All methods should have the prefix `timestamp_`.

**Comment by mm-ng** [comment]
> I think we should make naming in `test/format/timestamp.c` consistent. All methods should have the prefix `timestamp_`.

I thought about this but I also felt like moving the `timestamp` word to become a prefix changes the meaning a bit

**Comment by AlexeyAnisimovAU** [comment]
> I haven't changed the `wt_wrap_open_session` and `wt_wrap_close_session` function declarations because the compiler throws a warning that is treated as an error when the `inline` keyword is removed. It complains that the function is defined but not used. I'm thinking it would be cleaner to keep the `inline` in there rather than suppressing the warnings but let me know if there's another preferred workaround.

To make those methods non-inline we should:
1. Move them from `format.i` to probably `util.c`. `format.i` is for inline methods only.
2. Remove `static inline` from the methods 
3. Add forward declarations of the methods to `fromat.h`

**Review by AlexeyAnisimovAU — APPROVED** [review]
LGTM!

**Pull request merged**
