### PR TITLE
WT-3288 fix error codes for event_handler to be consistent in file operations

### PR DESCRIPTION
**Pull request by keithbostic**
Replacement for pull-request #3392.

### CODE REVIEW

**Comment by agorrod** [comment]
Thanks @keithbostic this lgtm. 

@halex2005 this is a slightly shuffled version of your original change (thanks very much for contributing) - would you mind testing this change before we merge to ensure it provides the functionality you needed?

**Comment by halex2005** [comment]
@agorrod, its ok, you can merge it. Thanks!

**Comment by michaelcahill** [comment]
Thanks @halex2005, will do.

**Comment by halex2005** [comment]
When do you plan to release next version?

**Comment by halex2005** [comment]
When do you plan to release next version?

**Comment by keithbostic** [comment]
@halex2005, although we can't yet commit to a date, we're preparing for a release in the near future.

**Pull request merged**
