### PR TITLE
LZ4 external compressor

### PR DESCRIPTION
**Pull request by agorrod**
Not yet ready for merge.

### CODE REVIEW

**Comment by agorrod** [comment]
This is related to issue #1751

**Comment by agorrod** [comment]
@daveh86 Could you try out this branch please? I'm interested to know whether it will work with autoconf as a starting point.

Configuring WiredTiger with:

```
--with-builtins=lz4
```

Then in a clean tree configuring and building with:

```
--enable-lz4
```

Making sure the build works, and LZ4 support is present in both builds.

Then it would be interesting to ensure that the compression is working. I'd do that using the wtperf application. https://github.com/wiredtiger/wiredtiger/tree/develop/bench/wtperf

There are a bunch of example configuration files for wtperf in:
https://github.com/wiredtiger/wiredtiger/tree/develop/bench/wtperf/runners

I'd take one of those (maybe ```evict-btree.wtperf```), and turn LZ4 compression on. If you configured with --with-builtins that should be as simple as changing:

```
table_config="type=file"
```

To:

```
table_config="type=file,block_compressor=lz4"
```

When configuring with ```--enable-lz4```, you'll need the above change as well as changing:

```
conn_config="cache_size=50M"
```

To:

```
conn_config="cache_size=50M,extensions=(lz4/.libs/libwiredtiger_lz4.so)"
```

**Comment by sueloverso** [comment]
@agorrod I think it would be better to add the support into the wtperf sources like it is for snappy and other compressors.  Then all that is needed is `compression=lz4` in a config file.

**Comment by agorrod** [comment]
Thanks @qconner lgtm - I'll merge into WiredTiger develop now.

**Pull request merged**
