### PR TITLE
WT-2605 Add C tests used in testing joins

### PR DESCRIPTION
**Pull request by ddanderson**

### CODE REVIEW

**Comment by ddanderson** [comment]
Not ready for merge, I'm going to add some more tests to satisfy the scope of the JIRA.

**Comment by ddanderson** [comment]
retest this please

**Comment by ddanderson** [comment]
@michaelcahill, this is ready for review.  I was going to add a c test for async, but then discovered that wtperf implicitly tests async ops.

**Comment by michaelcahill** [comment]
Thanks @ddanderson, these new tests lgtm.  I'll merge.

**Pull request merged**
