### PR TITLE
WT-9742 Add timestamp support to Simple and Complex data sets in Python tests.

### PR DESCRIPTION
**Pull request by ddanderson**
These data set classes are now outfitted to use an optional WiredTigerTimeStamp (timestamp allocator) object. If a timestamp allocator is attached to the data set, then all modifications use the timestamp allocator to get a commit timestamp, which also means that each individual modification is in an explicit transaction. This is done via instrumented cursors that are used by the data sets.  Running with the tiered hook causes a timestamp allocator to be used.

Any test that uses data sets, that want to use its own cursors, now need to use a *DataSet.open_cursor() call to get an instrumented cursor.  Likewise, truncate calls on the data set need to be transactional, so use a *DataSet.truncate() call.

There are some exceptions to this.  If a transaction is already in progress, we do not want to start a new transaction, but rather use timestamp_transaction to give a timestamp to the existing transaction.

To make this all work, we now (in the tiered hook) override {begin,commit,rollback}_transaction so we can track thr current transactional state on the session object.  And because our SWIG/Python interface may give us new Python objects every time we reference WT_SESSION.connection, and new objects won't have that new transactional state, we now create a different back reference to the connection from every session, and to the session from every cursor.  Someday we may be able to fix the SWIG/Python layer to "do the right thing" with WT_SESSION.connection and WT_CURSOR.session, but this is our workaround for now.  And to be clear, these new references (WT_SESSION._connection and WT_CURSOR._session) are only available when running with the tiered hook.

With all this, most uses of the data sets work with timestamps.  There are some tests that do their own timestamping, that will skip the tiered/timestamp mashup.  And there are about 5 tests that fail for still unknown reasons, we'll tackle those in other tickets.

### CODE REVIEW

**Comment by ddanderson** [comment]
@keitharnoldsmith and @raviprakashgiri29, can you please review?  I think the large initial commit comment should describe the overall ideas.  There are currently only five tests that use data sets that fail when timestamps are added. These are marked with \@wttest.skip_for_hook() annotations, and will be triaged separately.

**Comment by keitharnoldsmith** [comment]
> Running with the tiered hook causes a timestamp allocator to be used.

And if I'm reading the PR correctly, running existing tests (i.e., without any hook) will not use a timestamp allocator. I.e., this isn't changing the behavior we see with tests when they run without any hook. Is that right?

**Comment by ddanderson** [comment]
@keitharnoldsmith, that is correct.  Normal test runs don't have timestamps for data sets.

**Review by keitharnoldsmith — APPROVED** [review]
LGTM. I can follow this and it makes sense, but I'm no python expert. 

A couple of abstract questions. They are beyond the scope of this PR, but depending on what you think, maybe they merit tickets for possible future work?

- Now that we have support for timestamped datasets, would it be worth adding it to some of the standard tests?
- Conversely. Do we want to include some testing *without* timestamps in the tiered table testing?

**Comment by ddanderson** [comment]
@keitharnoldsmith, thanks for you great questions.  I originally wrote a long answer here, that collected enough thoughts to put it in a ticket: https://jira.mongodb.org/browse/WT-9890. I made one ticket rather than two, as I think if we can tease out just the timestamp work into its own hook, we can cover all the combinations.

**Pull request merged**
