### PR TITLE
Memory allocation

### PR DESCRIPTION
**Pull request by keithbostic**
This is the set of changes to remove the memory allocation adjustment code, replacing it with a new configuration string that adjusts the cache size by a percentage. See #1564.

### CODE REVIEW

**Comment by wtbuild** [comment]
Test PASSed.

**Comment by wtbuild** [comment]
Test FAILed.

**Comment by wtbuild** [comment]
Test PASSed.

**Comment by michaelcahill** [comment]
I've taken a look, and overall this matches what I expected.  I have a few high-level questions / comments:

* how confident are we about the default value of 8%?  Has this been tested for a particular workload? Do we know whether WiredTiger uses more or less RAM with this branch using tcmalloc than develop?

* it looks like the adjustment is missing for shared caches -- I think we need to apply it in `__cache_pool_adjust`.  One complication is that the adjustment is per-connection -- it would be weird, but an application could decide to use 10% on one connection and 20% on another, both using the same shared cache.

* If we go this way, some more cleanup should be possible: we shouldn't need the `WT_MEMSIZE_*` macros, for starters...

**Comment by keithbostic** [comment]
> how confident are we about the default value of 8%? Has this been tested for a particular workload? Do we know whether WiredTiger uses more or less RAM with this branch using tcmalloc than develop?

We're not especially confident: I ran a few test/format workloads (and I'm happy to agree test/format isn't the right application to measure, it's just what was easy). I searched around on the net but couldn't find anything useful. Some of the things I did find made it clear different allocators have wildly different overheads for different allocation patterns, there's not going to be any one value that's going to work for everybody.

> it looks like the adjustment is missing for shared caches -- I think we need to apply it in __cache_pool_adjust. One complication is that the adjustment is per-connection -- it would be weird, but an application could decide to use 10% on one connection and 20% on another, both using the same shared cache.

My mistake, I'm sure -- I thought everything was based off that single value, perhaps @agorrod can take a quick look?

> If we go this way, some more cleanup should be possible: we shouldn't need the WT_MEMSIZE_* macros, for starters...

Yes. There's a ton more cleanup in the split code (including getting rid of the hard-wired 5%, of course). I deliberately left all of that work out of this change to minimize what we'd be changing in the MongoDB tree, if we merge.

**Comment by michaelcahill** [comment]
We should check whether Dan's repro in https://jira.mongodb.org/browse/SERVER-16997 is fixed by this branch (and/or #1596).

**Comment by keithbostic** [comment]
I believe SERVER-16997 was showing two symptoms, the first was the accounting errors (fixed by this branch and by #1593), the second was some stalling which we never fully understood, but which was associated with too-small caches.

I believe #1596 has no behavior changes.

**Comment by wtbuild** [comment]
Test PASSed.

**Comment by wtbuild** [comment]
Test PASSed.

**Pull request merged**
