### PR TITLE
WT-9291 Fix return value not wrapped in a pair of parentheses

### PR DESCRIPTION
**Pull request by quchenhao**

### CODE REVIEW

**Review by kommiharibabu — APPROVED** [review]
LGTM

**Comment by agorrod** [comment]
@quchenhao how did this get through the first time? Do we need to improve our PR testing?

**Comment by quchenhao** [comment]
@agorrod Yes, we can make this check a part of s_all I think.

**Comment by korteland** [comment]
I made WT-8908 a little while ago after a similar mistake, maybe we can bump the prio of that.

**Pull request merged**
