### PR TITLE
WT-4310 Add option to not abort in diagnostic builds on data corruption

### PR DESCRIPTION
**Pull request by sulabhM**

### CODE REVIEW

**Comment by sulabhM** [comment]
I have created a new pull request for this change. The original pull request that was merged:
https://github.com/wiredtiger/wiredtiger/pull/6014

This pull request additionally contains a change for disabling wt4156_metadata_salvage csuite test for asan builds.

**Comment by sulabhM** [comment]
@lukech can you review the last commit in this change please

**Comment by sulabhM** [comment]
I have reconfigured the pull request tester for all tests on Ubuntu 18.04 variant.

**Review by lukech — APPROVED** [review]
The bypass test change looks good to me. 

I do not totally understand the background of disabling the test for ASAN. Should a new ticket be created to re-enable the test once the restriction is removed?

**Comment by sulabhM** [comment]
@lukech , the reason the test is being disabled is that we expect the memory to be leaked and we have decided that in the given situation it is not possible to release the memory safely. To shutdown wiredtiger properly, any memory allocated for the cache structures needs to be released. To do that we need to evict all the pages. In the case of corruption, it is not safe to walk the btree evicting the data, hence we decide to forgo releasing the memory.

The change in this pull request enables execution of the code that shuts down the connection after detecting corruption. Prior to this change, in the debug build, we aborted as soon as corruption was detected. Hence, with this change the ASAN build correctly reports that we leak memory, but we are going to treat it as expected. Hence we are permanently disabling this test. The restriction is not going to be removed.

**Comment by lukech** [comment]
Thanks for the detailed answer, which makes sense to me!

**Pull request merged**
