### PR TITLE
WT-9311 Ensure log messages clearly identify storage HW corruption

### PR DESCRIPTION
**Pull request by etienneptl**

### CODE REVIEW

**Comment by etienneptl** [comment]
Sorry for the noise. It's better not to change the letter case of the existing string so we don't break anything that could rely on it.

**Comment by mickgraham-mongodb** [comment]
Looks good to me.

**Comment by mickgraham-mongodb** [comment]
Approved

**Review by mickgraham-mongodb — APPROVED** [review]

**Review by agorrod — APPROVED** [review]
LGTM

**Pull request merged**
