### PR TITLE
WT-4058 Release a slot outside of the lock.

### PR DESCRIPTION
**Pull request by sueloverso**
@agorrod Please review this change. After the user opened the ticket and questioned this, I believe this is safe. I have been running on this branch for a few hours in both the `wiredtiger-test-recovery-stress` and `wiredtiger-perf` jobs and have not seen any problems.

Other uses of `wt_log_release` do not hold any locks so that function does not require it.

### CODE REVIEW

**Comment by sueloverso** [comment]
autobuild: retest this please

**Comment by sueloverso** [comment]
autobuild: retest this please

**Comment by agorrod** [comment]
Some performance testing shows a regression due to this change - we should hold off merging for now.

**Comment by agorrod** [comment]
The performance regression was an anomaly. I'm going to go ahead and merge.

**Pull request merged**
