### PR TITLE
WT-11996 Remove long-running label for several C tests

### PR DESCRIPTION
**Pull request by etienneptl**
After [WT-11583](https://jira.mongodb.org/browse/WT-11583):

- Several C tests are not taking that long to run (< 100 seconds)
- Since only a few of them are left, we don't need multiple buckets to run the remaining tests
- A large instance is not necessary either

See the JIRA ticket for the patch build. Please note that these labels might be re-introduced when they will be executed on slower variants, see WT-11989.

### CODE REVIEW

**Review by lukech — APPROVED** [review]
LGTM

**Comment by jiechenbo** [comment]
I took a look at the evergreen waterfall, and see that bucket1 and bucket2 are taking roughly 40~ minutes each. I personally don't mind it being a low, since msan will eventually need the buckets anyways. @etienneptl What are your thoughts?

**Review by jiechenbo — APPROVED** [review]
LGTM

**Comment by etienneptl** [comment]
evergreen merge

**Pull request merged**
