### PR TITLE
WT-5657 Fix a race in deletion when running  with lower isolation levels

### PR DESCRIPTION
**Pull request by quchenhao**

### CODE REVIEW

**Comment by lukech** [comment]
autobuild: Can one of the admins verify this patch?

**Comment by agorrod** [comment]
@quchenhao do you think we should push to get this change in now, or can it wait until after MongoDB RC0, since it's not necessary for MongoDB?

**Comment by quchenhao** [comment]
> @quchenhao do you think we should push to get this change in now, or can it wait until after MongoDB RC0, since it's not necessary for MongoDB?

Yes, I agree this is not necessary and we can merge it later.

**Comment by agorrod** [comment]
@quchenhao is it time to resuscitate this PR?

**Comment by quchenhao** [comment]
> @quchenhao is it time to resuscitate this PR?

@agorrod Not now I think. I found more issues we have to solve before lower isolation levels can work. We should have a wholistic plan how to fix them I think.

There are three major issues I have encountered: 1) The race condition partially addressed in this ticket. (I only solve the case two deletions race with each other, which triggers an assert. It's also possible that other operations race with each other (e.g., an insert race with another insert). However, other cases are likely to be benign so may be we don't need to do anything. 2) We don't check conflict in lower isolation levels including read committed, which doesn't make sense to me. I think we should still check conflict for read committed.(WT-5957) 3) Some operations like prepared updates cannot be run together with operations in lower isolation levels. We need to make api changes to forbid these cases. I'm thinking passing a config in `wiredtiger_open` to force everything to run in snapshot isolation. If that config is not set, you are not allowed to run certain operations like prepared updates.

**Comment by quchenhao** [comment]
@agorrod I'm fine to first merge this one. Though it's not going to fix lower isolation levels, at least we can increase our test coverage by enabling join_visibility test.

**Comment by quchenhao** [comment]
Seems join_visibility is still failing. We need to have a discussion about how to fix lower isolation levels. Close this PR for now.

**Pull request closed without merging**
