### PR TITLE
WT-6610 It is not an error if the backup rename configuration is not …

### PR DESCRIPTION
**Pull request by sueloverso**
…found.

### CODE REVIEW

**Comment by agorrod** [comment]
@sueloverso I've gone ahead and merged develop in here, and re-applied the changes from WT-6215 and WT-6539.

I suspect you are right that my testing change has a bug - I'd appreciate if you can pick this up and fix it from here. Would that be OK?

**Review by agorrod — APPROVED** [review]
Thanks @sueloverso for cleaning up my code and fixing the problem. LGTM.

**Comment by sueloverso** [comment]
@tammybailey please review so we can get this testing on WT jobs.

@agorrod let's keep an eye on the compatibility evergreen job once this is merged for any fallout from allowing backup in the backward compatibility code. It is what will allow us to test this all going forward, but I don't know if there's a subtle reason why it was disabled to begin with.

**Review by tammybailey — APPROVED** [review]
I added links in the Jira ticket for MongoDB & WiredTiger patch builds. Assuming all is good there, this change LGTM.

**Comment by sueloverso** [comment]
@tammybailey I checked the patch builds. The WT ones were all successful. The MongoDB ones had some failures, but AFAICT they seem network or host related and not related to this. But I'm not super familiar with those kinds of failures. Can you look at one or two and if you agree, please merge. If the failure is related to this patch, let me know because I couldn't see it.

**Pull request merged**
