### PR TITLE
WT-11586 Skip test_compact03.py when tiered is enabled

### PR DESCRIPTION
**Pull request by etienneptl**
Skip the `test_compact03.py` test with tiered is enabled.

### CODE REVIEW

**Comment by etienneptl** [comment]
As explained by @ddanderson [here](https://jira.mongodb.org/browse/WT-11586?focusedCommentId=5706083&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-5706083), this does not solve the problem. I am moving this into draft until a better solution is found.

**Review by Sean04 — APPROVED** [review]
LGTM

**Comment by etienneptl** [comment]
evergreen merge

**Comment by etienneptl** [comment]
The commit queue failed because of a known issue: WT-11297.

**Pull request merged**
