### PR TITLE
WT-9559 Update comments in __btcur_search_neighboring

### PR DESCRIPTION
**Pull request by sonar3ddy**

### CODE REVIEW

**Comment by luke-pearson** [comment]
Make sure you run ./s_all locally to fix up the indentation issues.

**Review by luke-pearson — COMMENTED** [review]
We should update the function comment on line 878 to something along the lines of: "Search for a valid record around the cursor location."

**Review by luke-pearson — APPROVED** [review]
LGTM.

**Review by ruby-oujo — APPROVED** [review]
LGTM

**Pull request merged**
