### PR TITLE
WT-10522 Fix a bug that leads to an unexpected aborted tombstone on update chain (v5.0 backport)

### PR DESCRIPTION
**Pull request by svc-bot-sebb**
ddef7fee8

### CODE REVIEW

**Comment by marcbutler** [comment]
@lukech I feel the failed checks are actually an environment problem rather than with the backport. Could you confirm?

**Comment by lukech** [comment]
@marcbutler you are right - the failure pattern matches that reported WT-11362.

**Comment by marcbutler** [comment]
@lukech But it looks like the v5.0 backport of WT-11362 was declined?

**Comment by lukech** [comment]
> it looks like the v5.0 backport of [WT-11362](https://jira.mongodb.org/browse/WT-11362) was declined?

I think the 5.0 backport was declined in favor of WT-11380 (because the original fix is not suitable to be backported/cherrypicked as a whole and needs some rework). @clarissecheah has more information.

**Comment by clarissecheah** [comment]
Yes, in the case of [WT-11233](https://jira.mongodb.org/browse/WT-11233) the backport was declined in favour of a new ticket ([WT-11380](https://jira.mongodb.org/browse/WT-11380)) since versions 5.0 and under use the v3 toolchain and the changes being backported were v4 toolchain specific. We'd simply like to ensure that WT is compiled with the mongodbtoolchain (which for v5.0 and v4.4 should remain being the v3 toolchain).

**Review by clarissecheah — APPROVED** [review]
LGTM! Thanks :)

**Pull request merged**
