### PR TITLE
WT-7507 Update salvage for a history store and timestamp world

### PR DESCRIPTION
**Pull request by keithbostic**

### CODE REVIEW

**Comment by keithbostic** [comment]
@sulabhM, @kommiharibabu, each commit in the PR Is a specific change, so it might be easier to review this as a set of separate commits rather than as a whole change.

**Review by sulabhM — COMMENTED** [review]
@keithbostic , sorry for the delay, I have been mostly away this week. I have picked up this review now and trying to understand the changes. I should get back to you by Monday.

**Review by kommiharibabu — APPROVED** [review]
LGTM

**Review by sulabhM — APPROVED** [review]
LGTM. I have low understanding of the topic and the discussion, so feel free to get one more review if you think it is needed.

**Comment by keithbostic** [comment]
@kommiharibabu, I've done the final step of hooking RTS in as a final step for `WT_SESSION.salvage`, does this look correct to you?

The changes are pushed in 48792c3 and 5d29c95 (or just do a full diff against 6d040f3).

The test suite isn't going to pass, as far as I can tell, RTS is corrupting column-store trees -- I'll chase that after you approve the overall approach.

I'm completely clueless as to whether or not I'm choosing the `rollback_timestamp` value correctly, can you please let me know how to fix that (or feel free to just push the change if it's easier).

Also, what is the appropriate "clear everything that globally visible" setting for `rollback_timestamp`? If it's set to `WT_TXN_FIRST` will that do what we want?

**Review by kommiharibabu — APPROVED** [review]
lgtm to the approach of RTS call.

> Also, what is the appropriate "clear everything that isn't globally visible" setting for rollback_timestamp? If it's set to WT_TXN_FIRST will that do what we want?

All the updates that are less than the `oldest timestamp` are considered globally visible. Setting the `rollback_timestamp` to the `oldest timestamp` does the job. I want to know where you want to use the `oldest_timestamp` as the `rollback_timestamp`?

**Comment by keithbostic** [comment]
@sulabhM, @kommiharibabu, I think I'm finally getting the PR WT-7507 into shape for merge, only a single test failure and an open question or two to go, and then I'll queue it up for final review.

I wanted to call your attention to WT-7737 (https://jira.mongodb.org/browse/WT-7737), which explains commit 1b9b3cd. Sulabh, I believe you're familiar with the dhandle aspects of this change, and Hari, I know you are the go-to person on rollback-to-stable: this change is tricky, and I'd appreciate a closer than usual check on it. Thanks!

**Comment by keithbostic** [comment]
@kommiharibabu, @sulabhM, this one is ready to for the final review before merge.

I'm seeing occasional failures from `test_prepare_hs03` on Windows-64, but nowhere else, and I will chase that down before I merge. Everything else is good as far as I know.

**Comment by sulabhM** [comment]
Thanks, @keithbostic , I will have a look. It is a big change, I will take thurs/fri to go through it.

**Comment by keithbostic** [comment]
@sulabhM, @kommiharibabu: if either of you would like a tour of the change before you do your review, hit me up, I'm happy to spend a little time explaining the big components before you dive in. -- Thanks!

**Comment by sulabhM** [comment]
@keithbostic , that will be awesome. Both @kommiharibabu and I are interested in a code walk through.

**Review by kommiharibabu — APPROVED** [review]
LGTM.

**Pull request merged**
