### PR TITLE
WT-7795 CppSuite fails on Jenkins with "expected ) before PRIxMAX"

### PR DESCRIPTION
**Pull request by AlexeyAnisimovAU**

### CODE REVIEW

**Review by tetsuo-cpp — APPROVED** [review]
LGTM. That's interesting. I guess that is only certain versions of libc++ and libstdc++?

**Comment by AlexeyAnisimovAU** [comment]
Tested this fix on Jenkins.

**Review by luke-pearson — APPROVED** [review]
LGTM.

**Review by etienneptl — APPROVED** [review]
LGTM

**Comment by AlexeyAnisimovAU** [comment]
Accidentally pulled changes from master. I will close this PR and request another one.

**Pull request closed without merging**
