### PR TITLE
WT-2552 Add public API for pluggable filesystems

### PR DESCRIPTION
**Pull request by keithbostic**
@agorrod, I'm putting some minor cleanups into this branch for your review/consideration.

### CODE REVIEW

**Comment by keithbostic** [comment]
autobuild: retest this please

**Comment by keithbostic** [comment]
autobuild: retest this please

**Comment by keithbostic** [comment]
autobuild: retest this please

**Comment by agorrod** [comment]
Thanks @keithbostic lgtm - I'll merge.

**Pull request merged**
