### PR TITLE
WT-6015 Check compatibility after logpath and extensions are set up.

### PR DESCRIPTION
**Pull request by sueloverso**
This PR is not yet complete, as it does not contain a reproducer test. I debugged it by running recovery on the tarball in the ticket as the issue was happening on restart. The backup content was valid.

The reason WT-5930 did not fully solve the problem is that the compatibility was tested before the logging subsystem configuration was done. That leads to some convoluted startup configuration setting. I'm not thrilled with where that ended up. So I'm marking this as a draft but wanted to put the fix out there for initial review.

### CODE REVIEW

**Comment by sueloverso** [comment]
@ddanderson and @agorrod this is the form I want for this change in how the configuration is parsed and processed. At the moment I'm debugging test failures that seem to be real relating to this change.

**Comment by sueloverso** [comment]
The testing is not trivial because MongoDB uses logpath subdirectories and that requires more than a few minutes of Python code smithing for me. I have made sure it works on the MongoDB tarball and can open a new ticket for adding a test because I do want one. @agorrod we can merge now or hold off a day or two as I work on a test. I could also back off and just write a csuite test. That would probably be faster.

**Comment by sueloverso** [comment]
I opened WT-6316 for adding a test. I'm going to merge this.

**Comment by lukech** [comment]
@sueloverso I reverted this together with #5725. Feel free to create a new PR.

**Pull request merged**
