### PR TITLE
WT-7994 Add docs compile task to PR testing

### PR DESCRIPTION
**Pull request by tammybailey**

### CODE REVIEW

**Comment by tammybailey** [comment]
I added a new task `doc-compile` to run as part of pull request testing. This task is configured to run on Ubuntu 20.04, but currently lives under the "! Ubuntu 18.04" build variant. This is the cleanest way to make the requested changes, particularly as we are soon upgrading our 18.04 build variant to 20.04 anyway. Once WT-7059 is merged, we no longer need to specify `run_on: ubuntu2004-test` in the `doc-compile` task config.

**Review by lukech — APPROVED** [review]
LGTM. Thanks for making the change!

**Comment by luke-pearson** [comment]
Is it worth having doc_update depend on doc_compile and sharing artifacts between them? I guess this can the quick fix option for preventing further reverts.

**Comment by lukech** [comment]
> Is it worth having doc_update depend on doc_compile and sharing artifacts between them? I guess this can the quick fix option for preventing further reverts.

That's actually my initial thought as well. If we put doc_update and doc_compile into the same builder, and let the former depend on the latter, then the build frequency (batchtime) would be an issue. We do want doc to be compiled for each commit, while doc update being less frequent i.e. once a day. Then I felt the current solution Tammy put in makes more sense.

**Comment by luke-pearson** [comment]
> 
> 
> > Is it worth having doc_update depend on doc_compile and sharing artifacts between them? I guess this can the quick fix option for preventing further reverts.
> 
> That's actually my initial thought as well. If we put doc_update and doc_compile into the same builder, and let the former depend on the latter, then the build frequency (batchtime) would be an issue. We do want doc to be compiled for each commit, while doc update being less frequent i.e. once a day. Then I felt the current solution Tammy put in makes more sense.

I don't think frequency would be an issue, as long at it depends on doc_update then it'll always run doc_compile prior to doc_update. Doc_compile could be every commit and doc_update, once a day.

**Comment by luke-pearson** [comment]
I'm happy to go with this as is and make a ticket for the more complex solution, at least we can prevent bad merges in the meantime.

**Review by luke-pearson — APPROVED** [review]
LGTM.

**Comment by lukech** [comment]
> I don't think frequency would be an issue, as long at it depends on doc_update then it'll always run doc_compile prior to doc_update. Doc_compile could be every commit and doc_update, once a day.

I believe `batchtime` is a build variant/project level configuration. Some trick needs to be played to let tasks within the same builder use different batchtime values. And it's kind of an anti-pattern to have one task in "A" build variant depend on another task in "B" build variant.

**Comment by luke-pearson** [comment]
> I believe `batchtime` is a build variant/project level configuration. Some trick needs to be played to let tasks within the same builder use different batchtime values. And it's kind of an anti-pattern to have one task in "A" build variant depend on another task in "B" build variant.

Ah okay I didn't know that `batchtime` could only be specified at the variant level.

**Comment by tammybailey** [comment]
@luke-pearson, my reasoning was in line with Luke C's comments. You would only be saving on that one run per day at the cost of complicating our yml file even more than it already is (as this is not an intended usage pattern). Also, we probably don't need to run the doc update even every day (that's another discussion, however!)

**Comment by luke-pearson** [comment]
Makes sense let's go with this.

**Pull request merged**
