### PR TITLE
WT-2909 Add fault injection test to verify checkpoint integrity

### PR DESCRIPTION
**Pull request by ddanderson**
See comments in test/csuite/wt2909_checkpoint_integrity/main.c describing the new test.

### CODE REVIEW

**Comment by ddanderson** [comment]
Not ready for review yet.  I'm currently using this as a test case for WT-3157.

**Comment by ddanderson** [comment]
I've incorporated fixes from #3273 into this test. It probably won't pass until (at a minimum) fixes from WT-3157 and WT-3161 are merged.

**Comment by ddanderson** [comment]
@sueloverso, @agorrod, can you please review? The problems that this test exposed have been fixed, and fixes has been merged into this branch.

**Comment by sueloverso** [comment]
@ddanderson I pushed some minor KNF/formatting type changes.  Otherwise LGTM.

**Comment by ddanderson** [comment]
Thanks, @sueloverso.  @agorrod, can you also take a look, and merge if you like?

**Comment by agorrod** [comment]
Thanks @ddanderson - this test will be very useful. I'll go ahead and merge.

**Pull request merged**
