### PR TITLE
WT-4840 WT_CURSOR.modify must require explicit, snapshot-isolation transaction (v4.0 backport)

### PR DESCRIPTION
**Pull request by lukech**
Disallow WT_CURSOR.modify in anything other than an explicit transaction
at snapshot isolation.

Add tests that other transaction configurations fail.

(cherry picked from commit 7c486eb1d4aecb67a635e06cdd74d179d69638f1)

### CODE REVIEW

**Comment by lukech** [comment]
retest this please

**Comment by lukech** [comment]
retest this please

**Comment by lukech** [comment]
I tried to cherry-pick the commit, and the only conflict I manually fixed is the change in `test/format/config.c`. The pull request testing failed on `test_las01.py` 
```
ERROR: test_las01.test_las01.test_las
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Z:\jenkins\workspace\wiredtiger-pull-request-windows\test\suite\test_las01.py", line 140, in test_las
    self.large_modifies(self.session, uri, 0, ds, nrows)
  File "Z:\jenkins\workspace\wiredtiger-pull-request-windows\test\suite\test_las01.py", line 69, in large_modifies
    self.assertEqual(cursor.modify(mods), 0)
WiredTigerError: Operation not supported
```
@keithbostic do you see any change or dependent ticket missed that could have caused the problem here?

**Comment by keithbostic** [comment]
@lukech 
> The pull request testing failed on `test_las01.py`

The problem is the `mongodb-4.0` branch doesn't have commit 1af9265, specifically this change:
```
diff --git a/test/suite/test_las01.py b/test/suite/test_las01.py
index 25f34c0195..6f736d7223 100755
--- a/test/suite/test_las01.py
+++ b/test/suite/test_las01.py
@@ -37,8 +37,8 @@ def timestamp_str(t):
 # Smoke tests to ensure lookaside tables are working.
 class test_las01(wttest.WiredTigerTestCase):
     # Force a small cache.
-    def conn_config(self):
-        return 'cache_size=50MB'
+    conn_config = 'cache_size=50MB'
+    session_config = 'isolation=snapshot'
 
     def large_updates(self, session, uri, value, ds, nrows, timestamp=False):
         # Update a large number of records, we'll hang if the lookaside table
```

That change sets the basic `WT_SESSION` configuration for the test, and matches the WT-4840 change that requires snapshot-isolation transactions for cursor modify operations.

**Comment by lukech** [comment]
Thanks @keithbostic, I made the change suggested only for `test_las01.py` then the test became happy. Not sure if the test only change is enough. I did attempt to cherry-pick the whole changes of WT-4738 and got quite a few merge conflicts, thus did not go that path.

**Pull request merged**
