### PR TITLE
WT-9268 Delay deletion the history store record to reconciliation (#7939)

### PR DESCRIPTION
**Pull request by mm-ng**
(cherry picked from commit 3bb3b50bc1ee65e92a83966e095f61abbb89ffa6)

### CODE REVIEW

**Review by quchenhao — CHANGES_REQUESTED** [review]
This change should be backported together with all the follow on fixes.

**Comment by mm-ng** [comment]
Please hold off on reviewing this until we determine whether we still want this backported.

**Comment by agorrod** [comment]
@mm-ng let me know when this is ready for review. I agree with @quchenhao that we need to be careful about this backport.

**Comment by mm-ng** [comment]
@agorrod @quchenhao We're not able to go ahead with this ticket as there's still another related change that hasn't been resolved yet and may have fallout. Going to close out this PR, sorry about that.

**Pull request closed without merging**
