### PR TITLE
WT-11421 Prevent background compaction from processing incompatible files

### PR DESCRIPTION
**Pull request by etienneptl**
The changes:

- Fix the background compaction algorithm so it does not call compact on incompatible files
- Update the tests with the method `assertRaisesWithMessage`
- Add more tests

### CODE REVIEW

**Review by kommiharibabu — APPROVED** [review]
LGTM

**Comment by etienneptl** [comment]
The current failing tests are because Python is too quick at executing the API calls while the C layer has not processed the signals for the background compaction. I will need to add a sleep to give a chance to the C layer to process them.

**Review by Sean04 — APPROVED** [review]
LGTM

**Comment by etienneptl** [comment]
evergreen merge

**Comment by etienneptl** [comment]
The commit queue failed due to WT-10798 which introduced a bug.

**Comment by korteland** [comment]
https://github.com/wiredtiger/wiredtiger/pull/9477 sorry about that

**Comment by etienneptl** [comment]
evergreen merge

**Pull request merged**
