### PR TITLE
WT-6257 rows out-of-order in history store file

### PR DESCRIPTION
**Pull request by keithbostic**
@michaelcahill, I've asked @tetsuo-cpp for PR review, but would you please review 984b4f5?

What I think is happening:

* we search an internal page, setting `skiphigh` and `skiplow`
* we select a leaf page that is not the last `WT_REF` in the internal page's page-index
* the last leaf page in the internal page is deleted making our chosen page the last entry
* more entries are added to the chosen page, extending its name space
* the chosen page is evicted and read back in
* we swap the internal page for the chosen page and our `skiphigh` value is no longer correct

I'm not terribly confident of that analysis, but it seems to me it can happen and so far I haven't seen a failure with the fix applied.

### CODE REVIEW

**Comment by keithbostic** [comment]
@tetsuo-cpp, I've pushed each change into an individual commit so hopefully review isn't difficult. Feel free to revert any specific change without further discussion if you don't like anything.

**Comment by agorrod** [comment]
Nice catch @keithbostic - I can't speak to whether this is the root cause of all WT-6257 failures, but the description and fix make sense to me.

**Comment by tetsuo-cpp** [comment]
I'm running `test/checkpoint` on a spawn host overnight with this change. I'll let you know how it goes.

**Comment by keithbostic** [comment]
@michaelcahill, thanks for the writeup, much better than mine! :)

 > One idea from writing this up: in diagnostic mode, could we have `__wt_lex_compare_skip` assert that the first `*matchp` bytes do actually match?

I did something similar eventually (calling `__wt_lex_compare_skip` twice, once with 0 bytes skipped, and asserting the results were the same). My concern is it would affect performance more than we're willing to spend on a #diagnostic test, given this is the heart of page search?

@agorrod, please let us know what you prefer.

**Pull request merged**
