### PR TITLE
WT-11791 Remove extraneous whitespace from Evergreen YAML files

### PR DESCRIPTION
**Pull request by pmacko86**

### CODE REVIEW

**Comment by etienneptl** [comment]
It would be great to have something that does it automatically so we don't have to do this in the future. Could s_all take care of it?

**Review by ddanderson — APPROVED** [review]
LGTM

**Comment by ddanderson** [comment]
> It would be great to have something that does it automatically so we don't have to do this in the future. Could s_all take care of it?

Maybe `dist/s_evergreen_validate`

**Comment by pmacko86** [comment]
Yes, that's a good idea. Let me merge this in, and let me create a separate ticket to do something in `s_all`. At that point, let's figure out more holistically where else we should be removing trailing whitespace. Besides the YAML files, our Python scripts come to mind. I'm sure we can come up with other places. I'm thinking something more like `s_whitespace` that would take care of it everywhere else too.

**Pull request merged**
