### PR TITLE
WT-11121 If an operation times out, don't retry the resulting WT_ROLLBACK error

### PR DESCRIPTION
**Pull request by ddanderson**

### CODE REVIEW

**Comment by ddanderson** [comment]
This is an alternative approach to #9277 that makes sense to me.

**Comment by sueloverso** [comment]
@ddanderson should that conditional instead be `wt_op_timer_fired(session)`?

**Comment by luke-pearson** [comment]
I think probably @sueloverso is correct that `__wt_op_timer_fired` would be the way to go, only checking on the session seems like an invalid usage.

**Comment by ddanderson** [comment]
@sueloverso and @luke-pearson, agreed, `__wt_op_timer_fired` is better.  This change is untested against the failure.  Do either of you have a reproducer and would you try this if you prefer this to other PR?

**Comment by luke-pearson** [comment]
I have a repro and can try it against this PR, I'm still on the fence as to which is better. Perhaps this one has less potential consequences for users of the optimer mechanism.

**Comment by luke-pearson** [comment]
Given the potential side effects of the other solution on MongoDB my call is that we go with this solution and resolve the "natural/unnatural" rollback conversation in time.

**Review by luke-pearson — APPROVED** [review]
LGTM.

**Comment by ddanderson** [comment]
@sueloverso - when you have a chance, please take a look.  I changed the PR to use `__wt_op_timer_fired`. Do you have any additional comments?  I just added a long comment on the ticket that (I think!) explains what's going on, and why this fix makes sense to me.

@luke-pearson says in the ticket that tests have passed for both PRs, and he's ready to merge this one.

**Comment by sueloverso** [comment]
@luke-pearson I'm trying to understand how this fixes the issue. I can see that it fixes resetting the cursor. But test/format when checking mirrors does not do so in a transaction and is not expected a rollback. Doesn't this change mean that WT_ROLLBACK will still be returned from `wt_txn_is_blocking` and then simply be passed all the way back out to `format`? Won't that cause it to fail?

**Comment by ddanderson** [comment]
@sueloverso I see this in `table_mirror_row_next`:
```
        /* WT_ROLLBACK isn't illegal, but it would mean restarting the verify somehow. */
        testutil_assert(ret == 0);
```
So test/format (in comments) admits it is a possibility but doesn't really handle it currently.  If test/format is verifying the mirror in a single threaded state, it should set operation_timeout_ms to 0 so it won't get a rollback, at least due to a timeout.

**Comment by sueloverso** [comment]
@ddanderson and I discussed this on our Tora meeting. He is correct above, but I think that just moves the problem from a cursor reset/mismatch to a format assert/crash. I don't see how this change really allows format mirror checking to succeed.

The `operation_timeout_ms` is just set on the connection and applies to all the workload threads doing transactional work. We discussed some possibilities:
1. Reconfigure, at the connection level, the `operation_timeout_ms`, around the verification. There would be a small period when the workload threads would not be testing using it with that.
2. Don't allow format to choose mirrors and operation_timeout at the same time.
3. Add in a session setting to turn off `operation_timeout_ms` on a specific session level. Currently it is only set on the connection or as a configuration to the 3 transaction APIs.
4. Go back to the original fix and/or combine them together.

This fix as-is won't allow format to successfully verify, I think.

**Comment by ddanderson** [comment]
I agree with everything @sueloverso just wrote.

I had suggested 2) as a possibility in our meeting, but I don't love it.  MDB uses `operation_timeout_ms`, and if we're not testing it with verify, then we're not testing it the best we could.

Option 3) feels the best to me, but it's a little more work.  It allows the application to say: I want to turn on operation_timeout_ms for sessions where I think I might need it and I'm prepared to catch WT_ROLLBACK.  It allows test/format (and MDB if it wants to) generally have timeouts on, but in certain circumstances where it's awkward to deal with rollback, and we don't mind a long operation, turn the timeout off.  I would not be surprised if MDB found this to be valuable for background activity, or long read scans, just as test/format does.

**Comment by sueloverso** [comment]
Based on the fact that there is a connection-wide timeout or it can only be set on the transactions API, another option would be to update the documentation (and code) and say that the operation timeout only applies to transactional operations and is ignored on non-transactional operations. Then the timeout would be ignored for the cursor walks and would not fire.

**Comment by luke-pearson** [comment]
> another option would be to update the documentation (and code) and say that the operation timeout only applies to transactional operations and is ignored on non-transactional operations. Then the timeout would be ignored for the cursor walks and would not fire.
This seems like the best solution to me.

**Comment by ddanderson** [comment]
> another option would be to update the documentation (and code) and say that the operation timeout only applies to transactional operations

We should check with the server side (execution team at least) to see if this meets their expectations.  If so, that seems like a fine solution.

**Comment by luke-pearson** [comment]
I think we should close this in favour of: #9307

**Comment by ddanderson** [comment]
Closed in favor of #9307 per discussion on the ticket.

**Pull request closed without merging**
