### PR TITLE
WT-9779 Remove redundant string comparison and fix `TRACE_ALL`

### PR DESCRIPTION
**Pull request by korteland**

### CODE REVIEW

**Comment by korteland** [comment]
`TRACE_ALL` was previously 0x00 :scream:

**Comment by mm-ng** [comment]
Maybe I'm misunderstanding this but I thought we needed the `&` comparator since the `TRACE_ALL` flag should be set only if the other relevant were set? Or are we using `|` to get all the relevant bits?

**Comment by korteland** [comment]
> the TRACE_ALL flag should be set only if the other relevant were set

I believe it's the other way round - we can set "all" in the config string, and that should set all of the bulk, cursor, read etc flags. It worked before because of the extra logic after the loop where we would check `all`, but the value of `TRACE_ALL` was still zero.

**Comment by mm-ng** [comment]
> > the TRACE_ALL flag should be set only if the other relevant were set
> 
> I believe it's the other way round - we can set "all" in the config string, and that should set all of the bulk, cursor, read etc flags. It worked before because of the extra logic after the loop where we would check `all`, but the value of `TRACE_ALL` was still zero.

Yes, the `all` config string should set all those other flags, but I have a feeling that setting the config to something like "bulk" will also set the `TRACE_ALL` flag in this case, which I don't think is what we want.

**Comment by korteland** [comment]
> Yes, the all config string should set all those other flags, but I have a feeling that setting the config to something like "bulk" will also set the TRACE_ALL flag in this case

Hmm, that's not what I can see in testing. Is there any specific bit of code that gives you that feeling?

**Comment by mm-ng** [comment]
> > Yes, the all config string should set all those other flags, but I have a feeling that setting the config to something like "bulk" will also set the TRACE_ALL flag in this case
> 
> Hmm, that's not what I can see in testing. Is there any specific bit of code that gives you that feeling?

What I'm assuming is if we have some config that is not "all", but corresponds to one of the other flags that is used to determine `TRACE_ALL`, `TRACE_ALL` will be set since it is non-zero

**Comment by korteland** [comment]
> TRACE_ALL will be set since it is non-zero

Oh, I think there might be a misunderstanding here - there's not actually a `TRACE_ALL` flag (I think?), it just sets the other flags. Are you talking about the `TRACE` flag that should be set if any trace flags are set? That one seems to be working fine.

**Comment by mm-ng** [comment]
> > TRACE_ALL will be set since it is non-zero
> 
> Oh, I think there might be a misunderstanding here - there's not actually a `TRACE_ALL` flag (I think?), it just sets the other flags. Are you talking about the `TRACE` flag that should be set if any trace flags are set? That one seems to be working fine.

I thought we needed a flag that checks if all the tracing configs are on, rather than one that checks if any tracing is on. And instead of having another flag for this we had `TRACE_ALL`.

**Comment by mm-ng** [comment]
I understand that we don't actually have a `TRACE_ALL` flag, but I thought we could still check if the `TRACE_ALL` field is set.

**Comment by korteland** [comment]
> I thought we needed a flag that checks if all the tracing configs are on, rather than one that checks if any tracing is on.

I don't believe that to be the case, and `grep` would seem to agree (I think?). There's only one usage `TRACE_ALL`, which is the one we're discussing. My understanding is that all of the `TRACE_x` flags are checked by individual trace operations, so `bulk.c` would only check `TRACE_BULK` etc. (i.e. nothing checks against `TRACE_ALL`.)

**Comment by korteland** [comment]
(In any case, even if something was checking against the old definition of `TRACE_ALL`, it was wrong - that bitwise and evaluated to zero, so `FLD_ISSET` and friends would have always returned zero)

**Comment by mm-ng** [comment]
> > I thought we needed a flag that checks if all the tracing configs are on, rather than one that checks if any tracing is on.
> 
> I don't believe that to be the case, and `grep` would seem to agree (I think?). There's only one usage `TRACE_ALL`, which is the one we're discussing. My understanding is that all of the `TRACE_x` flags are checked by individual trace operations, so `bulk.c` would only check `TRACE_BULK` etc. (i.e. nothing checks against `TRACE_ALL`.)

Yeah you're right in the sense that we just need a way to turn on all the other flags if the "all" config is passed in. If you've tested that all of these get set then that should be fine. Sorry for the misunderstanding :-)

**Comment by korteland** [comment]
All good! It's reassuring to know that at least one person is really checking and thinking about it :-)

**Review by mm-ng — APPROVED** [review]

**Comment by korteland** [comment]
Sue won't be able to review this for a while, so going to merge. We can always revert if someone finds issues later.

**Comment by korteland** [comment]
evergreen merge

**Comment by korteland** [comment]
Evergreen failure is unrelated

**Pull request merged**
