### PR TITLE
WT-9968 Upgrade to v4 toolchain for evergreen tests

### PR DESCRIPTION
**Pull request by mariammojid**
Removed:
```
cmake/toolchains/mongodbtoolchain_v3_gcc.cmake
cmake/toolchains/mongodbtoolchain_v3_clang.cmake
```

Modified:
```
test/evergreen.yml
test/evergreen_develop.yml
```

### CODE REVIEW

**Review by korteland — COMMENTED** [review]
These changes look good - but just out of caution, could you please reconfigure the patch build to do a full test of everything?

**Review by lukech — COMMENTED** [review]
I agree with Will. Scheduling a full patch build to ensure no overlook is suggested. Lmk if you need help doing that.

**Comment by mariammojid** [comment]
v4 toolchain not installed on zSeries. Closing the PR till resolution.

**Review by korteland — APPROVED** [review]
LGTM! I had to jump in and fix the Amazon Linux thing since the prio of this got bumped up, but it was a two-liner (we needed env vars for the build step, since Amazon Linux didn't appear to have a usable fallback `ccache`).

**Review by tammybailey — APPROVED** [review]
Assuming all looks good with testing, LGTM!

**Comment by korteland** [comment]
evergreen merge

**Pull request merged**
