### PR TITLE
WT-6996 Fix suite_random.rand32() in python test suite

### PR DESCRIPTION
**Pull request by boboeee**
Currently the suite_random.rand32() only returns values that are < 2^16, this PR fixes the precedence of operations to return 2^32 values. This PR needed to double check if it exposes any other tests through having a bigger value being returned

### CODE REVIEW

**Review by tammybailey — APPROVED** [review]
LGTM. Looks like the PR testing is taking a bit to finish so just wait on that (and the other reviewers approval!) before you merge.

**Review by sulabhM — APPROVED** [review]
LGTM .. what is wrong with the PR testing. Merge only at the final green for the testing.

**Comment by boboeee** [comment]
re-running due to known failure WT-7047

**Comment by boboeee** [comment]
evergreen retry

**Pull request merged**
