### PR TITLE
WT-12961 Txn log improve and add macro OLDEST_STRICT_THRESHOLD

### PR DESCRIPTION
**Pull request by y123456yz**
Txn log improve
fix bug for some log Missing delimiter
add macro OLDEST_STRICT_THRESHOLD

WT-12961

### CODE REVIEW

**Comment by y123456yz** [comment]
sorry, PR WT-12799 is Revert, because unit-test-hook-tiered-timestamp tests fails in __txn_timestamp_usage_check.

This is my new PR, it is related to WT-12799.
thanks.

**Comment by luke-pearson** [comment]
I have added the previously failing task to the list of tasks to execute.

**Comment by raviprakashgiri29** [comment]
The test fix looks good to me. Merge whenever @luke-pearson reviews other parts of code.

**Review by luke-pearson — APPROVED** [review]
LGTM.

**Review by raviprakashgiri29 — APPROVED** [review]
LGTM

**Pull request merged**
