### PR TITLE
WT-3919 Add Python test cases for cursor cache sweep.

### PR DESCRIPTION
**Pull request by agorrod**

### CODE REVIEW

**Comment by agorrod** [comment]
@ddanderson I did a bit of git/JIRA shuffling and re-created your changes. They look fine to me, though the test takes a little while to run - do you think we should consider it for the long suite?

**Comment by michaelcahill** [comment]
autobuild: retest this please

**Comment by ddanderson** [comment]
@agorrod, it looks like it is failing in the same way as before. I find that it runs fine when I run it locally (even with `run.py -j N`) but fails the pull request test on a timeout. I haven't come up with a solution for this.

**Comment by ddanderson** [comment]
This branch was superseded by https://github.com/wiredtiger/wiredtiger/pull/3949 .

**Pull request closed without merging**
