### PR TITLE
WT-3542 Python test_stats_log_on_json_with_tables timeout on the PPC

### PR DESCRIPTION
**Pull request by keithbostic**

### CODE REVIEW

**Comment by sueloverso** [comment]
I'm not sure how this solves the problem.  I think this is another situation similar to WT-3541 where the PPC is very slow.  Maybe change the 30 to 100 like `reconfig02`?  Make the 30 a variable instead of hard-coded in code and comments while you're in there please!

**Comment by keithbostic** [comment]
> Maybe change the 30 to 100 like `reconfig02`?  Make the 30 a variable instead of hard-coded in code and comments while you're in there please!

The problem here was that (although the comments described a requirement to sleep), there was no sleep within the loop.

**Comment by keithbostic** [comment]
autobuild: retest this please

**Comment by sueloverso** [comment]
Ah, I see the addition of the second sleep now, not just a line movement.  LGTM

**Pull request merged**
