### PR TITLE
WT-3994 Avoid GCC-7 and Clang errors for mongodb-3.4 branch

### PR DESCRIPTION
**Pull request by lukech**
Test old branch PR Jenkins jobs

### CODE REVIEW

**Comment by michaelcahill** [comment]
@lukech, I like this change (apart from the dummy change to `txn.c`).  Is it ready for review and merge?

**Comment by lukech** [comment]
@michaelcahill I probably need to talk with @agorrod about the solution being taken, before kicking off the code review (and likely converting the BUILD ticket into a WT ticket).

**Comment by lukech** [comment]
@agorrod @keithbostic (cc @michaelcahill), please help to review the changes, which were based on the list of GCC warning option changes in WT-3394. Added a couple of more lines to avoid fatal errors for some warnings. Please note warnings will be retained with the "-Wno-error-xxx" setting (though not treated as errors).

**Comment by lukech** [comment]
Confirmed the same build errors triggered by the default GCC-7 warning settings also existed on mongodb-3.2, but not mongodb-3.6. We may need the same changes to be ported back to mongodb-3.2 later on.

**Comment by agorrod** [comment]
@lukech is this branch ready to merge?

**Comment by lukech** [comment]
@agorrod Yes, will merge.

**Pull request merged**
