### PR TITLE
WT-6518 An update with start timestamp of 0 obsoletes older updates.

### PR DESCRIPTION
**Pull request by sulabhM**

### CODE REVIEW

**Comment by sulabhM** [comment]
@quchenhao , this change is for 4.2. We are hitting a bug with an unexpected birthmark that has not been marked obsolete.

**Comment by quchenhao** [comment]
@sulabhM Sorry, I didn't notice it is for 4.2. However, I think it is possible that a reader may be reading the update chain after the 0 timestamped update. e.g.,

When a read only txn tries to read that update chain with read timestamp 20, we have:

U@20->U@10

on the update chain.

Then a context switch happens and another session put a 0 timestamped update on that:

U@0 -> U@20 -> U@10

Since the read only txn doesn't have a txnid, so it won't stop the oldest txnid to move beyond the txnid of U@0, making it globally visible. If we discard everything after that in obsolete check, the read only txn will read corrupted value after it resumes execution from context switch.

Also if this fix is necessary, why we are not making it in develop and back port that to 4.2 as we have the same issue in 4.4 I think.

**Comment by quchenhao** [comment]
@sulabhM In addition, we need to consider the case of lower isolation levels. There may be uncommitted updates after the globally visible update. When we try to commit or rollback the update, we may find it has been freed.

**Comment by sulabhM** [comment]
Closing this for now, the change is not understood to be correct yet and needs to be targetted to develop.

**Pull request closed without merging**
