### PR TITLE
WT-12924 Fix __wt_evict_file may read pages back to memory

### PR DESCRIPTION
**Pull request by quchenhao**

### CODE REVIEW

**Review by korteland — COMMENTED** [review]
I agree this is a valid fix, but is there a way to test it?

**Comment by quchenhao** [comment]
@korteland I don't have any good way to test that. It barriers too deep in the system. Do you have any idea?

**Review by korteland — APPROVED** [review]
@quchenhao yeah I spent some time thinking about this and couldn't find a way to do it. LGTM

**Comment by quchenhao** [comment]
@korteland pointed out the issue has actually been fixed in develop in another place but still it's a problem on 6.0 and 5.0.

**Pull request closed without merging**
