### PR TITLE
WT-11537 Remove no-ftruncate support

### PR DESCRIPTION
**Pull request by korteland**

### CODE REVIEW

**Review by ddanderson — COMMENTED** [review]
This change looks good to me as far as it goes, but I have a higher level comment/question.  The [WT API](https://source.wiredtiger.com/develop/struct_w_t___f_i_l_e___h_a_n_d_l_e.html#aadcd969865c263c9e9b00d39308e296c) allows a custom file system to set it's truncate handle to NULL: ("This method is not required, and should be set to NULL" in the above link).  It looks like `__wt_ftruncate` will still handle a `NULL` entry by returning `ENOTSUP`.

So are we:

1. allowing file system implementers to have a `NULL` file truncate, but disallowing such file systems to be used with chunk cache - I think we'd get a ENOTSUP error in that case.
2. disallowing file system implementations to have a `NULL` file truncate (in which case we need to fix doc and change the NULL check in `__wt_ftruncate`.
3. something else?

I think this change implements choice 1 , but I wanted to make sure that's the intention.  I think it's a theoretical question at the moment, but maybe some combination of circumstances will trigger it in the future.  Also If this is our intention, should we document this somewhere?

**Comment by korteland** [comment]
Yes, choice (1) is the goal here. (2) is a non-starter due to the tiered storage extensions, e.g. Azure, where the objects are immutable. (I guess we could still disallow a `NULL` truncate function pointer, but then these extensions would have to just return `ENOTSUP` themselves, so it's more work for the same result.)

Good question about documentation - I think this should live in the chunk cache documentation, I'll push a change that adds it as a starting point.

**Comment by Siddhartha8899** [comment]
Could we clean up [__log_truncate_file](https://github.com/wiredtiger/wiredtiger/blob/develop/src/log/log.c#L1395C1-L1395C20) as well?

**Comment by korteland** [comment]
> Should we clean up __log_truncate_file as well? I am unsure about this tbh, but thought it would be worth pointing out.

Sid and I discussed this offline. The conclusion was to leave it as-is, since logged tables have existing users and therefore it's a possible removal of functionality to make this bubble the `ENOTSUP` back to the user. The chunk cache has the advantage that it's new, so it's not taking anything away to fail configuration on non-ftruncate file systems.

**Review by Siddhartha8899 — APPROVED** [review]

**Review by ddanderson — APPROVED** [review]
LGTM!  Thanks for the doc addition.

**Comment by korteland** [comment]
PR test failure is WT-11579

**Comment by korteland** [comment]
evergreen merge

**Review by agorrod — APPROVED** [review]
Looks like this is approved, but adding my LGTM for good measure.

**Comment by korteland** [comment]
evergreen merge

**Pull request merged**
