### PR TITLE
BACKPORT-2218 Don't retry fsync calls after EIO failure

### PR DESCRIPTION
**Pull request by keithbostic**
Cherry-pick ae8bccc from WT-4045.

### CODE REVIEW

**Comment by lukech** [comment]
Hi @keithbostic, change lgtm. I noticed the pull request testing failed on the compilation step with GCC8. Similar failure happened on mongodb-3.4 (as tested in https://github.com/wiredtiger/wiredtiger/pull/4129). Created WT-4123. Could we hold off merging this PR till WT-4123 is addressed, so that we can ensure all testing are passed?

**Comment by keithbostic** [comment]
@lukech,
> Could we hold off merging this PR till WT-4123 is addressed, so that we can ensure all testing are passed?

That's certainly fine with me, whatever is best in your opinion.

**Comment by agorrod** [comment]
autobuild: retest this please

**Comment by lukech** [comment]
I'm going to merge since the PR testing passed on mongodb-3.2 branch.

**Pull request merged**
