### PR TITLE
WT-10254 Use wt_overwrite macro.

### PR DESCRIPTION
**Pull request by sueloverso**

### CODE REVIEW

**Review by ddanderson — COMMENTED** [review]
I think the existing code has a desired behavior that the bytes are overwritten even in a release build.  __wt_overwrite_and_free_len won't do that in release build.  Maybe it needs a comment to that effect.

**Comment by sueloverso** [comment]
I will add a comment. I am not sure it would be desired to use that debug_mode option in a release build (given its extremely slow performance impact).

**Comment by ddanderson** [comment]
I don't agree - if we have a memory bug that only occurs in release mode, we might want to turn this on, and the debug bytes are helpful.

**Comment by sueloverso** [comment]
@ddanderson I added a script for errant uses of free(). See if the current PR meets your needs.

**Review by ddanderson — APPROVED** [review]
LGTM!

**Pull request merged**
