### PR TITLE
WT-7489 rollback to stable can fail if running concurrently with a checkpoint

### PR DESCRIPTION
**Pull request by keithbostic**
RTS cannot run concurrently with checkpoints, lock them out.

### CODE REVIEW

**Review by kommiharibabu — APPROVED** [review]
LGTM

**Comment by kommiharibabu** [comment]
@keithbostic The test is leading to hanging as the original session lock flags are not transferred to the internal session that is started as part of the rollback to stable. We need something like the below to transfer the lock_flags.

> diff --git a/src/txn/txn_rollback_to_stable.c b/src/txn/txn_rollback_to_stable.c
> index 018a42a71..835607edf 100644
> --- a/src/txn/txn_rollback_to_stable.c
> +++ 
> 
> b/src/txn/txn_rollback_to_stable.c
> 
> @@ -1630,7 +1630,7 @@ __wt_rollback_to_stable(WT_SESSION_IMPL *session, const char *cfg[], bool no_ckp
>       * rollback to stable doesn't generate log records.
>       */
>      WT_RET(__wt_open_internal_session(S2C(session), "txn rollback_to_stable", true,
> -      F_MASK(session, WT_SESSION_NO_LOGGING), 0, &session));
> +      F_MASK(session, WT_SESSION_NO_LOGGING), session->lock_flags, &session));
>  
>      /*
>       * Rollback to stable should ignore tombstones in the history store since it needs to scan the

**Comment by keithbostic** [comment]
evergreen retry

**Comment by keithbostic** [comment]
evergreen retry

**Comment by keithbostic** [comment]
@kommiharibabu, thank you for pointing that out, I was just thinking evergreen was slow. :) 

I kind of hate to copy all of the lock flags from the caller's session, especially since it might be an application session, that feels dangerous (although I can't think of any reason it's actually  unsafe).

I pushed a change in 6a046b1 for your consideration.

That change moves all of the actual rollback-to-stable work from `__wt_rollback_to_stable()` to `__rollback_to_stable()`, and that allowed me to acquire the checkpoint lock around the call to `__rollback_to_stable()`. By "actual rollback-to-stable work", I mean things like configuring the session to ignore tombstones, resetting the durable timestamp, that kind of stuff. The only real change should be that `txn_rollback_to_stable_running` is set while the RTS checkpoint runs, but that feels correct to me, RTS is still "running" during that checkpoint.

Please let me know what you think -- if you don't like it, say so and I'll do the change you suggested of copying the caller's session lock flags to the internal session instead.

If you do like this change, should we pull the schema lock up into `__wt_rollback_to_stable()` as well? Is it reasonable for schema changes to happen while RTS is doing its checks, or before the RTS checkpoint completes?

**Review by kommiharibabu — APPROVED** [review]
LGTM

**Pull request merged**
