### PR TITLE
WT-2397: Cursor search/traversal returns out of order keys.

### PR DESCRIPTION
**Pull request by keithbostic**
WT-2397: Invariant failure newCommittedSnapshot.opTime >= _currentCommittedSnapshot->opTime

### CODE REVIEW

**Comment by keithbostic** [comment]
@agorrod, @michaelcahill, this is a tentative fix for SUPPORT-1577.

It's dropping core on tinderbox because there's no block manager connected to the btree handle.

I'm going to keep looking, but I'm having a hard time thinking of a way the change could have resulted in this failure. Does this make sense to either of you?
```
(gdb) where
#0  0x00007f057fedc6e1 in __wt_bt_read (session=session@entry=0x1c76550, 
    buf=buf@entry=0x7f057fc79c80, 
    addr=addr@entry=0x1df4a2c "\300\364\201\344?\231{`\231\060\060\060\060\060\060\060\060\063\067.10/opqrstuvwxyzabcdefghijkl \210\302`\201\344\030n\376\237\201\060\060\060\060\060\060\060\061\062\065.00/opqrstuvwxyzabcdef \210\302\302\201\344\021&\002Du0000000177.00/opqrstuvwxyzabc \210\303n\201\344\267K\v\243y0000000234.05/opqrstuvwxyzabcd \210\303ہ\344.\300Z\225\225\060\060\060\060\060\060\060\062\070\067.13/opqr"..., addr_size=addr_size@entry=8)
    at ../src/btree/bt_io.c:40
#1  0x00007f057fee0d24 in __page_read (ref=0x1df7220, session=0x1c76550)
    at ../src/btree/bt_read.c:393
#2  __wt_page_in_func (session=session@entry=0x1c76550, 
    ref=ref@entry=0x1df7220, flags=flags@entry=256, 
    file=file@entry=0x7f057ff9a734 "../src/btree/bt_walk.c", 
    line=line@entry=303) at ../src/btree/bt_read.c:488
#3  0x00007f057fefa058 in __wt_page_swap_func (line=303, 
    file=0x7f057ff9a734 "../src/btree/bt_walk.c", flags=256, want=0x1df7220, 
    held=0x7f054c017a98, session=0x1c76550) at ../src/include/btree.i:1310
#4  __firstlast (prev=false, refp=<synthetic pointer>, session=0x1c76550)
    at ../src/btree/bt_walk.c:302
#5  __tree_walk_internal (session=session@entry=0x1c76550, 
    refp=refp@entry=0x7f054c017af8, walkcntp=walkcntp@entry=0x7f057fc79ef8, 
    skipleafcntp=skipleafcntp@entry=0x0, flags=121, flags@entry=113)
    at ../src/btree/bt_walk.c:399
#6  0x00007f057fefc79c in __wt_tree_walk_count (
    session=session@entry=0x1c76550, refp=refp@entry=0x7f054c017af8, 
    walkcntp=walkcntp@entry=0x7f057fc79ef8, flags=flags@entry=113)
    at ../src/btree/bt_walk.c:675
#7  0x00007f057ff367db in __evict_walk_file (slotp=<synthetic pointer>, 
    session=0x1c76550) at ../src/evict/evict_lru.c:1245
#8  __evict_walk (session=0x1c76550) at ../src/evict/evict_lru.c:1119
#9  __evict_lru_walk (session=0x1c76550) at ../src/evict/evict_lru.c:878
#10 __evict_pass (session=0x1c76550) at ../src/evict/evict_lru.c:623
#11 __evict_server (arg=0x1c76550) at ../src/evict/evict_lru.c:188
#12 0x0000003a76007555 in start_thread () from /lib64/libpthread.so.0
#13 0x0000003a75d02b9d in clone () from /lib64/libc.so.6
(gdb) p ((WT_BTREE *)session->dhandle->handle)->bm
$20 = (WT_BM *) 0x0
(gdb) p session->dhandle->name
$21 = 0x7f054c0199f0 "file:wt-000009.lsm"
```

**Comment by keithbostic** [comment]
@agorrod, @michaelcahill, figured it out.

**Comment by agorrod** [comment]
@keithbostic I see where you are going with this, and I think it's a reasonable direction. It would be nice to avoid pulling in pages unconditionally - there are "things" that walk trees which assume they won't pull anything in, and needing to reason through exceptions worries me.

**Comment by keithbostic** [comment]
@agorrod, I think you're right: I've pushed a new branch in pull request #2495 that integrates the race check with the standard walk setup code.

**Pull request closed without merging**
