### PR TITLE
WT-5940 Migrate to Clang Format 10 (v4.2 backport)

### PR DESCRIPTION
**Pull request by tetsuo-cpp**
This PR is backporting the Clang Format 10 migration to v4.2.

### CODE REVIEW

**Comment by tetsuo-cpp** [comment]
autobuild: retest this please

**Comment by tetsuo-cpp** [comment]
@lukech I'm going to wait until `develop` and `mongodb-4.4` get synced before merging this.

**Comment by lukech** [comment]
Thanks @tetsuo-cpp sounds good to me.

**Comment by tetsuo-cpp** [comment]
@lukech Do we know when this is going to happen?

**Comment by lukech** [comment]
@tetsuo-cpp the current plan is early next week.

**Comment by tetsuo-cpp** [comment]
@lukech Any word on this?

**Comment by lukech** [comment]
@tetsuo-cpp some recent breakage was identified which mandated the cut of 4.4.1-rc2 today. That means the 4.4.1 GA and the subsequent 4.4 & master sync needs to be delayed. I hope the sync could happen early next week.

**Comment by tetsuo-cpp** [comment]
@lukech I'm going to resolve this conflict and merge. Agreed?

**Comment by lukech** [comment]
@tetsuo-cpp sgtm.

**Pull request merged**
