### PR TITLE
WT-8572 Remove unused history store verification code

### PR DESCRIPTION
**Pull request by keitharnoldsmith**

### CODE REVIEW

**Comment by keitharnoldsmith** [comment]
In addition to the code changes in this PR, I've left a comment on WT-6682 indicating that this code has been removed.

**Review by sueloverso — APPROVED** [review]
LGTM

**Comment by quchenhao** [comment]
@keitharnoldsmith We would still like to enable this verification if the problems are fixed. However, that is still a long way to go. Do we really want to remove this for now? If we do, can we create a ticket to reintroduce this once everything is fixed?

**Review by quchenhao — APPROVED** [review]
LGTM

**Comment by keitharnoldsmith** [comment]
@quchenhao: I agree it would be good to support this kind of verification.  But I don't think we should keep code that we might someday want in the develop branch. If we did that with every change that isn't quite ready, the source would be a mess. My preference would be to keep changes like this in a separate branch. It also makes it clear what has changed in the code since work stopped on the branch. For example, this is what Keith Bostic did with WT-7408. 

I'll update WT-6682 to explicitly point to this change as a way to find and reintroduce the relevant code.

**Pull request merged**
