### PR TITLE
WT-9268 Don't panic if inserting to hs returns ebusy

### PR DESCRIPTION
**Pull request by quchenhao**

### CODE REVIEW

**Comment by quchenhao** [comment]
I'm able to reproduce this in a python test. Here's the implementation of the first solution we proposed .

**Comment by agorrod** [comment]
Did you use the wrong ticket number for this PR Chenhao? I think it should be WT-9268

**Comment by quchenhao** [comment]
> Did you use the wrong ticket number for this PR Chenhao? I think it should be [WT-9268](https://jira.mongodb.org/browse/WT-9268)

Sorry, fixed the title.

**Review by kommiharibabu — APPROVED** [review]
LGTM

**Review by agorrod — CHANGES_REQUESTED** [review]
I prefer looking to see whether there is a different solution that avoids leaving a redundant entry in the history store. I'm going to "request changes" until that conversation on the ticket is resolved.

**Pull request closed without merging**
