### PR TITLE
WT-3933 test/format failure illegal WT_REF.state rolling back deleted page

### PR DESCRIPTION
**Pull request by keithbostic**
@michaelcahill, setting `WT_REF.page_del.txnid` to `WT_TXN_ABORTED` allows the page to be evicted and the `WT_REF.page_del` structure to be discarded.

So, making that change before marking the updates are aborted means we can drop core accessing the updates, making the change after we swap in the WT_REF's previous state means we can drop core getting to the `WT_REF.page_del.txnid` field.

### CODE REVIEW

**Comment by michaelcahill** [comment]
@keithbostic, I'm not following this part:

> making the change after we swap in the WT_REF's previous state means we can drop core getting to the WT_REF.page_del.txnid field

It shouldn't be possible to evict the page at that point because the truncating transaction is still running, so

**Comment by michaelcahill** [comment]
Apologies for the clicking the wrong button.

**Comment by keithbostic** [comment]
@keithbostic, I'm not following this part:

>> making the change after we swap in the WT_REF's previous state means we can drop core getting to the WT_REF.page_del.txnid field

> It shouldn't be possible to evict the page at that point because the truncating transaction is still running, so the `visible_all` check on `page_del` will fail.  Maybe some other operation could clobber the `page_del`, but that seems scary since the truncating transaction is still running.

The test in `__wt_page_can_evict()` checks `WT_TXN_ABORTED`, not the visibility of `ref.page_del.txnid`, which I think makes this problematical, that is, we've made the page evictable before the transaction has been fully rolled back.

If it's the last thing the routine does, well maybe...

**Comment by michaelcahill** [comment]
@keithbostic, I'm talking about this part of the condition:
```
 	    !__wt_txn_visible_all(session,
 	    ref->page_del->txnid, WT_TIMESTAMP_NULL(&ref->page_del->timestamp)))
```
That can't be true while `ref->page_del->txnid` is the running transaction's ID.

**Comment by michaelcahill** [comment]
@keithbostic, sorry we didn't overlap today -- I've pushed 50308f2 with the change I'd prefer, but haven't had a chance to kick off tests on zSeries to see whether this reintroduces the bug.

**Comment by keithbostic** [comment]
@michaelcahill, your change lgtm, I'll merge into develop so it runs over the weekend.

**Pull request merged**
