### PR TITLE
Change log alignment to 32 bytes. #1772

### PR DESCRIPTION
**Pull request by sueloverso**
Not yet ready to merge.  But want to test log-related wtperf jobs with this.

### CODE REVIEW

**Comment by michaelcahill** [comment]
Hi @sueloverso, this looks fine to me if it increases performance and reduces the disk footprint of log files.

Are there compatibility implications of making this change: is there any chance of a existing logs not being correctly handled if read by a version of WiredTiger with different alignment?  What about in the other direction: if someone tried to downgrade after running with this change, could the downgraded version of WiredTiger fail to read the log?

**Comment by sueloverso** [comment]
Yes, there are compatibility issues - I mentioned those in #1772.  I've been thinking about that issue and have only partially solved it so far.

**Comment by sueloverso** [comment]
I ran with Bruce's insert workload from 17111.  I ran 3 timings with both 128-byte and the 32-byte alignment.  I ran the timings with 16 MongoDB `wiredTigerConcurrentWriteTransaction` threads and with 128 threads (the default).  The 32-byte alignment seems to be <= 1% slower through MongoDB.  The 16-thread case is nearly identical and the 128-thread case is 1% slower.  I suspect almost all customers use the default thread count and I wouldn't want even a 1% penalty even offset by some disk savings.

So far, I think I am not a fan.

**Comment by michaelcahill** [comment]
@sueloverso, if you decide not to pursue this, please close the pull request and delete the branch.  Thanks!

**Comment by sueloverso** [comment]
There was not compelling evidence that this was helpful.  So close this without merging.

**Pull request closed without merging**
