### PR TITLE
WT-4333 WiredTiger cursor cache doesn't handle all possible locked handle states (v3.6 backport)

### PR DESCRIPTION
**Pull request by lukech**
@keithbostic Could you help to take a quick look? 
This is a clean cherry-pick (to backport the change to v3.6).

### CODE REVIEW

**Comment by lukech** [comment]
@keithbostic It looks it always failed at the Python sweep test in PR testing. In my local testing it failed at Python rollback to stable timestamp test. Any idea what could have caused it? Please note there's WT-4340 that addressed some fallout from this ticket, not sure if the Python test failure here is related. 

`FAIL: test_timestamp04.test_timestamp04.test_rollback_to_stable(V2.lsm) (subunit.RemotedTestCase)
test_timestamp04.test_timestamp04.test_rollback_to_stable(V2.lsm)
----------------------------------------------------------------------
_StringException: Traceback (most recent call last):
  File "/mnt/data0/lchen/work/wiredtiger/test/suite/test_timestamp04.py", line 173, in test_rollback_to_stable
    self.assertEqual(calls, 1)
  File "/usr/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 1`

**Comment by keithbostic** [comment]
autobuild: retest this please

**Comment by keithbostic** [comment]
@lukech, as you suggested, the problem is that the changes from WT-4340 weren't included in your cherry-pick. Here's the smoking gun core dump:
```
(gdb) where
#0  0x00007ffff6e12c73 in select () from /lib64/libc.so.6
#1  0x00007ffff5044afd in __wt_sleep (seconds=100, micro_seconds=0)
    at src/os_posix/os_sleep.c:32
#2  0x00007ffff503c1b8 in __wt_abort (session=0x8ca3c8)
    at src/os_common/os_abort.c:28
#3  0x00007ffff509282f in __wt_readunlock (session=0x8ca3c8, l=0xaa6bd0)
    at src/support/mtx_rw.c:296
#4  0x00007ffff5089c73 in __wt_session_release_dhandle (session=0x8ca3c8)
    at src/session/session_dhandle.c:306
#5  0x00007ffff4fc92ea in __curfile_reopen (cursor=0xac3350, check_only=false)
    at src/cursor/cur_file.c:571
#6  0x00007ffff5075185 in __session_close_cursors (session=0x8ca3c8,
    cursors=0x963340) at src/session/session_api.c:229
#7  0x00007ffff5075316 in __session_close_cached_cursors (session=0x8ca3c8)
    at src/session/session_api.c:256
#8  0x00007ffff507576c in __session_close (wt_session=0x8ca3c8, config=0x0)
    at src/session/session_api.c:294
#9  0x00007ffff4f9d16b in __conn_close (wt_conn=0x8adee0, config=0x0)
    at src/conn/conn_api.c:1092
```
I cherry-picked fe312cf into the branch, let's see how that works.

**Comment by lukech** [comment]
@keithbostic Thanks for confirming and cherry-pick the commit of WT-4340. I will go ahead and merge.

**Pull request merged**
