### PR TITLE
Check that every scenario has a unique name within its test.

### PR DESCRIPTION
**Pull request by michaelcahill**
refs #1813

### CODE REVIEW

**Comment by ddanderson** [comment]
@michaelcahill, lgtm.

**Comment by michaelcahill** [comment]
Re-reading your suggestion, we could catch it like this instead, without changing test code:

```diff
diff --git a/test/suite/wttest.py b/test/suite/wttest.py
--- a/test/suite/wttest.py
+++ b/test/suite/wttest.py
@@ -177,6 +177,8 @@ class WiredTigerTestCase(unittest.TestCa
         sys.stderr = WiredTigerTestCase._stderr

     def __init__(self, *args, **kwargs):
+        if hasattr(self, 'scenarios'):
+            assert(len(self.scenarios) == len(dict(self.scenarios)))
         unittest.TestCase.__init__(self, *args, **kwargs)
         if not self._globalSetup:
             WiredTigerTestCase.globalSetup()
```

Does that look better?

**Comment by agorrod** [comment]
@michaelcahill I like both of these solutions - redundancy here doesn't hurt.

The original change you made makes the requirement more obvious when implementing new test cases. The second solution should catch any cases where we don't add the check in the future.

I'll merge once the test suite finishes.

**Comment by ddanderson** [comment]
@michaelcahill, @agorrod, great, I like the extra backstop.

**Pull request merged**
