### PR TITLE
WT-9448 Python test to reproduce checkpoint cursor assertion

### PR DESCRIPTION
**Pull request by sauclovian-wt**
Add a python reproducer for the failure seen in WT-9440.

### CODE REVIEW

**Comment by sauclovian-wt** [comment]
This has an odd problem where the eviction cursor works on the metadata... but only after one or two scans of the checkpoint. (Before that it does not trigger any reads in the metadata; after it does reliably.) I stuck in two extra scans and made the most important scan the last one (of four "real" ones) but if anyone knows why this is happening it would be great to fix it properly, since otherwise it might turn out to not actually be able to reproduce the problem in the field, or not be reliable.

**Comment by agorrod** [comment]
@sauclovian-wt I'm trying to help tie up loose ends. Would it help if I found someone to dig into the issue you describe above?

**Comment by sauclovian-wt** [comment]
Probably? I'm not sure why this has been sitting all this time but I've been guessing that issue is a big part of it.

Evidently nobody who's seen this already knows, so either we leave it (with or without merging this test) or someone's going to have to dig it up. I'll probably get to it eventually but for the moment I'm trying to get all the truncate stuff pushed through first...

**Comment by sauclovian-wt** [comment]
I just merged this with develop.

I think it would be good to get it merged, with or without figuring out what's up with the eviction cursor, unless since I wrote it someone's committed something else that covers this case. But at this point that probably requires someone else take it up...

**Comment by korteland** [comment]
Hmm, there's something up with the automated testing - not sure if `test_timestamp_abort` failing with `cur_local->insert(cur_local): WT_ROLLBACK` rings a bell for you, it seems fine on develop. I can't see how it could be related to your changes, so I'll give the CI another shot.

**Comment by korteland** [comment]
evergreen retry

**Review by korteland — COMMENTED** [review]
I think this is better off living in develop than a branch, so I'm happy to defer the "proper" fix. To that end, I've two review comments: I've made WT-10236 to track the issue with needing multiple scans of the checkpoint, could you please update the `XXX` comment with that ticket number? And secondly, a bit of a nitpick - the commented-out begin/end transaction pair is pointless, it would be better to remove it.

**Review by korteland — APPROVED** [review]
Approving this to get it in, and I'll follow it up with another PR for the changes I wanted.

**Pull request merged**
