### PR TITLE
WT-10245 Check output of Workgen and Wtperf workloads

### PR DESCRIPTION
**Pull request by etienneptl**
- Added an assertion when the `run` command is expected. We expect it to return `0`.
- Modified a few workloads to align with Python3 and work with the latest version of Workgen.

### CODE REVIEW

**Review by ddanderson — APPROVED** [review]
LGTM.  Can you also modify wtperf.py to generate code those same asserts?

If you don't know wtperf.py takes as input a .wtperf file and generates a python script that uses workgen to do the same workload.

**Comment by etienneptl** [comment]
> LGTM. Can you also modify wtperf.py to generate code those same asserts?

@ddanderson, good idea, I did it in 02348e3d878eddecc61199e69d54f9a7e713d00a.

**Comment by ddanderson** [comment]
@etienneptl that change to wtperf.py looks great, thanks.

**Review by raviprakashgiri29 — APPROVED** [review]
Changes LGTM. Is there any particular reason that you have modified the sample_interval_ms in some of the workloads?

**Pull request merged**
