### PR TITLE
Create ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by loadwiki**
New Feature	Required.
Description in ISSUE_TEMPLATE.md

### CODE REVIEW

**Comment by wtbuild** [comment]
autobuild: Can one of the admins verify this patch?

**Comment by keithbostic** [comment]
Hi, @loadwiki, thank you for your comments. It looks to me like you're suggesting a new feature for WiredTiger, but it's unclear to me exactly what you're asking for.

We are happy to consider feature requests of course!

Would you please create a "WiredTiger" JIRA ticket at MongoDB ([https://jira.mongodb.org](https://jira.mongodb.org)), and then we can have a conversation to better understand what you're proposing.

Thanks!

**Comment by keithbostic** [comment]
@loadwiki: were you notified of my response in the JIRA WT-3770 ticket? No rush, but want to make sure we get to the bottom of this one.

Thanks!

**Comment by loadwiki** [comment]
Yes, notification received. Thanks.
You can review my comment from the JIRA ticket.

2017-12-12 6:38 GMT+08:00 Keith Bostic <notifications@github.com>:

**Pull request closed without merging**
