### PR TITLE
WT_CURSOR::search/search-near, near current position.

### PR DESCRIPTION
**Pull request by keithbostic**
WT_CURSOR::search/search-near should check the current (pinned) page before restarting the search from the top of the tree.

### CODE REVIEW

**Comment by keithbostic** [comment]
@michaelcahill, I think this is ready for discussion/review. Open questions:
- statistics we should add, to determine effectiveness?
- check if page should be forcibly evicted before searching?
- requirement for `__wt_txn_cursor_op` call

**Comment by agorrod** [comment]
@keithbostic Do you have any idea how much this helps/hurts performance in relevant cases? I guess relevant cases are:

* Doing a search or search_near when the item is near by.
* Doing a search or search_near when the item isn't near by.
* The size of the tree (out of cache, in cache, multiple internal levels).

Feels like it'd be a big win if it finds the item without a lot of cost when it doesn't - but it'd be nice to confirm that.

**Comment by keithbostic** [comment]
@agorrod, I haven't done any performance measurements.

There's some motivation for the feature from @RedBeard0531 here: https://groups.google.com/a/10gen.com/forum/#!topic/wiredtiger/MsflpPotspA.

When I first looked at this, I considered checking just the first/last keys on the page before searching the page for real, but that proved more complex than searching the page (it takes a fair amount of code to find the first/last keys, they can be in a number of different places). If searching the page is too expensive, then we could fallback to implementing that code.

One other idea is we could make this adaptive: do the current-page check and if we don't find what we're looking for, turn off the current-page check, and vice-versa (save a copy of the cursor's WT_REF, and if we do a full search and end up at the same page, turn on the current-page check). I doubt there are many applications that cycle between searching locally and then remotely, that might be a simple solution.

**Comment by michaelcahill** [comment]
@daveh86, can you please add to your queue running some MongoDB performance tests against this branch to compare with develop?

**Comment by michaelcahill** [comment]
@keithbostic, the change looks good to me.  Let's see some performance numbers before deciding whether to have it on unconditionally or try to do something more clever to avoid the overhead.

The `__wt_txn_cursor_op` call is required to update the transactional context.  I think it's fine to avoid the cache check in `__cursor_func_init` when we're staying on the same page, but we will need to check for forced eviction (i.e., `page->read_gen == WT_READGEN_OLDEST`) and take the slow path in that case.

**Comment by keithbostic** [comment]
@michaelcahill, I've pushed the change to check for forced eviction before searching the already pinned-page. I'm not sure about it though: it seems to me that a cursor doing searches (as opposed to next/prev calls), is unlikely to stay on the page that long, what's the scenario the forced eviction test defends against?

**Comment by keithbostic** [comment]
@michaelcahill, @daveh86, I ran some basic performance tests (although it would be good to have David confirm them).

In a small tree, where the search of the pinned page always succeeds, each search is about 10% faster, so where this feature consistently pays off, it pays off at 10% per search, or better. I say "better" because I tested with a tiny tree, and the deeper the tree, the more a successful pinned-page search rewards us because we skip pinning/searching that many more pages.

Where the search of the pinned page never succeeds, the overall search is about 3% slower, so we'll pay roughly 3% per search when the pinned-page search misses. This cost isn't relative to the depth of the tree, but is relative to how large pages are. (That said, because we do binary searches of both on- and off-page keys, I'm not expecting the cost to vary much, pages would have to be very large for it to matter.)

My suggestion is to do something simple to flag applications repeatedly using cursors where there's little chance of a close-by hit: keep a local counter in the cursor, and if the pinned-page search fails 10 times in a row, we quit doing pinned-page searches.

Since this is a MongoDB-requested feature, we should ask Mathias; @RedBeard0531, do that make sense to you, does that algorithm work with MongoDB patterns?

**Comment by keithbostic** [comment]
@michaelcahill, @daveh86, I should mention @RedBeard0531 ran some tests with this branch, and he reports:

> FYI, I just tried your patch and in the best case the perf impact is huge. Distinct on 1M values went from 2.7s to 2.2s

I don't know what specific test he was running.

**Comment by keithbostic** [comment]
@michaelcahill, I'm ready to merge this branch if you are, we can fine-tune when/if we do pinned-page searches after the merge.

**Comment by RedBeard0531** [comment]
The benchmark was pretty simple:

    bulk = db.million.initializeUnorderedBulkOp()
    for (var i = 0; i<1000*1000; i++) bulk.insert({_id:i});
    bulk.execute()
    db.million.distinct('_id')

And looking at the server logs to see how long the distinct ran for. Currently distinct does a lot of work above the WT layer so the room for potential improvement is a bit lower. I did take a peek at the profiler (using perf top) and saw that the time spent inside WT functions was much less, but I didn't do a thorough analysis. If needed, I could break it down to just the time spent in WT and try a larger mix of operations, including some where this wont help.

The downside to flipping a switch after 10 failed inner-seeks is that this is highly data dependent.
Some values may have only a single value and seek(next-value) is just skipping to the next value.
Other values may have millions of entries. Both may exist in the same index.

@keithbostic, was your 3% max overhead on a small tree, or a large one? I assume that the overhead
as a percentage would go down as the tree grows while the savings go up.

**Comment by keithbostic** [comment]
@RedBeard0531, my 3% max overhead was on a small tree; yes, I agree with your analysis.

**Comment by michaelcahill** [comment]
Thanks, @keithbostic -- lgtm and I'm sold on the performance tradeoff.  I'll merge.

**Pull request merged**
