### PR TITLE
WT-3947 Added wiredtiger_open configuration 'cache_cursors' to disable cursor caching.

### PR DESCRIPTION
**Pull request by ddanderson**
Added and improved tests that check cursor caching.

### CODE REVIEW

**Comment by ddanderson** [comment]
@sueloverso, could you review this change please?

**Comment by michaelcahill** [comment]
I'd also be fine with not allowing `cache_cursors` to be reconfigured: it seems like something the application is either prepared to pay for (extra memory per open session for more performance), or it isn't.  I'm struggling to think of when an application would switch it on/off.

**Comment by michaelcahill** [comment]
I reviewed, and we were only checking for `cache_cursors` during `wiredtiger_open`.  In other words, the code didn't allow the setting to be reconfigured.  I pushed a change with the update to `api_data.py` to reflect that.

This otherwise LGTM, so if you're happy, please merge.

**Comment by ddanderson** [comment]
@michaelcahill and @sueloverso, thanks for your review and changes.  LGTM, I'll merge.

**Pull request merged**
