### PR TITLE
WT-8930 Make s_string hex number search compatible with MacOS

### PR DESCRIPTION
**Pull request by korteland**
There's a few things going on with GNU vs. BSD sed. The order of the arguments matters a bit more (need to have the filename last), the `+` operator is only supported with extended regexes (`-E`) but that breaks other stuff so just use a `{0,}` range operator. I also added the `global` flag to catch cases where there are multiple constants on the one line.

### CODE REVIEW

**Comment by sauclovian-wt** [comment]
You might want {1,} since 0x by itself isn't valid, but it doesn't really matter. Otherwise LGTM. 
(It broke for me as well on NetBSD, works with this change)

**Comment by korteland** [comment]
> You might want {1,} since 0x by itself isn't valid, but it doesn't really matter. Otherwise LGTM. (It broke for me as well on NetBSD, works with this change)

You're right, thanks for that.

**Comment by sauclovian-wt** [comment]
YW :-)

**Review by jeremythorp — APPROVED** [review]
Thanks Will, LGTM!

**Pull request merged**
