### PR TITLE
WT-3630 Avoid the system Python binary on Evergreen.

### PR DESCRIPTION
**Pull request by michaelcahill**
The System Integrity Protection feature of macOS means DYLD_LIBRARY_PATH is ignored for /usr/bin/python, so choose another by default.  Luckily there is a Python binary included in MongoDB's toolchain, so prefer than unless overridden.

### CODE REVIEW

**Comment by michaelcahill** [comment]
@ddanderson, can you please review this change?  There is an explanation on the ticket, in short I see `/usr/bin/python` ignore `DYLD_LIBRARY_PATH` if macOS System Integrity Protection is enabled.  This change prefers the Python binary that is part of MongoDB's toolchain.

**Comment by michaelcahill** [comment]
@ddanderson this doesn't quite work: https://evergreen.mongodb.com/task/wiredtiger_macos_1012_unit_test_patch_1d345ecbc116b82f5bfab4bcc4cae8e1fa8e3987_59e949ece3c33144860057f8_17_10_20_00_57_25

We'll have to figure out the path to the MongoDB toolchain in the macOS builders -- I just copied that from the Evergreen build for MongoDB but it's not working here.

**Comment by ddanderson** [comment]
@michaelcahill, I took your change 08cd70c and added some debug instrumentation, it fails with this error: 
```
ERROR: wt command expected success, got failure: ['/data/mci/138534eb64683753dbc1217df797faf5/wiredtiger/wt', 'backup', 'backup.dir']
[2017/10/21 11:15:13.917] output files follow:
[2017/10/21 11:15:13.919] **************************************************
[2017/10/21 11:15:13.919] wt.err
[2017/10/21 11:15:13.919] **************************************************
[2017/10/21 11:15:13.919] dyld: Library not loaded: /usr/local/lib/libwiredtiger-3.0.0.dylib
[2017/10/21 11:15:13.919]   Referenced from: /data/mci/138534eb64683753dbc1217df797faf5/wiredtiger/.libs/wt
[2017/10/21 11:15:13.919]   Reason: image not found
```
(The evergreen run is here: https://evergreen.mongodb.com/task/wiredtiger_macos_1012_unit_test_patch_1d345ecbc116b82f5bfab4bcc4cae8e1fa8e3987_59eb53cce3c3317b16000186_17_10_21_14_04_23 , the text above is buried in the output).  I'm looking further at ways to pass or alter the environment passed to `wt`, I would think that is involved.

**Comment by agorrod** [comment]
FYI: I've updated this branch to the latest version of WiredTiger develop - in case having the fixes in WT-3679 helps.

**Comment by ddanderson** [comment]
Thanks, @agorrod.  I think I have a fix, testing in evergreen now. If it works, I'll push it for review.

**Comment by ddanderson** [comment]
@michaelcahill, can you take a look at this please? It has passed evergreen (https://evergreen.mongodb.com/build/wiredtiger_macos_1012_patch_23ec0f4ff2a1ccf5ee35955b17f0b1ca674b5a4f_59efad9be3c3316d0f00a74f_17_10_24_21_16_31 ).  That evergreen patch (but not this commit) also included some code that deduces/prints if SIP is enabled (to really make sure we were really testing against a SIP machine). And SIP was enabled, so I think that's the best we can test it.

**Comment by ddanderson** [comment]
@michaelcahill, sorry spoke too soon. Looks like this code doesn't pass on Linux. I'll take another look tomorrow.

**Comment by ddanderson** [comment]
@michaelcahill, this is ready for review. I don't understand why directly invoking .libs/wt caused Jenkins tests to fail on Linux, but it seems to be the case.  So this change works on Linux by running the libtool generated script and on OS/X *not* running the libtool generated script works whether or not SIP is present.

**Comment by agorrod** [comment]
lgtm

**Pull request merged**
